### DISCUSSION TITLE
Is it possible not to run argo in the "argo-rollouts" namespace?

### DISCUSSION THREAD

**Discussion by bahramrushenas** [argoproj/argo-rollouts#1148] [Q&A] [answered]
We have not been successful in configuring argo-rollouts to run in a different namespace than "argo-rollouts". Is that even possible?

Thank you

**Comment by jessesuen** [comment, marked as answer]
Yes, it should be possible.  I assume you must be getting permission problems. You will need need to adjust the ClusterRoleBinding to reference the namespace of the new location. e.g.:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-rollouts-clusterrolebinding
  labels:
    app.kubernetes.io/component: rollouts-controller
    app.kubernetes.io/name: argo-rollouts-clusterrolebinding
    app.kubernetes.io/part-of: argo-rollouts
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-rollouts-clusterrole
subjects:
- kind: ServiceAccount
  name: argo-rollouts
  namespace: DIFFERENT-NAMESPACE # <<<<< change this
```
