### DISCUSSION TITLE
Debug web metric 403

### DISCUSSION THREAD

**Discussion by DanTulovsky** [argoproj/argo-rollouts#1201] [Q&A]
Hi,

I am getting:

```
        - finishedAt: '2021-05-19T20:54:42Z'
          message: 'received non 2xx response code: 403'
          phase: Error
          startedAt: '2021-05-19T20:54:42Z'
```

using the web provider. Is there a debug mode I can enable to see the actual URL being sent?  My config is:

```
spec:
  args:
    - name: access-token
      valueFrom:
        secretKeyRef:
          key: staging
          name: api
  metrics:
    - failureCondition: result == 'true'
      interval: 1m
      name: error-rate
      provider:
        web:
          headers:
            - key: Authorization
              value: 'Bearer {{ args.access-token }}'
          jsonPath: '{$.data.attributes.state}'
          timeoutSeconds: 20
          url: >-
            https://my/url
```
And I've confirmed that the secret contains the correct apikey.

Thank you
Dan
