### DISCUSSION TITLE
Argo Rollout Spec

### DISCUSSION THREAD

**Discussion by sidiney-crescencio** [argoproj/argo-rollouts#1309] [Q&A] [answered]
Hi there,

I'm running some tests with argo rollouts, but from what I can see in the docs doesn't seem to be possible to specify specs like:

- imagepullsecrets
- volumemounts
- env variables

Also, once I specify that in the rollout definition is ignored, and my pod cannot start, because it relies on these things to be healthy.
Is that how it works or am I missing something? Is there any way around for that ?

Thanks in advance.

**Comment by nextrevision** [comment, marked as answer]
We use rollouts quite and rely heavily on environment variables using the `env` and `envFrom` keys. The rollouts CRD should support what your asking, since it essentially mimics a deployment, see:
 
env: https://github.com/argoproj/argo-rollouts/blob/master/manifests/crds/rollout-crd.yaml#L848
volumeMounts: https://github.com/argoproj/argo-rollouts/blob/master/manifests/crds/rollout-crd.yaml#L1345
imagePullSecrets: https://github.com/argoproj/argo-rollouts/blob/master/manifests/crds/rollout-crd.yaml#L1946

These keys are case sensitive, however.

For example, the following works for me:

```
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: podinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: podinfo
      app.kubernetes.io/name: podinfo
  strategy:
    blueGreen:
      activeService: podinfo
      previewService: podinfo-preview
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: podinfo
        app.kubernetes.io/name: podinfo
    spec:
      containers:
        - name: podinfo
          image: 'stefanprodan/podinfo:latest'
          imagePullPolicy: Always
          env:
            - name: FOO
              value: bar
          ports:
            - containerPort: 9898
              protocol: TCP
            - containerPort: 9797
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9898
              scheme: HTTP
            initialDelaySeconds: 30
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 9898
              scheme: HTTP
          volumeMounts:
            - name: foo-config
              mountPath: /etc/foo
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: foo-config
          configMap:
            name: foo-config
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo
  labels:
    app.kubernetes.io/instance: podinfo
    app.kubernetes.io/name: podinfo
spec:
  type: ClusterIP
  ports:
    - name: '9898'
      protocol: TCP
      port: 9898
      targetPort: 9898
    - name: '9797'
      protocol: TCP
      port: 9797
      targetPort: 9797
  selector:
    app.kubernetes.io/instance: podinfo
    app.kubernetes.io/name: podinfo

---
apiVersion: v1
kind: Service
metadata:
  name: podinfo-preview
  labels:
    app.kubernetes.io/instance: podinfo
    app.kubernetes.io/name: podinfo
spec:
  type: ClusterIP
  ports:
    - name: '9898'
      protocol: TCP
      port: 9898
      targetPort: 9898
    - name: '9797'
      protocol: TCP
      port: 9797
      targetPort: 9797
  selector:
    app.kubernetes.io/instance: podinfo
    app.kubernetes.io/name: podinfo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: foo-config
data:
  foo.properties: |
    bar=baz
```
