### DISCUSSION TITLE
Working example to test BlueGreen Pre and Post Analysis

### DISCUSSION THREAD

**Discussion by shrey-183** [argoproj/argo-rollouts#1440] [Q&A]
Is there a complete example that can be used to test blueGreen rollout with pre and post analysis?
I saw in the documentation there is some snippet [here ](https://argoproj.github.io/argo-rollouts/features/analysis/#bluegreen-pre-promotion-analysis) for instance, however I was wondering if someone could point me to a concrete working example. I looked around the testing code and found the following manifest: 
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: bluegreen-analysis
spec:
  strategy:
    blueGreen:
      activeService: bluegreen-analysis-active
      previewService: bluegreen-analysis-preview
      prePromotionAnalysis:
        templates:
        - templateName: sleep-job
        args:
        - name: duration
          value: "5"
      postPromotionAnalysis:
        templates:
        - templateName: sleep-job
        args:
        - name: duration
          value: "5"
      autoPromotionEnabled: false
  selector:
    matchLabels:
      app: bluegreen-analysis
  template:
    metadata:
      labels:
        app: bluegreen-analysis
    spec:
      containers:
      - name: bluegreen-analysis
        image: nginx:1.19-alpine
        resources:
          requests:
            memory: 16Mi
            cpu: 5m

---
kind: Service
apiVersion: v1
metadata:
  name: bluegreen-analysis-active
spec:
  selector:
    app: bluegreen-analysis-active
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: bluegreen-analysis-preview
spec:
  selector:
    app: bluegreen-analysis-preview
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

```

however when I run `kubectl apply -f theAboveManifest.yaml` and then run `kubectl-argo-rollouts get rollout bluegreen-analysis --watch` I see the following output
```
Name:            bluegreen-analysis
Namespace:       argo-rollouts
Status:          ✖ Degraded
Message:         InvalidSpec: The Rollout "bluegreen-analysis" is invalid: spec.strategy.blueGreen.prePromotionAnalysis.templates[0].templateName: Invalid value: "sleep-job": analysistemplates.argoproj.io "sleep-job" not found
Strategy:        BlueGreen
Replicas:
  Desired:       1
  Current:       0
  Updated:       0
  Ready:         0
  Available:     0

NAME                  KIND     STATUS      AGE  INFO
⟳ bluegreen-analysis  Rollout  ✖ Degraded  95m  

```
I am not sure why this is happening, any comments would be much appreciated!

**Comment by songhohoon** [comment]
you must create AnalysisTemplate.
the error is Rollout cannot find AnalysisTemplate. `Invalid value: "sleep-job": analysistemplates.argoproj.io "sleep-job" not found`
See this link `https://argoproj.github.io/argo-rollouts/features/analysis/#bluegreen-pre-promotion-analysis`

i use just simple sleep template to make blue env standby.
```
kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: pass
spec:
  metrics:
  - name: pass
    failureLimit: 1
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: sleep
                image: alpine:3.8
                command: ["/bin/sh", "-c"]
                args: ["sleep 4h && exit 0"]
              restartPolicy: Never
          backoffLimit: 0
    count: 1
```
