### DISCUSSION TITLE
Is VPA supported by argo rollouts?

### DISCUSSION THREAD

**Discussion by uS-aito** [argoproj/argo-rollouts#1459] [Q&A] [answered]
Hello everyone,

I tried to apply vpa to rollout with the following manifest.
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: php-apache-rollout
spec:
  selector:
    matchLabels:
      run: php-apache-rollout
  replicas: 1
  template:
    metadata:
      labels:
        run: php-apache-rollout
    spec:
      containers:
      - name: php-apache
        image: k8s.gcr.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache-rollout
  labels:
    run: php-apache-rollout
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    run: php-apache-rollout
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: php-apache-vpa
spec:
  targetRef:
    apiVersion: "argoproj.io/v1alpha1"
    kind:       Rollout
    name:       php-apache-rollout
  updatePolicy:
    updateMode: "Auto"
```

I tried to load the pod, but the pod was not regenerated and the value of `resources.requests` remained the same.
vpa suggests a new value for requirements.
```
$ kubectl describe vpa
...
  Recommendation:
    Container Recommendations:
      Container Name:  php-apache
      Lower Bound:
        Cpu:     1765m
        Memory:  144703488
      Target:
        Cpu:     2240m
        Memory:  179306496
      Uncapped Target:
        Cpu:     2240m
        Memory:  179306496
      Upper Bound:
        Cpu:     253675m
        Memory:  20171456512
Events:          <none>
...
```

When I changed rollout to deployment and loaded it in the same way, the value of requirements was changed.I also looked through the documentation and found some mention of HPA, but no mention of VPA.
Does this mean that I can't use vpa with argo rollouts?
