### DISCUSSION TITLE
why rollout restarting is stuck

### DISCUSSION THREAD

**Discussion by 13567436138** [argoproj/argo-rollouts#1488] [Q&A]
```
Name:            reviews-v1
Namespace:       istio
Status:          ◌ Progressing
Message:         rollout is restarting
Strategy:        Canary
  Step:          4/4
  SetWeight:     100
  ActualWeight:  100
Images:          docker.io/istio/examples-bookinfo-reviews-v2:1.16.2 (stable)
Replicas:
  Desired:       5
  Current:       5
  Updated:       5
  Ready:         5
  Available:     5

NAME                                    KIND        STATUS         AGE    INFO
⟳ reviews-v1                            Rollout     ◌ Progressing  7m6s   
├──# revision:2                                                           
│  └──⧉ reviews-v1-6b87995785           ReplicaSet  ✔ Healthy      6m42s  stable
│     ├──□ reviews-v1-6b87995785-bk9vp  Pod         ✔ Running      6m42s  ready:2/2
│     ├──□ reviews-v1-6b87995785-clcxt  Pod         ✔ Running      6m28s  ready:2/2
│     ├──□ reviews-v1-6b87995785-t56lq  Pod         ✔ Running      6m28s  ready:2/2
│     ├──□ reviews-v1-6b87995785-xxbrm  Pod         ✔ Running      6m28s  ready:2/2
│     └──□ reviews-v1-6b87995785-rl6fz  Pod         ✔ Running      6m10s  ready:2/2
└──# revision:1                                                           
   └──⧉ reviews-v1-7f9bff4bbb           ReplicaSet  • ScaledDown   7m6s   
```
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: reviews-v1
  labels:
    app: reviews
    version: v1
spec:
  replicas: 5
  restartAt: "2021-09-11T16:16:20Z"
  selector:
    matchLabels:
      app: reviews
      version: v1
  template:
    metadata:
      labels:
        app: reviews
        version: v1
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
      - name: reviews
        image: docker.io/istio/examples-bookinfo-reviews-v1:1.16.2
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        ports:
        - containerPort: 9080
        resources:
          requests:
            cpu: 0.02
            memory: 10Mi
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
        securityContext:
          runAsUser: 1000
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
```
