### DISCUSSION TITLE
how to check revisionHistoryLimit,what command I can see history?

### DISCUSSION THREAD

**Discussion by 13567436138** [argoproj/argo-rollouts#1491] [Q&A]
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: reviews-v1
  labels:
    app: reviews
    version: v1
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: reviews
      version: v1
  template:
    metadata:
      labels:
        app: reviews
        version: v1
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
      - name: reviews
        image: docker.io/istio/examples-bookinfo-reviews-v1:1.16.2
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        ports:
        - containerPort: 9080
        resources:
          requests:
            cpu: 0.02
            memory: 10Mi
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
        securityContext:
          runAsUser: 1000
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}
  strategy:
    canary:
      maxSurge: 1
      maxUnavailable: 1
```
revisionHistoryLimit
how to check revisionHistoryLimit,what command I can see history?
