### DISCUSSION TITLE
the traffic through outbound|9080||productpage.istio.svc.cluster.local  I have set subset in vs.why not outbound|9080|v1|productpage.istio.svc.cluster.local

### DISCUSSION THREAD

**Discussion by 13567436138** [argoproj/argo-rollouts#1497] [Q&A]
[2021-09-11T22:53:19.644Z] "GET /productpage HTTP/1.1" 200 - via_upstream - "-" 0 5183 1083 1083 "172.20.0.0" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36 Edg/93.0.961.44" "8a48dac4-1303-9039-95fb-b9964cc1aa4d" "192.168.229.134:30684" "172.20.0.37:9080" outbound|9080||productpage.istio.svc.cluster.local 172.20.1.44:41474 172.20.1.44:8080 172.20.0.0:45531 - -

the traffic through outbound|9080||productpage.istio.svc.cluster.local  I have set subset in vs.why not outbound|9080|v1|productpage.istio.svc.cluster.local

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews-vs
spec:
  gateways:
  - istio/bookinfo-gateway
  hosts:
  - "*"
  http:
  - name: http-primary
    route:
    - destination:
        host: reviews-v1-stable
        subset: v1
      weight: 100
    - destination:
        host: reviews-v1-canary
        subset: v2
      weight: 0
```
