### DISCUSSION TITLE
why no no_healthy_upstream ?

### DISCUSSION THREAD

**Discussion by 13567436138** [argoproj/argo-rollouts#1499] [Q&A]
[2021-09-11T23:42:33.831Z] "GET /reviews/0 HTTP/1.1" 503 UH no_healthy_upstream - "-" 0 19 0 - "172.20.0.0" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36 Edg/93.0.961.44" "cc1bedc5-3f81-98e3-9f9b-41e5ea48e2bb" "192.168.229.134:30684" "-" outbound|9080|v1|reviews.istio.svc.cluster.local - 172.20.1.44:8080 172.20.0.0:16404 - http-primary

I have v1 pod ,why no endpoint?
```
release/canary/argo/rollout-canary-istio-destinationRule.yaml

kubectl apply -f rollout-canary-istio-destinationRule.yaml -n istio


apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: reviews-v1
  labels:
    app: reviews
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      argo: argo
  template:
    metadata:
      labels:
        app: reviews
        argo: argo
        version: v1
        version: v2
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
      - name: reviews
        image: docker.io/istio/examples-bookinfo-reviews-v1:1.16.2
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        ports:
        - containerPort: 9080
        resources:
          requests:
            cpu: 0.02
            memory: 10Mi
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
        securityContext:
          runAsUser: 1000
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}
  strategy:
    canary:
      trafficRouting:
        istio:
          virtualService:
            name: reviews-vs
            routes:
            - http-primary
          destinationRule:
            name: reviews
            canarySubsetName: v2
            stableSubsetName: v1
      steps:
      - setWeight: 20
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}






release/canary/argo/argo-vs-reviews-subset.yaml

kubectl apply -f argo-vs-reviews-subset.yaml -n istio



apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews-vs
spec:
  gateways:
  - istio/bookinfo-gateway
  hosts:
  - "*"
  http:
  - name: http-primary
    route:
    - destination:
        host: reviews
        subset: v1
      weight: 100
    - destination:
        host: reviews
        subset: v2
      weight: 0



release/canary/argo/dr-reviews.yaml

kubectl apply -f dr-reviews.yaml -n istio



apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews
spec:
  host: reviews.istio.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
  subsets:
  - name: v1
    labels:
      version: v1
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
  - name: v2
    labels:
      version: v2
    trafficPolicy:
      loadBalancer:
        simple: LEAST_CONN




```
