### DISCUSSION TITLE
how to understand setCanaryScale,I can not see any affect.no new pod created?

### DISCUSSION THREAD

**Discussion by 13567436138** [argoproj/argo-rollouts#1500] [Q&A]
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: reviews-v1
  labels:
    app: reviews
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v1
  template:
    metadata:
      labels:
        app: reviews
        version: v1
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
      - name: reviews
        image: docker.io/istio/examples-bookinfo-reviews-v1:1.16.2
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        ports:
        - containerPort: 9080
        resources:
          requests:
            cpu: 0.02
            memory: 10Mi
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
        securityContext:
          runAsUser: 1000
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}
  strategy:
    canary:
      trafficRouting:
        istio:
          virtualService:
            name: reviews-vs
            routes:
            - http-primary
          destinationRule:
            name: reviews
            canarySubsetName: v2
            stableSubsetName: v1
      steps:
      - setWeight: 20
      - setCanaryScale:
          matchTrafficWeight: true
          replicas: 3
          weight: 40
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
```
how to understand setCanaryScale,I can not see any affect.no new pod created?
