### DISCUSSION TITLE
what‘s the behavior of consecutiveErrorLimit？I tested reach consecutiveErrorLimit will not degrade

### DISCUSSION THREAD

**Discussion by 13567436138** [argoproj/argo-rollouts#1502] [Q&A] [answered]
```
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 60s
    count: 5
    successCondition: result[0] >= 0.5
    failureLimit: 3
    consecutiveErrorLimit: 2
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            metadata:
              annotations:
                sidecar.istio.io/inject: “true”
            spec:
              containers:
              - name: test
                image: busybox
                command: [wget]
                args: ["http://192.168.229.134:30684/error"]
              restartPolicy: Never
```

what‘s the behavior of consecutiveErrorLimit？I tested reach consecutiveErrorLimit will not degrade
