### DISCUSSION TITLE
why my config will not trigger bluegreen update

### DISCUSSION THREAD

**Discussion by 13567436138** [argoproj/argo-rollouts#1505] [Q&A] [answered]
```
release/blueGreen/argo-rollout/bg-reviews-activeService-previewService.yaml

kubectl apply -f bg-reviews-activeService-previewService.yaml -n istio

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: reviews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
      - name: reviews
        image: docker.io/istio/examples-bookinfo-reviews-v1:1.16.2
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        ports:
        - containerPort: 9080
        resources:
          requests:
            cpu: 0.02
            memory: 10Mi
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
        securityContext:
          runAsUser: 1000
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}
  strategy:
    blueGreen: 
      activeService: rollout-bluegreen-active
      previewService: rollout-bluegreen-preview


svc-rollout-bluegreen-active.yaml

kubectl apply -f svc-rollout-bluegreen-active.yaml -n istio


apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-active
spec:
  ports:
  - name: http
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: reviews


svc-rollout-bluegreen-preview.yaml

kubectl apply -f svc-rollout-bluegreen-preview.yaml -n istio


apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-preview
spec:
  ports:
  - name: http
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: reviews



```
