### DISCUSSION TITLE
Generated resources by Kustomize are not generated as expected when using "rollout_cr_schema.json"

### DISCUSSION THREAD

**Discussion by morix1500** [argoproj/argo-rollouts#1610] [Q&A]
This repository provides an OpenAPISchema file.
https://github.com/argoproj/argo-rollouts/blob/master/docs/features/kustomize/rollout_cr_schema.json

I use it when applying resources to k8s by Kustomize.
But generated resources by Kustomize do not seem to merge well.

Sample repository: https://github.com/morix1500/argorollouts-kustomize-sample

I prepared the following samples to test `kustomize build`.(Kustomize version is 4.2.0)

```yaml
# base/kustomization.yaml
resources:
  - rollouts.yaml
openapi:
  path: rollout_cr_schema.json
```

```yaml
# base/rollouts.yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: sample
spec:
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: AAA
          value: AAA
        - name: BBB
          value: BBB
```

```yaml
# overlays/sample/rollouts.yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: sample
spec:
  template:
    spec:
      containers:
      - name: rollouts-demo
        env:
        - name: CCC
          value: CCC
```

Expectation generated resource:

```yaml
$ kustomize build overlays/sample/
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: sample
spec:
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - env:
        - name: CCC
          value: CCC
        - name: AAA
          value: AAA
        - name: BBB
          value: BBB
        image: argoproj/rollouts-demo:blue
        imagePullPolicy: Always
        name: rollouts-demo
        ports:
        - containerPort: 8080
```

Actual generated resource:

```yaml
$ kustomize build overlays/sample/
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: sample
spec:
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - env:
        - name: CCC
          value: CCC
        image: argoproj/rollouts-demo:blue
        imagePullPolicy: Always
        name: rollouts-demo
        ports:
        - containerPort: 8080
```

Apparently, the env section in resources does not merge well.

I add a merge key rule to the OpenAPISchema file.
https://github.com/morix1500/argorollouts-kustomize-sample/blob/main/base/rollout_cr_schema_v2.json#L267-L268

Then generated resources by Kustomize were generated as expected.

---

Is this something I'm doing wrong?
Or is it a bug?
