### DISCUSSION TITLE
How to configure Notifications for ArgoRollouts

### DISCUSSION THREAD

**Discussion by dvp34** [argoproj/argo-rollouts#1993] [Q&A]
Hello,

I am using only argo-rollouts for canary deployments. which seems pretty neat. 
Now I want to use the notifications described here - https://argoproj.github.io/argo-rollouts/features/notifications/
few things are not so very clear to me. So requesting some clarifications.

-  Do we need to install notification controller? - https://argocd-notifications.readthedocs.io/en/stable/#getting-started

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-notification-configmap
data:
  # detail of the templates is omitted
  # detail of the triggers is omitted
  service.slack: |
    token: $slack-token
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-rollouts-notification-secret
stringData:
  slack-token: <my-slack-token>
```
in the above stub, should the names be as provided above? does these need to created in each namespace or just in `argo-rollouts` namespace?

 I did create the above resources in `argo-rollouts` namespace, subscribed rollout resource with the annotations but I don't see any notifications getting triggered. How could I triage this? 
 I would really appreciate any suggestions on this. Thanks!

**Comment by RaviHari** [comment]
Hi @durprasa ,

1. You don't need to install notification controller it is already embedded in argo-rollouts.
2. Yes you need to keep the names of configmap and secret as given.
3. The cm and secret need to be created in argo-rollouts namespace.
4. You can check details here: https://github.com/argoproj/argo-rollouts/issues/1894 for notification configuration with slack.

**Reply by dvp34** [reply]
@RaviHari Thanks for the input. Although we have configured the configmap and secret and I do see in the logs 
```
time="2022-04-26T21:08:10Z" level=info msg="Trigger on-rollout-step-completed result: []" resource=onecloud/deploy-test
time="2022-04-26T21:08:10Z" level=info msg="Trigger on-rollout-updated result: []" resource=onecloud/deploy-test
```
But I don't see notifications in teams channel. 
Could you please help what could be reason or things that you think that I can triage?

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-notification-configmap
  namespace: argo-rollouts
data:
  service.teams: |
    recipientUrls:
      channelName: $channel-teams-url
  defaultTriggers: |
    - on-rollout-completed
    - on-rollout-step-completed
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-rollouts-notification-secret
  namespace: argo-rollouts
stringData:
  channel-teams-url: <team url>

```

and updated annotations for rollout resource

```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    meta.helm.sh/release-name: deploy-test
    meta.helm.sh/release-namespace: onecloud
    notifications.argoproj.io/subscribe.on-rollout-step-completed.teams: channelName
    notifications.argoproj.io/subscribe.on-rollout-updated.teams: channelName
....
```
I see that the issue that you have referenced has a comment that itsn't working for another person. https://github.com/argoproj/argo-rollouts/issues/1894#issuecomment-1087830104 

when you can please provide any suggestions or inputs you can. Thanks! Appreciate your help.
