### DISCUSSION TITLE
rollouts stuck and unable to proceed when initial deployment contains an error

### DISCUSSION THREAD

**Discussion by raffaelespazzoli** [argoproj/argo-rollouts#2079] [Q&A]
When I first create a deployment via argocd, the image does not exist yet, so I use a dummy tag value. Argo rollouts tries to deploy and gets a set of pods unable to start. When an image is built, the argocd application is updated with the correct tag, but argo rollouts does not recover from the error. 
I have 3 environments `dev` with one replicas, `qa` with three replicas and `prod` with with 5 replicas and interetsingly in prod argo rollouts is able to recover from the error.
here is what the rollout definition loooks like:
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include ".helm.fullname" . }}
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  workloadRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include ".helm.fullname" . }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include ".helm.selectorLabels" . | nindent 6 }}      
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 10}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
      # Reference to a Service which the controller updates to point to the canary ReplicaSet
      canaryService: {{ include ".helm.fullname" . }}-canary
      # Reference to a Service which the controller updates to point to the stable ReplicaSet
      stableService: {{ include ".helm.fullname" . }}-stable
      trafficRouting:
        istio:
          virtualServices:
          # One or more virtualServices can be configured
          # Reference to a VirtualService which the controller updates with canary weights
          - name: {{ include ".helm.fullname" . }}
```
and here is the status of the roll out in qa:
```
Name:            raffa-qrs2
Namespace:       brightly-demo-app-qa
Status:          ✖ Degraded
Message:         RolloutAborted: Rollout aborted update to revision 2
Strategy:        Canary
  Step:          0/8
  SetWeight:     0
  ActualWeight:  0
Images:          quay.io/raf-backstage-demo/raffa-qrs2:d80e0d17e590738626de06c65cf8e000efdd2573 (canary)
                 quay.io/raf-backstage-demo/raffa-qrs2:dummy (stable)
Replicas:
  Desired:       3
  Current:       4
  Updated:       1
  Ready:         1
  Available:     1

NAME                                    KIND        STATUS              AGE   INFO
⟳ raffa-qrs2                            Rollout     ✖ Degraded          173m  
├──# revision:2                                                               
│  └──⧉ raffa-qrs2-55b688587c           ReplicaSet  ✔ Healthy           167m  canary
│     └──□ raffa-qrs2-55b688587c-p5swc  Pod         ✔ Running           167m  ready:2/2
└──# revision:1                                                               
   └──⧉ raffa-qrs2-bd7748f9d            ReplicaSet  ◌ Progressing       173m  stable
      ├──□ raffa-qrs2-bd7748f9d-hfk8m   Pod         ⚠ ImagePullBackOff  173m  ready:1/2
      ├──□ raffa-qrs2-bd7748f9d-cmlcd   Pod         ⚠ ImagePullBackOff  173m  ready:1/2
      └──□ raffa-qrs2-bd7748f9d-qn9bc   Pod         ⚠ ImagePullBackOff  173m  ready:1/2
```
Because of the fact that this works in prod with 5 pods, I suspect that the canary steps determine this behavior.
Can someone explain to me what is going on and possibly how to fix this issue?
