### DISCUSSION TITLE
How to overriding pod env using Bluegreen deployment?

### DISCUSSION THREAD

**Discussion by effy-coding** [argoproj/argo-rollouts#2114] [Q&A]
In preview(green) pod, i want to use some different env values from active(blue) pod. Is it possible?

For example, 

```
strategy:
    blueGreen: 
      activeService: rollout-bluegreen-active
      previewService: rollout-bluegreen-preview
      previewEnv:
       foo: baz
```
