### DISCUSSION TITLE
ValidationError: unknown field "setHeaderRoute"

### DISCUSSION THREAD

**Discussion by labaq** [argoproj/argo-rollouts#2124] [Q&A] [answered]
I have follow this  https://argoproj.github.io/argo-rollouts/features/traffic-management/#traffic-routing-based-on-a-header-values-for-canary to setup my rollout, but get error response
```
error validating data: [ValidationError(Rollout.spec.strategy.canary.steps[1]): unknown field "setHeaderRoute" in io.argoproj.v1alpha1.Rollout.spec.strategy.canary.steps, ValidationError(Rollout.spec.strategy.canary.steps[3]): unknown field "setHeaderRoute" in io.argoproj.v1alpha1.Rollout.spec.strategy.canary.steps]
```
here is my rollout spec
```
  strategy:
    canary:
      dynamicStableScale: true
      steps:
        - setWeight: 25
        - setHeaderRoute:
            match:
              - headerName: X-Canary
                headerValue:
                  exact: test
            name: set-header-1
        - pause: {}
        - setHeaderRoute:
            name: set-header-1
        - setWeight: 50
        - pause: {}
        - setWeight: 75
        - pause: {}
      trafficRouting:
        istio:
          destinationRule:
            canarySubsetName: canary
            name: rollout-destrule
            stableSubsetName: stable
          virtualService:
            name: istio-vs
            routes:
              - primary
```
am i missing something or this is a bug?

I have test on version 2.14.0 and 2.17.0
