### DISCUSSION TITLE
ClusterRole in namespace-install

### DISCUSSION THREAD

**Discussion by theJaxon** [argoproj/argo-rollouts#2132] [Q&A]
- I'm deploying argo-rollouts in a single namespace and I wanted to use the resources in [namespace-install](https://github.com/argoproj/argo-rollouts/tree/master/manifests/namespace-install) 
- There's already a patch in place for changing ClusterRole to Role for namespaced mode but it only affects a single ClusterRole that is [argo-rollouts](https://github.com/argoproj/argo-rollouts/blob/master/manifests/role/argo-rollouts-clusterrole.yaml#L4)
- There are 3 other ClusterRoles that still need to be applied which is why I'm asking, are ClusterRoles needed for argo-rollouts to function correctly ?
- Shouldn't Kustomization YAML patch be as follows In order to patch all Cluster Roles ?
```yaml
patchesJson6902:
- path: clusterrole-to-role.yaml
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: '.*'
    version: v1
```
