### DISCUSSION TITLE
How does maxSurge and maxUnavailable work for canary strategy?

### DISCUSSION THREAD

**Discussion by Vignesh-Au** [argoproj/argo-rollouts#2237] [Q&A] [answered]
Hello,

I am using canary strategy for an application with following config.
```
replicaCount: 3
maxSurge: 1
maUnavailable: 0
steps:
          - setWeight: 20
          - pause: { }
          - setWeight: 40
          - pause: { duration: 30 }
          - setWeight: 60
          - pause: { duration: 30 }
          - setWeight: 80
          - pause: { duration: 30 }
```

Based on [this documentation](https://argoproj.github.io/argo-rollouts/features/specification/#:~:text=%23%20update.%20%2Boptional-,maxUnavailable,-%3A%201%0A%0A%20%20%20%20%20%20%23%20The), I expected the following behavior.

1. Stable release is already up and running with 3 pods
2. Canary release starts with pod 1
3. Completes analysis run and passed
4. Resume deployment manually due to indefinite pause in steps
5. Canary release starts pod 2 and Stable release terminates 1 pod
6. Completes analysis run and passed
7. Pause for 30s, starts 3rd canary pod and terminates 2nd stable pod
8. Completes analysis run and passed
9. Pause for 30s, make canary as stable and terminates 3rd previous stable pod and scale down previous version.

But what I am missing is the previous stable version pods does not terminate during the canary process. It waits for all the canary pods to be successfully created, makes the canary release as stable and then scales down all previous version pods. So, during deployment, it takes double the resources (6 pods) at one stage. Is this the default behavior? Or should I change any configuration to meet my expected scenario?
