### DISCUSSION TITLE
unknown field "trafficRouting" in Bluegreen deployment

### DISCUSSION THREAD

**Discussion by ShahadSha** [argoproj/argo-rollouts#2302] [Q&A] [answered]
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-bluegreen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rollout-bluegreen
  template:
    metadata:
      labels:
        app: rollout-bluegreen
    spec:
      containers:
      - name: superapi
        image: shahadsha/hello-world:35
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 6789
  strategy:
    blueGreen:
      activeService: rollout-bluegreen-active
      previewService: rollout-bluegreen-preview
      autoPromotionEnabled: false

      trafficRouting:
        istio:
          virtualService:
            name: springboot-vs  # required
            routes:
            - primary   


```

### Trying to deploy with istio but it shows the error on the argo cd
`error validating data: ValidationError(Rollout.spec.strategy.blueGreen): unknown field "trafficRouting" in io.argoproj.v1alpha1.Rollout.spec.strategy.blueGreen`

###searched the whole internet to deploy with istio, argo rollouts, bluegreen 
sorry for grammer mistakes
