### DISCUSSION TITLE
Change Image Rollouts with Kustomize

### DISCUSSION THREAD

**Discussion by yusufitsari** [argoproj/argo-rollouts#2392] [Q&A] [answered]
Hi all,

Today i'm trying to integrate argo rollouts using kustomize. unfortunately, the container image is not updated using `kustomize images newTag`. is it still not supported updating image with kustomize or there's something wrong with my configuration? 
here's my configuration

rollouts.yaml
``` yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: testing
spec:
  replicas: 0
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: testing
  template:
    metadata:
      labels:
        app: testing
    spec:
      containers:
      - name: testing
        image: testing:stable
```
overlays/dev/kustomize.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: testing

images:
- name: testing
  newTag: latest
```

kubectl version:
- Client: v1.25.2
- Server: v1.21.14

with that configuration somehow the imageTag is not changing to `latest` when running `kubectl kustomize`. for now the workaround is using `patchesJson6902` but i think its ugly.

thanks
