### DISCUSSION TITLE
Cookie based routing with Argo Rollouts

### DISCUSSION THREAD

**Discussion by shirel-h** [argoproj/argo-rollouts#2401] [Q&A]
Hi,
I'm trying to achieve canary deployment that is based only on cookies and without using weights at all.
Is it possible to do it using `- setHeaderRoute`?
I tried something like that, but it's not achieving the goal, the traffic is randomly routed to stable/canary deployments.
```
strategy:
    canary:
       canaryService: rollout-demo-canary
       stableService: rollout-demo-stable
       trafficRouting:
        managedRoutes:
          - name: by-version-route
        istio:
          virtualService:
            name: rollout-demo-vsvc
       steps:
           - setCanaryScale:
                weight: 20
           - setHeaderRoute: 
                name: "by-version-route"
                match:
                   - headerName: Cookie
                     headerValue:
                           exact: cookie-name=v1.0.0
           - pause: {}
```
