### DISCUSSION TITLE
Is it possible to disable canary service when no rollouts underway?

### DISCUSSION THREAD

**Discussion by buddyledungarees** [argoproj/argo-rollouts#2435] [Q&A]
I have setup a basic canary deployment test that uses istio traffic routing that looks something like:

```
    steps:
      - setCanaryScale:
          replicas: 1
          #weight: 10  #alternatively set as a percentage of spec.replicas
      - pause:
          duration: 1m
      - setWeight: 10  # percentage
      - pause: {}      # pause indefinitely
 ```

Istio virtualservice snippet:
```
  - name: http-rest
    match:
    - port: 443
    route:
    - destination:
        host: my-test
        port:
          number: 8080
      weight: 100
    - destination:
        host: my-test-canary
        port:
          number: 8080
      headers:
        response:
          set:
            X-Custom-Canary: "true"
      weight: 0
  - name: canary-traffic
    match:
    - port: 443
      authority:
        exact: my-service-canary.mydomain.com
      gateways:
      - my-gateway
    route:
    - destination:
        host: my-test-canary
        port:
          number: 8080
      headers:
        response:
          set:
            X-Custom-Canary: "true"
      weight: 100
```

The traffic shifting and canary rollouts work as documented however I wanted to see if I can disable access to the canary endpoint if there's no rollout in progress. It looks like the k8s service selector still matches the promoted pods.

I realize this starts to sound more like a blue/green deployment but just curious if there's any way under a canary strategy to do this? I looked at doing something at the istio level via outlier or circuit breaking but because the k8s service endpoint for the canary service shows valid pods, I don't think it'll work.
