### DISCUSSION TITLE
Metrics are doubled counted in Prometheus after canary rollout completes?

### DISCUSSION THREAD

**Discussion by MatthewHou** [argoproj/argo-rollouts#2561] [Q&A]
We are using Prometheus ServiceMonitor to collect pod metrics. The service monitor is configured to scrape both stable and canary services. 

````
---
apiVersion: v1
kind: Service
metadata:
  name: service-stable
  labels:
    app.kubernetes.io/name: my-app
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
      protocol: TCP
    - port: 9095
      targetPort: metrics
      name: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: my-app
---
apiVersion: v1
kind: Service
metadata:
  name: service-canary
  labels:
    app.kubernetes.io/name: my-app
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
      protocol: TCP
    - port: 9095
      targetPort: metrics
      name: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: my-app
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: my-app
  name: service-monitor
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: metrics
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: instance
  selector:
    matchLabels:
      app.kubernetes.io/name: myapp
````

We noticed that metrics count are correctly during the canary rollout but becomes double counted once the rollout completes.

I looked deeper and it appears that Prometheus are scrapping every pod twice once rollout completes because both stable and canary services point to the same set of pods. 

Is there a issue with my monitoring or rollout setup?  Or this is a know issue / limitation with argo rollouts? Is there any workaround to address this issue?
