### DISCUSSION TITLE
Can't setup Teams Notifications triggers.

### DISCUSSION THREAD

**Discussion by Duck5el** [argoproj/argo-rollouts#2588] [Q&A]
I am getting an error msg:

"Failed to process: failed to unmarshal template analysis-run-error: error converting YAML to JSON: yaml: line 2: did not find expected key"

My template looks like this:
```yaml
  template.analysis-run-error: |-
    message: Test
    teams:
      title: {{.rollout.metadata.name}} analysis run
      text: Rollout {{.rollout.metadata.name}}'s analysis run is in error state.
      summary: "{{.rollout.metadata.name}} analysis run error!"
      themeColor: "#00ffff"
      sections: |
      [{
        "facts": [
          {
            "name": "Rollout",
            "value": "{{.rollout.metadata.name}}"
          }
        ]
      }]
```

I followed the entire instruction [argo-rollouts/generated/notification-services/teams](https://argoproj.github.io/argo-rollouts/generated/notification-services/teams/)

And after that I found [this](https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/troubleshooting-errors/#service-type-xxxx-is-not-supported)

Could it be that Argo-Rollout integrated [Notifications Engine](https://github.com/argoproj/notifications-engine).
Like Mentioned [argo-rollouts/features/notifications/#notifications](https://argoproj.github.io/argo-rollouts/features/notifications/#notifications) is not on the newest version and is not supporting Teams?
