### DISCUSSION TITLE
How to set canary traffic percentage?

### DISCUSSION THREAD

**Discussion by caibirdme** [argoproj/argo-rollouts#2620] [Q&A] [answered]
Say, I have a HPA deployment, I want to upgrade it from v1 to v2, and I want to use canary strategy like this:
```yaml
trafficRouting:
  nginx:
    xxx
steps:
- setWeight: 5
- puase: {}
- setWeight: 20
- puase: {} 
- ...
```
I want to know if there's a way to set the percentage of traffic to v2 at the same time? Like upgrade 
```yaml
- upgrade 5% pod
- give them 10% traffic
- pause: {}
- upgrade 20% pod
- give them 50% traffic
- ...
```
