### DISCUSSION TITLE
Rollout controller pod cert for external APIs?

### DISCUSSION THREAD

**Discussion by trv-bmpage** [argoproj/argo-rollouts#2650] [Ideas]
It would be nice to mount certs onto the rollouts controller pod, these certs are for connecting to external APIs during notification calls. Would it be possible to provide this option in the values file of the chart.
I see that the same issues was suggested before - #https://github.com/argoproj/argo-rollouts/issues/1192. 
However I dont see an option in the chart.

https://github.com/argoproj/argo-helm/blob/main/charts/argo-rollouts/templates/controller/deployment.yaml 
```
   volumes:
              - name: {{ .Values.controller.volumename }}
                secret:
                  #Create a secret and add in the dependent chart 
                             secretName: {{ .Values.controller.certsecret }} 
              containers:
              - image: "{{ .Values.controller.image.registry }}/{{ .Values.controller.image.repository }}:{{ default .Chart.AppVersion .Values.controller.image.tag }}"
                volumeMounts:
                               - name: {{ .Values.controller.volumename }}
                                           mountPath: {{ .Values.controller.volumepath }} 
                                           readOnly: true  
```
