### DISCUSSION TITLE
Analysis Datadog query with division

### DISCUSSION THREAD

**Discussion by meskander-nydig** [argoproj/argo-rollouts#2666] [Q&A]
Hello,
I am trying to create a datadog query in argo rollouts analysis template to calculate success or error rate, like in the [doc examples using prometheus](https://argo-rollouts.readthedocs.io/en/latest/features/analysis/#background-analysis:~:text=%3A%2010m%7D-,AnalysisTemplate,-apiVersion%3A%20argoproj) 
```
    provider:
      prometheus:
        address: http://prometheus.example.com:9090
        query: |
          sum(irate(
            istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}",response_code!~"5.*"}[5m]
          )) /
          sum(irate(
            istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}"}[5m]
          ))
```
I create an analysis template using args so the query can be directly passed in from the user
```
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate
spec:
  args:
  - name: error_query
  - name: error_query_success_condition
  metrics:
  - name: error-rate
    successCondition: "{{`{{args.error_query_success_condition}}`}}"
    interval: 60s
    count: 5
    provider:
      datadog:
        query: "{{`{{args.error_query}}`}}"
        interval: 60s
```
The query I'm passing in to args.error_query is:
```
            sum:istio_requests.count{region:{{ .Values.region }} AND destination_service_name:{{ .Release.Name }} AND (response_code:5* OR response_code:4*)} /
            sum:istio_requests.count{region:{{ .Values.region }} AND destination_service_name:{{ .Release.Name }}}
```
Problem is, I don't see anything happening in the analysis run and the rollout succeeds even if the error rate is higher than expected
