### DISCUSSION TITLE
How to filter Analysis for canary revisions?

### DISCUSSION THREAD

**Discussion by jasondamour** [argoproj/argo-rollouts#2706] [Q&A] [answered]
Hello,

We are using Argo Rollouts Canary strategy, on a GKE cluster with istio (but not using Istio for Argo traffic splitting). 

Right now, we're using analysis runs to determine the number of 5XX responses to the service, which looks like this:
```
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
spec:
  args:
  - name: service-name
  metrics:
  - consecutiveErrorLimit: 10000
    failureLimit: 5
    initialDelay: 20s
    interval: 15s
    name: failure-rate
    provider:
      prometheus:
        address: http://prometheus.istio-system.svc.cluster.local:9090
        query: |
          (
              sum(rate(istio_requests_total{destination_service=~"{{ args.service-name }}", response_code=~"5.*"}[30s]))
              /
              ((sum(rate(istio_requests_total{destination_service=~"{{ args.service-name }}"}[30s])) > 0) or vector(1))
          )
          or vector(0)
    successCondition: result[0] <= 0.1
```

However, there is a **major** flaw, where this prometheus query returns the number of 5XX for both the stable AND canary revisions. We need to only run analysis on the traffic being sent to the new canary revision pods.

Is this possible via a system argument? Does (or could) argo expose the new replicaset ID to the analysis run, so we could use it to filter? Or, if we used istio traffic routing, does that enable us to filter for traffic of the canary revision?

**Comment by zachaller** [comment, marked as answer]
You could always pass down the canary hash from in the rollout object something like

```
      args:
        - name: stable-hash
          valueFrom:
            podTemplateHashValue: Stable
        - name: canary-hash
          valueFrom:
            podTemplateHashValue: Latest
```
