### DISCUSSION TITLE
Support OAuth2 for analysis provider

### DISCUSSION THREAD

**Discussion by OpenGuidou** [argoproj/argo-rollouts#2909] [Ideas]
Hello,

If we use OAuth 2 as authentication for a provider, there is currently no way to execute the small logic to get an access token before running the analysis.

Do you think it would be a valid improvement to support that ?

In the PrometheusMetric, we have available an Authentication for AWS sigv4.
It could be enhanced to support also OAuth2 protocol.

I would propose the following structure:

For Prometheus:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: args-example
spec:
  args:
  - name: service-name
  - name: api-url
    value: http://example/measure
  # from secret
  - name: oauthSecret
    valueFrom:
      secretKeyRef:
        name: oauth-secret
        key: secret
provider:
      prometheus:
        address: "{{ args.api-url }}"
        authentication:
          type: oauth2
          url: https://myoauthprovider
          clientId: someid
          secret: "{{ args.oauthSecret }}" 
        query: |
          sum(irate(
            istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}",response_code!~"5.*"}[5m]
          )) /
          sum(irate(
            istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}"}[5m]
          ))
```

Also available for web:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: args-example
spec:
  args:
  - name: service-name
  - name: api-url
    value: http://example/measure
  # from secret
  - name: oauthSecret
    valueFrom:
      secretKeyRef:
        name: oauth-secret
        key: secret
    provider:
      web:
        url: "{{ args.api-url }}?service={{ args.service-name }}"
        timeoutSeconds: 20 # defaults to 10 seconds
        authentication:
          type: oauth2
          url: https://myoauthprovider
          clientId: someid
          secret: "{{ args.oauthSecret }}" 
        jsonPath: "{$.data.ok}"
```

The OAuth authorization would be run before the analysis actual run, and the "Authorization: Bearer " header would be appended to the actual api call (prom or web) with the access_token resolved.

Thanks
