### DISCUSSION TITLE
Argocd rollouts & linkerd

### DISCUSSION THREAD

**Discussion by dmouse** [argoproj/argo-rollouts#2972] [General]
I'm trying to integrate `rollouts` with `linkerd` and `traefik` using kustomize but when I tried to deploy a rollout it says that `the server could not find the requested resource (post trafficsplits.split.smi-spec.io)`  I saw the issue #2125 and I added the patch to the controller but nothing happened 

full error
```
time="2023-08-21T15:42:25Z" level=info msg="rollout syncHandler queue retries: 6063 : key \"linkerd/rollouts-demo\"" namespace=linkerd rollout=rollouts-demo
time="2023-08-21T15:42:25Z" level=error msg="the server could not find the requested resource (post trafficsplits.split.smi-spec.io)\n" error="<nil>"
time="2023-08-21T15:42:25Z" level=info msg="Event(v1.ObjectReference{Kind:\"Rollout\", Namespace:\"linkerd\", Name:\"rollouts-demo\", UID:\"ee47857a-7779-4f9f-baa3-455274087899\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"197679299\", FieldPath:\"\"}): type: 'Normal' reason: 'TrafficSplitNotCreated' TrafficSplit `rollouts-demo` failed creation: the server could not find the requested resource (post trafficsplits.split.smi-spec.io)"
time="2023-08-21T15:42:25Z" level=info msg="Event(v1.ObjectReference{Kind:\"Rollout\", Namespace:\"linkerd\", Name:\"rollouts-demo\", UID:\"ee47857a-7779-4f9f-baa3-455274087899\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"197679299\", FieldPath:\"\"}): type: 'Warning' reason: 'TrafficRoutingError' the server could not find the requested resource (post trafficsplits.split.smi-spec.io)"
time="2023-08-21T15:42:35Z" level=info msg="Started syncing rollout" generation=1 namespace=linkerd resourceVersion=197679299 rollout=rollouts-demo
time="2023-08-21T15:42:35Z" level=info msg="delaying service switch from  to d5cf99ddf: ReplicaSet not fully available" namespace=linkerd rollout=rollouts-demo service=rollouts-demo-canary
time="2023-08-21T15:42:35Z" level=info msg="Found 1 TrafficRouting Reconcilers" namespace=linkerd rollout=rollouts-demo
time="2023-08-21T15:42:35Z" level=info msg="Reconciling TrafficRouting with type 'SMI'" namespace=linkerd rollout=rollouts-demo
time="2023-08-21T15:42:35Z" level=info msg="TrafficSplit `rollouts-demo` failed creation: the server could not find the requested resource (post trafficsplits.split.smi-spec.io)" event_reason=TrafficSplitNotCreated namespace=linkerd rollout=rollouts-demo
time="2023-08-21T15:42:35Z" level=warning msg="the server could not find the requested resource (post trafficsplits.split.smi-spec.io)" event_reason=TrafficRoutingError namespace=linkerd rollout=rollouts-demo
time="2023-08-21T15:42:35Z" level=error msg="roCtx.reconcile err the server could not find the requested resource (post trafficsplits.split.smi-spec.io)" generation=1 namespace=linkerd resourceVersion=197679299 rollout=rollouts-demo
time="2023-08-21T15:42:35Z" level=info msg="Reconciliation completed" generation=1 namespace=linkerd resourceVersion=197679299 rollout=rollouts-demo time_ms=8.186067
time="2023-08-21T15:42:35Z" level=error msg="rollout syncHandler error: the server could not find the requested resource (post trafficsplits.split.smi-spec.io)" namespace=linkerd rollout=rollouts-demo
```

### Files

`argo-rollout.yaml`

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts-develop
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: argo
  source:
    path: bases/argo-rollouts
    repoURL: git@github.com/...
    targetRevision: develop
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
```

`kustimization.yaml`
```
namespace: argo

resources:
  - https://github.com/argoproj/argo-rollouts/releases/download/v1.5.1/install.yaml
  - https://github.com/argoproj/argo-rollouts/releases/download/v1.5.1/dashboard-install.yaml

images:
  - name: quay.io/argoproj/argo-rollouts
    newTag: v1.5.1

patches:
  - patch: |
      - op: replace
        path: /subjects/0/namespace
        value: argo
    target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
      name: argo-rollouts
  - patch: |
      - op: replace
        path: /subjects/0/namespace
        value: argo
    target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
      name: argo-rollouts-dashboard
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args
        value:
          - --traffic-split-api-version=v1alpha3
    target:
      group: apps
      version: v1
      kind: Deployment
      name: argo-rollouts
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "0.1"
            memory: 32Mi
          limits:
            cpu: "0.1"
            memory: 64Mi
    target:
      group: apps
      version: v1
      kind: Deployment
```

`rollout.yaml`

```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  replicas: 1
  strategy:
    canary:
      canaryService: rollouts-demo-canary
      stableService: rollouts-demo-stable
      trafficRouting:
        smi: {}
      steps:
      - setWeight: 5
      - pause: {}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: rollouts-demo
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
```

```bash
$ kubectl auth can-i create trafficsplits.split.smi-spec.io                             
Warning: the server doesn't have a resource type 'trafficsplits' in group 'split.smi-spec.io'
yes
```

`live ClusterRole manifest`

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: ....
  creationTimestamp: '2022-11-10T04:45:11Z'
  labels:
    app.kubernetes.io/component: rollouts-controller
    app.kubernetes.io/instance: argo-rollouts-develop
    app.kubernetes.io/name: argo-rollouts
    app.kubernetes.io/part-of: argo-rollouts
  name: argo-rollouts
  resourceVersion: '86367988'
  uid: 64aeba32-ea6b-4a1f-bd24-733f87b4b0d8
rules:
  - ....
  - apiGroups:
      - split.smi-spec.io
    resources:
      - trafficsplits
    verbs:
      - create
      - watch
      - get
      - update
      - patch
   ....
```

Any thoughts to help me solve this?
