### DISCUSSION TITLE
[ALB trafficRouting] Service with multiple ports

### DISCUSSION THREAD

**Discussion by maxtacu** [argoproj/argo-rollouts#3026] [Q&A]
Given the example service configuration with multiple ports in it:
```
apiVersion: v1
kind: Service
metadata:
  name: rollouts-poc
spec:
  selector:
    app.kubernetes.io/name: rollouts-poc
    app.kubernetes.io/instance: rollouts-poc
  type: ClusterIP
  ports:
  - name: main
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: second
    protocol: TCP
    port: 8081
    targetPort: 8081
  - name: third
    protocol: TCP
    port: 8082
    targetPort: 8082
```
And the example ingress configuration:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rollouts-poc
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=60
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.kubernetes.io/internal: "true"
spec:
  ingressClassName: internal
  rules:
    - http:
        paths:
        - backend:
            service:
              port:
                name: main
              name: rollouts-poc
          path: /
          pathType: Prefix
      host: canary-demo.example.app
    - http:
        paths:
        - backend:
            service:
              port:
                name: second
              name: rollouts-poc
          path: /
          pathType: Prefix
      host: canary-demo1.example.app
    - http:
        paths:
        - backend:
            service:
              port:
                name: third
              name: rollouts-poc
          path: /
          pathType: Prefix
      host: canary-demo2.example.app
```
I want to enable canary for the whole service keeping the possibility to route the traffic depending on the host. This is achievable by using Gateway API instead of ALB, but there are no sticky sessions available. How can I configure trafficRouting for the alb in order to support these multiple service ports depending on the accessed host? Thanks in advance
