### DISCUSSION TITLE
Regarding the issue of using traefik as traffic management in rollout

### DISCUSSION THREAD

**Discussion by ShyunnY** [argoproj/argo-rollouts#3074] [Q&A]
When I deployed the application using rollout, I encountered a problem. When I select Traefik as the trafficRouting of Rollout, I seem to be unable to start Rollout normally.

**Please see the following documents:**
```yaml
apiVersion: v1
kind: Service
metadata:
  name: application-preview-svc
spec:
  ports:
    - name: http
      port: 7089
      targetPort: 7089
---
apiVersion: v1
kind: Service
metadata:
  name: application-stable-svc
spec:
  ports:
    - name: http
      port: 7089
      targetPort: 7089
---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: traefik-shyunn-service
spec:
  weighted:
    services:
      - name: application-stable-svc
        port: 7089
      - name: application-preview-svc
        port: 7089
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: shyunn-canary
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      shyunn.io: application
  template:
    metadata:
      labels:
        shyunn.io: application
    spec:
      containers:
        - name: shyunn-app
          image: 
          ports:
            - containerPort: 7089
  strategy:
    canary:
      canaryService: application-preview-svc
      stableService: application-stable-svc
      maxUnavailable: 20%
      scaleDownDelaySeconds: 60
      minPodsPerReplicaSet: 2
      canaryMetadata:
        labels:
          shyunn.app.stage: preview
      stableMetadata:
        labels:
          shyunn.app.stage: stable
      trafficRouting:
        traefik:
          weightedTraefikServiceName: traefik-shyunn-service
      steps:
        - setWeight: 20
        - pause:
            duration: 3m
        - setCanaryScale:
            weight: 50
        - pause: { }
```
When I checked the logs, I found. TraefikService seems to need the corresponding Endpoints associated with the K8s Service when it is created, otherwise it cannot be created. But Rollout seems to also depend on TraefikService when it is created. This leads to being stuck in an interdependent scenario and not being able to build properly? Is there any way to solve this? grateful!
