### DISCUSSION TITLE
Make activeService optional for a blueGreen rollout

### DISCUSSION THREAD

**Discussion by ibuiltthis** [argoproj/argo-rollouts#3162] [General]
I am using Istio and routing traffic based on labels .  This is useful as I can ensure that all pods in preview communicate together and all pods in active communicate together.  I am able to set the labels on the pods during the rollout using the ativeMetadata and previewMetadata config below.  

However I am still required to nominate a service for the activeService even though I don't want argo rollouts to modify the service in any way.   I have created a workaround by creating a second service that isn't used but this messy and confusing.  Is there a reason that argo rollout must modify an activeService during a rollout?

```yaml
  strategy:
    blueGreen:
      autoPromotionEnabled: false
      activeMetadata:
        labels:
          role: active
      previewMetadata:
        labels:
          role: preview
      # This is only here because an activeService is required so we make a unused service. 
      #   Routing is achieved through setting role label to active / preview on each pod and using config in Virtual Service and Destination 
      activeService: argorollouts-workaround-helloworld
```
