### DISCUSSION TITLE
Ingress preview/stable host routes

### DISCUSSION THREAD

**Discussion by Desolar1um** [argoproj/argo-rollouts#3376] [General]
Hi everyone, 
I'll preface first that I'm not sure if this is an issue or not hence posting here. This concerns the following [documentation page](https://argoproj.github.io/argo-rollouts/best-practices/#ingress-desiredstable-host-routes) concerning settings up an ingress with separate hosts for preview, stable, and split traffic respectively. I'm using Nginx ingress controller.

So far I've been implementing canary using only 2 hosts on my Ingress:
1. Main host (where traffic splitting also occurs)
2. Canary host

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-api
  labels:
    app: test-api
spec:
  ingressClassName: ingress-test
  rules:
    - host: test-api.com
      http:
        paths:
          - backend:
              service:
                name: test-api
                port:
                  number: 9080
            path: /actuator
            pathType: Prefix
          - backend:
              service:
                name: test-api
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: test-api-canary.com
      http:
        paths:
          - backend:
              service:
                name: test-api-canary
                port:
                  number: 9080
            path: /actuator
            pathType: Prefix
          - backend:
              service:
                name: test-api-canary
                port:
                  number: 80
            path: /
            pathType: Prefix
```

This allows me to set up a direct path to the Canary, but I noticed today that 0 traffic is routed towards the canary during traffic routing steps in my canary. All requests to `test-api.com` only go to the stable version. I realized the issue is the `test-api-canary.com` rule on my ingress. After deleting it, the traffic routing respects what is represented in canary steps. 

Now, I'm looking at this [ingress setup](https://argoproj.github.io/argo-rollouts/best-practices/#ingress-desiredstable-host-routes) , and I don't understand how the traffic routing will take place for `guestbook-root` service. Will all requests that dont match the first 2 rules go to `guestbook-root` service regardless of host? as a sort of default backend? because that doesn't work for me, I need requests only for `test-api.com` to go through for the `root` service, and to have a separate route for `desired` i.e canary service.

I feel like some more information is needed on this page to make it fool-proof. 
Thanks in advance
