### DISCUSSION TITLE
Would it be possible to schedule a horizontal autoscaling while using HPA?

### DISCUSSION THREAD

**Discussion by NMZ0429** [argoproj/argo-rollouts#3380] [Q&A]
I am currently using HPA to configure autoscaling as explained in [official docs](https://argo-rollouts.readthedocs.io/en/stable/features/hpa-support/).
My question is whether it is possible to increase the values of `minReplicas` and `max Replicas`  at scheduled time like CronJob so that the server can withstand an expected CPU spike.  According to the [discussion](https://github.com/argoproj/argo-rollouts/discussions/1521), Rollouts supports external metrics but I simply want to  upscale pods based on the time.

I am new to k8s and Argo Rollouts so any help would be much appreciated.

### Example HPA Setting

```yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-rollout-example
spec:
  maxReplicas: 6 # I want to configure this value at scheduled time
  minReplicas: 2 # I want to configure this value at scheduled time
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: example-rollout
  targetCPUUtilizationPercentage: 80
```
