### DISCUSSION TITLE
How to configure Notifications for Argo Rollouts

### DISCUSSION THREAD

**Discussion by RoyZohar-akamai** [argoproj/argo-rollouts#3423] [Q&A] [answered]
Hello,
I working on integrating argo rollouts into our CI/CD process we currently use a central argocd running on one cluster and it deploys the applications onto all the other cluster environments. I installed argo rollouts with helm on one of the clusters . 
I created a few applications manifests that are on the argocd cluster and it installed them on the cluster with where the argo rollouts controller is running. Now I wanted to use the notifications feature to send webex message to a room and configured the notifications as describe here  https://argoproj.github.io/argo-rollouts/generated/notification-services/webex/. + https://github.com/argoproj/argo-rollouts/blob/master/manifests/notifications-install.yaml
I added the subscribe annotations but when I trigger a rollout I don't get any messages.

**- Do I need to configure the notifications in argocd-notification-configmap/secret ?**
**-Do I need to add conditions to the triggers ?**

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-notification-configmap
data:
  service.webex: |
    token: $webex-token
  template.analysis-run-error: >
    message: Rollout {{.rollout.metadata.name}}'s analysis run is in error
    state.
  template.analysis-run-failed: |
    message: Rollout {{.rollout.metadata.name}}'s analysis run failed.
  template.analysis-run-running: |
    message: Rollout {{.rollout.metadata.name}}'s analysis run is running.
  template.rollout-completed: |
    message: Rollout {{.rollout.metadata.name}} has been completed.
  template.rollout-paused: |
    message: Rollout {{.rollout.metadata.name}} has been paused.
  template.rollout-step-completed: >
    message: Rollout {{.rollout.metadata.name}} step number {{ add
    .rollout.status.currentStepIndex 1}}/{{len
    .rollout.spec.strategy.canary.steps}} has been completed.
  template.rollout-updated: |
    message: Rollout {{.rollout.metadata.name}} has been updated.
  template.scaling-replicaset: >
    message: Scaling Rollout {{.rollout.metadata.name}}'s replicaset to
    {{.rollout.spec.replicas}}.
  trigger.on-analysis-run-error: |
    - send: [analysis-run-error]
  trigger.on-analysis-run-failed: |
    - send: [analysis-run-failed]
  trigger.on-analysis-run-running: |
    - send: [analysis-run-running]
  trigger.on-rollout-aborted: |
    - send: [rollout-aborted]
  trigger.on-rollout-completed: |
    - send: [rollout-completed]
  trigger.on-rollout-paused: |
    - send: [rollout-paused]
  trigger.on-rollout-step-completed: |
    - send: [rollout-step-completed]
  trigger.on-rollout-updated: |
    - send: [rollout-updated]
  trigger.on-scaling-replica-set: |
    - send: [scaling-replicaset]
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-rollouts-notification-secret
stringData:
  webex-token: <my-webex-token>
  ```
