### DISCUSSION TITLE
The priority between autoPromotionEnabled and the steps defined in the strategy section of an Argo Rollouts

### DISCUSSION THREAD

**Discussion by zitrocy** [argoproj/argo-rollouts#3566] [Q&A] [answered]
Hi, folks!

I have a question. I've set rollout.yaml as follows, and I want autoPromotion to be in action as I intended.
However, it's not working as I thought.
Maybe it's because of the pause option in the configuration.
So, I'd like to know which one takes priority: autoPromotionEnabled or pause in the steps?

```
 strategy:
   canary:
     maxSurge: 25%
     maxUnavailable: 0
     autoPromotionEnabled: true
     steps:
     - setWeight: 20
     - pause: {}
```

I thought autoPromotionEnabled takes priority over pause, as indicated in this link: [Link Text](https://argo-rollouts.readthedocs.io/en/stable/features/bluegreen/#autopromotionenabled),
but it wasn't the case.

Thanks for any help in advance,
