### DISCUSSION TITLE
Is it possible to set more than one Datadog api key and app key?

### DISCUSSION THREAD

**Discussion by ariadnarouco** [argoproj/argo-rollouts#3726] [Q&A]
I have a case where we have multiple Datadog accounts. Is there a way to define that? 
https://github.com/argoproj/argo-rollouts/blob/master/metricproviders/datadog/datadog.go#L421
Based on the code, this is not possible. 
BUT... I guess I can define a new plugin... https://argo-rollouts.readthedocs.io/en/stable/analysis/plugins/

Thanks in advance.

**Comment by j-martin** [comment]
I have not tried it, but you should be able to specify the `secretRef` pointing to the credential at the provider level: 

> The process for retrieving Datadog credentials is as follows: 1. If a secretRef is defined in the AnalysisTemplate: Argo Rollouts will search for the secret with the specified name in the namespace where the template resides. 2. If the secret is not found in the specified namespace: Argo Rollouts will then check the environment variables. 3. If the credentials are not found in environment variables: Argo Rollouts will look for a secret named "Datadog" in the namespace where Argo Rollouts itself is deployed.

https://argo-rollouts.readthedocs.io/en/latest/analysis/datadog/#:~:text=1.%20If%20a-,secretRef,-is%20defined%20in

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: loq-error-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: error-rate
    interval: 5m
    successCondition: result <= 0.01
    failureLimit: 3
    provider:
      datadog:
        apiVersion: v2
        interval: 5m
        secretRef:
          name: "mysecret" # <-------------- this
          namespaced: true
        query: |
          sum:requests.error.rate{service:{{args.service-name}}}
```

I think it should work with 1.7.2, but it is not referenced in `stable` docs: https://argo-rollouts.readthedocs.io/en/stable/analysis/datadog/ only in the `latest` https://argo-rollouts.readthedocs.io/en/latest/analysis/datadog/
