### DISCUSSION TITLE
AnalysisTemplates oauth2 problems with Azure Managed Prometheus

### DISCUSSION THREAD

**Discussion by OlleDecerno** [argoproj/argo-rollouts#3861] [Q&A] [answered]
I am currently trying to get AnalysisRun to query a managed prometheus in Azure but having some issues with the oauth2 authentication. What i've done is creating a analysis run based on the documentation:

```yaml
...
spec:
    metrics:
    - name: success-rate
      provider:
        prometheus:
          address: https://<workspace>.prometheus.monitor.azure.com
          authentication:
            oauth2:
              clientId: <clientid>
              clientSecret: <clientsecret>
              scope:
              -   https://monitor.azure.com/.default
              tokenUrl: https://login.microsoftonline.com/<tenantid>/oauth2/token
...
```

but i'm getting 401. I've tried to cURL it manually and got it to work if i add resource="https://monitor.azure.com" but that's not possible to do in the AnalysisRun manifest.

Has anyone got it to work, and if so, how?
