### DISCUSSION TITLE
Running Job before traffic shifting

### DISCUSSION THREAD

**Discussion by n0rm4l-me** [argoproj/argo-rollouts#4002] [Q&A]
With Canary Deployment strategy, would it be possible to create new canary PODs and execute Job (smoke tests) before shifting the traffic? Here is the example of our configuration:
```
    canary:
      canaryService: xxx-some-service-canary
      stableService: xxx-some-service-stable
      steps:
        - pause:
            duration: 1m
        - setWeight: 1
        - analysis:
            analysisRunMetadata: {}
            args:
              - name: service-name
                value: xxx-some-service
            templates:
              - templateName: xxx-some-service-analysis <--- smoke test job is here
        - pause:
            duration: 5m
        - setWeight: 50
        - pause:
            duration: 5m
        - setWeight: 100
        - pause:
            duration: 5m
      trafficRouting:
        plugins:
          argoproj-labs/gatewayAPI:
            httpRoute: xxx-some-service-route
            namespace: application-namespace
```
