### DISCUSSION TITLE
Is it possible to not use "rollouts-pod-template-hash"?

### DISCUSSION THREAD

**Discussion by sedflix** [argoproj/argo-rollouts#4093] [General]
When using “trafficRouting”, Rollout automatically adds `rollouts-pod-template-hash` to either the Service or Destination Rule.

Would it be possible for Rollout to use selectors like `role: stable` or `role: canary` instead of relying on `rollouts-pod-template-hash`?

We are running a multi-cluster Istio setup with multiple control planes on a single network. The addition of `rollouts-pod-template-hash` as a selector label in the Service or Destination Rule causes us to lose namespace sameness across the cluster, ultimately affecting multi-cluster load balancing. The same would happen with Gateway API(for example GKE usage of Gateway API to support multi-cluster load balancing)

For example, the configuration below makes the service single cluster because "rollouts-pod-template-hash" is unique for each cluster.  Therefore, we loose our ability to do any sort of multi-cluster routing or failovers.
```
apiVersion: v1
kind: Service
metadata:
  name: istio-rollout-stable
  namespace: rollouts-demo-istio
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: istio-rollout
    rollouts-pod-template-hash: 597c465644
  type: ClusterIP
```

Question)
Is there any possible way to use Traffic Management without losing this multi-cluster load balancing?
