### DISCUSSION TITLE
Is it possible to run at a certain weight until `x` requests have been made?

### DISCUSSION THREAD

**Discussion by sondrelg** [argoproj/argo-rollouts#4095] [Q&A]
Hi!

I'm looking for a way to say "run at a certain weight until at least x amount of traffic has hit the canary". Is that possible?

Extending this I'd like to be able to wait for any metric to be true, so I can say "wait for x amount of messages to be ingested from queue y", in addition to the ingress traffic.

## What I've tried

Inuitively, I'd want the following flow in my `Rollout`:

```yaml
steps:
  # Route 10% of traffic to canary
  - setWeight: 10
  # Pause until 5 requests have been made 
  - analysis:
      templates:
        - templateName: wait-for-traffic
      args:
        - name: minimum-requests
          value: "5"
  # Ensure the canary is preforming as expected
  - analysis:
      templates:
        - templateName: success-rate
  # Route 30% of traffic to canary
  - setWeight: 30
  # Pause until 50 requests have been made 
  - analysis:
      templates:
        - templateName: wait-for-traffic
      args:
        - name: minimum-requests
          value: "50"
  # Ensure the canary is preforming as expected
  - analysis:
      templates:
        - templateName: success-rate
# and so on
```

I set up a template like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: wait-for-traffic
spec:
  args:
    - name: minimum-requests
    - name: prometheus-address
  metrics:
    - name: requests
      successCondition: result[0] >= {{args.minimum-requests}}
      failureCondition: result[0] < 0
      count: 100
      inconclusiveLimit: 99
      provider:
        prometheus:
          address: "{{args.prometheus-address}}"
          query: sum(my_metric{role="canary"})
      interval: 30s
```

This almost does what I want, but I seem to be missing the ability to specify `successThreshold: 1` and `inconclusiveLimit: 100`. I'd like the analysis to pass as soon as the threshold is met. 

As far as I can tell, `count` is the proxy for `successThreshold` and there is a built-in requirement that `count >= limits` (failure and inconclusive). So to allow an `inconclusiveLimit` of 99 periods, count has to be 100, making it necessary to have 100 successes.

-----

Hopefully I'm missing an existing feature here. If not, does this use-case seem reasonable?

Seems kind of related to https://github.com/argoproj/argo-rollouts/discussions/3071.
