### DISCUSSION TITLE
Does `AnalysisTemplate` support successful once and error retry until reach count or time limit

### DISCUSSION THREAD

**Discussion by tangkhaiphuong** [argoproj/argo-rollouts#4238] [Q&A]
Hi, my scenario that I want to use AnalysisTemplate for Kargo as Continuous Promotion. In Verification phase. The AnalysisTemplate call `Verification Healthy`. It query Prometheus metric base on metric to make sure that all Pods are scale and replicates to reach the schedule number. My AnalysisTemplate

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: healthy-verification
  namespace: kargo
spec:
  args:
    - name: application
      value: test
    - name: target-revision
      value: 1.1.0.0
  metrics:
    - name: healthy-verification
      interval: 1m
      successCondition: "len(result) == 1"
      failureCondition: "len(result) == 0"
      count: 30
      failureLimit: 30
      provider:
        prometheus:
          address: https://localhost:9090/prometheus
          query: |
            sum by (target_revision, sync_revision) (
              argocd_app_info{name="{{ args.application }}", sync_status="Synced", health_status="Healthy"}
            * on (name) group_left (target_revision, sync_revision)
              argocd_app_target_revision_info{target_revision="{{ args.target-revision
 }}", sync_revision="{{ args.target-revision }}"}
            )
```

If the `len(result) == 1"` It doesn't stop, and marks as successfully but keeps running 30 times (take 30 mins). So how AnalysisTemplate support with configure: 
> If run prometheus query and get successCondition only once. Mark successful and stop. Otherwise, retry based on interval until 30 mins)
