### DISCUSSION TITLE
How to handle timeouts and non 200 HTTP status

### DISCUSSION THREAD

**Discussion by mangatmodi** [argoproj/argo-rollouts#4245] [Q&A] [answered]
We are using a web provider as below
```yaml
name: some-name
interval: 60s
successCondition: result == true
failureCondition:  result == false
count: 3
provider:
  web:
    url: my-service.example.com
    method: POST
    timeoutSeconds: 20
    jsonBody:
        foo:bar
    jsonPath: "{$.healthy}"

```
However, the service is quite new and in the beta version. We would like to return success when the service is not available (timeouts or non 200 status code).
Looking at the [source code](https://github.com/argoproj/argo-rollouts/blob/master/metricproviders/webmetric/webmetric.go#L91) and documentation, looks like there is no way to do that. I know I can put an API gateway at front of my service and do request rewrite, but is there anything I can do natively in the web analysis?
