### DISCUSSION TITLE
Setup the Path Based Canary Deployment using Istio

### DISCUSSION THREAD

**Discussion by ajaydevtron** [argoproj/argo-rollouts#4263] [Q&A]
Hi Team,
We have two use cases for adopting Canary deployments with Istio in our applications:

1.  Header-based Canary Deployments
2. Path-based Canary Deployments

We have successfully implemented the first use case using the following Rollout configuration:

```
strategy:
    canary:
      canaryService: canary-svc
      maxSurge: 25%
      maxUnavailable: 1
      stableService: stable-service
      steps:
        - setHeaderRoute:
            match:
              - headerName: X-Version
                headerValue:
                  prefix: v2
            name: header-based
        - pause:
            duration: 2m
        - analysis:
            templates:
              - templateName: success-rate
        - setWeight: 50
        - pause:
            duration: 2m
        - analysis:
            templates:
              - templateName: success-rate
        - setWeight: 100
      trafficRouting:
        istio:
          virtualService:
            name: xyz-virtualservice
            routes:
              - primary
        managedRoutes:
          - name: header-based
          ```

Virtual Service manifest

kind: VirtualService
metadata:
  name: xyz-virtualservice
spec:
  gateways: 
    - xyz-istio-gateway
  hosts:
    - "istio-test.xyz.info"
 
  http: 
    - name: primary
      route:
      - destination:
          host: stable-svc
        weight: 100
      - destination:
          host: canary-svc
        weight: 0
        
Now I want to implement the second one. I tried using setMirrorRoute as documented here: (https://argo-rollouts.readthedocs.io/en/stable/features/specification/), but it is not forwarding live traffic to the canary service it is just send the mirror traffic their. I want the canary service to receive live traffic as well, whenever the path prefix matches the incoming request.

Below is the strategy configuration I'm using for this setup

    strategy:
    canary:
      canaryService: canary-svc
      maxSurge: 25%
      maxUnavailable: 1
      stableService: stable-svc
      steps:
        - setCanaryScale:
            weight: 25
        - setMirrorRoute:
            match:
              - path:
                  prefix: /QWE/*
              - path:
                  prefix: /DEF/*
            name: canary-paths
            percentage: 100
        - pause:
            duration: 2m
        - analysis:
            templates:
              - templateName: success-rate-2
        - setWeight: 50
        - pause:
            duration: 2m
        - analysis:
            templates:
              - templateName: success-rate-2
        - setWeight: 100
      trafficRouting:
        istio:
          virtualService:
            name: xyz-virtualservice
            routes:
              - primary
        managedRoutes:
          - name: canary-paths
          
        Could anyone please help me out? Any kind of assistance would be greatly appreciated. Please let me know if any Kubernetes manifests are required.
