### DISCUSSION TITLE
Blue green introspection

### DISCUSSION THREAD

**Discussion by frejonb** [argoproj/argo-rollouts#881] [Q&A]
I have the following situation. Service A talks to service B. In service A’s configmap I have a variable pointing to B’s service name. 

Is there any way that when I rollout a new revision of A, that the environment variable is changed to now point to B’s preview service? For example using kustomize?

I think the promotion phase might be a bit tricky. Any ideas how to solve this issue in rollouts?

**Comment by jessesuen** [comment]
I think you should use kustomize VARS feature to accomplish this use case.

See: https://kubectl.docs.kubernetes.io/references/kustomize/vars/

Rollout spec:
```yaml
spec:
  template:
    spec:
      containers:
      - image: myimage
        command: ["start", "--host", "$(MY_ENV_VAR)"]
        env:
        - name: MY_ENV_VAR
          value: $(SERVICE_B_NAME)
```

In kustomization.yaml:
```yaml
vars:
- name: SERVICE_B_NAME
  objref:
    kind: Service
    name: service-b
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name
```
