### DISCUSSION TITLE
ArgoCD can't apply kustomization with rollout

### DISCUSSION THREAD

**Discussion by eroji** [argoproj/argo-rollouts#890] [Q&A] [answered]
I followed the instructions on installing argo-rollouts and I was already using ArgoCD for deployments. However, when I included the rollout strat YAML, I'm getting the following error when I attempt to sync. What am I doing wrong?

Error
```
ComparisonError: rpc error: code = Unknown desc = Manifest generation error (cached): `kustomize build /tmp/argocd@bitbucket.example.com:7999_devops_container-config/bluegreen-demo/k8s/overlays/test-namespace` failed exit status 1: Error: no matches for OriginalId argoproj.io_v1alpha1_Rollout|~X|bluegreen-demo; no matches for CurrentId argoproj.io_v1alpha1_Rollout|~X|bluegreen-demo; failed to find unique target for patch argoproj.io_v1alpha1_Rollout|bluegreen-demo
```

rollout.yaml
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: bluegreen-demo
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: bluegreen-demo
  template:
    metadata:
      labels:
        app: bluegreen-demo
    spec:
      containers:
      - name: bluegreen-demo-pod
        image:  test/bluegreen-demo
        ports:
        - containerPort: 8080
  strategy:
    blueGreen: 
      activeService: bluegreen-demo
      autoPromotionEnabled: false
```
