### ISSUE TITLE
function "args" not defined when using AnalysisTemplate with datadog

### ISSUE THREAD

**Issue by daleront** [argoproj/argo-rollouts#1004]
## Summary 

Recently upgraded to v0.10.2 to use the datadog provider analysis for rollouts.

NOTE: This works fine as an inline analysis but I would would like to use and AnalysisTemplate for scalability

When passing in args to an AnalysisTemplate from an canary analysis I am getting the error:

```
Error: parse error in "/templates/analysis.yaml": template: /templates/analysis.yaml:20: function "args" not defined

```

# Rollout

```
strategy:
    canary:
      maxUnavailable: 0
      maxSurge: 3
      analysis:
        templates:
        - templateName: success-rate
        args:
        - name: service-name
          value: {{ .Release.Name }}
        startingStep: 1 
      - setWeight: 20
      - pause: {duration: {{ .Values.argo_rollouts.canary_step_pause }}}
      - setWeight: 50
      - pause: {duration: {{ .Values.argo_rollouts.canary_step_pause }}}
      - setWeight: 100
      - pause: {duration: 1m}
      canaryService: {{ .Release.Name }}-canary
      stableService: {{ .Release.Name }} 
      trafficRouting:
        istio:
          virtualService:
            name: {{ .Release.Name }}-services 
            routes:
            - {{ .Release.Name }}-routes 
```

# AnalysisTemplate

```

apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 2m
    count: 3
    successCondition: result <= 0.01
    provider:
      datadog:
        interval: 1m
        query: |
          sum:http_requests_received_total{service:{{args.service-name}},!code:200} /
          sum:http_requests_received_total{service:{{args.service-name}},code:200}

```

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
