### ISSUE TITLE
Kayenta demo setup problems

### ISSUE THREAD

**Issue by andreasevers** [argoproj/argo-rollouts#1005]
## Summary 

Hi folks.
I’m trying to get a demo running the Kayenta analysis experiments. It seems there’s some drift between [the documentation](https://argoproj.github.io/argo-rollouts/analysis/kayenta/) and the actual controller.
E.g:
> The AnalysisTemplate “mann-whitney” is invalid:
> * spec.metrics.provider.kayenta.scopes.controlScope.end: Required value
> * spec.metrics.provider.kayenta.scopes.controlScope.start: Required value
> * spec.metrics.provider.kayenta.scopes.experimentScope.end: Required value
> * spec.metrics.provider.kayenta.scopes.experimentScope.start: Required value

It's unclear from the docs how the `args.start-time` and `args.end-time` arguments get filled in.
> Error: Failed to create AnalysisRun for analysis ‘my-analysis’: args.start-time was not resolved

## Diagnostics

What version of Argo Rollouts are you running?
Current stable version

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by phuongnd96** [comment]
Up since this is still an issue

**Comment by phuongnd96** [comment]
Actually i found a way for this to work, documents seems to be outdated for setup with Kayenta. You can try https://gist.github.com/phuongnd96/1614a7b2a301c5965045941d92cf3ced.

**Comment by jeromeguiard** [comment]
Can we get a clarification from the team. Is the documentation outdated and those parameters are going to be eventually remove, or the dev hasn't been done yet? 
In my usecase I am trying to pass dynamic parameters to Kayenta as part of a rollout step outside an experiment.

I want to be able to trigger the analysis whenever I want as part of release steps.

 I was planning to rely on those parameters. Any suggestion on how it can be done?

**Comment by zachaller** [comment]
If you look at the [docs](https://argoproj.github.io/argo-rollouts/analysis/kayenta/) the time values are coming in via the experiment

```
# This is the resulting experiment that is produced by the step
apiVersion: argoproj.io/v1alpha1
kind: Experiment
name:
  name: guestbook-6c54544bf9-0
spec:
  duration: 1h
  templates:
  - name: baseline
    replicas: 1
    spec:
      containers:
      - name: guestbook
        image: guestbook:v1
  - name: canary
    replicas: 1
    spec:
      containers:
      - name: guestbook
        image: guestbook:v2
  analysis:
    templateName: mann-whitney
    args:
    - name: start-time
      value: "{{experiment.availableAt}}"
    - name: end-time
      value: "{{experiment.finishedAt}}"
```
