### ISSUE TITLE
Analysis evaluation errors are not surfaced

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#1006]
## Summary 

When trying a metric query, I made a user error comparing mismatched types (array to float). However, the rollout controller did not surface this.

## Diagnostics

What version of Argo Rollouts are you running? v0.10.2

```
time="2021-02-24T09:42:15Z" level=warning msg="invalid operation: >= (mismatched types []float64 and float64)" analysisrun=success-rate-9prjw metric=success-rate namespace=argo-rollouts
time="2021-02-24T09:42:15Z" level=info msg="measurement completed Error" analysisrun=success-rate-9prjw metric=success-rate namespace=argo-rollouts```
```

```yaml
status:
  metricResults:
  - consecutiveError: 4
    error: 4
    measurements:
    - finishedAt: "2021-02-24T09:26:59Z"
      metadata:
        timestamps: '[1614158812,1614158812,1614158782,1614158812,1614158812,1614158782,1614158812,1614158812,1614158782,1614158812,1614158782,1614158782,1614158812,1614158782]'
      phase: Error
      startedAt: "2021-02-24T09:26:47Z"
      value: '[1.60,12.00,1.57,1.07,12.00,1.10,3.50,0.57,0.50,1.23,1.40,1.80,1.33,2.37]'
    - finishedAt: "2021-02-24T09:32:05Z"
      metadata:
        timestamps: '[1614159112,1614159112,1614159112,1614159112,1614159112,1614159112,1614159112,1614159112,1614159112,1614159112,1614159112,1614159112,1614159112,1614159112]'
      phase: Error
      startedAt: "2021-02-24T09:31:59Z"
      value: '[1.60,12.00,1.67,0.97,12.00,1.40,3.50,0.40,1.43,1.30,0.90,4.50,1.17,0.40]'
    - finishedAt: "2021-02-24T09:37:11Z"
      metadata:
        timestamps: '[1614159412,1614159412,1614159412,1614159412,1614159412,1614159412,1614159412,1614159412,1614159412,1614159412,1614159412,1614159412,1614159412,1614159412]'
      phase: Error
      startedAt: "2021-02-24T09:37:05Z"
      value: '[1.60,12.00,1.63,0.93,12.00,1.60,3.50,0.63,1.63,1.07,0.83,4.50,1.37,0.50]'
    - finishedAt: "2021-02-24T09:42:15Z"
      metadata:
        timestamps: '[1614159712,1614159712,1614159712,1614159712,1614159712,1614159712,1614159712,1614159712,1614159712,1614159712,1614159712,1614159712,1614159712,1614159712]'
      phase: Error
      startedAt: "2021-02-24T09:42:11Z"
      value: '[1.60,12.00,1.83,1.13,12.00,1.20,3.50,0.43,1.70,1.30,0.77,4.50,1.33,0.50]'
    name: success-rate
    phase: Running
  phase: Running
  startedAt: "2021-02-24T09:26:59Z"
```
