### ISSUE TITLE
Allow setCanaryScale step without traffic management

### ISSUE THREAD

**Issue by olfway** [argoproj/argo-rollouts#1020]
# Summary

Add support for starting new version without production traffic and without traffic management

# Use Cases

```
spec:
  replicas: 6
  strategy:
    canary:
      canaryService: preview

      steps:
      # start one canary replica but doesn't send production traffic to it
      # it will be accessible via canaryService only
      - setCanaryScale:
          replicas: 1

      # pause to allow some tests or preview
      - pause: {}

      # send ~30% of traffic to the new version
      # (it will have to start a second canary replica to match 30%)
      - setWeight: 30

      # traditional canary release
      - pause: { duration: 5m }
      - setWeight: 60
      - pause: { duration: 5m }
      - setWeight: 100
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
This is not possible fundamentally because of the way label selectors work with services. The new canary will have the same labels as the stable stack, and so the selector will choose it.

That said, the way you can achieve your use case while using basic canary, is to launch an experiment step, which will have different labels which are unique to the experiment. The experiment pod will have a set of labels (which you can control) and so you can reach the experiment pod without prod traffic hitting it.

**Comment by jessesuen** [comment]
Example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
...
  strategy:
    canary: 
      steps:
      - experiment:
          templates:
          - name: canary
            specRef: canary
```
