### ISSUE TITLE
Resource requests/limits are ignored by Kubernetes

### ISSUE THREAD

**Issue by PedroArvela** [argoproj/argo-rollouts#1043]
## Summary 

When trying to apply resource requests/limits to a rollout the apply succeeds, but the resulting object in the API service has resources set as an empty object.

Anderson Silva in the Slack channel found this was related to the CRD for Rollouts defining the `resources` just as an object without any elements. By patching the additional elements the CRD would work.

This seems like a regression caused by https://github.com/argoproj/argo-rollouts/pull/480 and I think it is caused by field pruning: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#controlling-pruning

### Steps to reproduce

1. Apply https://gist.github.com/PedroArvela/66dec9c51ce0872caf272f90603e28e8
2. Run `kubectl get rollout -o yaml borker`

### Expected Results

Returned yaml should have:

```yaml
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
            limits:
              cpu: 600m
              memory: 1Gi
```

### Actual Results

Resources are:

```yaml
resources: {}
```

## Diagnostics

* Example resource file that shows the problem: https://gist.github.com/PedroArvela/66dec9c51ce0872caf272f90603e28e8
* Argo Rollouts 0.10.2
* Logs for the entire controller: https://gist.github.com/PedroArvela/a18a4362f57c1063db32a329101c4b6c
* Logs for a specific rollout: https://gist.github.com/PedroArvela/7cf5256fb5485de729a3960ff0aea301

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
