### ISSUE TITLE
controller can panic on startup when starting up with invalid object

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#1045]
## Summary 

The recent use of tolerant informers helped deal with the problem when the controller was **_introduced_** to bad rollout objects. However, I am still able to crash the controller if I change the order of steps. I can induce a crash if I introduce the bad rollout *before* the controller starts e.g.:

1. stop the controller
2. introduce a bad rollout (e.g. like below)

```yaml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: borker
      env: development
  strategy:
    canary:
      maxSurge: 50%
      maxUnavailable: 0
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: borker
        env: development
    spec:
      containers:
      - image: argoproj/rollouts-demo:blue
        name: main
        resources:
          requests:
            cpu: 0.1
            memory: 256Mi
      dnsPolicy: ClusterFirst
      ephemeralContainers:
      - image: argoproj/rollouts-demo:blue
        name: main
        resources:
          requests:
            cpu: asdfadsf       # <<<<<< bad
            memory: 256Mi
```

3. start the controller

Then I am able to crash the controller:

```
E0324 16:13:36.084998   47797 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 152 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x27593a0, 0x3847730)
        /Users/jsuen/go/src/github.com/argoproj/argo-rollouts/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /Users/jsuen/go/src/github.com/argoproj/argo-rollouts/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
panic(0x27593a0, 0x3847730)
        /usr/local/Cellar/go/1.15.5/libexec/src/runtime/panic.go:969 +0x1b9
github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1.(*Rollout).GetNamespace(0x0, 0x0, 0x2c8f280)
        <autogenerated>:1 +0x5
k8s.io/client-go/tools/cache.MetaNamespaceKeyFunc(0x2983480, 0x0, 0x1, 0xc00039a310, 0xc00069dcc8, 0x2214fd5)
        /Users/jsuen/go/src/github.com/argoproj/argo-rollouts/vendor/k8s.io/client-go/tools/cache/store.go:107 +0x131
github.com/argoproj/argo-rollouts/utils/controller.metaNamespaceKeyFunc(0x2983480, 0x0, 0xc00069dcb8, 0x1, 0x1, 0xc0005364e8)
        /Users/jsuen/go/src/github.com/argoproj/argo-rollouts/utils/controller/controller.go:184 +0x66
github.com/argoproj/argo-rollouts/utils/controller.EnqueueRateLimited(0x2983480, 0x0, 0x2c7f040, 0xc000365240)
        /Users/jsuen/go/src/github.com/argoproj/argo-rollouts/utils/controller/controller.go:210 +0x39
github.com/argoproj/argo-rollouts/rollout.NewController.func2(0x2983480, 0x0)
        /Users/jsuen/go/src/github.com/argoproj/argo-rollouts/rollout/controller.go:189 +0x51
github.com/argoproj/argo-rollouts/rollout.NewController.func4(0x29b5420, 0xc00039e100, 0x29b5420, 0xc0005364e8)
        /Users/jsuen/go/src/github.com/argoproj/argo-rollouts/rollout/controller.go:224 +0x24f
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
        /Users/jsuen/go/src/github.com/argoproj/argo-rollouts/vendor/k8s.io/client-go/tools/cache/controller.go:238
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /Users/jsuen/go/src/github.com/argoproj/argo-rollouts/vendor/k8s.io/client-go/tools/cache/shared_informer.go:775 +0x1c5
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0008b4760)
        /Users/jsuen/go/src/github.com/argoproj/argo-rollouts/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00069df60, 0x2c1c320, 0xc00063e090, 0x2717301, 0xc00063c120)
        /Users/jsuen/go/src/github.com/argoproj/argo-rollouts/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0008b4760, 0x3b9aca00, 0x0, 0x1, 0xc00063c120)
        /Users/jsuen/go/src/github.com/argoproj/argo-rollouts/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /Users/jsuen/go/src/github.com/argoproj/argo-rollouts/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc00002ed80)
        /Users/jsuen/go/src/github.com/argoproj/argo-rollouts/vendor/k8s.io/client-go/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0007b9020, 0xc00004e080)
        /Users/jsuen/go/src/github.com/argoproj/argo-rollouts/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /Users/jsuen/go/src/github.com/argoproj/argo-rollouts/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x65
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x20c44c5]
```

If i swap steps 2 and 3, then it cannot be reproduced.

## Diagnostics

What version of Argo Rollouts are you running? v1.0 as of 92c1b166942a60982390b37a045092ae22f30802

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
