### ISSUE TITLE
Unresolved argument errors to templates does not surface as validation error

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#1052]
## Summary 

When debugging a rollout that had an analysis template and the rollout did not supply a required argument to the template, the rollout simply stops with an unhelpful message:

```
Name:            cloud-ops-rollout-vite-fat-jar2-e2e-usw2
Namespace:       cloud-ops-vitefatjar2-usw2-e2e
Status:          ◌ Progressing
Message:         more replicas need to be updated
```

In reality, it's not a problem when more replicas needing to be updated. The real problem is that the rollout did not supply necessary arguments to analysis template, as seen in controller logs:

```
time="2021-03-26T20:59:57Z" level=info msg="Reconciliation completed" namespace=cloud-ops-vitefatjar2-usw2-e2e rollout=cloud-ops-rollout-vite-fat-jar2-e2e-usw2 time_ms=6.004360999999999
time="2021-03-26T20:59:57Z" level=error msg="rollout syncHandler error: args.service-name was not resolved" namespace=cloud-ops-vitefatjar2-usw2-e2e rollout=cloud-ops-rollout-vite-fat-jar2-e2e-usw2
```

The bug is that we should Degrade the rollout with a validation error when arguments are not supplied.

## Diagnostics

What version of Argo Rollouts are you running? v0.10.2

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by huikang** [comment]
Hi, Jesse (@jessesuen), I am new to argo-rollout, but am interested in investigating this issue. If no one has taken it, may I take this one?

**Comment by jessesuen** [comment]
@huikang yes that would be great! To get you started, I think the error  should be returned by this method:
https://github.com/argoproj/argo-rollouts/blob/master/rollout/controller.go#L447

**Comment by huikang** [comment]
Rollout and analysisTemplate to reproduce the bug

```yaml
# Adapted from argo-rollouts/docs/getting-started/basic/rollout.yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  replicas: 5
  strategy:
    canary:
      analysis:
        templates:
          - templateName: success-rate
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 40
        - pause: {}
        # - pause: {duration: 10}
        - setWeight: 60
        - pause: {}
        # - pause: {duration: 10}
        - setWeight: 80
        - pause: {duration: 10}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
        - name: rollouts-demo
          image: argoproj/rollouts-demo:blue
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
    - name: service-name
  metrics:
    - name: success-rate
      interval: 5m
      # NOTE: prometheus queries return results in the form of a vector.
      # So it is common to access the index 0 of the returned array to obtain the value
      successCondition: result[0] >= 0.95
      failureLimit: 3
      provider:
        prometheus:
          address: http://prometheus.example.com:9090
          query: |
            sum(irate(
              istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}",response_code!~"5.*"}[5m]
            )) /
            sum(irate(
              istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}"}[5m]
            ))

```

I figured out that the root cause is that the call to https://github.com/argoproj/argo-rollouts/blob/37668f19dc976bb7c5847a4cd8c7572f1006a6ca/rollout/controller.go#L458 does not return any error because the callee method https://github.com/argoproj/argo-rollouts/blob/37668f19dc976bb7c5847a4cd8c7572f1006a6ca/pkg/apis/rollouts/validation/validation_references.go#L95 does not check the args between those defined in the template and provided by the rollout.

```go
func ValidateAnalysisTemplateWithType(rollout *v1alpha1.Rollout, template AnalysisTemplateWithType) field.ErrorList {
    // ... ...

   if template.TemplateType != BackgroundAnalysis {
      // ...
   } else {
      // verify arg names between rollout and template
		for _, arg := range templateSpec.Args {
			foundArg := false
			for _, rolloutarg := range rollout.Spec.Strategy.Canary.Analysis.Args {
				if arg.Name == rolloutarg.Name {
					foundArg = true
					break
				}
			}
			if !foundArg {
				allErrs = append(allErrs, field.Invalid(fldPath, templateName, arg.Name))
			}
		}
   }
}
```

@jessesuen , WDYT?
