### ISSUE TITLE
Traffic Routing ability with Experiment steps

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#1059]
# Summary

Currently, if you are using canary along with traffic routing, and have an experiment step, you cannot split traffic to the experiment stacks in a fine-grained manner. We should improve the Rollout Experiment step to also allow traffic to be shifted to experiment pods. Something like:

```yaml
    canary:
      steps:
      - experiment:
          templates:
          - name: baseline
            replicas: 1
            specRef: stable
            weight: 5
          - name: canary
            replicas: 1
            specRef: canary
            weight: 5
      - setWeight: 25
      - pause: {duration: 10m}
      - setWeight: 50
      - pause: {duration: 10m}
      - setWeight: 75
      - pause: {duration: 10m}
```

In the above example,  during an update, the first step would start a baseline vs. canary experiment. When pods are ready (Experiment enters Running phase), the rollout would direct 5% of traffic to canary and 5% to baseline, leaving the remaining 90% of traffic to the old stack.

# Use Cases

Today, Experiment steps are only useful with basic canary, but not very useful when used with traffic routing. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by huikang** [comment]
Hi, @jessesuen , I'd like to do some investigation on this enhancement. If no one has been looking into this issue, please assign it to me. Thanks.

**Comment by jessesuen** [comment]
Some design notes:

1. When the experiment step (with weights) is used in conjunction with setWeight, the combined amount will be subtracted from 100 until the experiment is completed. For example:

```yaml
    canary:
      steps:
      - setWeight: 25       # 25% to canary, 75% to stable
      - experiment:           # 25% to canary, 5% to baseline template, 5% to test template, 65% to stable
          templates:
          - name: baseline
            replicas: 1
            specRef: stable
            weight: 5
          - name: test
            replicas: 1
            specRef: canary
            weight: 5
      - pause: {}            # back to 25% canary, 75% stable
```

2. SetWeight will be updated to take an *optional* list of additional destinations (excluding canary), in which to split traffic:

```golang
type TrafficRoutingReconciler interface {
	// SetWeight sets the canary weight to the desired weight.
	// Optionally splits the weight to N additional destinations. Combined weights must not exceed 100.
	// Remaining weight will direct to the stable.
	SetWeight(desiredWeight int32, additionalDestinations ...WeightDestination) error
...
}

type WeightDestination struct {
	ServiceName     string
	PodTemplateHash string
	Weight          int32
}
```

3. Experiment CRs will now auto-create Service objects for each of its templates, which will also include the rollouts-pod-template-hash in the auto-created Service.

These values should be recorded to the templateStatuses. e.g.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Experiment
...
status:
  phase: Pending
  templateStatuses:
  - name: canary
    phase: Running
    podTemplateHash: abc123
    serviceName: my-experiment-canary-abc123
  - name: baseline
    phase: Pending
    podTemplateHash: def456
    serviceName: my-experiment-baseline-def456
```


4. As soon as the Experiment in an experiment step transitions to Running, the Rollout controller will rereconcile (because of the state change of the Experiment) and then call `SetWeight` with the additional destinations using the information in the Experiment's `status.templateStatuses`

As soon as the Experiment completes (e.g. Successful, Failed, Error), the rollout controller will call `SetWeight` and *exclude* additional destinations from the call to SetWeight.


5. For Istio using **_subset splitting with DestinationRule_**, the auto-created Services are not actually used, but it will still use the information from `status.templateStatuses.XXXX.podTemplateHash`  to manipulate a DestinationRule from:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: rollout-destrule
spec:
  host: rollout-example
  subsets:
  - name: canary     # referenced in canary.trafficRouting.istio.destinationRule.canarySubsetName
    labels:
      app: rollout-example
  - name: stable   # referenced in canary.trafficRouting.istio.destinationRule.stableSubsetName
    labels:
      app: rollout-example
```

Notice there are actually four pod-template-hashes involved:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: rollout-destrule
spec:
  host: rollout-example
  subsets:
  - name: canary     # referenced in canary.trafficRouting.istio.destinationRule.canarySubsetName
    labels:
      app: rollout-example
      rollouts-pod-template-hash: aaa111
  - name: stable   # referenced in canary.trafficRouting.istio.destinationRule.stableSubsetName
    labels:
      app: rollout-example
      rollouts-pod-template-hash: bbb222

  # these two subsets are injected during the experiment step (removed afterwards)
  - name: baseline
    labels:
      app: rollout-example
      rollouts-pod-template-hash: abc123
  - name: test
    labels:
      app: rollout-example
      rollouts-pod-template-hash: def456

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rollout-vsvc
spec:
  gateways:
  - istio-rollout-gateway
  hosts:
  - istio-rollout.dev.argoproj.io
  http:
  - name: primary
    route:
    - destination:
        host: rollout-example
        subset: stable  # referenced in canary.trafficRouting.istio.destinationRule.stableSubsetName
      weight: 65
    - destination:
        host: rollout-example
        subset: canary  # referenced in canary.trafficRouting.istio.destinationRule.canarySubsetName
      weight: 25

    # these two destinations are injected during the Experiment step (removed afterwards)
    - destination:
        host: rollout-example
        subset: baseline
      weight: 5
    - destination:
        host: rollout-example
        subset: test
      weight: 5
```


6. Since Experiments can shut themselves down this means we could still accidentally direct traffic to a stopped ReplicaSet causing 5XX errors upon shutdown. We need to introduce the following to Experiment spec to delay scaledown of the Experiment ReplicaSets, to give the rollout controller time to stop directing traffic to the Experiment templates:

```yaml
spec:
  scaleDownDelaySeconds: 30
```
