### ISSUE TITLE
canary strategy not expected，there may be have a capacity risk in the prod

### ISSUE THREAD

**Issue by caoyang001** [argoproj/argo-rollouts#1068]
## Summary 

What happened/what you expected to happen?
case1:
```
  replicas: 10
  strategy:
    canary:
      maxSurge: 3
      maxUnavailable: 0
      canaryService: rollout-preview
      stableService: rollouts-demo
      steps:
      - setWeight: 30
      - pause: {}
```
Expected results：
**return newRS 3 stableRS 10**
![image](https://user-images.githubusercontent.com/4578910/113671311-c5338880-96e8-11eb-9f2d-4ecbd0fd2605.png)

Actual results：
**return newRS 3 stableRS 7**

![image](https://user-images.githubusercontent.com/4578910/113673421-8f43d380-96eb-11eb-9391-b143671ddb0a.png)
![image](https://user-images.githubusercontent.com/4578910/113673893-1c872800-96ec-11eb-9d23-58863c26229e.png)
![image](https://user-images.githubusercontent.com/4578910/113673557-ba2e2780-96eb-11eb-82f4-f07579f43473.png)

case2:
```
  replicas: 5
  strategy:
    canary:
      maxSurge: 5
      maxUnavailable: 0
      canaryService: rollout-preview
      stableService: rollouts-demo
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 50
      - pause: {}
      - setWeight: 80
      - pause: {}
```
Expected results：
**return newRS 5 stableRS 5**

Actual results：
**return newRS 4 stableRS 1**
- there may be have a capacity risk in the prod

![image](https://user-images.githubusercontent.com/4578910/113674891-50168200-96ed-11eb-8745-03eaf83f56a3.png)

## Diagnostics

What version of Argo Rollouts are you running?

argoproj/argo-rollouts:v0.10.2

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
For case 1, the screenshot and behavior appear to be correct:

> Actual results：
> **return newRS 3 stableRS 7**
> 
> ![image](https://user-images.githubusercontent.com/4578910/113673421-8f43d380-96eb-11eb-9391-b143671ddb0a.png)

The total pods did not go below maxUnavailable of 0 (10 pods). It terminated three of the revision 1 ReplicaSets pods only *after* revision 2 had three ready pods.

**Comment by jessesuen** [comment]
For case 2, I see that you are highlighting the fact that the EndPoint does not have the correct total of pods in the list. However, please know that just like Deployments, Rollouts does not monitor if the Endpoints or EndpointSlices. Rollouts only operates on what the ReplicaSet reports as available and uses those numbers to calculate weight.

> Expected results：
> **return newRS 5 stableRS 5**
> 
> Actual results：
> **return newRS 4 stableRS 1**
> 
> * there may be have a capacity risk in the prod
> 
> ![image](https://user-images.githubusercontent.com/4578910/113674891-50168200-96ed-11eb-8745-03eaf83f56a3.png)
> 

So from what I can tell, the Rollout is behaving as designed.

**Comment by jessesuen** [comment]
> Expected results：
> return newRS 5 stableRS 5

The above is an incorrect expectation. 

> Actual results：
> return newRS 4 stableRS 1

`newRS 4 stableRS 1` are expected given the parameters:

```yaml
    canary:
      maxSurge: 5
      maxUnavailable: 0
```
