### ISSUE TITLE
Support integration with istio virtual-service in another namespace for canary traffic routing

### ISSUE THREAD

**Issue by gaurav517** [argoproj/argo-rollouts#1096]
# Summary

In current canary traffic routing with istio, we can refer to a istio virtual service but that virtual service needs to be in same namespace as rollout. We should be able to refer to a virtual service that is not in rollout namespace.

Current:
```
  strategy:
    canary:
      canaryService: canary-svc  
      stableService: stable-svc 
      trafficRouting:
        istio:
          virtualService: 
            name: rollout-vsvc   # expects virtual service to be in same namespace
            routes:
            - primary
```

Solution should enable following:
```
  strategy:
    canary:
      canaryService: canary-svc
      stableService: stable-svc
      trafficRouting:
        istio:
          virtualService: 
            name: rollout-vsvc.vsvc-ns  # rollout-vsvc in in vscv-ns namespace. 
            routes:
            - primary
```

# Use Cases

In some cases istio virtual service can live in different namespace.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
