### ISSUE TITLE
Support having multiple VirtualService objects

### ISSUE THREAD

**Issue by dsbos** [argoproj/argo-rollouts#1100]
# Summary

Rollout does not seem to support having (specifically, updating weights in) multiple VirtualService objects.

Per the Rollout specification currently at
https://argoproj.github.io/argo-rollouts/features/specification/, in particular, this part:
```
        # Istio traffic routing configuration
        istio:
          virtualService: 
            name: rollout-vsvc  # required
            routes:
            - primary # At least one route is required
```
it _does_ support having multiple Istio HTTPRoute sub-objects in a VirtualService (via having that `routes` member be a list of HTTPRoute names).

However, Rollout does _not_ support having multiple VirtualService objects (since the value of member `virtualService` is single object)

If member `virtualService`, which currently gives one sub-object specifying a VirtualService, were replaced with a member (e.g., `virtualServices`) listing _multiple_ such specification sub-objects, then Rollout would support having multiple VirtualServices (each with its own name and own list of HTTPRoute names).

For backward compatibility, Rollout could keep `virtualService` when adding `virtualServices` (making it a semantic error to specify both).

# Use Cases

This enhancement is needed to support Istio-based setups in which a service's routes are given in multiple VirtualService objects rather than just a single one. 

(Recall that Istio allows splitting up a service's routing into multiple VirtualService objects. Also, note that mapping from ingress host names to services might involve multiple host names, per–URI-path routing, and multiple target services. For multiple routes going to the same target service, sometimes splitting into multiple VirtualService objects makes things (e.g., matching rules) much simpler.)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
