### ISSUE TITLE
validation error when service fqdn is used in virtual service destination

### ISSUE THREAD

**Issue by gaurav517** [argoproj/argo-rollouts#1105]
## Summary 

If fqdn is used in istio virtual service route destinations, rollout gives error. 

For example, if following is the virtual service definition:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    app: test-deployment-app
  name: test-deployment-app-intra-cluster
  namespace: test-ns
spec:
  gateways:
  - mesh
  hosts:
  - test-deployment-app.test-ns.svc.cluster.local
  http:
  - name: main
    route:
    - destination:
        host: test-deployment-app-canary.test-ns.svc.cluster.local
        port:
          number: 8080
      weight: 0
    - destination:
        host: test-deployment-app.test-ns.svc.cluster.local
        port:
          number: 8080
      weight: 100
```
rollout gives following error:
```
The Rollout "test-deployment-app" is invalid: spec.strategy.canary.trafficRouting.istio.virtualService.name: Invalid value: "test-deployment-app-intra-cluster": Istio VirtualService has invalid HTTP routes. Error: Canary Service 'test-deployment-app-canary' not found in route
```

Using fqdn is recommended by istio (https://istio.io/latest/docs/reference/config/networking/virtual-service/#Destination):
```
To avoid potential misconfiguration, it is recommended to always use fully qualified domain names over short names.
```

## Diagnostics

v0.10

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
