### ISSUE TITLE
[Bug] Kustomize configMapGenerator and merged patch do not work with apiVersion: argoproj.io/v1alpha1

### ISSUE THREAD

**Issue by henrydecovo** [argoproj/argo-rollouts#111]
Hi,

I've spent a few hours trying to debug an issue introduced when trying out Rollouts with Kustomize.

I was following the guide at the link below which suggests that on each kustomize build, the config map name has a hash suffix appended to trigger a rolling update of pods on configmap changes.

https://github.com/kubernetes-sigs/kustomize/blob/master/examples/configGeneration.md

The issue is, Kustomize works as expected when the standard Deployment resource type is used (see Kustomize renaming api-2-config-map -> production-api-2-config-map-g875tt789c):

![image](https://user-images.githubusercontent.com/31742730/59726515-c5e2ee00-91e6-11e9-8161-f64e5e3c9a71.png)

However, when using the Rollout resource type under apiVersion argoproj.io/v1alpha1:

![image](https://user-images.githubusercontent.com/31742730/59726540-ead76100-91e6-11e9-93a9-063204431537.png)

Note how the name in configMapKeyRef is not updated with the prefix and hash suffix.

**Environment:**
Kustomize v2.0.3 (installed on Mac via Homebrew)
Argo Rollouts API version: argoproj.io/v1alpha1
Resource type: Rollout

**Comment by jessesuen** [comment]
This requires the the use of Kustomize name reference transformers:
https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/README.md#name-reference-transformer

in combination with CRDs:
https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/crd/README.md

The issue is that Kustomize needs to be "taught" about a Rollout object, and that configMaps can be referenced under `spec/template/spec/volumes/configMap/name` just like Deployments.

We should figure out the appropriate transformer config to and publish this information as part of our documentation.

**Comment by jessesuen** [comment]
@Gknoblau did the dirty work of figuring this out.

The transformer config should look like:

`rollout-transform.yaml`
```yaml
nameReference:
  - kind: ConfigMap
    fieldSpecs:
      - path: spec/template/spec/volumes/configMap/name
        kind: Rollout
      - path: spec/template/spec/initContainers/envFrom/configMapRef/name
        kind: Rollout
      - path: spec/template/spec/initContainers/env/valueFrom/configMapKeyRef/name
        kind: Rollout
      - path: spec/template/spec/containers/envFrom/configMapRef/name
        kind: Rollout
      - path: spec/template/spec/containers/env/valueFrom/configMapKeyRef/name
        kind: Rollout
  - kind: Secret
    fieldSpecs:
      - path: spec/template/spec/volumes/secret/secretName
        kind: Rollout
      - path: spec/template/spec/initContainers/envFrom/secretRef/name
        kind: Rollout
      - path: spec/template/spec/initContainers/env/valueFrom/secretKeyRef/name
        kind: Rollout
      - path: spec/template/spec/containers/envFrom/secretRef/name
        kind: Rollout
      - path: spec/template/spec/containers/env/valueFrom/secretKeyRef/name
        kind: Rollout
  - kind: Service
    fieldSpecs:
      - path: spec/strategy/blueGreen/activeService
        kind: Rollout
      - path: spec/strategy/blueGreen/previewService
        kind: Rollout

commonLabels:
  - path: spec/selector/matchLabels
    create: true
    kind: Rollout
  - path: spec/template/metadata/labels
    create: true
    kind: Rollout

commonAnnotations:
  - path: spec/template/metadata/annotations
    create: true
    kind: Rollout

varReference:
  - path: spec/template/spec/initContainers/command
    kind: Rollout
  - path: spec/template/metadata/annotations
    kind: Rollout
  - path: spec/template/metadata/annotations
    kind: Deployment
```

And the config should be referenced in a `kustomization.yaml` like so:
```yaml
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

configurations:
  - ./rollout-transform.yaml
```
