### ISSUE TITLE
Add the ability to cherry pick / exclude metrics from analysis templates and cluster analysis templates

### ISSUE THREAD

**Issue by mclarke47** [argoproj/argo-rollouts#1124]
# Summary

(This change applies to Cluster Analysis Templates and namespaced Analysis Templates, but I am going to refer to them jointly as "analysis templates" for brevity)

In order to reduce duplication it would be useful to have the ability to cherry pick or exclude specific metrics from analysis templates.

For example:

Given an analysis template with the following metrics:

`http-latency`
`http-error-ratio`

If a Rollout wishes to use this analysis template, both metrics must pass. However if we have a service with a very strict `http-error-ratio` SLO but a lax `http-latency` SLO then it cannot use this analysis template and must create a new template with just the `http-error-ratio` metric. The metric sections of the analysis templates here might even be duplicated leading to further problems like diverging definitions.

# Use Cases

A solution to this could be the ability to include/exclude metrics from analysis templates like so:

Given an analysis template with the metrics:

`http-latency` `http-error-ratio` `cpu-util`

A canary Rollout with the following definition:

```yaml
steps:
  - setWeight: 10
  - pause: {duration: 5m}
  - analysis:
      templates:
        - templateName: my-template
          clusterScope: true
          excludeMetrics:
            - http-latency
```

Would only execute the metrics `http-error-ratio` and `cpu-util`.

While a canary Rollout with the following:

```yaml
steps:
  - setWeight: 10
  - pause: {duration: 5m}
  - analysis:
      templates:
        - templateName: my-template
          clusterScope: true
          includeMetrics:
            - http-latency
```
Would only execute the metrics `http-latency`.

## Possible error scenarios:

It would not be possible to use both `excludeMetrics` and `includeMetrics` at the same time.

If `includeMetrics` is present it must have a length > 0

`excludeMetrics` cannot include all metrics in an analysis template

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
