### ISSUE TITLE
Provide manifests so rollout dashboard can be accessed via Ingress

### ISSUE THREAD

**Issue by DanTulovsky** [argoproj/argo-rollouts#1184]
# Summary

It would be very helpful if the GUI Dashboard was served by the operator itself, so that we could setup a stable URL for people to use to see the current rollout status.

# Use Cases

All the time instead of the CLI started dashboard.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
We actually made the kubectl-argo-rollouts plugin available as an image:
https://quay.io/repository/argoproj/kubectl-argo-rollouts

It should already be possible to create a set of manifests that make this pod available via Ingress/Service.

We can/should do this in an official capacity as an optional set of manifests to apply if you want to expose the dashboard.

**Comment by carlosalca** [comment]
Hi! 

Is it possible to run the dashboard locally ? I'm not able to do it. I'm using the argo rollouts plugin in a macOS and when execute the command ```kubectl argo rollouts dashboard``` and I get this error:
```
Error: unknown command "dashboard" for "kubectl-argo-rollouts"
Run 'kubectl-argo-rollouts --help' for usage.
```

Any idea ? 

Thanks!

**Comment by jessesuen** [comment]
It is but since we didnt update brew formulate you are probably running v0.10 and not v1.0. You can download 1.0-rc1 directly:
https://github.com/argoproj/argo-rollouts/releases/tag/v1.0.0-rc1 until we cut the official release next week

**Comment by carlosalca** [comment]
Thanks a lot @jessesuen !! I'll try!

Regards!

**Comment by jessesuen** [comment]
FYI, v1.0 is released! https://github.com/argoproj/argo-rollouts/releases/tag/v1.0.0

**Comment by perenesenko** [comment]
@jessesuen 
I'll take this one

**Comment by DanTulovsky** [comment]
Hi.

Thank you for this, but it looks like there is no way to select a namespace in the UI. It's hard-coded to the namespace the dashboard is in.

Is the expectation that one dashboard is run in every namespace?

Dan

**Comment by mikutas** [comment]
>Is the expectation that one dashboard is run in every namespace?

Yes until #1255 closed, I guess.

**Comment by armenr** [comment]
I understand what the dashboard is intended for, and that it's not meant for production use or to be accessed as some kind of administrative plane for real-world cases.

With that said, I'm building out a local cluster for development and tooling within our TechOps board, as we spec out and learn about how to apply argo-rollouts in our workloads.

To that end, I'm trying to expose rollouts with an ingress...but I must be missing something obvious. :-\ 

Code can be found here: https://github.com/armenr/5thK8s/blob/main/dependencies/argo-rollouts/patches/

I've tried with both an Ingress and an IngressRoute (Traefik) and neither seem to work. I also wondered whether I needed a middleware to rewrite the path, but that doesn't seem to help either (although it's been the key for getting /workflows and /argocd accessible via local cluster).

I'd appreciate any help, or any eyes that can point out what I'm stupidly missing. Thank you! :)

Ingress: 
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rollouts-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /$2
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: argo-rollouts-prefix-middleware@kubernetescrd
spec:
  rules:
    - host: kubernetes.docker.internal
      http:
        paths:
          - backend:
              service:
                name: argo-rollouts-dashboard
                port:
                  name: http
            path: /rollouts
            pathType: ImplementationSpecific

```

Middleware:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: prefix-middleware
  namespace: argo-rollouts
spec:
  stripPrefix:
    prefixes:
      - /rollouts/
```

Helm values:
```yaml
## Custom values
clusterInstall: true
installCRDs: true
keepCRDs: true

dashboard:
  enabled: true
  component: rollouts-dashboard
  service:
    type: ClusterIP
  serviceAccount:
    create: true
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

```

**Comment by Sudhamsh** [comment]
Did anyone solve exposing the dashboard with ingress?

**Comment by Sudhamsh** [comment]
Found the solution: install dashboard manifest and create ingress to svc argo-rollouts-dashboard
https://raw.githubusercontent.com/argoproj/argo-rollouts/master/manifests/dashboard-install.yaml

**Comment by Hronom** [comment]
@jessesuen do you plan to make dashboard ready for production use or properly support [Rollout Extension in Argo CD](https://github.com/argoproj-labs/rollout-extension)?

**Comment by ayush-aroraa** [comment]
> Found the solution: install dashboard manifest and create ingress to svc argo-rollouts-dashboard https://raw.githubusercontent.com/argoproj/argo-rollouts/master/manifests/dashboard-install.yaml

i tried this but Target group is unhealthy and no dashboard gets opened, could you tell how you connected your argo-rollout resources to ingress. I followed the official Argo documentation to install Argo rollouts

**Comment by fixdigitalinc** [comment]
This worked for me with Pomerium Ingress. you just need to use extra paths.

controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
dashboard:
  enabled: true
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: "pomerium"
    annotations:
      ingress.pomerium.io/policy: |
        allow:
          or:
            - domain:
                is: domain1.com
            - domain:
                is: domain2.com
      external-dns.alpha.kubernetes.io/hostname: rollouts.domain.com
    hosts:
      - rollouts.domain.com
    paths: {}
    extraPaths:
      - path: /rollouts
        pathType: ImplementationSpecific
        backend:
           service:
             name: argo-rollouts-dashboard
             port:
               number: 3100
      - path: /api
        pathType: ImplementationSpecific
        backend:
           service:
             name: argo-rollouts-dashboard
             port:
               number: 3100

**Comment by sv6375261073** [comment]
```
ingress:
    # -- Enable dashboard ingress support
    enabled: true
    # -- Dashboard ingress annotations
    annotations: {}
    # -- Dashboard ingress labels
    labels: {}
    # -- Dashboard ingress class name
    ingressClassName: "kong-class"

    # -- Dashboard ingress hosts
    ## Argo Rollouts Dashboard Ingress.
    ## Hostnames must be provided if Ingress is enabled.
    ## Secrets must be manually created in the namespace
    hosts: ["argorollouts.xyz.com"]
      # - argorollouts.example.com

    # -- Dashboard ingress paths
    paths:
      - /
    # -- Dashboard ingress path type
    pathType: Prefix
    # -- Dashboard ingress extra paths
    extraPaths: []
      # - path: /*
      #   backend:
      #     serviceName: ssl-redirect
      #     servicePort: use-annotation
      ## for Kubernetes >=1.19 (when "networking.k8s.io/v1" is used)
      # - path: /*
      #   pathType: Prefix
      #   backend:
      #     service
      #       name: ssl-redirect
      #       port:
      #         name: use-annotation

    # -- Dashboard ingress tls
    tls: []
      # - secretName: argorollouts-example-tls
      #   hosts:
      #     - argorollouts.example.com

```
