### ISSUE TITLE
Allow insecure Prometheus provider in AnalysisTemplate

### ISSUE THREAD

**Issue by saberkan** [argoproj/argo-rollouts#1192]
# Summary

What change needs making?
Currently, there is no known procedure to add an additional trusted CA to argo rollouts. 
When using an HTTPS prometheus provider in AnalysisTemplate, the following error message occurs: 
`Error Message: Post <myprometheus url>: x509: certificate signed by unknown authority`

We would like to have the possibility to configure an insecure flag for prometheus provider in AnalysisTemplate (as it's the case for web provider).  Like the following: 
```
    provider:
      prometheus:
        insecure: true # this is the requested feature
        address: myprometheus
        query: |
          myquery
```

# Use Cases

When would you use this?
When the prometheus CA used in AnalysisTemplate is not trusted by argo rollouts pod.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
