### ISSUE TITLE
promote ROLLOUT doesn't handle two analysis steps in a row

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#1203]
## Summary 

What happened/what you expected to happen?

Tried to write an e2e test where a canary rollout had two analysis steps in a row, and the test would promote the rollout from the first analysis step to the next. The controller did not realize that the currentAnalysisRun for the rollout is actually for the previous step, and continues to wait for it to complete, rather than starting the next analysisrun.

## Diagnostics

What version of Argo Rollouts are you running? v1.0

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
Test was:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: inconclusive
spec:
  metrics:
  - name: inconclusive
    successCondition: "false"
    failureCondition: "false"
    provider:
      web:
        url: https://api.github.com/repos/argoproj/argo-rollouts
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-promote-full
spec:
  strategy:
    canary:
      # this analysis should not run because it has a starting step of 5 which we never get to
      analysis:
        templates:
        - templateName: sleep-job
        startingStep: 5

      steps:
      - pause: {duration: 24h}
      - analysis:
          templates:
          - templateName: sleep-job
          args:
          - name: duration
            value: 24h
      - analysis:
          templates:
          - templateName: inconclusive
      - pause: {}
      - analysis: # we should never get to step 5
          templates:
          - templateName: sleep-job
  selector:
    matchLabels:
      app: canary-promote-full
  template:
    metadata:
      labels:
        app: canary-promote-full
    spec:
      containers:
      - name: canary-promote-full
        image: nginx:1.19-alpine
        resources:
          requests:
            memory: 16Mi
            cpu: 1m
```

**Comment by huikang** [comment]
Hi, @jessesuen , I can look into this issue if you don't have bandwidth.

**Comment by jessesuen** [comment]
@huikang sure! I think I have an idea for the fix:

The current code assumes `c.currentArs.CanaryStep` is correct. However, in the case of two AnlysisRuns in a row, c.currentArs.CanaryStep refers to the previous analysisrun so we are miscalculation it. We need to differentiate the two and realize that the `status.canary.currentStepAnalysisRunStatus` is actually obsolete.

The way I'm thinking of fixing this is: we should inject more bookkeeping to the annotations of the analysis run, namely a new annotation to record the step index. 

Then, this logic will need to change, so that we do not consider the previous analysiRun current (because the annotation of the analysirun does not match current step index):

```golang
// FilterCurrentRolloutAnalysisRuns returns analysisRuns that match the analysisRuns listed in the rollout status
func FilterCurrentRolloutAnalysisRuns(analysisRuns []*v1alpha1.AnalysisRun, r *v1alpha1.Rollout) (CurrentAnalysisRuns, []*v1alpha1.AnalysisRun) {
	currArs := CurrentAnalysisRuns{}
	otherArs := []*v1alpha1.AnalysisRun{}
	getArName := func(s *v1alpha1.RolloutAnalysisRunStatus) string {
		if s == nil {
			return ""
		}
		return s.Name
	}
	for i := range analysisRuns {
		ar := analysisRuns[i]
		if ar != nil {
			switch ar.Name {
			case getArName(r.Status.Canary.CurrentStepAnalysisRunStatus):
				currArs.CanaryStep = ar
			case getArName(r.Status.Canary.CurrentBackgroundAnalysisRunStatus):
				currArs.CanaryBackground = ar
			case getArName(r.Status.BlueGreen.PrePromotionAnalysisRunStatus):
				currArs.BlueGreenPrePromotion = ar
			case getArName(r.Status.BlueGreen.PostPromotionAnalysisRunStatus):
				currArs.BlueGreenPostPromotion = ar
			default:
				otherArs = append(otherArs, ar)
			}
		}
	}
	return currArs, otherArs
}
```

**Comment by huikang** [comment]
@jessesuen , thanks for the guidance.

**Comment by huikang** [comment]
Hi, @jessesuen I was trying reproduce what you observed by the following simplified example

```yaml
# Adapted from argo-rollouts/docs/getting-started/basic/rollout.yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  replicas: 5
  strategy:
    canary:
      steps:
        - setWeight: 20
        - analysis:                                        # <-------- first analysis step, exit 0 (success)
            templates:
              - templateName: sleep-job
            args:
            - name: duration
              value: 10s
        - analysis:                                        # <-------- second analysis step, exit 0 (success)
            templates:
              - templateName: sleep-job
            args:
            - name: duration
              value: 5s
        - setWeight: 40                               # step 4 after two analysis steps in a row
        - pause: {}
        - setWeight: 60
        - pause: {}
```

In this example, I see that the controller can promote from the first analysis step to the second one, and then reach step 4 after the second analysis step. Do I miss anything to reproduce the error?

**Comment by jessesuen** [comment]
In your test did you see both AnalysisRuns get created? In my example, the rollout believed it was on the second analysisrun even though the second one never got created (there was only a total of one analysisruns)

**Comment by huikang** [comment]
Yes, both AnalysisRuns got created in the order as defined in the canary steps: the 10s sleep job and then the 5s sleep job.


Are you referring to the following 2 analysisrun in your example? If so, are you saying the second one (inconclusive) never got created )
```
      - analysis:
          templates:
          - templateName: sleep-job
          args:
          - name: duration
            value: 24h
      - analysis:
          templates:
          - templateName: inconclusive
```
