### ISSUE TITLE
ValueFrom on web provider isn't working properly

### ISSUE THREAD

**Issue by DanTulovsky** [argoproj/argo-rollouts#1205]
## Summary 

I have an AnalysisTemplate that uses the web provider. I am trying to populate the Authorization Header. This is what it looks like:

```
spec:
  args:
    - name: access-token
      valueFrom:
        secretKeyRef:
          key: staging
          name: api
  metrics:
    - failureCondition: result == 'true'
      interval: 1m
      name: error-rate
      provider:
        web:
          headers:
            - key: Authorization
              value: 'Bearer {{ args.access-token }}'
          jsonPath: '{$.data.attributes.state}'
          timeoutSeconds: 20
          url: >-
            https://my/url
```

If I change `valueFrom` to a simple `value`, and populate that directly with what is in the 'api' secret under the 'staging' key, then everything works correctly.  With `valueFrom`, when I do a tcpdump, I see:

```
Authorization: Bearer dummy-value
```

The code seems to set that by default, and, I think, it's supposed to override it with the value from the secret.

Note:

- The secret exists in the same namespace as the binary being updated (staging-foo)
- argo-rollouts is running in a different namespace (staging)

If I move the secret from staging-foo -> staging, I get an error in the argo-rollouts log that the secret does not exist, so it seems to be finding it correctly.  I've tried having the secret in both namespaces, with the same result as described here (dummy-value).

## Diagnostics

What version of Argo Rollouts are you running?  

Version: `v1.0.0-rc1`

```
# Paste the logs from the rollout controller

The only relevant log I see is:

```
msg="measurement had error: received non 2xx response code: 403"
```

but that is because the Bearer token is not getting set correctly.

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
