### ISSUE TITLE
More aggressive cleanup of old AnalysisRuns and Experiments

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#1214]
# Summary

The current default behavior for deleting old AnalysisRuns and Experiments, is that a Rollout will keep around the old objects for the same amount of `spec.revisionHistoryLimit`, which defaults to 10. This seems to be too much for users, who don't really care to keep these around that long. 

I think the default should be changed to delete the old objects when the Rollout reaches Healthy (a.k.a. Completed) state. This will declutter the namespace and things like the Argo UI.

If we change the default to delete old objects more aggressively, one question is if should we provide a knob to increase the retention of old AnalysisRuns/Experiments (e.g. for debugging purposes)? 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by MarkSRobinson** [comment]
IMO, a successful experiments/analysis has basically zero value after the service has been rolled out.  A failed run actually does.  I would prefer something like keep up to X failed runs before recycling them, and just delete successful runs soon after a deployment has completed.

**Comment by huikang** [comment]
Sometimes we may need to keep some successful analysis run for debugging purpose (e.g., to compare the results between successful run and failed one). The proposed change could be 

1. decouple the retention of analysisrun from spec.revisionHistoryLimit
2. introduce two retention knobs: 

```yaml
        - analysis:
               retentionSuccessfulRuns: 1 # number of successful run to keep, default is 0
               retentionFailedRuns: 2 # number of failed run to keep, default is 2
```

What do you think?
