### ISSUE TITLE
Support traffic managment in bluegreen strategy

### ISSUE THREAD

**Issue by huikang** [argoproj/argo-rollouts#1216]
# Summary

Support traffic management in bluegreen strategy

# Use Cases

During bluegreen update, after the preview RS is ready, I'd like to control the percentage of traffic being sent to the stable version and the preview version.

One workaround is to use canary strategy with `setWeight: 100` as the first step. However, having the traffic routing in the bluegreen strategy would the configuration more manageable and clear.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
I don't think this can work because fundamentally, (basic) canary traffic shaping works is by sharing label selectors of some service and adjusting the replica counts of the canary vs. stable proportionally to the desired weight. If you are sharing label selectors with blue-green strategy, then you are already sending 50% of traffic to blue vs. green stack, since the blue and green are fully scaled.

Unless you are referring to ingress/mesh support in blue-green, but I don't think it is worth the effort of integrating traffic router support in blue-green, when the canary is already able to achieve the use case. The only benefit I see here is syntax.

**Comment by huikang** [comment]
@jessesuen , thanks for your comment. I agreed that the major benefit is syntax. For example, currently we have to ask customer to do something like following and use a mutating webhook to convert to canary strategy.

```
kind: Rollout
    strategy:
      bluegreen:
      trafficRouting:
          istio:
                virtualService:
                    name: istio-rollout-vsvc
          destinationRule:
                    name: rollout-destrule
                    previewSubsetName: preview
                    stableSubsetName: stable
```

With this syntax enhancement, it will simplify the process. If you think this is doable for v1.1, I can look into this issue.

**Comment by jessesuen** [comment]
> During bluegreen update, after the preview RS is ready, I'd like to control the percentage of traffic being sent to the stable version and the preview version.

The fact that you want to split traffic at all, means you really want to be using canary strategy not, blue-green. So I don't even think syntax is incorrect here.

> One workaround is to use canary strategy with setWeight: 100 as the first step. However, having the traffic routing in the bluegreen strategy would the configuration more manageable and clear.

Actually, to achieve your use case using canary strategy,  the syntax would be:

```yaml
steps:
- setCanaryScale: {weight: 100}     # scale up canary stack to 100% (without it receiving traffic)
- setWeight: 5                                   # once it is scaled up, send 5% of traffic to canary stack
- pause: {}
```

I really don't think we should complicate the implementation of blue-green strategy with traffic routing support since:
1) use case is already covered by canary
2) the canary syntax appropriate given the use case is to achieve traffic splitting
