### ISSUE TITLE
InvalidSpec not properly set in some circumstances

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#1222]
## Summary 

A user applied the following invalid rollout (which specifies both workloadRef and template/selector):

```yaml
spec:
  selector:
    matchLabels:
      app: credential-adapter
  strategy:
    blueGreen:
      activeService: credential-adapter-appd-stable-service
  template:
    metadata:
      labels:
        app: credential-adapter
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: credential-adapter-appd-deployment
```

In this scenario, the controller did not update the rollout status with a condition/phase about the invalid spec.

## Diagnostics

What version of Argo Rollouts are you running? v1.0.0

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
