### ISSUE TITLE
unknown field "name" in io.argoproj.v1alpha1.Rollout.spec.template.metadata

### ISSUE THREAD

**Issue by vadasambar** [argoproj/argo-rollouts#1235]
## Summary 

What happened/what you expected to happen?
I updated argo rollouts from `v0.10.2` -> `v1.0.0` and my rollouts started throwing error on `kubectl apply`.

## Diagnostics
I think this is related to the change in how CRDs handle `spec.preserveUnknownFields` as written in the [release notes](https://github.com/argoproj/argo-rollouts/releases). 

Steps to reproduce
```bash
# Install v0.10.2
kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-rollouts/v0.10.2/manifests/install.yaml
# No error
# Based on https://raw.githubusercontent.com/argoproj/argo-rollouts/master/docs/getting-started/basic/rollout.yaml
kubectl apply -f rollout-demo-with-pod-name.yaml
kubectl delete -f rollout-demo-with-pod-name.yaml
# Update to v1.0.0
kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-rollouts/v1.0.0/manifests/install.yaml
# Apply the same yaml again
kubectl apply -f rollout-demo-with-pod-name.yaml
# Leads to error
# error: error validating "rollout-demo-with-pod-name.yaml": error validating data: ValidationError(Rollout.spec.template.metadata): unknown field "name" in io.argoproj.v1alpha1.Rollout.spec.template.metadata; if you choose to ignore these errors, turn validation off with --validate=false

```
yaml
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      # THIS FIELD IS THE PROBLEM
      name: rollouts-demo
      labels:
        app: rollouts-demo
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
```
Rollout is using the same `PodTemplateSpec` as Deployment
https://github.com/argoproj/argo-rollouts/blob/04201fb068dab917218e0533231f8007d2cba71c/pkg/apis/rollouts/v1alpha1/types.go#L49
And it has a `Name` field. 
https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1#ObjectMeta
But Argo Rollouts considers it an error for some reason. 

What version of Argo Rollouts are you running?
v0.10.2

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by huikang** [comment]
I think this is an expected behavior. You don't need the `name` in `spec.template` because the name of the replicaset will be generated from the rollout name.

Do I miss anything here?

**Comment by jessesuen** [comment]
@huikang is right. I didn't read through the issue carefully before triaging and assumed this was a regression.

```
  template:
    metadata:
      # THIS FIELD IS THE PROBLEM
      name: rollouts-demo
```

It's not expected to specify name at this level. The reason this is now suddenly happening with v1.0 is that v1.0 CRDs no longer accept "unknown fields" and reject attempts to set them. 

Will close this as expected behavior.
