### ISSUE TITLE
Surface ALB information into rollout status

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#1241]
# Summary

The recent [ALB weight verification](https://argoproj.github.io/argo-rollouts/features/traffic-management/alb/#weight-verification) feature allowed Argo Rollouts to discover information about the underlying AWS LoadBalancer and TargetGroups, including ARN, IDs, tags, etc... Currently this is only used for verifying the weights of the TargetGroup, but it is not used anywhere else. For debugging and analysis purposes, it would be useful to surface the ALB and target group information in the rollout status. Like so:

```yaml
status:
  alb:
    loadBalancer:
      name: k8s-devdeplo-testdele-b9061572ad
      arn: arn:aws:elasticloadbalancing:us-west-2:1234567891011:loadbalancer/app/k8s-devdeplo-testdele-abcdef1234/3a47c96b75571d0e
    canaryTargetGroup:
      name: k8s-devdeplo-testdele-ab72c5b132
      arn: arn:aws:elasticloadbalancing:us-west-2:1234567891011:targetgroup/k8s-devdeplo-testdele-ab72c5b132/df2957821c1214fc
    stableTargetGroup:
      name: k8s-devdeplo-testdele-8832d6519a
      arn: arn:aws:elasticloadbalancing:us-west-2:1234567891011:targetgroup/k8s-devdeplo-testdele-8832d6519a/df2957821c1214fc 
```

# Use Cases

When would you use this?

In order to query AWS CloudWatch for metrics about a canary service, we need to know the canary TargetGroup. However, the target group name is not easily known to the user. By filling in the target group information under the rollout status, it would allow users to perform queries about metrics specific to the canary target group by [passing the target group name to the cloudwatch query](https://github.com/argoproj/argo-rollouts/issues/1242)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
