### ISSUE TITLE
Allow analysis arguments to get valueFrom Rollout status

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#1242]
# Summary

Currently, we can pass arguments to AnalysisTemplates from `metadata` labels and annotations, e.g.

```yaml
  strategy:
    canary:
      analysis:
        templates:
        - templateName: args-example
        args:
        - name: region
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['region']
```

We should also allow passing arguments to AnalysisTemplates whose value is derived from fields in the rollout status.

# Use Cases

As part of https://github.com/argoproj/argo-rollouts/issues/1241, we will be surfacing ALB information under the rollout status. For example:

```yaml
status:
  alb:
    loadBalancer:
      name: k8s-devdeplo-testdele-b9061572ad
      arn: arn:aws:elasticloadbalancing:us-west-2:1234567891011:loadbalancer/app/k8s-devdeplo-testdele-abcdef1234/3a47c96b75571d0e
    canaryTargetGroup:
      name: k8s-devdeplo-testdele-ab72c5b132
      arn: arn:aws:elasticloadbalancing:us-west-2:1234567891011:targetgroup/k8s-devdeplo-testdele-ab72c5b132/df2957821c1214fc
    stableTargetGroup:
      name: k8s-devdeplo-testdele-8832d6519a
      arn: arn:aws:elasticloadbalancing:us-west-2:1234567891011:targetgroup/k8s-devdeplo-testdele-8832d6519a/df2957821c1214fc 
```

Once that is available, it would then be useful to pass that information to an AnalysisTemplate, so that argo rollouts could perform CloudWatch queries against the canary targetgroup vs. stable targetgroup, like so:

```yaml
      analysis:
        templates:
        - templateName: cloud-watch-error-rate
        args:
        - name: env
          valueFrom:
            fieldRef:
              fieldPath: status.alb.canaryTargetGroup.name
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
