### ISSUE TITLE
Implement OpenShift Routes as a Traffic Manager

### ISSUE THREAD

**Issue by mbhatip** [argoproj/argo-rollouts#1258]
# Summary

OpenShift routes is an alternative for managing traffic on a service level. It should be available as another Traffic Manager option.

# Use Cases

The user has an OpenShift cluster without a service mesh installed. Argo Rollouts can still carry out canary deployments on a service level.

I will be making a PR for this soon, wanted to gauge whether this was practical, relevant, or necessary. I'd appreciate any feedback or advice!

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
> The user has an OpenShift cluster without a service mesh installed. Argo Rollouts can still carry out canary deployments on a service level.
> I will be making a PR for this soon, wanted to gauge whether this was practical, relevant, or necessary. I'd appreciate any feedback or advice!

Supporting OpenShift's canary mechanism would be a great improvement to Rollouts. Since I'm unfamiliar with OpenShift Routes, can you provide some details on how this would work, as well as the proposed spec changes to support this? Links to their docs would also help.

**Comment by mbhatip** [comment]
https://docs.openshift.com/container-platform/4.7/applications/deployments/route-based-deployment-strategies.html#deployments-ab-testing_route-based-deployment-strategies

This link highlights how to shift traffic from one service to another using routes. Routes have the following format: 

```
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: main-route
  ...
spec:
  host: >-
    hostlinkhere
  to:
    kind: Service
    name: stable-service
    weight: 100
  alternateBackends:
    - kind: Service
      name: canary-service
      weight: 0
  port:
    targetPort: http
  wildcardPolicy: None
```
Where you can specify as many or as little backends as you want using the alternateBackends field, as well as adjust the weight of traffic that goes to each.

The idea is the user would presumably have a route that exposes their stable service initially, then would deploy argo rollouts with: 
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
...
spec:
  strategy:
    canary:
      stableService: stable-service
      canaryService: canary-service
      trafficRouting:
        openshift:
          routes:
            - main-route
      steps:
      - setWeight: 30
      - pause: {duration: 60s}
      - setWeight: 60
      - pause: {duration: 60s}
```
and argo rollouts would handle adding the alternateBackend to the route if it doesn't exist already, change the weights according to the step of the deployment, and finally delete the alternateBackend once the deployment is complete (since stable-service would be pointing at the new updated pods)
