### ISSUE TITLE
scaleDownDelayRevisionLimit to limit number of old replicasets scaled up

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#129]
To complement https://github.com/argoproj/argo-rollouts/issues/128, we should introduce a new field, scaleDownDelayRevisionLimit, which is a max count of how many old replicasets in which we would honor their scaleDownDelay for.

For example, if I set:

```yaml
strategy:
  blueGreen:
    scaleDownDelaySeconds: 86400 # 1 day
    scaleDownDelayRevisionLimit: 1
```

Then I would only have one old ReplicaSet which is still scaled higher than zero. This solves the problem of deploying multiple times in a day, and not having too many old replicasets using up cluster resources.
