### ISSUE TITLE
ALB weight stays the same

### ISSUE THREAD

**Issue by mosheavni** [argoproj/argo-rollouts#1294]
## Summary 

I have a simple Rollout with canary, using ALB traffic router, I'm trying to set the weight, but for some reason the annotation in the ingress which controls the action remains at 100-0 weights all the time:
```
{
  "Type": "forward",
  "ForwardConfig": {
    "TargetGroups": [
      {
        "ServiceName": "express-info-stage-stable",
        "ServicePort": "80",
        "Weight": 100
      },
      {
        "ServiceName": "express-info-stage-canary",
        "ServicePort": "80",
        "Weight": 0
      }
    ]
  }
}
```

## Diagnostics

What version of Argo Rollouts are you running?
```
quay.io/argoproj/argo-rollouts:v1.0.2
```
## Paste the logs from the rollout controller
http://ix.io/3qKL

## Rollout manifest
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: express-info
    environment: stage
  name: express-info-stage
  namespace: backend
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: express-info-stage
      environment: stage
  strategy:
    canary:
      canaryService: express-info-stage-canary
      stableService: express-info-stage-stable
      steps:
      - setCanaryScale:
          weight: 10
      - pause: {}
      - setCanaryScale:
          weight: 50
      - pause: {}
      - setCanaryScale:
          matchTrafficWeight: true
      trafficRouting:
        alb:
          ingress: express-info-stage-private
          rootService: express-info-stage
          servicePort: 80
  template:
    metadata:
      labels:
        app.kubernetes.io/name: express-info-stage
        environment: stage
    spec:
      containers:
      - env:
        - name: VERSION
          value: c8fd2991
        image: mosheavni/express-info:c8fd2991
        imagePullPolicy: IfNotPresent
        name: express-info-stage
        ports:
        - containerPort: 3000
          name: app-port
          protocol: TCP
```
![image](https://user-images.githubusercontent.com/17252601/122948041-44993580-d383-11eb-9455-67809caa8ad1.png)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
