### ISSUE TITLE
Dashboard should support rootpath with ingress

### ISSUE THREAD

**Issue by sanzenwin** [argoproj/argo-rollouts#1318]
Recently I get the Http404 error about static files when I go to the homepage.
```yaml

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/configuration-snippet: |-
      proxy_ssl_server_name on;
      proxy_ssl_name $host;
      rewrite ^(/argo-rollouts)$ $1/ redirect;
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/secure-backends: "true"
  paths:
    - /argo-rollouts(/|$)(.*)
 ```
Argo-cd has support it:  https://github.com/argoproj/argo-cd/pull/3503
