### ISSUE TITLE
The lint subcommand shouldn't report missing '.spec.selector' for rollout using workload ref 

### ISSUE THREAD

**Issue by huikang** [argoproj/argo-rollouts#1327]
## Summary 

The lint subcommand reports error for the following valid rollout

```yaml
apiVersion: argoproj.io/v1alpha1               # Create a rollout resource
kind: Rollout
metadata:
  name: rollout-ref-deployment
spec:
  replicas: 5
  workloadRef:                                 # Reference an existing Deployment using workloadRef field
    apiVersion: apps/v1
    kind: Deployment
    name: rollout-ref-deployment
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 10s}
```

```
Error: spec.selector: Required value: Rollout has missing field '.spec.selector'
```

What happened/what you expected to happen?

no error should be reported

## Diagnostics

What version of Argo Rollouts are you running?

master

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
