### ISSUE TITLE
Terminated metric is marked as successful under analysisrun status

### ISSUE THREAD

**Issue by mclarke47** [argoproj/argo-rollouts#1329]
## Summary 

Terminated metric is marked as successful under `analysisrun.status.metricResults[]`.

```
  - count: 1
    measurements:
    - finishedAt: "2021-07-07T14:45:45Z"
      message: metric terminated
      metadata:
        job-name: 951f5097-1cdc-4308-9e18-650c0d87c5c4.my-metric.1
      phase: Successful
      startedAt: "2021-07-07T14:44:45Z"
    message: metric terminated
    name: my-metric
    phase: Successful
    successful: 1
```

A metric result was terminated, I'm assuming because the rollout was failing legitimately. However the `successful` field reads `1` which isn't really true as the job/po for the metric was never run.

## Diagnostics

What version of Argo Rollouts are you running? **V0.10.0**

```
# Paste the logs from the rollout controller

```
time="2021-07-07T14:45:34Z" level=info msg="terminating in-progress measurement" analysisrun=my-ar metric=my-metric namespace=my-ns
time="2021-07-07T14:45:34Z" level=info msg="job my-rollout/951f5097-1cdc-4308-9e18-650c0d87c5c4.my-metric.1 terminated" analysisrun=my-ar metric=my-metric namespace=my-ns

```
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
