### ISSUE TITLE
Rollout incorrectly determines that maxSurge and maxUnavailable are both zero

### ISSUE THREAD

**Issue by dthomson25** [argoproj/argo-rollouts#133]
The comparison used to determine if the maxSurge and maxUnavailable are both zero can return true in cases where the spec is valid. The following example will result in this case:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: example-rollout-canary
spec:
  minReadySeconds: 30
  replicas: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook
  strategy:
    canary:
      maxSurge: 25%
      maxUnavailable: 0
      steps:
      - setWeight: 20
      - pause:
          duration: 20
      - setWeight: 40
      - pause: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: guestbook
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        name: guestbook
        ports:
        - containerPort: 80
```
This conditional needs to be modified to allow situations like the above.
