### ISSUE TITLE
Abort rollout does not remove all canary pods for setCanaryScale

### ISSUE THREAD

**Issue by huikang** [argoproj/argo-rollouts#1337]
## Summary 

What happened/what you expected to happen?

Rollout abort should remove all canary pods for canary strategy. However, if the canary scale is set for >= 2 steps such as

```yaml
spec:
  replicas: 5
  strategy:
    canary:
      steps:
        - setCanaryScale:      <---- 1st set canary scale
            replicas: 2
        - setWeight: 20
        - pause: {}
        - setCanaryScale:      <---- 2nd set canary scale
            replicas: 4
        - setWeight: 40
        - pause: {}
```

When the rollout is aborted after the "2nd set canary scale" step, the abort will leave 2 canary pods running.
The expectation is that all canary should be removed after abort.

```
Namespace:       default
Status:          ✖ Degraded
Message:         RolloutAborted: Rollout aborted update to revision 2
Strategy:        Canary
  Step:          0/10
  SetWeight:     0
  ActualWeight:  0
Images:          argoproj/rollouts-demo:blue (stable)
                 argoproj/rollouts-demo:yellow (canary)
Replicas:
  Desired:       5
  Current:       7
  Updated:       2
  Ready:         7
  Available:     7

NAME                                       KIND        STATUS      AGE   INFO
⟳ rollouts-demo                            Rollout     ✖ Degraded  3m8s  
├──# revision:2                                                          
│  └──⧉ rollouts-demo-75f756d67b           ReplicaSet  ✔ Healthy   105s  canary
│     ├──□ rollouts-demo-75f756d67b-l4dhk  Pod         ✔ Running   105s  ready:2/2
│     └──□ rollouts-demo-75f756d67b-lfprx  Pod         ✔ Running   105s  ready:2/2
└──# revision:1                                                          
   └──⧉ rollouts-demo-6668595956           ReplicaSet  ✔ Healthy   3m8s  stable
      ├──□ rollouts-demo-6668595956-8s8kh  Pod         ✔ Running   3m8s  ready:2/2
      ├──□ rollouts-demo-6668595956-dktjd  Pod         ✔ Running   3m8s  ready:2/2
      ├──□ rollouts-demo-6668595956-rrwqm  Pod         ✔ Running   3m8s  ready:2/2
      ├──□ rollouts-demo-6668595956-rtb7d  Pod         ✔ Running   3m8s  ready:2/2
      └──□ rollouts-demo-6668595956-vtf4n  Pod         ✔ Running   3m8s  ready:2/2

```

## Diagnostics

What version of Argo Rollouts are you running?

master branch

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
