### ISSUE TITLE
Injecting Jaeger sidecar annotation to argo kind: rollouts.

### ISSUE THREAD

**Issue by RjYogi7880** [argoproj/argo-rollouts#1341]
Hello, I have argocd and argo-rollout setup on my digital ocean Kubernetes cluster, I tried deploying one sample application with "sidecar.jaegertracing.io/inject": "true"  annotation (kind: Rollout) but sidecar injection didn't work. Any help on this?

**Comment by jessesuen** [comment]
@RjYogi7880 - I doubt Jaeger knows how to inject into Rollout kinds (or CRDs for that matter). If Jaeger injection works similar to Istio or other typical mutating webhooks, then I expect that it needs to be done at the pod level. e.g.:

```yaml
kind: Rollout
...
spec:
  template:
    metadata:
      annotations:
        sidecar.jaegertracing.io/inject: "true"
```

**Comment by RjYogi7880** [comment]
Hi @jessesuen 

This is our sample YAML file for rollout to deploy
 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name:
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
  labels:
    environment: dev
    project:
    tier: 
    app: 
spec:
  replicas: 2
  strategy:
    canary:
      canaryService: 
      stableService: 
      trafficRouting:
        nginx:
          stableIngress: 
      steps:
      - setWeight: 5
      - pause: {duration: 10}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: 
      environment: dev
      project: 
      tier: 
  template:
    metadata:
      annotations:
        "sidecar.jaegertracing.io/inject": "true"
      labels:
        environment: dev
        project: 
        tier:       
        app: 
    spec:
      containers:
      - name: 
        image: 
        imagePullPolicy: Always 
        envFrom:
          - configMapRef:
              name: 
          - secretRef:
              name: 
        ports:
        - containerPort: 3400
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /live
            port: 3400
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /live
            port: 3400
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: "700m"
            memory: "700Mi"
          requests:
            memory: "250Mi"
            cpu: "250m"
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: 
      restartPolicy: Always
```
we have tried but no luck....
