### ISSUE TITLE
Incorrect pod template change detection after upgrade from v0.10 to v1.0

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#1356]
## Summary 

We updated a controller from v0.10.x to v1.0.2. After the update, the rollout controller incorrectly decided that a steady-state rollout was updated, as indicated by this log:

```log
time="2021-07-01T19:24:49Z" level=info msg="Pod template change detected (new: 5f74ffd77f, old: 849cf644f5)" 
```

This caused the rollout to go through an update, even though the pod specs were identical.

I captured the ReplicaSet yaml of each version and verified there was no difference. So this must be a change in the way pod templates are compared in v1.0.

## Diagnostics

What version of Argo Rollouts are you running? v1.0.2

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
I can reproduce this with the following rollout first deployed in v0.10, then upgrading the controller to v1.0:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
  name: foo
spec:
  selector:
    matchLabels:
      app: foo
  strategy:
    canary: {}
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - image: argoproj/rollouts-demo:blue
        name: app
      serviceAccountName: default
```

The detected difference is that the `serviceAccount` field (which has been deprecated in k8s) is no longer defaulted using 

live object:
```yaml
metadata:
  creationTimestamp: null
  labels:
    app: foo
spec:
  containers:
  - image: argoproj/rollouts-demo:blue
    imagePullPolicy: IfNotPresent
    name: app
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
```

defaulted object:
```yaml
metadata:
  creationTimestamp: null
  labels:
    app: foo
spec:
  containers:
  - image: argoproj/rollouts-demo:blue
    imagePullPolicy: IfNotPresent
    name: app
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
```


```golang
func PodTemplateEqualIgnoreHash(live, desired *corev1.PodTemplateSpec) bool {
	live = live.DeepCopy()
	desired = desired.DeepCopy()
	// Remove hash labels from template.Labels before comparing
	delete(live.Labels, v1alpha1.DefaultRolloutUniqueLabelKey)
	delete(desired.Labels, v1alpha1.DefaultRolloutUniqueLabelKey)

	podTemplate := corev1.PodTemplate{
		Template: *desired,
	}
	corev1defaults.SetObjectDefaults_PodTemplate(&podTemplate)  // this no longer defaults serviceAccount in later k8s libraries
	desired = &podTemplate.Template
	liveBytes, _ := yaml.Marshal(live)
	desiredBytes, _ := yaml.Marshal(desired)
	return apiequality.Semantic.DeepEqual(live, desired)
}
```

**Comment by jessesuen** [comment]
It seems this is what happened:

1. We **_partially_** rely on k8s controller.ComputeHash to detect a change in the pod template.

2. controller.ComputeHash() changed between K8s v1.18 to v1.20.4 - it returns different values for the same template

For the following YAML:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: foo
spec:
  selector:
    matchLabels:
      app: foo
  strategy:
    canary: {}
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - image: argoproj/rollouts-demo:blue
        name: app
```

It returns the following hashes for different k8s libraries:
1. 5c5f4fdfd8 - k8s 1.17.3
2. 5c5f4fdfd8 - k8s v1.18.2
3. 68f647646d - k8s v1.20.4

3. When controller.ComputeHash() changes underneath us (and returns a new value), we use a fallback mechanism,  PodTemplateEqualIgnoreHash, to detect if the templates are truly different.

4. PodTemplateEqualIgnoreHash did not work as expected. The live object had the `serviceAccount` field in the template, but the defaulted one we used in comparison did not. And thus, we detected this as a difference in pod template.

5. Because of the difference, we triggered an update.
