### ISSUE TITLE
Analysis with arguments not working 

### ISSUE THREAD

**Issue by harikrongali** [argoproj/argo-rollouts#1358]
## Summary 

Analysis template with arguments for fields counter, interval, intitial-delay, failedCount etc arent resolved properly and are failing with validation errors.

```
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate-qal-usw2
spec:
  args:
  - name: analysis-interval
    value: "300s"
  - name: analysis-runs
    value: "36"
  - name: failure-limit
    value: "4"
  - name: inconclusive-limit
    value: "4"
  - name: secret-url
    valueFrom:
      secretKeyRef:
        name: example-secret
        key: secretUrl  
  metrics:
    - name: webmetric
      successCondition: result == 'It worked!'
      count: "{{args.analysis-runs}}"
      interval: "{{args.analysis-interval}}"
      failureLimit: "{{args.failure-limit}}"
      provider:
        web:
          # placeholders are resolved when an AnalysisRun is created
          url: "{{args.secret-url}}"
          jsonPath: "{$.message}"
## Diagnostics


Above template when included in rollout fails with validation error: 
```
  Message:  analysis spec invalid: metrics[0]: invalid interval string: time: invalid duration "{{args.analysis-interval}}"

Also if arg is removed for the interval, then with counter greater than 1 value, analysis runs infinitely. 

What version of Argo Rollouts are you running?
1.1

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
