### ISSUE TITLE
Promote full did not work against BlueGreen with previewReplicaCount

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-rollouts#1383]
## Summary 

Rollout stuck in degrade state during blue-green rollout. 

## Diagnostics

Rollout got paused (as expected) during blue-green. It was not approved within `progressDeadlineSeconds` timeout and switched into Degraded state. Promote was executed using Argo CD action but nothing happened - rollout stayed in Degraded state.

Based on logs rollout got unpaused but controller was trying to set `previewReplicaCount` to the new replicaset instead of `spec.replicas`.

```yaml
  strategy:
    blueGreen:
      activeService: paaf-active-service
      antiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution: {}
      autoPromotionEnabled: false
      previewReplicaCount: 1
      previewService: paaf-preview-service
      scaleDownDelayRevisionLimit: 2
      scaleDownDelaySeconds: 300
```
status:

```
status:
  HPAReplicas: 3
  availableReplicas: 3
  blueGreen:
    activeSelector: 77954699c5
    previewSelector: 6599fdc6d
  canary: {}
  conditions:
    - lastTransitionTime: '2021-07-30T08:17:29Z'
      lastUpdateTime: '2021-07-30T08:17:29Z'
      message: RolloutCompleted
      reason: RolloutCompleted
      status: 'False'
      type: Completed
    - lastTransitionTime: '2021-07-30T08:45:37Z'
      lastUpdateTime: '2021-07-30T08:45:37Z'
      message: Rollout is paused
      reason: RolloutPaused
      status: 'False'
      type: Paused
    - lastTransitionTime: '2021-07-30T09:17:29Z'
      lastUpdateTime: '2021-07-30T09:17:29Z'
      message: Rollout has minimum availability
      reason: AvailableReason
      status: 'True'
      type: Available
    - lastTransitionTime: '2021-07-30T09:39:12Z'
      lastUpdateTime: '2021-07-30T09:39:12Z'
      message: ReplicaSet "reducted-rollout-6599fdc6d" has timed out progressing.
      reason: ProgressDeadlineExceeded
      status: 'False'
      type: Progressing
  currentPodHash: 6599fdc6d
  message: >-
    ProgressDeadlineExceeded: ReplicaSet "reducted-rollout-6599fdc6d" has timed out
    progressing.
  observedGeneration: '22'
  phase: Degraded
  promoteFull: true
  readyReplicas: 3
  replicas: 4
  restartedAt: '2021-07-30T09:07:56Z'
  selector: 'app=reducted,rollouts-pod-template-hash=77954699c5'
  stableRS: 77954699c5
  updatedReplicas: 1
```

Version: `v1.0.2`

Rollout has previewReplicas

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
