### ISSUE TITLE
Canary deployment scaledDown stable pods during HPA scale event 

### ISSUE THREAD

**Issue by harikrongali** [argoproj/argo-rollouts#1415]
## Summary 

When canary deployment is progressing and when HPA scale event happened during the time. Rollout controller scaled down stable pods to zero
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: qb-company-service-appd
    app.kubernetes.io/instance: company-qbcompanyservice-usw2-prd
    env: prd-usw2-eks
  name: qb-company-service-appd-rollout
  namespace: company-qbcompanyservice-usw2-prd
spec:
  progressDeadlineSeconds: 1200
  selector:
    matchLabels:
      app: qb-company-service-appd
  strategy:
    canary:
      canaryService: qb-company-service-appd-desired-service
      maxSurge: 100%
      maxUnavailable: 1
      stableService: qb-company-service-appd-stable-service
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: k8s-company-qbcompanyservice-usw2-prd
    spec:
      containers:
          image: >-
            docker.artifactory.a.intuit.com/###
          name: app
          ports:
            - containerPort: 8443
              name: service
            - containerPort: 8490
              name: metrics
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/full
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 400
            periodSeconds: 5
            successThreshold: 3
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 1
              memory: 4096M
            requests:
              cpu: 1
              memory: 4096M
          volumeMounts:
            - mountPath: /etc/secrets
              name: secrets
    
```

## Diagnostics

1.0.2
```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
