### ISSUE TITLE
Ambassador mapping in other namespace than where ambassador is running

### ISSUE THREAD

**Issue by cldmnky** [argoproj/argo-rollouts#1417]
## Summary 

With a base mapping in a different namespace than ambassador is running in, the service in the canary mapping is created with a service name without a namespace suffix.

The base mapping has a stable service with namespace suffix in order for ambassador to setup lb endpoints in envoy correctly (cross namespace):

```yaml
spec:
  host: api.xxx.xxx
  prefix: /test-progressive/
  resolver: endpoint
  service: test-app-stable.test-progressive:80
```

When Argo Rollouts creates the canary mapping, it does not add the namespace suffix which leads to that ambassador cannot add the endpoints to Envoy:

```yaml
spec:
  host:  api.xxx.xx
  prefix: /test-progressive/
  resolver: endpoint
  service: test-app-stable-canary:80
  weight: 10
```

Adding the namespace suffix to the rollout spec causes rollouts to mark the rollout spec invalid:

```text
argo-rollouts-5bfd68678c-hkks2 argo-rollouts time="2021-08-13T09:21:58Z" level=error msg="The Rollout \"test-app\" is invalid: spec.strategy.canary.canaryService: Invalid value: \"test-app-canary.test-progressive\": service \"test-app-canary.test-progressive\" not found" namespace=test-progressive rollout=test-app
```

Rollout spec (without namespace suffix for the canary service):

```yaml
spec:
  paused: true
  replicas: 2
  strategy:
    canary:
      canaryService: test-app-canary
      stableService: test-app-stable
      steps:
      - setWeight: 10
      - pause:
          duration: 10m
      trafficRouting:
        ambassador:
          mappings:
          - test-app-int-0
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-app
```

Since we deploy mappings in a different namespace than ambassador the canary mapping created should add the namespace as a suffix to the service field in the canary mapping.

## Diagnostics

What version of Argo Rollouts are you running?
1.0.1

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
