### ISSUE TITLE
Canary releases with ALB ingress not getting traffic

### ISSUE THREAD

**Issue by rhishikeshj** [argoproj/argo-rollouts#1480]
## Summary 

What happened
Canary service isn't getting any traffic even when weight is 20%.
Also, I see only 1 rule in the ALB listeners which is at 100%

What you expected to happen?
Canary service should get traffic 20% of the times.
ALB listener should have 2 rules, one for stable and one for canary service as documented here : https://argoproj.github.io/argo-rollouts/getting-started/alb/#2-perform-an-update

## Diagnostics

What version of Argo Rollouts are you running?
1.0.6

Here is the relevant section from the manifest yaml files

rollout.yaml
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: app-name
  name: app-name
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    canary:
      canaryService: app-name-canary
      stableService: app-name
      trafficRouting:
        alb:
          # The referenced ingress will be injected with a custom action annotation, directing
          # the AWS Load Balancer Controller to split traffic between the canary and stable
          # Service, according to the desired traffic weight (required).
          ingress: app-name
          # Service port is the port which the Service listens on (required).
          servicePort: 4001
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 50
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
```

ingress.yaml
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app-name
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: app-name
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              serviceName: app-name
              servicePort: use-annotation
```

service.yaml
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-name
  name: app-name
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '4004'
spec:
  ports:
  - port: 4001
  selector:
    app: app-name
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-name
  name: app-name-canary
spec:
  ports:
  - port: 4001
  selector:
    app: app-name
  type: NodePort

```

```
time="2021-09-08T13:15:21Z" level=info msg="Started syncing rollout" generation=32 namespace=default resourceVersion=10685129 rollout=app-name
time="2021-09-08T13:15:21Z" level=info msg="Event(v1.ObjectReference{Kind:\"Rollout\", Namespace:\"default\", Name:\"app-name\", UID:\"a5fd76b3-f9a4-4177-8f31-4663dd1bd409\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"10685129\", FieldPath:\"\"}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up ReplicaSet app-name-5484d77b89 (revision 8) from 0 to 1"
time="2021-09-08T13:15:21Z" level=info msg="Enqueueing parent of default/app-name-5484d77b89: Rollout default/app-name"
time="2021-09-08T13:15:21Z" level=info msg="Reconciling TrafficRouting with type 'ALB'" namespace=default rollout=app-name
time="2021-09-08T13:15:21Z" level=info msg="no changes to the ALB Ingress" ingress=app-name namespace=default rollout=app-name
time="2021-09-08T13:15:21Z" level=info msg="Desired weight (stepIdx: 0) 0 verified" namespace=default rollout=app-name
time="2021-09-08T13:15:21Z" level=error msg="roCtx.reconcile err Operation cannot be fulfilled on replicasets.apps \"app-name-5484d77b89\": the object has been modified; please apply your changes to the latest version and try again" generation=32 namespace=default resourceVersion=10685129 rollout=app-name
time="2021-09-08T13:15:21Z" level=info msg="Reconciliation completed" generation=32 namespace=default resourceVersion=10685129 rollout=app-name time_ms=11.372772
time="2021-09-08T13:15:21Z" level=error msg="rollout syncHandler error: Operation cannot be fulfilled on replicasets.apps \"app-name-5484d77b89\": the object has been modified; please apply your changes to the latest version and try again" namespace=default rollout=app-name
time="2021-09-08T13:15:21Z" level=info msg="rollout syncHandler queue retries: 2 : key \"default/app-name\"" namespace=default rollout=app-name
E0908 13:15:21.351428       1 controller.go:174] Operation cannot be fulfilled on replicasets.apps "app-name-5484d77b89": the object has been modified; please apply your changes to the latest version and try again
time="2021-09-08T13:15:21Z" level=info msg="Started syncing rollout" generation=32 namespace=default resourceVersion=10685129 rollout=app-name
time="2021-09-08T13:15:21Z" level=info msg="Reconciling TrafficRouting with type 'ALB'" namespace=default rollout=app-name
time="2021-09-08T13:15:21Z" level=info msg="no changes to the ALB Ingress" ingress=app-name namespace=default rollout=app-name
time="2021-09-08T13:15:21Z" level=info msg="Desired weight (stepIdx: 0) 0 verified" namespace=default rollout=app-name
time="2021-09-08T13:15:21Z" level=info msg="Timed out (false) [last progress check: 2021-09-08 13:15:21 +0000 UTC - now: 2021-09-08 13:15:21.354470303 +0000 UTC m=+177901.809865342]" namespace=default rollout=app-name
time="2021-09-08T13:15:21Z" level=info msg="No status changes. Skipping patch" generation=32 namespace=default resourceVersion=10685129 rollout=app-name
time="2021-09-08T13:15:21Z" level=info msg="Queueing up rollout for a progress after 599s" namespace=default rollout=app-name
time="2021-09-08T13:15:21Z" level=info msg="Reconciliation completed" generation=32 namespace=default resourceVersion=10685129 rollout=app-name time_ms=3.557003
time="2021-09-08T13:15:21Z" level=info msg="Started syncing rollout" generation=32 namespace=default resourceVersion=10685129 rollout=app-name
time="2021-09-08T13:15:21Z" level=info msg="Reconciling TrafficRouting with type 'ALB'" namespace=default rollout=app-name
time="2021-09-08T13:15:21Z" level=info msg="no changes to the ALB Ingress" ingress=app-name namespace=default rollout=app-name
time="2021-09-08T13:15:21Z" level=info msg="Desired weight (stepIdx: 0) 0 verified" namespace=default rollout=app-name
time="2021-09-08T13:15:21Z" level=info msg="Timed out (false) [last progress check: 2021-09-08 13:15:21 +0000 UTC - now: 2021-09-08 13:15:21.359479485 +0000 UTC m=+177901.814874528]" namespace=default rollout=app-name
time="2021-09-08T13:15:21Z" level=info msg="No status changes. Skipping patch" generation=32 namespace=default resourceVersion=10685129 rollout=app-name
time="2021-09-08T13:15:21Z" level=info msg="Queueing up rollout for a progress after 599s" namespace=default rollout=app-name
time="2021-09-08T13:15:21Z" level=info msg="Reconciliation completed" generation=32 namespace=default resourceVersion=10685129 rollout=app-name time_ms=4.841087
time="2021-09-08T13:15:21Z" level=info msg="Enqueueing parent of default/app-name-5484d77b89: Rollout default/app-name"
time="2021-09-08T13:15:21Z" level=info msg="Started syncing rollout" generation=32 namespace=default resourceVersion=10685129 rollout=app-name
time="2021-09-08T13:15:21Z" level=info msg="Reconciling TrafficRouting with type 'ALB'" namespace=default rollout=app-name
time="2021-09-08T13:15:21Z" level=info msg="no changes to the ALB Ingress" ingress=app-name namespace=default rollout=app-name
time="2021-09-08T13:15:21Z" level=info msg="Desired weight (stepIdx: 0) 0 verified" namespace=default rollout=app-name
time="2021-09-08T13:15:21Z" level=info msg="Timed out (false) [last progress check: 2021-09-08 13:15:21 +0000 UTC - now: 2021-09-08 13:15:21.460135533 +0000 UTC m=+177901.915530558]" namespace=default rollout=app-name
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by harikrongali** [comment]
@khhirani can you triage?

**Comment by harikrongali** [comment]
@rhishikeshj  can you post the output of following command
```
kubectl argo rollouts get rollout <rolloutname>
```

**Comment by rhishikeshj** [comment]
Output from the command

_ignore the timestamps for now. I had started this rollout yesterday_

```
Name:            app-name
Namespace:       default
Status:          ॥ Paused
Message:         CanaryPauseStep
Strategy:        Canary
  Step:          1/6
  SetWeight:     20
  ActualWeight:  20
Images:          <ecr-repo-url>:dev-latest (stable)
                 <ecr-repo-url>:dev-playground (canary)
Replicas:
  Desired:       2
  Current:       3
  Updated:       1
  Ready:         3
  Available:     3

NAME                                      KIND        STATUS     AGE    INFO
⟳ app-name                            Rollout     ॥ Paused   2d21h
├──# revision:8
│  └──⧉ app-name-5484d77b89           ReplicaSet  ✔ Healthy  2d20h  canary
│     └──□ app-name-5484d77b89-r77gn  Pod         ✔ Running  21h    ready:2/2
└──# revision:7
   └──⧉ app-name-6bd6bccb75           ReplicaSet  ✔ Healthy  2d20h  stable
      ├──□ app-name-6bd6bccb75-jwdvm  Pod         ✔ Running  24h    ready:2/2
      └──□ app-name-6bd6bccb75-nbncz  Pod         ✔ Running  24h    ready:2/2
```

**Comment by leoluz** [comment]
@rhishikeshj As your ALB listener has only one rule, can you inspect the value in the `alb.ingress.kubernetes.io/actions.root-service` annotation in your Ingress resource? 
The Rollouts controller should update that annotation to something like:
```json
      { 
        "Type":"forward",
        "ForwardConfig":{ 
          "TargetGroups":[ 
            { 
                "Weight":20,
                "ServiceName":"canary-service",
                "ServicePort":"80"
            },
            { 
                "Weight":80,
                "ServiceName":"stable-service",
                "ServicePort":"80"
            }
          ]
        }
      }
```
This annotation will then be consumed by the ALB controller to correctly set the listener in AWS. We just need to understand which part is not doing its job to narrow down where the problem really is.

**Comment by rhishikeshj** [comment]
Hi @leoluz 
Here's the information that you want

```

metadata:
  annotations:
    alb.ingress.kubernetes.io/actions.app-name: >-
      {"Type":"forward","ForwardConfig":{"TargetGroups":[{"ServiceName":"app-name","ServicePort":"4001","Weight":80},{"ServiceName":"app-name-canary","ServicePort":"4001","Weight":20}]}}
    alb.ingress.kubernetes.io/scheme: internet-facing
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"networking.k8s.io/v1beta1","kind":"Ingress","metadata":{"annotations":{"alb.ingress.kubernetes.io/scheme":"internet-facing","kubernetes.io/ingress.class":"alb"},"labels":{"app":"app-name","app.kubernetes.io/instance":"app-name"},"name":"app-name","namespace":"default"},"spec":{"rules":[{"http":{"paths":[{"backend":{"serviceName":"app-name","servicePort":"use-annotation"},"path":"/*","pathType":"Prefix"}]}}]}}
    kubernetes.io/ingress.class: alb
    rollouts.argoproj.io/managed-alb-actions: 'app-name:alb.ingress.kubernetes.io/actions.app-name'

```

It seems the annotations are being set correctly, but I still don't see the second rule being added to the ALB listener.

![ingress_alb_listener_rules](https://user-images.githubusercontent.com/719190/133074973-3cc8f13e-186b-4d69-a2ea-cbe60c8b27ba.png)
