### ISSUE TITLE
OpenAPI validation should mark .spec.strategy.blueGreen.activeService as required

### ISSUE THREAD

**Issue by pkaramol** [argoproj/argo-rollouts#149]
I am trying to use `rollouts` to experiment with B-G deployment strategy.

My cluster is on GKE.

We are using a git ops flow via [flux](https://github.com/fluxcd/flux) so we have a repo of helm charts used in its turn via a `HelmRelease` file.

Trying to simplify the situation I have hard-coded the following `Rollout` definition in my helm chart:

(so as to avoid potential errors induced by the helm templating process)

```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    flux.weave.works/antecedent: workable:helmrelease/faros
  labels:
    app: faros
    chart: faros-0.0.3
    heritage: Tiller
    release: faros
    version: 2.0.1
  name: faros-web
  namespace: mynamespace
spec:
  strategy:
    blueGreen:
      previewService: faros-preview
      previewReplicaCount: 3
      autoPromotionSeconds: 10
  minReadySeconds: 5
  progressDeadlineSeconds: 2147483647
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: faros
      process: web
      release: faros
  template:
    metadata:
      annotations:
        checksum/configmap: 098430984309834509805985lkjfelkjlfkjlrfgkj
        checksum/sealedsecrets: efoki30kd03kd03mfdo3mioms2124n5n0tgk
        checksum/secrets: 96fb92427ae41e4649b934ca495991b7852b855
        sidecar.istio.io/inject: "true"
      labels:
        app: faros
        process: web
        release: faros
        version: 2.0.1
      containers:
      - env:
        - name: PROCESS_TYPE
          value: web
        envFrom:
        - configMapRef:
            name: faros
        - secretRef:
            name: faros
        image: myregistry/myimage:blue
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        name: faros
        ports:
        - containerPort: 20000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 150m
            memory: 128Mi
          requests:
            cpu: 150m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

```

However my `rollout` controller yields:

```
time="2019-09-02T09:48:51Z" level=error msg="Spec submitted is invalid" namespace=mynamespace rollout=faros-web
```

and the `Rollout` description:

```
Message:               Rollout has missing field '.Spec.Strategy.CanaryStrategy or .Spec.Strategy.BlueGreen'
```

However the field `.Spec.Strategy.BlueGreen` is there.

```
➢  kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.8", GitCommit:"7d3d6f113e933ed1b44b78dff4baf649258415e5", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:16Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

```
➢  kubectl describe pod argo-rollouts-6c8cc74d9b-zvd7x -n argo-rollouts | grep -i image
    Image:         argoproj/argo-rollouts:v0.4.1
```

**Comment by jessesuen** [comment]
Can you share output of:
```
kubectl get rollout -o yaml faros-web
```

Want to see if it's somehow getting dropped.

**Comment by pkaramol** [comment]
I have now tried the cluster level installation and the example `rollout` of the docs.

I am getting this error in the `argo-rollout` pods' logs

```
➢  kubectl apply -f charts/faros/templates/rollout.yaml                                                   The Rollout "example-rollout" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"argoproj.io/v1alp
ha1", "kind":"Rollout", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"argoproj.io/v1alpha1\",\"kind\":\"Rollout\",\"metadata\":{\"annotations\":{},\"name\":\"example-rollout\",\"namespace\":\"workable\"},\"spec\":{\"minReadySeconds\":30,\"replicas\":5,\"revisionHistoryLimit\":3,\"selector\":{\"matchLabels\":{\"app\":\"nginx\"}},\"strategy\":{\"blueGreen\":null},\"template\":{\"metadata\":{\"labels\":{\"app\":\"nginx\"}},\"spec\":{\"containers\":[{\"image\":\"nginx:1.15.4\",\"name\":\"nginx\",\"ports\":[{\"containerPort\":80}]}]}}}}\n"}, "generation":1, "uid":"58fddac8-cedf-11e9-a87a-42010a790808", "name":"example-rollout", "namespace":"workable", "creationTimestamp":"2019-09-04T06:43:47Z"}, "spec":map[string]interface {}{"replicas":5, "revisionHistoryLimit":3, "selector":map[string]interface {}{"matchLabels":map[string]interface {}{"app":"nginx"}}, "strategy":map[string]interface {}{"blueGreen":interface {}(nil)}, "template":map[string]interface {}{"metadata":map[string]interface {}{"labels":map[string]interface {}{"app":"nginx"}}, "spec":map[string]interface {}{"containers":[]interface {}{map[string]interface {}{"image":"nginx:1.15.4", "name":"nginx", "ports":[]interface {}{map[string]interface {}{"containerPort":80}}}}}}, "minReadySeconds":30}}: validation failure list:
spec.strategy.blueGreen in body must be of type object: "null"
```

```
apiVersion: argoproj.io/v1alpha1 # Changed from apps/v1
kind: Rollout # Changed from Deployment
# ----- Everything below this comment is the same as a deployment -----
metadata:
  name: example-rollout
  namespace: workable
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - containerPort: 80
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
  # ----- Everything above this comment are the same as a deployment -----
    blueGreen: # A new field that used to provide configurable options for a Canary strategy
```
