### ISSUE TITLE
"Error Message: unknown name response" but canary responds the entire time

### ISSUE THREAD

**Issue by jstewart612** [argoproj/argo-rollouts#1563]
## Summary 

I ran this Rollout:

```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    DEPLOY_DATE: '2021-10-04_20:46:52'
    argocd.argoproj.io/sync-wave: '1'
    reloader.stakater.com/auto: 'true'
  labels:
    app: maestro
    argocd.argoproj.io/instance: qa-maestro
  name: maestro
  namespace: qa
spec:
  minReadySeconds: 30
  paused: false
  progressDeadlineSeconds: 600
  replicas: null
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: maestro
  strategy:
    canary:
      canaryMetadata:
        labels:
          role: canary
      canaryService: maestro-canary
      maxSurge: 20%
      maxUnavailable: 1
      stableMetadata:
        labels:
          role: stable
      stableService: maestro
      steps:
        - setCanaryScale:
            replicas: 1
        - pause:
            duration: 1m
        - analysis:
            templates:
              - templateName: maestro-web
        - setCanaryScale:
            matchTrafficWeight: true
        - setWeight: 50
        - setWeight: 100
      trafficRouting:
        istio:
          virtualService:
            name: maestro
            routes:
              - maestro
  template:
    metadata:
      labels:
        app: maestro
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - maestro
              topologyKey: kubernetes.io/hostname
      containers:
        - envFrom:
            - secretRef:
                name: maestro-environment
          image: 'ghcr.io/rentpath/maestro:20211004-135-454b79a'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /ops/heartbeat
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          name: maestro
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /ops/heartbeat
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
      dnsConfig:
        nameservers:
          - 169.254.20.10
        options:
          - name: ndots
            value: '5'
        searches:
          - qa.svc.cluster.local
          - svc.cluster.local
          - cluster.local
          - qa.useast2.rentpath.com
          - rentpath.com
      dnsPolicy: None
      imagePullSecrets:
        - name: ghcr-registry-docker
      nodeSelector: {}
```

With this AnalysisTemplate:

```
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  annotations:
    DEPLOY_DATE: '2021-10-04_20:46:52'
    argocd.argoproj.io/sync-wave: '0'
  labels:
    app: maestro
    argocd.argoproj.io/instance: qa-maestro
  name: maestro-web
  namespace: qa
spec:
  metrics:
    - count: 20
      failureLimit: 3
      interval: 3s
      name: heartbeat
      provider:
        web:
          timeoutSeconds: 20
          url: 'http://maestro-canary.qa.svc.cluster.local/ops/heartbeat'
      successCondition: response.code == 200
```

Canary pod started and that URL works from another pod while the pod is started.... but the Rollout fails with "Error Message: unknown name response" and kills the canary pod that was returning 200 at that uri the entire time at that service name.

## Diagnostics

What version of Argo Rollouts are you running?

1.0.7

```
# Paste the logs from the rollout controller

time="2021-10-05T14:00:28Z" level=warning msg="Rollout aborted update to revision 5: metric \"heartbeat\" assessed Error due to consecutiveErrors (5) > consecutiveErrorLimit (4): \"Error Message: unknown name response\"" event_reason=RolloutAborted namespace=qa rollout=maestro
time="2021-10-05T14:00:28Z" level=info msg="Patched: {\"status\":{\"abort\":true,\"abortedAt\":\"2021-10-05T14:00:28Z\",\"canary\":{\"currentStepAnalysisRunStatus\":{\"message\":\"metric \\\"heartbeat\\\" assessed Error due to consecutiveErrors (5) \\u003e consecutiveErrorLimit (4): \\\"Error Message: unknown name response\\\"\",\"status\":\"Error\"}},\"conditions\":[{\"lastTransitionTime\":\"2021-10-04T17:44:46Z\",\"lastUpdateTime\":\"2021-10-04T17:44:46Z\",\"message\":\"Rollout has minimum availability\",\"reason\":\"AvailableReason\",\"status\":\"True\",\"type\":\"Available\"},{\"lastTransitionTime\":\"2021-10-05T13:57:58Z\",\"lastUpdateTime\":\"2021-10-05T13:57:58Z\",\"message\":\"RolloutCompleted\",\"reason\":\"RolloutCompleted\",\"status\":\"False\",\"type\":\"Completed\"},{\"lastTransitionTime\":\"2021-10-05T13:59:48Z\",\"lastUpdateTime\":\"2021-10-05T13:59:48Z\",\"message\":\"Rollout is paused\",\"reason\":\"RolloutPaused\",\"status\":\"False\",\"type\":\"Paused\"},{\"lastTransitionTime\":\"2021-10-05T14:00:28Z\",\"lastUpdateTime\":\"2021-10-05T14:00:28Z\",\"message\":\"Rollout aborted update to revision 5: metric \\\"heartbeat\\\" assessed Error due to consecutiveErrors (5) \\u003e consecutiveErrorLimit (4): \\\"Error Message: unknown name response\\\"\",\"reason\":\"RolloutAborted\",\"status\":\"False\",\"type\":\"Progressing\"}],\"currentStepIndex\":0,\"message\":\"RolloutAborted: Rollout aborted update to revision 5: metric \\\"heartbeat\\\" assessed Error due to consecutiveErrors (5) \\u003e consecutiveErrorLimit (4): \\\"Error Message: unknown name response\\\"\",\"phase\":\"Degraded\"}}" generation=14 namespace=qa resourceVersion=1526660001 rollout=maestro
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
