### ISSUE TITLE
template must be empty error when using workloadRef

### ISSUE THREAD

**Issue by alkalinecoffee** [argoproj/argo-rollouts#1571]
## Summary 

We are using `workloadRef` in our rollout to point at an existing deployment, but seeing the following error:

> template must be empty for workload reference rollout

Our rollout does not include a `template`--only the existing deployment does.  However, when exporting the rollout's yaml, we can see both `template` and `workloadRef` in the exported file (maybe that is what is triggering this error?).

## Diagnostics

Previously used 1.0.1 without issue, now trying 1.0.7 and seeing the following error (repeated indefinitely):

```
time="2021-10-08T12:20:28Z" level=info msg="Started syncing rollout" generation=10 namespace=xvp-ping-api-dev resourceVersion=25946816 rollout=canary-release
time="2021-10-08T12:20:28Z" level=error msg="The Rollout \"canary-release\" is invalid: template must be empty for workload reference rollout" namespace=xvp-ping-api-dev rollout=canary-release
time="2021-10-08T12:20:28Z" level=info msg="Reconciliation completed" generation=10 namespace=xvp-ping-api-dev resourceVersion=25946816 rollout=canary-release time_ms=1.155175
time="2021-10-08T12:20:28Z" level=error msg="rollout syncHandler error: template must be empty for workload reference rollout" namespace=xvp-ping-api-dev rollout=canary-release
time="2021-10-08T12:20:28Z" level=info msg="rollout syncHandler queue retries: 7913 : key \"xvp-ping-api-dev/canary-release\"" namespace=xvp-ping-api-dev rollout=canary-release
E1008 12:20:28.001343       1 controller.go:174] template must be empty for workload reference rollout
time="2021-10-08T12:20:38Z" level=info msg="Started syncing rollout" generation=10 namespace=xvp-ping-api-dev resourceVersion=25946816 rollout=canary-release
time="2021-10-08T12:20:38Z" level=error msg="The Rollout \"canary-release\" is invalid: template must be empty for workload reference rollout" namespace=xvp-ping-api-dev rollout=canary-release
time="2021-10-08T12:20:38Z" level=info msg="Reconciliation completed" generation=10 namespace=xvp-ping-api-dev resourceVersion=25946816 rollout=canary-release time_ms=1.157033
time="2021-10-08T12:20:38Z" level=error msg="rollout syncHandler error: template must be empty for workload reference rollout" namespace=xvp-ping-api-dev rollout=canary-release
time="2021-10-08T12:20:38Z" level=info msg="rollout syncHandler queue retries: 7914 : key \"xvp-ping-api-dev/canary-release\"" namespace=xvp-ping-api-dev rollout=canary-release
E1008 12:20:38.003190       1 controller.go:174] template must be empty for workload reference rollout
```

### Rollout:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app.kubernetes.io/component: ping-api
    app.kubernetes.io/environment: dev
    app.kubernetes.io/managed-by: Terraform
    app.kubernetes.io/name: xvp-ping-api
    app.kubernetes.io/part-of: XVPExp
    app.kubernetes.io/region: us-east-2
  name: canary-release
  namespace: xvp-ping-api-dev
spec:
  progressDeadlineSeconds: 1800
  replicas: 1
  strategy:
    canary:
      canaryService: xvp-ping-api-dev-canary
      stableService: xvp-ping-api-dev-stable
      steps:
      - setCanaryScale:
          replicas: 1
      - setWeight: 100
      trafficRouting:
        alb:
          ingress: xvp-ping-api-dev-alb
          servicePort: 8080
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xvp-ping-api-dev
```

### Deployment:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: ping-api
    app.kubernetes.io/environment: dev
    app.kubernetes.io/managed-by: Terraform
    app.kubernetes.io/name: Application
    app.kubernetes.io/part-of: XVPExp
    app.kubernetes.io/region: us-east-2
    component: xvp-ping-api-dev
    sidecar.istio.io/inject: "true"
  name: xvp-ping-api-dev
  namespace: xvp-ping-api-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: ping-api
      app.kubernetes.io/environment: dev
      app.kubernetes.io/managed-by: Terraform
      app.kubernetes.io/name: Application
      app.kubernetes.io/part-of: XVPExp
      app.kubernetes.io/region: us-east-2
      component: xvp-ping-api-dev
      sidecar.istio.io/inject: "true"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8081"
        prometheus.io/scrape: "true"
        sidecar.istio.io/proxyImage: xxx.dkr.ecr.us-east-2.amazonaws.com/proxyv2:1.10.0
      labels:
        app.kubernetes.io/component: ping-api
        app.kubernetes.io/environment: dev
        app.kubernetes.io/managed-by: Terraform
        app.kubernetes.io/name: Application
        app.kubernetes.io/part-of: XVPExp
        app.kubernetes.io/region: us-east-2
        component: xvp-ping-api-dev
        sidecar.istio.io/inject: "true"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: component
                operator: In
                values:
                - xvp-ping-api-dev
      automountServiceAccountToken: true
      containers:
      - env:
        - name: XVP_ENV
          value: dev
        - name: AWS_REGION
          value: us-east-2
        image: xxx.dkr.ecr.us-east-2.amazonaws.com/xvp-ping-api:0.0.187
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/app?clientId=EKS-healthcheck
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 10
        name: ping-api
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8081
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/readiness?clientId=EKS-healthcheck
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 45
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: "3"
            memory: 3000Mi
          requests:
            cpu: "2"
            memory: 2000Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: xvp-ping-api-dev
      serviceAccountName: xvp-ping-api-dev
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 35
```

### Exported Rollout YAML

> Here we can see both the `workloadRef` and `template`--could this be why I'm seeing this error?

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    rollout.argoproj.io/revision: "4"
  labels:
    app.kubernetes.io/component: ping-api
    app.kubernetes.io/environment: dev
    app.kubernetes.io/managed-by: Terraform
    app.kubernetes.io/name: xvp-ping-api
    app.kubernetes.io/part-of: XVPExp
    app.kubernetes.io/region: us-east-2
  name: canary-release
  namespace: xvp-ping-api-dev
spec:
  progressDeadlineSeconds: 1800
  replicas: 1
  strategy:
    canary:
      canaryService: xvp-ping-api-dev-canary
      stableService: xvp-ping-api-dev-stable
      steps:
      - setCanaryScale:
          replicas: 1
      - setWeight: 100
      trafficRouting:
        alb:
          ingress: xvp-ping-api-dev-alb
          servicePort: 8080
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8081"
        prometheus.io/scrape: "true"
        sidecar.istio.io/proxyImage: xxx.dkr.ecr.us-east-2.amazonaws.com/proxyv2:1.10.0
      labels:
        app.kubernetes.io/component: ping-api
        app.kubernetes.io/environment: dev
        app.kubernetes.io/managed-by: Terraform
        app.kubernetes.io/name: Application
        app.kubernetes.io/part-of: XVPExp
        app.kubernetes.io/region: us-east-2
        component: xvp-ping-api-dev
        sidecar.istio.io/inject: "true"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: component
                operator: In
                values:
                - xvp-ping-api-dev
      automountServiceAccountToken: true
      containers:
      - env:
        - name: XVP_ENV
          value: dev
        image: xxx.dkr.ecr.us-east-2.amazonaws.com/xvp-ping-api:0.0.183
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/app?clientId=EKS-healthcheck
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 10
        name: ping-api
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8081
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/app?clientId=EKS-healthcheck
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 45
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: "3"
            memory: 3000Mi
          requests:
            cpu: "2"
            memory: 2000Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: xvp-ping-api-dev
      serviceAccountName: xvp-ping-api-dev
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xvp-ping-api-dev
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
