### ISSUE TITLE
Allow "pre-warming" canary pods without waiting

### ISSUE THREAD

**Issue by bpoland** [argoproj/argo-rollouts#1582]
# Summary

When using the `setCanaryScale` step, the Rollout waits for the scaled pods to start and become ready before proceeding to the next canary step.  It would be nice if there was a way to tell the canary ReplicaSet to scale up ahead of time, while still allowing the following canary steps to proceed.

# Use Cases

For pods which take a long time to start and become ready, it would be helpful to "pre-warm" canary pods before they are truly needed based on the traffic percentage.  Then they would ideally be ready once the canary gets to the point where they are needed, and rollouts could take a more consistent amount of time (most waiting would be due to `pause` steps and not waiting for new pods to become ready).

I was initially thinking of an optional flag on `setCanaryScale` steps to skip waiting for the new pods to start, and move immediately to the next step.  This would allow for explicit pre-allocation of canary pods, but then on future `setWeight` calls you would want to make sure that there are enough canary pods to handle the traffic first (you can't use `setCanaryScale.matchTrafficWeight: true` because that would lower the canary RS back to a lower level).  I think it could get messy.

An easier to use option would be something similar to `maxSurge` for non-traffic-split canaries where you configure a "buffer" of either a number of replicas or a percentage, and the canary RS would always have that extra capacity allocated throughout the rollout.  I think we might be able to reuse the `maxSurge` name for this but let's assume it's called `canarySurge` instead.  If you imagine a Rollout with 5 replicas:

```
canarySurge: 20%
steps:
  # 2 canary pods started (20 weight + 20 canarySurge = 40%), wait for minimum of 1 to become ready before proceeding (to be >= 20% capacity)
  - setWeight: 20

  # 4 canary pods started (50 weight + 20 canarySurge = 70%, then round up), wait for minimum of 3 to become ready before proceeding (to be >= 50% capacity)
  - setWeight: 50

  # 5 canary pods started (don't surge over 100% of pods on the canary)
  - setWeight: 90
```

Interested in anyone's thoughts or ideas about alternative ways to do this :)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
