### ISSUE TITLE
Release assets appear to be missing dashboard install manifest

### ISSUE THREAD

**Issue by greenkiwi** [argoproj/argo-rollouts#1594]
## Summary 

We are using kustomize to deploy argo-rollouts.  We would like to deploy the dashboard, but the manifest install file is missing from the release. 

As it stands, we have to add the resources and then overwrite the tag.
```
resources:
  - https://github.com/argoproj/argo-rollouts/releases/download/v1.1.0/install.yaml
  - https://github.com/argoproj/argo-rollouts/manifests/dashboard-install?ref=v1.1.0

images:
  - name: quay.io/argoproj/kubectl-argo-rollouts
    newTag: v1.1.0
```

Can a `dashboard-install.yaml` be added to the resources associated with a release?  (And or is there a better way to install the dashboard?)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
