### ISSUE TITLE
Propagate AWS target group hash to rollout metadata

### ISSUE THREAD

**Issue by harikrongali** [argoproj/argo-rollouts#1608]
# Summary

What change needs making?
Similar to canary/stable hash values, propagate AWS target group hashes for canary & stable
Will be available only if --aws-verify-target-group enabled

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by noam-codefresh** [comment]
Hello.
I am trying to work on this request, and here is what I have currently made so far:
In the `awsVerifyTargetGroups` func, I added some code that adds the `targetGroupARN` as a label on the service. However, so far I keep getting a `!verifyRes.Verified` response from `aws.VerifyTargetGroupBinding`
When I drilled into it, I saw that the service's endpoints `Subsets.Address` have the internal IPs of the matching Pod(s), while the code is later comparing them to the `targetStr` which is basically the EC2 instance Id that contains the node (If I understand correctly). Is my current setup or deployment somehow messed up? Should I do anything differently to get a `Verified` response?

Also - do you expect the full ARN to be persisted as a label on the service? Or just the unique part of it? And what should I do when there are several TargetGroupBindings on the same service? Is this even a valid scenario?

**Comment by harikrongali** [comment]
you dont need full ARN, just the id is enough, for example arn:aws:elasticloadbalancing:us-east-2:795188202216:targetgroup/k8s-testargo-albrollo-2249f2dae0/7010986ede9433b1
 -->  k8s-testargo-albrollo-2249f2dae0 is enough

can you post the ingress and rollout manifest files?

**Comment by noam-codefresh** [comment]
Sure. I was mostly using the ALB getting started guide.
Here is my ingress:
```YAML
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: rollouts-demo-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: rollouts-demo-root
          servicePort: use-annotation
```

and Rollout:
```YAML
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  replicas: 1
  strategy:
    canary:
      canaryService: rollouts-demo-canary
      stableService: rollouts-demo-stable
      trafficRouting:
        alb:
          ingress: rollouts-demo-ingress
          servicePort: 80
          rootService: rollouts-demo-root
      steps:
        - setWeight: 5
        - pause: {}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
        - name: rollouts-demo
          image: argoproj/rollouts-demo:blue
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
```

I installed the ALB resources and controller from [v2.3](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/deploy/installation/), and after some fiddling got everything to work with internet-facing ingress (I had to manually set the availability zones of the ALB to use the public subnets, instead of the private ones).

**Comment by noam-codefresh** [comment]
oh, I think my problem is related to the `tgb.Spec.TargetType` being `instance` and not `ip`. I made a little hack to get it to pass some condition in the code (for debugging purposes, as a start), but of course, there are consequences to doing such hacks.
Is this feature meant to work with `instance` type as well? if so, I will probably need to add some resolving from the endpoints' IP addresses to the instance ids, in order to make the match.
If it's supposed to work only on `ip` - how can I easily make the required changes to my simple setup?

**Comment by noam-codefresh** [comment]
For the 2nd side of the task - I've been looking at adding the stable and canary (or active/preview) to the `BuildArgumentsForRolloutAnalysisRun` func. But it will require getting those two services from the rollout (there's a blueGreen implementation, I'll need to add a similar canary implementation as well - and wrap in a generic one that just returns both services maybe).
Maybe another option is to just put the targetGroupID values on the ReplicaSets directly, and then the `BuildArgumentsForRolloutAnalysisRun` func can keep its signature.

Also - do you expect the optional values of `targetGroupValue` to be `StableService`, `CanaryService`, or also allow `ActiveService` and `PreviewService` (depending on whether its blueGreen or canary strategy)?

**Comment by jessesuen** [comment]
> @jessesuen let me know if the above make sense or if there is a better way to do?

Instead of this:

```yaml
            valueFrom:
              targetGroupValue: StableService
          - name: canary-targetgroup
            valueFrom:
              targetGroupValue: CanaryService
```

When we spoke about this a while back, I was originally thinking we could have valueFrom do this in a more generic name, referencing field metadata in the status. This way it would not be specific to AWS. Also the work items could be split into two tasks:

1. populate AWS metadata into status (for debugging and/or to be passed to analysis)
2. support supplying status fields to analysis. To make this easier, the feature could be allowing JSON strings to analysis and allowing analysis to use dot-notation referencing if the string is a json object.
