### ISSUE TITLE
Undo/Abort rollouts when using workloadRef

### ISSUE THREAD

**Issue by itsnagaraj** [argoproj/argo-rollouts#1614]
## Summary 

What happened/what you expected to happen?
When I undo a rollout I expect the rollout to be reverted to previous version. The application was not reverted to old version and it remained scaled down in degraded state. Even when I scaled using `kubectl scale deploy/test-api --replicas 1` the application remained in degraded state and would not receive any traffic

## Diagnostics

Manifest used for deployment
```
apiVersion: v1
kind: Service
metadata:
  labels:
    name: test-api
  name: test-api
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    run: test-api
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: test-api-preview
  name: test-api-preview
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    run: test-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-api
spec:
  progressDeadlineSeconds: 1200
  replicas: 0
  selector:
    matchLabels:
      run: test-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: test-api
    spec:
      containers:
      - env:
        - name: KUBERNETES
          value: "true"
        - name: SERVICE_NAME
          value: test-api
        image: registry.test/test-api:1.0
      terminationGracePeriodSeconds: 60
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: test-api
spec:
  replicas: 1
  strategy:
    blueGreen:
      activeMetadata:
        labels:
          role: active
      activeService: test-api
      autoPromotionEnabled: false
      previewMetadata:
        labels:
          role: preview
      previewService: test-api-preview
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-api
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: test-api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      run: test-api    
```

What version of Argo Rollouts are you running?
```
time="2021-10-28T06:56:35Z" level=info msg="Argo Rollouts starting" version=v1.0.7+1d8052e
time="2021-10-28T06:56:35Z" level=info msg="Creating event broadcaster"
time="2021-10-28T06:56:35Z" level=info msg="Setting up event handlers"
time="2021-10-28T06:56:35Z" level=info msg="Setting up experiments event handlers"
time="2021-10-28T06:56:35Z" level=info msg="Setting up analysis event handlers"
time="2021-10-28T06:56:35Z" level=info msg="Waiting for controller's informer caches to sync"
```

# Paste the logs from the rollout controller
```
time="2021-10-28T06:06:56Z" level=error msg="The Rollout \"test-api\" is invalid: template must be empty for workload reference rollout" namespace=dev-api rollout=test-api
time="2021-10-28T06:06:56Z" level=info msg="Patched conditions: {\"status\":{\"conditions\":[{\"lastTransitionTime\":\"2021-10-28T05:43:19Z\",\"lastUpdateTime\":\"2021-10-28T05:43:19Z\",\"message\":\"Rollout has minimum availability\",\"reason\":\"AvailableReason\",\"status\":\"True\",\"type\":\"Available\"},{\"lastTransitionTime\":\"2021-10-28T05:54:00Z\",\"lastUpdateTime\":\"2021-10-28T05:54:00Z\",\"message\":\"RolloutCompleted\",\"reason\":\"RolloutCompleted\",\"status\":\"True\",\"type\":\"Completed\"},{\"lastTransitionTime\":\"2021-10-28T05:54:00Z\",\"lastUpdateTime\":\"2021-10-28T05:54:00Z\",\"message\":\"ReplicaSet \\\"test-api-74cc75bb6c\\\" has successfully progressed.\",\"reason\":\"NewReplicaSetAvailable\",\"status\":\"True\",\"type\":\"Progressing\"},{\"lastTransitionTime\":\"2021-10-28T05:54:00Z\",\"lastUpdateTime\":\"2021-10-28T05:54:00Z\",\"message\":\"Rollout is paused\",\"reason\":\"RolloutPaused\",\"status\":\"False\",\"type\":\"Paused\"},{\"lastTransitionTime\":\"2021-10-28T06:06:56Z\",\"lastUpdateTime\":\"2021-10-28T06:06:56Z\",\"message\":\"The Rollout \\\"test-api\\\" is invalid: template must be empty for workload reference rollout\",\"reason\":\"InvalidSpec\",\"status\":\"True\",\"type\":\"InvalidSpec\"}],\"message\":\"InvalidSpec: The Rollout \\\"test-api\\\" is invalid: template must be empty for workload reference rollout\",\"observedGeneration\":\"2\",\"phase\":\"Degraded\"}}" generation=2 namespace=dev-api resourceVersion=449716269 rollout=test-api
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
