### ISSUE TITLE
[FEATURE REQUEST] Allow to use custom metrics to promote a canary deployment

### ISSUE THREAD

**Issue by bvis** [argoproj/argo-rollouts#163]
# Description
As far as I've seen we have only the option of introduce a time based pause when doing a canary deployment, it can be useful on some cases but I've not seen how to automatise the promotion of the canary deployment when we see the new pods are working as expected.

# Proposal
A new strategy option could be introduced, working in a similar way HPA works right now, based on external metrics. For example:

```
 strategy:
    canary:
      steps:
      - setWeight: 20 
      - pause: 
        duration: 30
      - setWeight: 100
          metrics:
          - metricName: nodejs_active_requests_total
            targetAboveValue: 100
          - metricName: nodejs_error_requests_total
            targetBelowValue: 1
...
```
With this I've tried to say is that if the canary version has less than 1% of errors the canary version is good enough to be automatically deployed completely.

This is just to introduce the idea, the definition should be rich enough to define different scenarios.
