### ISSUE TITLE
scaleDownDelaySeconds: 0 does not keep old RS's scaled up indefinitely

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#1639]
## Summary 

I spoke with a user who is attempting to leave their old ReplicaSets scaled up *indefinitely* after an update, but also limit the total historical revisions by a certain count. I believed this could be accomplished using the following spec:

```yaml
spec:
  replicas: 4
  strategy:
    canary:
      scaleDownDelayRevisionLimit: 2
      scaleDownDelaySeconds: 0
      trafficRouting:
        istio: ...
```

So after three updates, I expect there to be three ReplicaSets, containing four pods each (12 total pods), since I indicate that I do not want them scaled down (`scaleDownDelaySeconds: 0`) and I have a revision limit of 2. Then, after the completion of a fourth update, the oldest ReplicaSet should then be scaled down and I still have 12 total pods, 3 ReplicaSets.

However, after testing this, I found that the controller will only keep the N-1 ReplicaSet scaled up indefinitely, and it will not honor  scale down the N-2 ReplicaSet. Also, I think it is having a strange interaction with `progressDeadlineSeconds` since it is claiming the desired ReplicaSet is still making progress.

## Diagnostics

What version of Argo Rollouts are you running? v1.1

The workaround for this issue is to give an extremely high value for `scaleDownDelaySeconds`. For example, you can specify the value for maxInt32 which is `2147483647` or 68 years.

```yaml
spec:
  replicas: 4
  strategy:
    canary:
      scaleDownDelayRevisionLimit: 2
      scaleDownDelaySeconds: 2147483647
```

After this workaround, the scaling behavior is working as expected.

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
Side note: if someone only specifies `scaleDownDelaySeconds: 0` and omits `scaleDownDelayRevisionLimit`, we should document that we will use `spec.revisionHistoryLimit` as the `scaleDownDelayRevisionLimit`. 

```yaml
spec:
  strategy:
    canary:
      scaleDownDelaySeconds: 0
```
