### ISSUE TITLE
AWS alb target verification is not working if rootService is not provided

### ISSUE THREAD

**Issue by harikrongali** [argoproj/argo-rollouts#1640]
as per https://argoproj.github.io/argo-rollouts/features/traffic-management/alb/
```
      trafficRouting:
        alb:
          # The referenced ingress will be injected with a custom action annotation, directing
          # the AWS Load Balancer Controller to split traffic between the canary and stable
          # Service, according to the desired traffic weight (required).
          ingress: ingress
          # Reference to a Service that the Ingress must target in one of the rules (optional).
          # If omitted, uses canary.stableService.
          rootService: root-service
          # Service port is the port which the Service listens on (required).
          servicePort: 443
```
In above rootService is optional but not providing rootService breaks targetVerification
to reproduce
```
      trafficRouting:
        alb:
          ingress: ingress
          servicePort: 443
```
Version 1.1.0
