### ISSUE TITLE
Race condition when running analysis from experiment after immediate upgrade (1.1.0 regression)

### ISSUE THREAD

**Issue by artem-nefedov** [argoproj/argo-rollouts#1652]
## Summary 

Version 1.1.0 introduced a new race condition, which seems to happen when you run immediate upgrades (meaning changing revision again as soon as rollout becomes ready). The chance for issue to be reproduced is around 25%-50%.

Manifest used for testing:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: podinfo-test-argo-rollouts
spec:
  args:
  - name: service
  - name: expectedVersion
  metrics:
  - name: webmetric
    successCondition: result == '{{ args.expectedVersion }}'
    provider:
      web:
        url: "http://{{ args.service }}"
        timeoutSeconds: 20
        jsonPath: "{$.version}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: podinfo-test-argo-rollouts
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo-test-argo-rollouts
  labels:
    app: podinfo-test-argo-rollouts
spec:
  ports:
  - name: http
    port: 9898
    targetPort: 9898
  selector:
    app: podinfo-test-argo-rollouts
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo-test-argo-rollouts-preview
  labels:
    app: podinfo-test-argo-rollouts-preview
spec:
  ports:
  - name: http
    port: 9898
    targetPort: 9898
  selector:
    app: podinfo-test-argo-rollouts-preview
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: podinfo-test-argo-rollouts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podinfo-test-argo-rollouts
  template:
    metadata:
      labels:
        app: podinfo-test-argo-rollouts
    spec:
      serviceAccountName: podinfo-test-argo-rollouts
      containers:
      - command:
        - ./podinfo
        - --port=9898
        - --level=info
        - --random-delay=false
        - --random-error=false
        image: stefanprodan/podinfo:3.1.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:9898/healthz
          initialDelaySeconds: 5
          timeoutSeconds: 5
        name: podinfo-test-argo-rollouts
        ports:
        - containerPort: 9898
          name: http
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:9898/readyz
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
  strategy:
    canary:
      steps:
      - experiment:
          templates:
          - name: canary-preview
            specRef: canary
            selector:
              matchLabels:
                app: podinfo-test-argo-rollouts-preview
            metadata:
              labels:
                app: podinfo-test-argo-rollouts-preview
          analyses:
          - name: test-version-3.1.1
            templateName: podinfo-test-argo-rollouts
            requiredForCompletion: true
            args:
            - name: service
              value: podinfo-test-argo-rollouts-preview.default.svc.cluster.local:9898
            - name: expectedVersion
              value: 3.1.1
```

This manifest has an experiment, which creates a preview replica (which in turn has a separate Service), and runs webmetric-based analisys, which expects podinfo version to be exactly "3.1.1" (which is returned in response json from the service).

Reproduction steps:

```bash
kubectl apply -f test.yaml &&
kubectl wait --for=condition=completed rollout/podinfo-test-argo-rollouts &&
kubectl patch rollout podinfo-test-argo-rollouts --type=json -p='[{"op":"replace","path":"/spec/template/spec/containers/0/image","value":"stefanprodan/podinfo:3.1.1"}]' &&
kubectl wait --for=condition=completed rollout/podinfo-test-argo-rollouts &&
kubectl patch rollout podinfo-test-argo-rollouts --type=json -p='[{"op":"replace","path":"/spec/template/spec/containers/0/image","value":"stefanprodan/podinfo:3.1.2"}]' &&
kubectl wait --for=condition=completed rollout/podinfo-test-argo-rollouts
```

Here, we first deploy rollout with version 3.1.0 (it doesn't become degraded because canary steps are skipped on initial deployment), then upgrade it to 3.1.1 (experiment run succeeds), then **immediately** upgrade it to 3.1.2 (experiment should fail), so we expect Rollout to become degraded at the end. However, what actually happens is sometimes rollout becomes green (Completed) with version 3.1.2 instead.

The first step of first upgrading to 3.1.1 is required. If you deploy it as 3.1.1 and only upgrade to 3.1.2, the issue won't be reproduced.

If the issue isn't reproduced on the first try, destroy everything and run it again.

## My root cause analysis

From what I observe, controller doesn't scale down all the pods from previous revision experiment (3.1.1) until after it has already run analysis for final revision (3.1.2). So, because pods from previous revision still exist, all traffic hitting preview Service has a 50/50 chance to go to ether 3.1.1 or 3.1.2 pod.

Also, this is a regression introduced in 1.1.0, and isn't reproduced with 1.0.7.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by perenesenko** [comment]
@artem-nefedov 
In the 1.1 there where `scaleDownDelaySeconds` feature introduced. By default there is 30 seconds scale down delay.
To avoid this you can set this value to 0

**Comment by artem-nefedov** [comment]
@perenesenko I've tried setting it like this:
```
  strategy:
    canary:
      scaleDownDelaySeconds: 0
      steps:
      ...
```
... and got an error:
```
Message:         InvalidSpec: The Rollout "podinfo-test-argo-rollouts" is invalid: spec.strategy.scaleDownDelaySeconds: Invalid value: 0: Canary scaleDownDelaySeconds can only be used with traffic routing
```
In my case, I don't use traffic routing features.

I also couldn't figure it out if it's possible to set for experiment specifically.
It looks like Experiment CRD does support scaleDownDelaySeconds field:
https://github.com/argoproj/argo-rollouts/blob/master/manifests/crds/experiment-crd.yaml#L92
But if I try to set it for inline experiment like this, I get an ValidationError:
```
  strategy:
    canary:
      steps:
      - experiment:
          scaleDownDelaySeconds: 0
          templates:
          ...
```
