### ISSUE TITLE
Rollout is not dynamic labels aware

### ISSUE THREAD

**Issue by kandeshvari** [argoproj/argo-rollouts#1658]
## Summary 

I use dynamic labeling to pass traffic to leader pod. Definition is

```yaml
apiVersion: v1
kind: Service
metadata:
    name: xxx
spec:
    ports:
        -   name: xxx
            port: 8080
            protocol: TCP
            targetPort: 8080
    selector:
        app: xxx
        role: leader
```

Label `role: leader` is added to pod by a sidecar container after a complex leader check. 

I do not use label `role` in `Rollout` and get this error

```yaml
status:
  conditions:
  - lastTransitionTime: "2021-11-14T16:13:51Z"
    lastUpdateTime: "2021-11-14T16:13:51Z"
    message: 'The Rollout "xxx" is invalid: spec.strategy.canary.stableService:
      Invalid value: "xxx": Service "xxx" has unmatch
      lable "role" in rollout'
    reason: InvalidSpec
```

Is there possibility to use argo rollout in such cases?

argo rollouts: master from 13 Nov '21
k8s: 1.22.3
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by huikang** [comment]
@kandeshvari , if the match label is added to the pod template as well, I think it should work. Could you verify if the pod label matches the service label?

**Comment by huikang** [comment]
The rollout's podTemplate likes Deployment, where all pods have the same labels. The behavior you described sounds a statefulset.

So I don't think dynamic labels will be supported for rollout CR.

**Comment by kandeshvari** [comment]
Dynamic labels are not for `Rollout`. They are for `Pod`. As I understand - `Rollout` cr is an extension of a `Deployment` and must act as a `Deployment`. If I use plain `Deployment` - everything works fine, if I "translate" it to `Rollout` - I'm getting the error. So, I may conclude - the problem is in the `Rollout` cr and excessive label checks, that are not present in the `Deployment`.

**Comment by huikang** [comment]
The rollout controller checks if the `service`'s label matches the pods label

```yaml
apiVersion: v1
kind: Service
metadata:
    name: xxx
spec:
    selector:
        L1: K1
        L2: K2
```

Then the rollout must have labels `L1: K1` and `L2: K2` in the its selector's label.

```yaml
piVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-test
spec:
  selector:
    matchLabels:
        L1: K1    # --------- > match service's label
        L2: K2  
```

Could you illustrate what you use cases?
