### ISSUE TITLE
Background analysis should ignore count value

### ISSUE THREAD

**Issue by harikrongali** [argoproj/argo-rollouts#1666]
Background analysis should ignore count value as it should run indefinitely until all steps are completed.
The issue that we are seeing is if there is a count value present in the analysis template, then Background analysis runs for a number of count values and stops even though rollout is still progressing.

In rollout code, for background analysis, we do ignore count during template validation but we are not ignoring it as a part of analysis runs.

sample 
```
kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: pass
spec:
  metrics:
  - name: pass
    interval: 5s
    failureLimit: 1
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: sleep
                image: alpine:3.8
                command: [sh, -c]
                args: [exit 0]
              restartPolicy: Never
          backoffLimit: 0
    count: 5
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-analysis-step
spec:
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-analysis-step
  template:
    metadata:
      labels:
        app: rollout-analysis-step
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    canary:
      analysis:
          templates:
          - templateName: always-pass
      steps:
      - setWeight: 25
      - pause: 1m
      - setWeight: 50
      - pause: 1m      
```

This will be useful for someone to use templates for inline and background analysis while passing args for count & other values

workaround is set count to zero
