### ISSUE TITLE
Notifications do not respect defaultTriggers

### ISSUE THREAD

**Issue by jali-clarke** [argoproj/argo-rollouts#1668]
## Summary 

Even though `Argo Rollouts` uses the same notification engine as `Argo CD`, it does not seem to respect `defaultTriggers` the same way that `Argo CD` does.

If I set the following in `argo-rollouts-notification-configmap`:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-notification-configmap
data:
  # other configs redacted

  defaultTriggers: |
    - on-rollout-completed
    - on-rollout-step-completed
    - on-rollout-updated
    - on-scaling-replica-set
```

and attach the following annotation to the `Rollout` object:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-canary
  annotations:
    notifications.argoproj.io/subscribe.slack: argo-notifications
  # spec and so on redacted
```

I don't get any event notifications in the `#argo-notifications` Slack channel on e.g. completed rollout, replicaset scale up, etc.  

It _does_ work fine if I set the following annotations, however:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-canary
  annotations:
      notifications.argoproj.io/subscribe.on-rollout-completed.slack: argocd-notifications
      notifications.argoproj.io/subscribe.on-rollout-step-completed.slack: argocd-notifications
      notifications.argoproj.io/subscribe.on-rollout-updated.slack: argocd-notifications
      notifications.argoproj.io/subscribe.on-scaling-replica-set.slack: argocd-notifications
```

This works regardless of whether `defaultTriggers` is configured, of course.

## Diagnostics

Using `quay.io/argoproj/argo-rollouts:v1.1.0`

```
# Paste the logs from the rollout controller

time="2021-11-24T12:33:33Z" level=info msg="Start processing" resource=rollout-canary/rollout-canary
time="2021-11-24T12:33:33Z" level=info msg="Started syncing rollout" generation=4 namespace=rollout-canary resourceVersion=310075394 rollout=rollout-canary
time="2021-11-24T12:33:33Z" level=info msg="Trigger on-scaling-replica-set result: [{[0].2jmj7l5rSw0yVb_vlWAYkK_YBwk  [scaling-replicaset] false}]" resource=rollout-canary/rollout-canary
time="2021-11-24T12:33:33Z" level=info msg="Trigger on-rollout-completed result: [{[0].2jmj7l5rSw0yVb_vlWAYkK_YBwk  [rollout-completed] false}]" resource=rollout-canary/rollout-canary
time="2021-11-24T12:33:33Z" level=info msg="Trigger on-rollout-step-completed result: [{[0].2jmj7l5rSw0yVb_vlWAYkK_YBwk  [rollout-step-completed] false}]" resource=rollout-canary/rollout-canary
time="2021-11-24T12:33:33Z" level=info msg="Trigger on-rollout-updated result: [{[0].2jmj7l5rSw0yVb_vlWAYkK_YBwk  [rollout-updated] false}]" resource=rollout-canary/rollout-canary
time="2021-11-24T12:33:33Z" level=info msg="Processing completed" resource=rollout-canary/rollout-canary
```

Nothing out of the ordinary here, it seems.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
