### ISSUE TITLE
Background Analysis run targets stable pod instead of canary pod

### ISSUE THREAD

**Issue by aldredb** [argoproj/argo-rollouts#1700]
## Summary 

I deployed `Rollout` with AWS ALB `trafficRouting` and background analysis using `web` provisioner (refer to the manifests below). I changed the image from `argoproj/rollouts-demo:blue` to `argoproj/rollouts-demo:bad-green` to simulate auto rollback, but I noticed that the analysis traffic goes to `blue` (stable) instead of `bad-green` (canary), therefore all the web requests succeed and `bad-green` is promoted to stable. Via the pod logs, I can confirm that the analysis traffic only hits the stable pod. Please find the screenshot here: https://www.dropbox.com/s/va7pvber8ep137k/argo.jpg?dl=0

The manifests:

```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  replicas: 1
  strategy:
    canary:
      analysis:
        templates:
        - templateName: success-rate
        args:
          - name: service-name
            value: rollouts-demo-canary
          - name: namespace
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      canaryService: rollouts-demo-canary
      stableService: rollouts-demo-stable
      trafficRouting:
        alb:
          ingress: rollouts-demo-ingress
          servicePort: 80
          rootService: rollouts-demo-root
      steps:
      - setWeight: 25
      - pause: { duration: 60 }
      - setWeight: 50
      - pause: { duration: 60 }
      - setWeight: 75
      - pause: { duration: 60 }
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: service-name
    value: rollouts-demo-canary
  - name: namespace
  metrics:
  - name: success-rate
    successCondition: "true"
    interval: 2s
    failureLimit: 1
    provider:
      web:
        url: http://{{args.service-name}}.{{args.namespace}}.svc.cluster.local/color
        timeoutSeconds: 5
```

My currrent workaround is to set delay to the analysis by using `startingStep` **or** to use inline analysis instead of background analysis

```bash
  strategy:
    canary:
      analysis:
        templates:
        - templateName: success-rate
        startingStep: 2 # <-- delay
```

## Diagnostics

What version of Argo Rollouts are you running?

**v1.1.1+0716c5d**

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
