### ISSUE TITLE
Status.ALBStatus should be a pointer

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#1705]
## Summary 

The upcoming ALB status fields is polluting the Rollout status with a ton of empty information for users who are not even using ALB (which is probably most of our users).

```yaml
status:
  alb:
    canaryTargetGroup:
      arn: ""
      name: ""
    loadBalancer:
      arn: ""
      name: ""
    stableTargetGroup:
      arn: ""
      name: ""
```

This needs to be changed to a struct pointer so that users who don't have alb enabled, won't see this.

## Diagnostics

What version of Argo Rollouts are you running? v1.2 (unreleased)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
