### ISSUE TITLE
Rollout failed to start with a small # of replicas and a large # of steps.

### ISSUE THREAD

**Issue by joeblubaugh** [argoproj/argo-rollouts#1713]
## Summary 

I have a rollout configured like:
```yaml
spec:
  replicas: 3
  # must be larger than any pause; https://github.com/argoproj/argo-rollouts/issues/1225
  progressDeadlineSeconds: 3600
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    # reference all settings from this Deployment
    name: foo
  strategy:
    canary:
      analysis:
        templates:
          - templateName: bar
        startingStep: 1
      {{- end }}
      maxUnavailable: 1
      maxSurge: "20%"
      stableMetadata:
        labels:
          role: stable
      canaryMetadata:
        labels:
          role: canary
      steps:
          canarySteps:
            - setWeight: 10
            - pause: {duration: 600s}
            - setWeight: 20
            - pause: {duration: 600s}
            - setWeight: 40
            - pause: {duration: 600s}
            - setWeight: 60
            - pause: {duration: 600s}
```

When this is run with a low replica count, the first step with weight 10 fails to start. My read of the code implies that one canary replica should still be started:
https://github.com/argoproj/argo-rollouts/blob/5e188f94ac5f678d27774249100078d88c8225ee/utils/replicaset/canary.go#L136

We worked around this problem by reducing the number of steps and setting a high initial weight. It would be great if this works with a smaller # of replicas so we could use the same set of steps in different operating environments with different #s of replicas.
## Diagnostics

What version of Argo Rollouts are you running?
v1.1.0+ff3471a

The rollout controller has already rolled past the logs for this.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by huikang** [comment]
@joeblubaugh , I couldn't reproduce the behavior even with a small replica number 1

The first step of my rollout is

```
    steps:
        - setWeight: 10
        - pause: {}
        - setWeight: 40
```

When the rollout paused at step 1, it shows 1 canary pod is created.

```
Status:          ॥ Paused
Message:         CanaryPauseStep
Strategy:        Canary
  Step:          1/8
  SetWeight:     10
  ActualWeight:  50
Images:          argoproj/rollouts-demo:blue (stable)
                 argoproj/rollouts-demo:green (canary)
Replicas:
  Desired:       1
  Current:       2
  Updated:       1
  Ready:         2
  Available:     2

NAME                                       KIND        STATUS     AGE  INFO
⟳ rollouts-demo                            Rollout     ॥ Paused   19s  
├──# revision:2                                                        
│  └──⧉ rollouts-demo-867888776f           ReplicaSet  ✔ Healthy  8s   canary
│     └──□ rollouts-demo-867888776f-qnq2x  Pod         ✔ Running  7s   ready:1/1
└──# revision:1                                                        
   └──⧉ rollouts-demo-6668595956           ReplicaSet  ✔ Healthy  19s  stable
      └──□ rollouts-demo-6668595956-t6s8x  Pod         ✔ Running  19s  ready:1/1
➜  argo-rollouts-backup2 git:(1711-get-rollouts-list-labels) ✗ 

```

My controller version is `v1.1.0+061efd4.dirty`. or if possible, could you paste the full rollout spec as I might miss something to reproduce the behavior? Thanks.
