### ISSUE TITLE
Kustomize fail to merge `.spec.template.spec.containers[].env` fields

### ISSUE THREAD

**Issue by shibataka000** [argoproj/argo-rollouts#1730]
## Summary 

Kustomize overwrite Rollout's `.spec.template.spec.containers[].env` fields when overlay. I think kustomize should merge its field instead of overwriting.

### Example

**Manifests**

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rollouts.yaml
patchesStrategicMerge:
- |-
  apiVersion: argoproj.io/v1alpha1
  kind: Rollout
  metadata:
    name: rollouts-demo
  spec:
    template:
      spec:
        containers:
        - name: rollouts-demo
          image: nginx
          env:
          - name: KEY2
            value: VALUE2
openapi:
 path: rollout_cr_schema.json # Same as https://argoproj.github.io/argo-rollouts/features/kustomize/rollout_cr_schema.json
```

```yaml
# rollouts.yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  strategy:
    blueGreen:
      activeService: rollouts-demo-service
      previewService: rollouts-demo-service-preview
      autoPromotionEnabled: false
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: KEY1
          value: VALUE1
```

**Expected output of `kustomize build` command**

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  strategy:
    blueGreen:
      activeService: rollouts-demo-service
      autoPromotionEnabled: false
      previewService: rollouts-demo-service-preview
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
      - env:
        - name: KEY1
          value: VALUE1
        - name: KEY2
          value: VALUE2
        image: nginx
        name: rollouts-demo
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
```

**Actual output of `kustomize build` command**

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  strategy:
    blueGreen:
      activeService: rollouts-demo-service
      autoPromotionEnabled: false
      previewService: rollouts-demo-service-preview
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
      - env:
        - name: KEY2
          value: VALUE2
        image: nginx
        name: rollouts-demo
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
```

### Note
I guess [rollout_cr_schema.json](https://github.com/argoproj/argo-rollouts/blob/v1.1.1/docs/features/kustomize/rollout_cr_schema.json) lack following annotation at `env` properties.

```
"x-kubernetes-patch-merge-key": "name",
"x-kubernetes-patch-strategy": "merge",
```

[swagger.json](https://github.com/kubernetes/kubernetes/blob/v1.21.0/api/openapi-spec/swagger.json), which is referred by [gen-crd-spec](https://github.com/argoproj/argo-rollouts/blob/v1.1.1/hack/gen-crd-spec/main.go), has forementioned annotation at `env` properties at [L5873-L5881](https://github.com/kubernetes/kubernetes/blob/v1.21.0/api/openapi-spec/swagger.json#L5873-L5881). But [rollout_cr_schema.json](https://github.com/argoproj/argo-rollouts/blob/v1.1.1/docs/features/kustomize/rollout_cr_schema.json) lack forementioned annotation at `env` properties at following lines.

- [rollout_cr_schema.json#L173-L268](https://github.com/argoproj/argo-rollouts/blob/v1.1.1/docs/features/kustomize/rollout_cr_schema.json#L173-L268)
- [rollout_cr_schema.json#L1022-L1117](https://github.com/argoproj/argo-rollouts/blob/v1.1.1/docs/features/kustomize/rollout_cr_schema.json#L1022-L1117)
- [rollout_cr_schema.json#L1901-L1996](https://github.com/argoproj/argo-rollouts/blob/v1.1.1/docs/features/kustomize/rollout_cr_schema.json#L1901-L1996).

## Diagnostics

```bash
$ kustomize version
{Version:kustomize/v4.4.0 GitCommit:63ec6bdb3d737a7c66901828c5743656c49b60e1 BuildDate:2021-09-27T16:24:12Z GoOs:linux GoArch:amd64}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
