### ISSUE TITLE
Web metric provider

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#177]
Instead of prometheus, a generic ~webhook~ HTTP URL may be desired as a metric provider. This might look something like:

```yaml
metrics:
- name: my-webhook
  provider:
    web:
      url: http://my-website/api/my-metric
      successCondition: result.data.values[1] > 99
```
