### ISSUE TITLE
AnalysisRun pre-conditions

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#178]
AnalysisRuns might need pre-conditions metrics before deciding to take measurements. For example, the following might describe that at least 1000 requests should have been made before measuring metrics.

```yaml
preConditions:
- name: min-requests
  prometheus:
    query: sum(increase(http_requests_total))
    successCondition: result > 1000
```

Additionally, we may need something like initialDelaySeconds, which waits some amount of time before starting measurements:

```yaml
spec:
  initialDelaySeconds: 600
```

Conceivably this could just be another preCondition
```yaml
preConditions:
- name: wait-10m
  wait: 600
```
