### ISSUE TITLE
Argo rollout notifications should support a list of triggers in a single annotation

### ISSUE THREAD

**Issue by RaviHari** [argoproj/argo-rollouts#1783]
# Summary

What change needs making?
Update Rollout Notifications to support a list of notifications in a single annotation.
Today we have to specify each notification in argo rollout in a seperate line e.g:
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-rollout-completed.slack: ar-notifications-test
    notifications.argoproj.io/subscribe.on-rollout-updated.slack: ar-notifications-test
    notifications.argoproj.io/subscribe.on-rollout-paused.slack: ar-notifications-test
    notifications.argoproj.io/subscribe.on-rollout-aborted.slack: ar-notifications-test
    notifications.argoproj.io/subscribe.on-rollout-step-completed.slack: ar-notifications-test
    notifications.argoproj.io/subscribe.on-scaling-replica-set.slack: ar-notifications-test
```

instead it would be better to declare this in a single annotation like:
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-rollout-completed,on-rollout-updated,on-rollout-pausedon-rollout-aborted,on-rollout-step-completed,on-scaling-replica-set.slack: ar-notifications-test
```

# Use Cases

When would you use this?

When we want to subscribe for multiple notifications.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
