### ISSUE TITLE
Kustomize configurations file is not complete

### ISSUE THREAD

**Issue by chrisjohnson** [argoproj/argo-rollouts#184]
For example, I needed to add this entry to `nameReference` to get it to pick up my PVC name for prefixing:

```yaml
  - kind: PersistentVolumeClaim
    fieldSpecs:
      - path: spec/template/spec/volumes/persistentVolumeClaim/claimName
        kind: Rollout
```

I'm sure there are others. Is is not intended to be a complete example? Is there a more complete version?

BTW I got it by looking at the default nameReference here: https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/transformers/config/defaultconfig/namereference.go
