### ISSUE TITLE
documentation - Rollout spec for bluegreen strategy missing previewMetadata and activeMetadata example fields

### ISSUE THREAD

**Issue by zswanson** [argoproj/argo-rollouts#1845]
## Summary 

The bluegreen strategy supports adding ephemeral labels and annotations during the rollout, but Rollout spec documentation page are missing this information. We had overlooked the 'ephemeral metadata' page in the user docs and only found this by accident when we assumed that if canary had the fields that it was likely bluegreen did too. This should be added to https://argoproj.github.io/argo-rollouts/features/specification/

```
  strategy:
    blueGreen:
      activeService: bluegreen-active
      previewService: bluegreen-preview
      previewMetadata:
        labels:
          version: preview
        annotations:
           myorg/team: v2
      activeMetadata:
        labels:
          version: active
        annotations:
           myorg/team: v1
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
