### ISSUE TITLE
autoPromotionEnabled: false not being respected

### ISSUE THREAD

**Issue by chrisjohnson** [argoproj/argo-rollouts#185]
I'm brand new to using rollouts and I've got a pretty simple blue/green rollout. The strategy is defined as such:

```yaml
    blueGreen:
      activeService: rxindicator-web
      previewService: rxindicator-web-preview
      previewReplicaCount: 3
      autoPromotionEnabled: false
      autoPromotionSeconds: 120
      scaleDownDelaySeconds: 60
```

But after a short period of time of both ReplicaSets being scaled appropriately, the older version gets scaled down and then terminated. It seems like this should not be happening without my input
