### ISSUE TITLE
Update while another rollout in progress produces inconsistent replica scaling

### ISSUE THREAD

**Issue by mjhuber** [argoproj/argo-rollouts#1852]
## Summary 
If a revision is deployed to a Rollout while another revision is in progress argo behaves unexpectedly and continuously scales up and down the previous revision.  The rollout eventually succeeds after some period of inconsistent scaling in/out of the old image.

Example rollout:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    rollout.argoproj.io/revision: "5"
  name: feature-do-1030-merchant-portal
  namespace: feature-do-1030
spec:
  analysis:
    successfulRunHistoryLimit: 10
    unsuccessfulRunHistoryLimit: 10
  minReadySeconds: 15
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: feature-do-1030
      app.kubernetes.io/name: merchant-portal
  strategy:
    canary:
      analysis:
        args:
        - name: application
          value: merchant-portal
        - name: projectSlug
          value: merchant-portal
        - name: environment
          value: stage
        - name: ingress
          value: merchant-portal
        startingStep: 1
        templates:
        - clusterScope: true
          templateName: newrelic
        - clusterScope: true
          templateName: nginx-ingress
        - clusterScope: true
          templateName: sentry
      canaryMetadata:
        annotations:
          rechargeapps.net/canary: "true"
      canaryService: feature-do-1030-merchant-portal-canary
      maxSurge: 100%
      maxUnavailable: 20%
      scaleDownDelayRevisionLimit: 2
      scaleDownDelaySeconds: 600
      stableMetadata:
        annotations:
          rechargeapps.net/canary: "false"
      stableService: feature-do-1030-merchant-portal
      steps:
      - setWeight: 20
      - pause:
          duration: 15m
      - setWeight: 50
      - pause:
          duration: 15m
      - setWeight: 80
      - pause:
          duration: 15m
      trafficRouting:
        nginx:
          stableIngress: feature-do-1030-merchant-portal
  template:
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: feature-do-1030-merchant-portal
        - secretRef:
            name: feature-do-1030-merchant-portal
            optional: true
        image: <redacted>
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - -c
              - sleep 15
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /merchant/ping
            port: http
          periodSeconds: 5
        name: merchant-portal
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /merchant/ping
            port: http
          periodSeconds: 2
        resources:
          limits:
            cpu: 1500m
            memory: 1Gi
          requests:
            cpu: 800m
            memory: 500Mi
        startupProbe:
          failureThreshold: 96
          httpGet:
            path: /merchant/ping
            port: http
          periodSeconds: 5
      serviceAccountName: feature-do-1030-merchant-portal
```

### Steps to Reproduce:
1.  Deploy rollout.
2. While rollout is still in progress, update the image version.  A new Rollout begins.
3. Argo Rollouts scales in the new revision but continues to scale up and down continuously the old revision.

![CleanShot 2022-02-07 at 08 37 48](https://user-images.githubusercontent.com/19253559/152809531-4bbb71e4-49d6-4379-9cb9-012c97774092.gif)

![CleanShot 2022-02-07 at 08 38 55](https://user-images.githubusercontent.com/19253559/152809653-886236f7-269c-43a2-a4ca-1e401b824baf.gif)

What happened/what you expected to happen?
When the new revision deploys the old rollout is cancelled and the new rollout begins.

## Diagnostics

What version of Argo Rollouts are you running?
* chart version `2.9.3`
* app version `1.1.1`
* [logs.output.txt](https://github.com/argoproj/argo-rollouts/files/8016217/output.txt)
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
