### ISSUE TITLE
Add support for variables in analysis templates

### ISSUE THREAD

**Issue by lextas** [argoproj/argo-rollouts#1861]
# Disclaimer

This might be a use case issue so if you disagree feel free to close this issue.

# Summary

Currently analysis templates support arguments but there is no easy way to define a list of variables. It would be nice to set hard-coded values in a template that cannot be overridden to keep queries clean. I know I can add `args` with a default value but it doesn't feel that arguments are meant for this use case.

My proposal would be to do something like this (example taken from [docs](https://argoproj.github.io/argo-rollouts/features/analysis/))

```
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: service-name
  vars:
  - name: quantiles
     value: 0.95
  - name: exclude-routes
    value: "some-route|some-other-route"
  metrics:
  - name: success-rate
    interval: 5m
    successCondition: result[0] >= {{ vars.quantiles }}
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus.example.com:9090
        query: |
          sum(irate(
            istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}",response_code!~"5.*", route!~"{{ vars.exclude-routes }}"}[5m]
          )) /
          sum(irate(
            istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}"}[5m]
          ))
```

This would allow to set the variables once and reuse them in multiple queries. Some variables might grow, like the `exclude-routes` in this example, which make it prone to errors when it's being copy/pasted in multiple queries and also hard to maintain.

# Use Cases

In my use case we have a base analysis-template for low latency that runs for every service. Some services have dependencies that affect the latency. Therefore we add an analysis template with service specific queries and higher limits. In some cases we actually adjust the thresholds on a route level.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
