### ISSUE TITLE
Dashboard crash after hitting Promote button

### ISSUE THREAD

**Issue by jasonwzm** [argoproj/argo-rollouts#1870]
## Summary 

Dashboard crashed after hitting the Promote button when step is paused. Abort seems to have the same issue. Using Istio for canary traffic routing. Rollout was progressing fine though.

What happened/what you expected to happen?
I don't have to restart the dashboard to get the dashboard working.

## Diagnostics

What version of Argo Rollouts are you running?
v1.2.0-rc1

```
bash-3.2$ kubectl argo rollouts dashboard
INFO[0000] Argo Rollouts Dashboard is now available at localhost 3100 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1fb8706]

goroutine 210 [running]:
github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1.(*IstioVirtualService).MarshalToSizedBuffer(0x0, 0xc000e8c000, 0x1ee6, 0x2142, 0x16, 0x0, 0x0)
        /go/src/github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1/generated.pb.go:5037 +0x26
github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1.(*IstioTrafficRouting).MarshalToSizedBuffer(0xc0004c1890, 0xc000e8c000, 0x1efe, 0x2142, 0xc0001ebe58, 0x19, 0x1520dd5)
        /go/src/github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1/generated.pb.go:5005 +0x2b1
github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1.(*RolloutTrafficRouting).MarshalToSizedBuffer(0xc0004c17d0, 0xc000e8c000, 0x1efe, 0x2142, 0x6, 0x0, 0x0)
        /go/src/github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1/generated.pb.go:6978 +0x377
github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1.(*CanaryStrategy).MarshalToSizedBuffer(0xc00114c5a0, 0xc000e8c000, 0x1f08, 0x2142, 0x0, 0x0, 0x6212c529)
        /go/src/github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1/generated.pb.go:4016 +0x6ab
github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1.(*RolloutStrategy).MarshalToSizedBuffer(0xc00002a418, 0xc000e8c000, 0x1f08, 0x2142, 0x8, 0x0, 0x0)
        /go/src/github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1/generated.pb.go:6883 +0x19c
github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1.(*RolloutSpec).MarshalToSizedBuffer(0xc00002a118, 0xc000e8c000, 0x1f16, 0x2142, 0x229, 0x0, 0x0)
        /go/src/github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1/generated.pb.go:6617 +0x24d
github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1.(*Rollout).MarshalToSizedBuffer(0xc00002a000, 0xc000e8c000, 0x2142, 0x2142, 0x100b745, 0x28bf320, 0x2b17ce0)
        /go/src/github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1/generated.pb.go:6020 +0x145
github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1.(*Rollout).Marshal(0xc00002a000, 0x2b17ce0, 0xc00002a000, 0x2e4daa20, 0xc00002a000, 0x1)
        /go/src/github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1/generated.pb.go:5992 +0x7a
google.golang.org/grpc/encoding/proto.codec.Marshal(0x2b17ce0, 0xc00002a000, 0xc000054088, 0xc000877730, 0x100a1bf, 0xc00003a000, 0x28d6fa0)
        /go/pkg/mod/google.golang.org/grpc@v1.33.1/encoding/proto/proto.go:70 +0x199
google.golang.org/grpc.encode(0x2e7f5990, 0x42755f0, 0x2b17ce0, 0xc00002a000, 0x42755f0, 0x205f930, 0x2943900, 0xc000390ac0, 0xc000618ba0)
        /go/pkg/mod/google.golang.org/grpc@v1.33.1/rpc_util.go:593 +0x52
google.golang.org/grpc.(*Server).sendResponse(0xc00022e000, 0x3512a18, 0xc00018a780, 0xc0010e6700, 0x2b17ce0, 0xc00002a000, 0x0, 0x0, 0xc000a275a9, 0x0, ...)
        /go/pkg/mod/google.golang.org/grpc@v1.33.1/server.go:999 +0x91
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00022e000, 0x3512a18, 0xc00018a780, 0xc0010e6700, 0xc0004a6540, 0x422ae18, 0x0, 0x0, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.33.1/server.go:1245 +0x625
google.golang.org/grpc.(*Server).handleStream(0xc00022e000, 0x3512a18, 0xc00018a780, 0xc0010e6700, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.33.1/server.go:1533 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000850030, 0xc00022e000, 0x3512a18, 0xc00018a780, 0xc0010e6700)
        /go/pkg/mod/google.golang.org/grpc@v1.33.1/server.go:871 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /go/pkg/mod/google.golang.org/grpc@v1.33.1/server.go:869 +0x1fd
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by harikrongali** [comment]
@jasonwzm can you post your manifest file? Do you see same with cli as well?
```
kubectl argo rollouts promote rollout <rolloutname> 
```

@perenesenko can you validate the use case?

**Comment by jasonwzm** [comment]
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: www
  labels:
    app: www
spec:
  selector:
    matchLabels:
      app: www
  strategy:
    canary:
      canaryService: www-canary
      stableService: www-stable
      maxUnavailable: 0
      trafficRouting:
        istio:
          virtualServices:
            - name: www
              routes:
              - primary
      steps:
        - setWeight: 50
        - pause: {}
        - setWeight: 100
  template:
    metadata:
      labels:
        app: www
    spec:
...
```

@harikrongali cli works fine and in the UI, promote actually works, it just crashed the UI once the button is hit.
