### ISSUE TITLE
Can't send Slack Notifications

### ISSUE THREAD

**Issue by ebkn** [argoproj/argo-rollouts#1894]
## Summary 
Hi. I want to notify BlueGreen rollout strategy status to `Slack`. 
Rollout works as expected but notification doesn't works.

However I can send notification manually by using `kubectl argo rollouts notifications template notify` command.
```sh
kubectl argo rollouts notifications template notify rollout-completed player-api --recipient slack:channel1 -n ar-test
{"ok":true,"channel":"xxxxxxx","ts":"1646322894.002729","message":{"type":"message","subtype":"bot_message","text":"Rollout player-api has been completed.","ts":"1646322894.002729","username":"Argo Rollouts Notifications","bot_id":"xxxxx","attachments":[{"id":1,"color":"18be52","fallback":"player-api","title":"player-api","fields":[{"value":"BlueGreen","title":"Strategy","short":true},{"value":"<xxxxxxx|xxxxxxxxx>","title":"player-api","short":true},{"value":"envoyproxy/envoy-alpine:v1.20.0","title":"envoy","short":true}]}]}}  service=slack
```

Do I missed some installation processes?

<details><summary>This is my manifests.</summary>

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ar-test
configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml
resources:
  - https://github.com/argoproj/argo-rollouts/releases/download/v1.2.0-rc2/namespace-install.yaml
  - https://github.com/argoproj/argo-rollouts/releases/download/v1.2.0-rc2/notifications-install.yaml
  - player-api-rollout.yaml
patchesStrategicMerge:
  - argo-rollouts-notifications-config.yaml
  - argo-rollouts-notification-secret.yaml

---
# argo-rollouts-notifications-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-notification-configmap
data:
  service.slack: |
    token: $slack-token
    username: Argo Rollouts Notifications

---
# argo-rollouts-notification-secret.yaml
apiVersion: v1
data:
  slack-token: xxxxx
kind: Secret
metadata:
  name: argo-rollouts-notification-secret

---
# player-api-rollout.yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: player-api
  labels:
    app: player-api
  annotations:
    notifications.argoproj.io/subscribe.on-rollout-completed.slack: channel1
    notifications.argoproj.io/subscribe.on-rollout-step-completed.slack: channel1
    notifications.argoproj.io/subscribe.on-rollout-updated.slack: channel1
    notifications.argoproj.io/subscribe.on-scaling-replica-set.slack: channel1
spec:
  revisionHistoryLimit: 2
  strategy:
    blueGreen:
      activeService: player-api
      previewService: player-api-preview
      autoPromotionEnabled: false
      maxUnavailable: 0
  selector:
    matchLabels:
      app: player-api
  template:
    metadata:
      labels:
        app: player-api
    spec:
      containers:
      - image: xxxxxx
        name: player-api
...
      - name: envoy
        image: envoyproxy/envoy-alpine:v1.20.0
...
```

Maybe this is related to https://github.com/argoproj/argo-rollouts/issues/1720 (https://github.com/argoproj/notifications-engine/issues/47) but I'm not sure.

</details>

## Diagnostics

What version of Argo Rollouts are you running?
`v1.2.0-rc2`
```sh
kubectl argo rollouts version
kubectl-argo-rollouts: v1.2.0-rc2+7b69058
  BuildDate: 2022-02-24T22:35:08Z
  GitCommit: 7b690580f69fd491f40c15b3ff4031f13bdae332
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: darwin/amd64
```

```
# Paste the logs from the rollout controller

time="2022-03-03T15:52:49Z" level=info msg="Start processing" resource=ar-test/player-api
time="2022-03-03T15:52:49Z" level=info msg="Trigger on-rollout-completed result: [{[0].2jmj7l5rSw0yVb_vlWAYkK_YBwk  [rollout-completed] false}]" resource=ar-test/player-api
time="2022-03-03T15:52:49Z" level=info msg="Trigger on-rollout-step-completed result: [{[0].2jmj7l5rSw0yVb_vlWAYkK_YBwk  [rollout-step-completed] false}]" resource=ar-test/player-api
time="2022-03-03T15:52:49Z" level=info msg="Processing completed" resource=ar-test/player-api
time="2022-03-03T15:52:49Z" level=info msg="persisted to informer" generation=7 namespace=ar-test resourceVersion=22009053 rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="Reconciliation completed" generation=7 namespace=ar-test resourceVersion=22009047 rollout=player-api time_ms=113.177942
time="2022-03-03T15:52:49Z" level=info msg="Started syncing rollout" generation=7 namespace=ar-test resourceVersion=22009053 rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="ComputePodTemplateHash hash changed (expected: 585c8548bc, actual: 68bff5d998)" namespace=ar-test rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="Reconciling stable ReplicaSet 'player-api-869fd7fb54'" namespace=ar-test rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="Enqueueing parent of ar-test/player-api-68bff5d998: Rollout ar-test/player-api"
time="2022-03-03T15:52:49Z" level=info msg="Scaled up ReplicaSet player-api-68bff5d998 (revision 5) from 0 to 2" event_reason=ScalingReplicaSet namespace=ar-test rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="New RS 'player-api-68bff5d998' is not ready to pause" namespace=ar-test rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="skipping active service switch: New RS 'player-api-68bff5d998' is not fully saturated" namespace=ar-test rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="Event(v1.ObjectReference{Kind:\"Rollout\", Namespace:\"ar-test\", Name:\"player-api\", UID:\"2ed4ae3f-cd81-4286-9a83-0ec6c527b2be\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"22009053\", FieldPath:\"\"}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up ReplicaSet player-api-68bff5d998 (revision 5) from 0 to 2"
time="2022-03-03T15:52:49Z" level=info msg="Timed out (false) [last progress check: 2022-03-03 15:52:48 +0000 UTC - now: 2022-03-03 15:52:49.100371685 +0000 UTC m=+4921.690838039]" namespace=ar-test rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="No status changes. Skipping patch" generation=7 namespace=ar-test resourceVersion=22009053 rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="Queueing up rollout for a progress after 598s" namespace=ar-test rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="Reconciliation completed" generation=7 namespace=ar-test resourceVersion=22009053 rollout=player-api time_ms=83.020865
time="2022-03-03T15:52:49Z" level=info msg="Started syncing rollout" generation=7 namespace=ar-test resourceVersion=22009053 rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="ComputePodTemplateHash hash changed (expected: 585c8548bc, actual: 68bff5d998)" namespace=ar-test rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="Reconciling stable ReplicaSet 'player-api-869fd7fb54'" namespace=ar-test rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="New RS 'player-api-68bff5d998' is not ready to pause" namespace=ar-test rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="skipping active service switch: New RS 'player-api-68bff5d998' is not fully saturated" namespace=ar-test rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="Timed out (false) [last progress check: 2022-03-03 15:52:48 +0000 UTC - now: 2022-03-03 15:52:49.103526712 +0000 UTC m=+4921.693993067]" namespace=ar-test rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="No status changes. Skipping patch" generation=7 namespace=ar-test resourceVersion=22009053 rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="Queueing up rollout for a progress after 598s" namespace=ar-test rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="Reconciliation completed" generation=7 namespace=ar-test resourceVersion=22009053 rollout=player-api time_ms=3.096895
time="2022-03-03T15:52:49Z" level=info msg="Enqueueing parent of ar-test/player-api-68bff5d998: Rollout ar-test/player-api"
time="2022-03-03T15:52:49Z" level=info msg="Started syncing rollout" generation=7 namespace=ar-test resourceVersion=22009053 rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="ComputePodTemplateHash hash changed (expected: 585c8548bc, actual: 68bff5d998)" namespace=ar-test rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="Reconciling stable ReplicaSet 'player-api-869fd7fb54'" namespace=ar-test rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="New RS 'player-api-68bff5d998' is not ready to pause" namespace=ar-test rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="skipping active service switch: New RS 'player-api-68bff5d998' is not fully saturated" namespace=ar-test rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="Timed out (false) [last progress check: 2022-03-03 15:52:48 +0000 UTC - now: 2022-03-03 15:52:49.556259689 +0000 UTC m=+4922.146726061]" namespace=ar-test rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="No status changes. Skipping patch" generation=7 namespace=ar-test resourceVersion=22009053 rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="Queueing up rollout for a progress after 598s" namespace=ar-test rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="Reconciliation completed" generation=7 namespace=ar-test resourceVersion=22009053 rollout=player-api time_ms=4.517347
time="2022-03-03T15:52:49Z" level=info msg="Enqueueing parent of ar-test/player-api-68bff5d998: Rollout ar-test/player-api"
time="2022-03-03T15:52:49Z" level=info msg="Started syncing rollout" generation=7 namespace=ar-test resourceVersion=22009053 rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="ComputePodTemplateHash hash changed (expected: 585c8548bc, actual: 68bff5d998)" namespace=ar-test rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="Reconciling stable ReplicaSet 'player-api-869fd7fb54'" namespace=ar-test rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="New RS 'player-api-68bff5d998' is not ready to pause" namespace=ar-test rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="skipping active service switch: New RS 'player-api-68bff5d998' is not fully saturated" namespace=ar-test rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="Patched: {\"status\":{\"conditions\":[{\"lastTransitionTime\":\"2022-03-03T14:25:55Z\",\"lastUpdateTime\":\"2022-03-03T14:25:55Z\",\"message\":\"Rollout has minimum availability\",\"reason\":\"AvailableReason\",\"status\":\"True\",\"type\":\"Available\"},{\"lastTransitionTime\":\"2022-03-03T14:34:40Z\",\"lastUpdateTime\":\"2022-03-03T14:34:40Z\",\"message\":\"Rollout is paused\",\"reason\":\"RolloutPaused\",\"status\":\"False\",\"type\":\"Paused\"},{\"lastTransitionTime\":\"2022-03-03T15:52:48Z\",\"lastUpdateTime\":\"2022-03-03T15:52:48Z\",\"message\":\"RolloutCompleted\",\"reason\":\"RolloutCompleted\",\"status\":\"False\",\"type\":\"Completed\"},{\"lastTransitionTime\":\"2022-03-03T14:34:40Z\",\"lastUpdateTime\":\"2022-03-03T15:52:49Z\",\"message\":\"ReplicaSet \\\"player-api-68bff5d998\\\" is progressing.\",\"reason\":\"ReplicaSetUpdated\",\"status\":\"True\",\"type\":\"Progressing\"}],\"message\":\"active service cutover pending\",\"replicas\":4,\"updatedReplicas\":2}}" generation=7 namespace=ar-test resourceVersion=22009053 rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="persisted to informer" generation=7 namespace=ar-test resourceVersion=22009068 rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="Reconciliation completed" generation=7 namespace=ar-test resourceVersion=22009053 rollout=player-api time_ms=40.725814
time="2022-03-03T15:52:49Z" level=info msg="Start processing" resource=ar-test/player-api
time="2022-03-03T15:52:49Z" level=info msg="Started syncing rollout" generation=7 namespace=ar-test resourceVersion=22009068 rollout=player-api
time="2022-03-03T15:52:49Z" level=error msg="Failed to process: Object 'Kind' is missing in 'xxxxxxxxxxx' resource=ar-test/player-api
time="2022-03-03T15:52:49Z" level=info msg="ComputePodTemplateHash hash changed (expected: 585c8548bc, actual: 68bff5d998)" namespace=ar-test rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="Reconciling stable ReplicaSet 'player-api-869fd7fb54'" namespace=ar-test rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="New RS 'player-api-68bff5d998' is not ready to pause" namespace=ar-test rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="skipping active service switch: New RS 'player-api-68bff5d998' is not fully saturated" namespace=ar-test rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="Timed out (false) [last progress check: 2022-03-03 15:52:49 +0000 UTC - now: 2022-03-03 15:52:49.642620533 +0000 UTC m=+4922.233086887]" namespace=ar-test rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="No status changes. Skipping patch" generation=7 namespace=ar-test resourceVersion=22009068 rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="Queueing up rollout for a progress after 599s" namespace=ar-test rollout=player-api
time="2022-03-03T15:52:49Z" level=info msg="Reconciliation completed" generation=7 namespace=ar-test resourceVersion=22009068 rollout=player-api time_ms=3.226279
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by harikrongali** [comment]
@RaviHari can you please verify when you get a chance?

**Comment by RaviHari** [comment]
Sure.. I will look into this.

**Comment by RaviHari** [comment]
Hi @ebkn ,
I verfied this with latest argo-rollouts (quay.io/argoproj/argo-rollouts:v1.2.0-rc2) deployed and I am getting the slack notifications.. can you please check the docs and see if any step is missing in your environment.

**Comment by RaviHari** [comment]
In your configmap I donot see the triggers and templates..
you can use default trigerrs e.g:
```
# argo-rollouts-notifications-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-notification-configmap
data:
  service.slack: |
    token: $slack-token
    username: Argo Rollouts Notifications
  defaultTriggers: |
    - on-scaling-replica-set
    - on-rollout-completed  
```

**Comment by ebkn** [comment]
@RaviHari I got notifications by adding `defaultTriggers` to configmap. Thanks!
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-notification-configmap
data:
  service.slack: |
    token: $slack-token
    username: Argo Rollouts Notifications
  defaultTriggers: |
    - on-rollout-completed
    - on-rollout-step-completed
```

**Comment by RaviHari** [comment]
@ebkn can you close this issue if it is working for you?

**Comment by juanvasquezreyes** [comment]
I'm getting same error using teams "Failed to process: Object 'Kind' is missing in "

this is my configuration
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-notification-configmap
data:
  service.teams: |
    recipientUrls:
      channelName: $channel-teams-url
  defaultTriggers: |
    - on-rollout-completed
    - on-rollout-step-completed
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-rollouts-notification-secret
stringData:
  channel-teams-url: <URL>
```

and in the rollout annottations this is what I have
notifications.argoproj.io/subscribe.on-rollout-step-completed.teams: channelName

can you please let me know what I'm missing?
