### ISSUE TITLE
Add validation for rollout if selector is not specified

### ISSUE THREAD

**Issue by harikrongali** [argoproj/argo-rollouts#1897]
Similar to deployment, Rollout should throw error and shouldn't create the object if the selector is not specified.

Current behavior: 
Rollout object gets created with Error status

Expected behavior:
Rollout object shouldn't be allowed to create and throw a validation error

Following file doesn't have selector defined
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-canary
spec:
  replicas: 2
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    canary:
      canaryService: rollouts-demo-canary
```
