### ISSUE TITLE
Rollout to pause when the analysis metric doesnot return a value and resume when it does

### ISSUE THREAD

**Issue by RaviHari** [argoproj/argo-rollouts#1905]
# Summary

When the analysis template metric return no values.. Rollout should pause and resume when the values are returned.

# Use Cases

This could be a case when the new deployment has been triggered but the app does not get traffic then rollout will revert it back to the previous version.. but as such the new version of the canary pods have not yet been validated with traffic as application is not receiving any.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by alexmt** [comment]
I think the closest available feature is [inconclusive run](https://argoproj.github.io/argo-rollouts/features/analysis/#inconclusive-runs). In both `successCondition` and `failureCondition` returns `false` then run is considered inconclusive and Rollout automatically pauses.

```yaml
 metrics:
  - name: success-rate
    successCondition: result && result[0] >= 0.90
    failureCondition: result && result[0] < 0.50
    provider:
      prometheus:
        address: http://prometheus.example.com:9090
        query: ...
```
