### ISSUE TITLE
analysis template: webmetric "method"  and "body" field are not supported error in v1.1

### ISSUE THREAD

**Issue by sankhyan** [argoproj/argo-rollouts#1989]
## Summary 

Trying you use webmetric in analysis template but getting method" and "body" field are not supported error

taken reference from argo rollouts document : https://argoproj.github.io/argo-rollouts/analysis/web/

code:- 

```
metrics:
    - name: webmetric
      successCondition: "result.ok && result.successPercent >= 89"
      provider:
        web:
          method: POST # valid values are GET|POST|PUT, defaults to GET
          url: "some value"
          timeoutSeconds: 20 # defaults to 10 seconds
          headers:
            - key: Authorization
              value: "some value"
            - key: Content-Type # if body is a json, it is recommended to set the Content-Type
              value: "application/json"
          body: "{\"namespace\": \"\",\"host\": \"\",\"awsRegion\": \"\",\"analysisPhaseNumber\": \"\",\"newTrafficPercentage\": \"\"}"
          jsonPath: "{$.}"
```

## Diagnostics

What version of Argo Rollouts are you running?

V 1.1

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
