### ISSUE TITLE
Add AnalysisServiceGraph CRD

### ISSUE THREAD

**Issue by zachaller** [argoproj/argo-rollouts#2005]
# Summary

WIP: Very Rough Draft
```
Notes to self:
  * Look into just using multiple analysis on a rollout would need to fix issue with all args being sent to all templates
  * Also look into a a RolloutApplicationSet idea for rolling out multiple rollouts in unison
```

Add an AnalysisServiceGraph CRD that would allow a rollout to aggregate multiple AnalysisTemplates that then based on the dependencies defined in the AnalysisServiceGraph would rollback the current rollout if a service that depends on the currently deploying rollout has a failure in one of its analysis's or its own. This would be a rough example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: guestbook
spec:
...
  strategy:
    canary:
      analysis:
        templates:
        - templateName: service-graph-example
           analysisServiceGraph: true
        startingStep: 2
        args:
        - name: service-name
          value: guestbook-svc.default.svc.cluster.local
      steps:
      - setWeight: 20
      - pause: {duration: 10m}
      - setWeight: 40
      - pause: {duration: 10m}
      - setWeight: 60
      - pause: {duration: 10m}
      - setWeight: 80
      - pause: {duration: 10m}
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisServiceGraph
metadata:
  name: service-graph-example
spec:
  services:
  - name: service1
     templateRef: success-rate
     args:
        - name: service-name
           defaultValue: guestbook-svc-1.default.svc.cluster.local
     depends: 
      - "service2"
      - "service3"
  - name: service2
     templateRef: success-rate
     args:
        - name: service-name
           defaultValue: guestbook-svc-2.default.svc.cluster.local
  - name: service3
     templateRef: success-rate
     args:
        - name: service-name
           defaultValue: guestbook-svc-3.default.svc.cluster.local
  status:
    #Would contain a list of AnalysisRun resources and their status if successful or not per service
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 5m
    successCondition: result[0] >= 0.95
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus.example.com:9090
        query: |
          sum(irate(
            istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}",response_code!~"5.*"}[5m]
          )) /
          sum(irate(
            istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}"}[5m]
          ))
```

# Use Cases

Say we are rolling out Service1 and Service1 depends on Service2 and Service3 in our Service1 rollout object we have a background AnalysisServiceGraph that runs analysis queries for all the services defined within the AnalysisServiceGraph if during rollout Service2 or Service3 fail their analysis quires we would rollback Service1. We would ignore Service4 analysis run because it is not a dependency.

```mermaid
flowchart TD
   Service1 --> Service2
   Service1 --> Service3
   Service2 --> Service4
   Service3 --> Service4
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
