### ISSUE TITLE
The Rollout "rollout-ref-deployment" is invalid:  * spec.selector: Required value * spec.template: Required value

### ISSUE THREAD

**Issue by 871690991** [argoproj/argo-rollouts#2037]
## Summary 

What happened/what you expected to happen?

[](https://argoproj.github.io/argo-rollouts/migrating/#reference-deployment-from-rollout)

I made an error executing the command，  my command is  kubectl apply -f 1.yaml 

The Rollout "rollout-ref-deployment" is invalid: 
* spec.selector: Required value
* spec.template: Required value

<img width="991" alt="image" src="https://user-images.githubusercontent.com/35527325/168633861-898fa89f-c72d-45a5-a784-22ea8e7c0fd7.png">

```

1.yaml file content is：

apiVersion: argoproj.io/v1alpha1               # Create a rollout resource
kind: Rollout
metadata:
  name: rollout-ref-deployment
spec:
  replicas: 5
  workloadRef:                                 # Reference an existing Deployment using workloadRef field
    apiVersion: apps/v1
    kind: Deployment
    name: rollout-ref-deployment
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 10s}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: rollout-canary
  name: rollout-ref-deployment
spec:
  replicas: 0                                  # Scale down existing deployment
  selector:
    matchLabels:
      app: rollout-ref-deployment
  template:
    metadata:
      labels:
        app: rollout-ref-deployment
    spec:
      containers:
        - name: rollouts-demo
          image: argoproj/rollouts-demo:blue
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
```

## Diagnostics

What version of Argo Rollouts are you running?
newest version
