### ISSUE TITLE
Traefik trafficRouting in canary strategy doesn't work as expected

### ISSUE THREAD

**Issue by ayanhamza** [argoproj/argo-rollouts#2051]
## Summary 

I configured trafficRouting via TraefikService like in docs. But still not working. Traffic to my service not splited by weights. It's still working round-robin (default behaviour of traefik-service) 50% of traffic goes to stable, and 50 % to canary. But expected only 20% to canary that declared in first step of my Rollout strategy.
Below my yaml files:

```
strategy:
    canary:
      canaryService: colorapi-canary
      stableService: colorapi-stable
      trafficRouting:
        traefik:
          weightedTraefikServiceName: traefik-service
      steps:
      - setWeight: 20
      - pause: {duration: 1h}
      - setWeight: 50
      - pause: {duration: 1h}
```

```

apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: traefik-service
  namespace: devops-services
spec:
  weighted:
    services:
      - name: colorapi-stable # k8s service name that you need to create for stable application version
        port: 80
      - name: colorapi-canary # k8s service name that you need to create for new application version
        port: 80

```

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: colorapi
  namespace: devops-services
spec:
  entryPoints: []
  routes:
  - kind: Rule
    match: Host(`colorapi.test.example`) && PathPrefix(`/`)
    middlewares:
    - name: colorapi
      namespace: devops-services
    services:
    - kind: TraefikService
      name: traefik-service
      namespace: devops-service
```

My argo-rollout version is latest. v1.2.1

Logs from pod argo-rollouts when it's starts deploy new version:
```
time="2022-05-25T05:15:30Z" level=info msg="No TrafficRouting Reconcilers found" namespace=devops-services rollout=colorapi
time="2022-05-25T05:15:30Z" level=info msg="Reconciling canary pause step (stepIndex: 1/4)" namespace=devops-services rollout=colorapi
time="2022-05-25T05:15:30Z" level=info msg="Not finished reconciling Canary Pause" namespace=devops-services rollout=colorapi
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
