### ISSUE TITLE
Validation check does not take canary labels into consideration

### ISSUE THREAD

**Issue by gageorsburn** [argoproj/argo-rollouts#2090]
## Summary 

What happened/what you expected to happen?
Upon upgrading Argo Rollouts to the latest version v1.2.1 our rollouts stopped working with a validation error saying that the rollout was invalid.

```
type: InvalidSpec
  message: 'InvalidSpec: The Rollout "api" is invalid: spec.strategy.canary.stableService:
    Invalid value: "api": Service "api" has unmatch lable
    "role" in rollout'
```

The rollout previously worked before upgrading. Upon investigating what was going on myself I looked at the change log and found this pull request: https://github.com/argoproj/argo-rollouts/pull/1618/files. The change in this pull request does not take into account that the canary/stable labels get applied by the controller. 

## Diagnostics

What version of Argo Rollouts are you running?
v1.2.1

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
```
(Pasted above)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
Can you post your rollout and service yaml's, you need to make sure the labels that are pre applied there match aka if you have say an app label on the rollout and an app label on the service the values need to match.

**Comment by zachaller** [comment]
Ahh I understand more what you are talking about now let me double check that validation logic now that I understand what your doing.

**Comment by zachaller** [comment]
Ok so I just did a quick test with adding labels via the snippet below and did not run into any issue with validation, I would double check that all your services do not have a label of with a key of `role`. The validation check dose not care if there are extra labels as long as the key:value pairs match.

```
canaryMetadata:
        labels:
          role: canary
```

**Comment by gageorsburn** [comment]
@zachaller I may be misunderstanding, but wouldn't our service want `role: stable` to select the stable pods in canary? 

Vs our other service which has a `role: canary`? If we just specified `app: workflow-api` the service would select every workflow-api pod regardless of whether or not it was stable.

**Comment by zachaller** [comment]
Argo rollouts will properly add the pod template hashes to separate stable from canary

```
rollouts-pod-template-hash: 7d4948d5bd
```

**Comment by gageorsburn** [comment]
Ahhh okay I see. This probably could be more clear in the docs but I'll close this now. Thanks for your help!

**Comment by chenfli** [comment]
Hi,
I seem to have the same issue, I have removed the stable/canary metadata, for the exact reason.
It seems that I still get both canary and stable pods on the stable service.
For example I got
```rollouts-pod-template-hash: 75fd44f76b``` - on all stable pods

and

```rollouts-pod-template-hash: 75fd44f76b``` - on canary pod

@zachaller, any idea why the stable service still selects a canary pod

## canary-service
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-demo-preview
  namespace: rollout-ing
  labels:
    app: rollouts-demo-preview
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: rollouts-demo
  type: ClusterIP
```

## Stable service

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-demo
  namespace: rollout-ing
  labels:
    app: rollouts-demo
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: rollouts-demo
  type: ClusterIP
```


The full question with drawing is under [Q&A](https://github.com/argoproj/argo-rollouts/discussions/2227)

Thanks
Chen
