### ISSUE TITLE
Controller can't find smi resource

### ISSUE THREAD

**Issue by gasgurda** [argoproj/argo-rollouts#2125]
**Describe the bug**

rollout controller cant find resource trafficsplits.split.smi-spec.io

**To Reproduce**

1) Install  traefik-mesh https://doc.traefik.io/traefik-mesh/install/
2) Install service.yml
3) Install rollout.yml

**Expected behavior**

rollout controller must find resource trafficsplits.split.smi-spec.io

**Version**

v1.2.0, v1.2.1, latest, 1.1.1

**Logs**

```
time="2022-07-05T19:07:22Z" level=info msg="Found 1 TrafficRouting Reconcilers" namespace=default rollout=rollouts-demo
time="2022-07-05T19:07:22Z" level=info msg="Reconciling TrafficRouting with type 'SMI'" namespace=default rollout=rollouts-demo
time="2022-07-05T19:07:22Z" level=info msg="TrafficSplit `rollouts-demo` failed creation: the server could not find the requested resource (post trafficsplits.split.smi-spec.io)" event_reason=TrafficSplitNotCreated namespace=default rollout=rollouts-demo
time="2022-07-05T19:07:22Z" level=warning msg="the server could not find the requested resource (post trafficsplits.split.smi-spec.io)" event_reason=TrafficRoutingError namespace=default rollout=rollouts-demo
time="2022-07-05T19:07:22Z" level=error msg="roCtx.reconcile err the server could not find the requested resource (post trafficsplits.split.smi-spec.io)" generation=1 namespace=default resourceVersion=57248099 rollout=rollouts-demo
time="2022-07-05T19:07:22Z" level=info msg="Reconciliation completed" generation=1 namespace=default resourceVersion=57248099 rollout=rollouts-demo time_ms=15.849542000000001
time="2022-07-05T19:07:22Z" level=error msg="rollout syncHandler error: the server could not find the requested resource (post trafficsplits.split.smi-spec.io)" namespace=default rollout=rollouts-demo
time="2022-07-05T19:07:22Z" level=info msg="rollout syncHandler queue retries: 3 : key \"default/rollouts-demo\"" namespace=default rollout=rollouts-demo
E0705 19:07:22.558331       1 controller.go:174] the server could not find the requested resource (post trafficsplits.split.smi-spec.io)
time="2022-07-05T19:07:22Z" level=info msg="Event(v1.ObjectReference{Kind:\"Rollout\", Namespace:\"default\", Name:\"rollouts-demo\", UID:\"ffcbdff3-704d-463c-a613-1fdf72aad1ad\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"57248099\", FieldPath:\"\"}): type: 'Normal' reason: 'TrafficSplitNotCreated' TrafficSplit `rollouts-demo` failed creation: the server could not find the requested resource (post trafficsplits.split.smi-spec.io)"
time="2022-07-05T19:07:22Z" level=info msg="Event(v1.ObjectReference{Kind:\"Rollout\", Namespace:\"default\", Name:\"rollouts-demo\", UID:\"ffcbdff3-704d-463c-a613-1fdf72aad1ad\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"57248099\", FieldPath:\"\"}): type: 'Warning' reason: 'TrafficRoutingError' the server could not find the requested resource (post trafficsplits.split.smi-spec.io)"
```
**api-resources**
```
NAME                               SHORTNAMES         APIVERSION                             NAMESPACED   KIND
traffictargets                     tt                 access.smi-spec.io/v1alpha2            true         TrafficTarget
httproutegroups                    htr                specs.smi-spec.io/v1alpha3             true         HTTPRouteGroup
tcproutes                          tr                 specs.smi-spec.io/v1alpha3             true         TCPRoute
trafficsplits                      ts                 split.smi-spec.io/v1alpha3             true         TrafficSplit
```
**RBAC**
```
$ kubectl auth can-i create trafficsplits.split.smi-spec.io --as system:serviceaccount:argo-rollouts:argo-rollouts
yes
$ kubectl auth can-i get trafficsplits.split.smi-spec.io --as system:serviceaccount:argo-rollouts:argo-rollouts
yes
```
**services.yml**
```
apiVersion: v1
kind: Service
metadata:
  name: rollouts-demo-canary
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: rollouts-demo
---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-demo-stable
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: rollouts-demo
```
**rollout.yml**
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  replicas: 1
  strategy:
    canary:
      canaryService: rollouts-demo-canary
      stableService: rollouts-demo-stable
      trafficRouting:
        smi: {}
      steps:
      - setWeight: 5
      - pause: {}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
