### ISSUE TITLE
When defining an analysis with multiple items, when one item fails, others are aborted but marked as successful.

### ISSUE THREAD

**Issue by marcportabellaclotet-mt** [argoproj/argo-rollouts#2158]
Checklist:

* [x ] I've included steps to reproduce the bug.
* [x ] I've included the version of argo rollouts.

**Describe the bug**

When defining an analysis with multiple items, when one item fails, others are aborted but marked as successful.
**To Reproduce**
Create an analysis template like this:
```
kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: sleep-and-fail
spec:
  metrics:
  - name: sleep-and-fail
    count: 1
    interval: 5s
    failureLimit: 0
    provider:
      job:
        spec:
          ttlSecondsAfterFinished: 60
          template:
            spec:
              containers:
              - name: sleep
                image: alpine:3.8
                command: [sh, -c]
                args: [sleep 10 && exit 1]
              restartPolicy: Never
          backoffLimit: 0
  - name: webmetric
    successCondition: result == "3.3.3.3"
    provider:
      web:
        url: "http://ip.jsontest.com/"
        timeoutSeconds: 20 # defaults to 10 seconds
        headers:
          - key: Authorization
            value: "Bearer lol"
        jsonPath: "{$.ip}"
``` 
create a rollout pointing to the above analysis:
```
  strategy:
    canary:
      canaryService: service-canary
      stableService: service
      canaryMetadata:
        labels:
          deployment: canary
      stableMetadata:
        labels:
          deployment: stable
      steps:
      - setWeight: 0
      - setCanaryScale:
          weight: 100
      - analysis:
          templates:
          - templateName: sleep-and-fail
```

**Expected behavior**

The expected behavior is that the "sleep-and-fail" item in the analysis is not marked as successful.
It could be marked as "aborted" or a similar naming.
It would be great to add a conditional spec to force items to complete, similar to the spec requiredForCompletion in experiments.

**Screenshots**

![image](https://user-images.githubusercontent.com/56038098/180644509-cc8c52a3-c40c-4321-9393-30a2367551a1.png)

**Version**

v1.2.1
**Logs**

```
# Paste the logs from the rollout controller
```
time="2022-07-24T11:19:19Z" level=info msg="Metric Assessment Result - Failed: failed (1) > failureLimit (0)" metric=webmetric
time="2022-07-24T11:19:19Z" level=info msg="Metric 'webmetric' transitioned from Running -> Failed" analysisrun=rollouts-demo-bg-54d9c868cc-13-2.2 metric=webmetric namespace=rollouts-demo-gb
time="2022-07-24T11:19:19Z" level=info msg="subsFromAnnotations: map[rollout.argoproj.io/revision:13]" analysisrun=rollouts-demo-bg-54d9c868cc-13-2.2 namespace=rollouts-demo-gb
time="2022-07-24T11:19:19Z" level=warning msg="Metric 'webmetric' Completed. Result: Failed" analysisrun=rollouts-demo-bg-54d9c868cc-13-2.2 event_reason=MetricFailed namespace=rollouts-demo-gb
time="2022-07-24T11:19:19Z" level=info msg="Event(v1.ObjectReference{Kind:\"AnalysisRun\", Namespace:\"rollouts-demo-gb\", Name:\"rollouts-demo-bg-54d9c868cc-13-2.2\", UID:\"9cb698d7-bb65-4726-98fe-8fed046e07e3\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"147211593\", FieldPath:\"\"}): type: 'Warning' reason: 'MetricFailed' Metric 'webmetric' Completed. Result: Failed"
time="2022-07-24T11:19:19Z" level=info msg="Patch status successfully" analysisrun=rollouts-demo-bg-54d9c868cc-13-2.2 namespace=rollouts-demo-gb
time="2022-07-24T11:19:19Z" level=info msg="Reconciliation completed" analysisrun=rollouts-demo-bg-54d9c868cc-13-2.2 namespace=rollouts-demo-gb time_ms=296.13838300000003
time="2022-07-24T11:19:19Z" level=info msg="Started syncing Analysis at (2022-07-24 11:19:19.096026315 +0000 UTC m=+311030.494992018)" analysisrun=rollouts-demo-bg-54d9c868cc-13-2.2 namespace=rollouts-demo-gb
time="2022-07-24T11:19:19Z" level=info msg="Resuming in-progress measurement" analysisrun=rollouts-demo-bg-54d9c868cc-13-2.2 metric=sleep-and-fail namespace=rollouts-demo-gb
time="2022-07-24T11:19:19Z" level=info msg="Taking 1 Measurement(s)..." analysisrun=rollouts-demo-bg-54d9c868cc-13-2.2 namespace=rollouts-demo-gb
time="2022-07-24T11:19:19Z" level=info msg="Terminating in-progress measurement" analysisrun=rollouts-demo-bg-54d9c868cc-13-2.2 metric=sleep-and-fail namespace=rollouts-demo-gb
time="2022-07-24T11:19:19Z" level=info msg="Enqueueing parent of rollouts-demo-gb/rollouts-demo-bg-54d9c868cc-13-2.2: Rollout rollouts-demo-gb/rollouts-demo-bg"
time="2022-07-24T11:19:19Z" level=info msg="Started syncing rollout" generation=19 namespace=rollouts-demo-gb resourceVersion=147211594 rollout=rollouts-demo-bg
time="2022-07-24T11:19:19Z" level=info msg="Found 1 TrafficRouting Reconcilers" namespace=rollouts-demo-gb rollout=rollouts-demo-bg
time="2022-07-24T11:19:19Z" level=info msg="Reconciling TrafficRouting with type 'Nginx'" namespace=rollouts-demo-gb rollout=rollouts-demo-bg
time="2022-07-24T11:19:19Z" level=info msg="No changes to canary ingress - skipping patch" ingress=rollouts-demo-bg-rollouts-demo-bg-canary namespace=rollouts-demo-gb rollout=rollouts-demo-bg
time="2022-07-24T11:19:19Z" level=info msg="Reconciling analysis step (stepIndex: 2)" namespace=rollouts-demo-gb rollout=rollouts-demo-bg
time="2022-07-24T11:19:19Z" level=info msg="subsFromAnnotations: map[kubectl.kubernetes.io/last-applied-configuration:{\"apiVersion\":\"argoproj.io/v1alpha1\",\"kind\":\"Rollout\",\"metadata\":{\"annotations\":{},\"labels\":{\"app.kubernetes.io/instance\":\"rollouts-demo-bg\",\"app.kubernetes.io/managed-by\":\"Helm\",\"app.kubernetes.io/name\":\"rollouts-demo-bg\",\"argocd.argoproj.io/instance\":\"rollouts-demo-bg\",\"helm.sh/chart\":\"rollouts-demo-bg-v1.0.0\"},\"name\":\"rollouts-demo-bg\",\"namespace\":\"rollouts-demo-gb\"},\"spec\":{\"analysis\":{\"successfulRunHistoryLimit\":2,\"unsuccessfulRunHistoryLimit\":2},\"replicas\":2,\"revisionHistoryLimit\":3,\"selector\":{\"matchLabels\":{\"app.kubernetes.io/instance\":\"rollouts-demo-bg\",\"app.kubernetes.io/name\":\"rollouts-demo-bg\"}},\"strategy\":{\"canary\":{\"canaryMetadata\":{\"labels\":{\"deployment\":\"canary\"}},\"canaryService\":\"rollouts-demo-bg-canary\",\"stableMetadata\":{\"labels\":{\"deployment\":\"stable\"}},\"stableService\":\"rollouts-demo-bg\",\"steps\":[{\"setWeight\":0},{\"setCanaryScale\":{\"weight\":100}},{\"analysis\":{\"templates\":[{\"templateName\":\"sleep-and-fail\"}]}},{\"pause\":{}},{\"setWeight\":100}],\"trafficRouting\":{\"nginx\":{\"additionalIngressAnnotations\":{\"canary-by-header\":\"X-Canary\",\"canary-by-header-value\":\"iwantsit\"},\"stableIngress\":\"rollouts-demo-bg\"}}}},\"template\":{\"metadata\":{\"annotations\":{\"checksum/config\":\"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\",\"image/digest\":\"none\"},\"labels\":{\"app.kubernetes.io/instance\":\"rollouts-demo-bg\",\"app.kubernetes.io/name\":\"rollouts-demo-bg\"}},\"spec\":{\"containers\":[{\"env\":null,\"image\":\"argoproj/rollouts-demo:purple\",\"imagePullPolicy\":\"IfNotPresent\",\"livenessProbe\":{\"failureThreshold\":6,\"initialDelaySeconds\":5,\"periodSeconds\":30,\"tcpSocket\":{\"port\":8080}},\"name\":\"rollouts-demo-bg\",\"ports\":[{\"containerPort\":80,\"name\":\"http\",\"protocol\":\"TCP\"}],\"readinessProbe\":{\"failureThreshold\":6,\"initialDelaySeconds\":5,\"periodSeconds\":30,\"tcpSocket\":{\"port\":8080}},\"resources\":{}}]}}}}\n rollout.argoproj.io/revision:13]" namespace=rollouts-demo-gb rollout=rollouts-demo-bg
time="2022-07-24T11:19:19Z" level=info msg="Step Analysis Run 'rollouts-demo-bg-54d9c868cc-13-2.2' Status New: 'Running' Previous: ''" event_reason=AnalysisRunRunning namespace=rollouts-demo-gb rollout=rollouts-demo-bg
time="2022-07-24T11:19:19Z" level=info msg="Event(v1.ObjectReference{Kind:\"Rollout\", Namespace:\"rollouts-demo-gb\", Name:\"rollouts-demo-bg\", UID:\"070d39fc-d3fa-45a2-92b0-9bffd302761a\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"147211594\", FieldPath:\"\"}): type: 'Normal' reason: 'AnalysisRunRunning' Step Analysis Run 'rollouts-demo-bg-54d9c868cc-13-2.2' Status New: 'Running' Previous: ''"
time="2022-07-24T11:19:19Z" level=info msg="Patched: {\"status\":{\"canary\":{\"currentStepAnalysisRunStatus\":{\"status\":\"Running\"}}}}" generation=19 namespace=rollouts-demo-gb resourceVersion=147211594 rollout=rollouts-demo-bg

```


---
<!-- Issue Author: Don't delete this message to encourage other users to support your issue! -->
**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
