### ISSUE TITLE
Allow creating analysis job in a different namespace than the analysis run

### ISSUE THREAD

**Issue by jlevesy** [argoproj/argo-rollouts#2241]
# Summary

I don't know if it's a bug or a feature, but here I go 😅 

It looks like that the [JobMetric](https://github.com/argoproj/argo-rollouts/blob/4848fb12833e6e14ff9a2d8c783d5be04960d303/pkg/apis/rollouts/v1alpha1/analysis_types.go#L225) carries a metadata object and  especially a namespace attribute.

Which makes me think that if I write something like this, the analysis job would actually be created in the different namespace than the analysis run:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisRun
metadata:
  name: some-job-run
  namespace: some-namespace
spec:
  metrics:
    - name: some-job-run
      provider:
        job:
          metadata:
            namespace: another-namespace # <-here
          spec:
            # awesome job.
```

But it seems to be ignored, and your CRD disallows it. 

The patch doesn't look complicated from where I stand, we [would need to do something like this here](https://github.com/argoproj/argo-rollouts/blob/4848fb12833e6e14ff9a2d8c783d5be04960d303/metricproviders/job/job.go#L82):

```golang 
namespace :=  metric.Provider.Job.Metadata.Namespace

if namespace == "" {
      namespace = run.Namespace
}
```

But this probably has some more impacts? 

The only thing I see is that It breaks the ownership reference between the analysis run on the job, [as it is not cross namespace](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/#owner-references-in-object-specifications).  That might be a sufficient reason to deny this feature request 🥲.

But If you wish, I would be happy to make the patch, just give me the green light!

Anyway, thanks and keep up the good work folks!

# Use Cases

We are using a jobMetric to run a shared test suite during a rollout on our platform against our apps instances running in separate namespaces. And this test suite requires certain namespace scoped resources (configmaps, secrets) to run properly. 

It would be nice if we could run this test suite in a namespace where those resources are already defined, and not have to replicate them across each a every namespace where we need to run this test suite.  

I don't know if this is super relevant  😅

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
