### ISSUE TITLE
rollouts lint throws nil pointer in 1.3.0 when there's a kong ingress specified

### ISSUE THREAD

**Issue by zidad** [argoproj/argo-rollouts#2248]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've inclued the version of argo rollouts.

When I update to the latest version of argo-rollouts the linting feature fails for me when there's a kong ingress specified with the following error (both on MacOS and Ubuntu):

panic: runtime error: invalid memory address or nil pointer dereference

**Describe the bug**

**To Reproduce**

run ```kubectl argo rollouts lint -f deployment.yaml```

on this file for example:

``` YAML
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: my-service
  name: my-service-6t6g87d9g8
  namespace: my-namespace
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    konghq.com/plugins: plugin-my-service-path-prefix
  labels:
    app: my-service
  name: my-service
  namespace: my-namespace
spec:
  ports:
  - name: web
    nodePort: null
    port: 80
    protocol: TCP
    targetPort: web
  selector:
    app: my-service
  type: ClusterIP
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    build: 2022.09.15.6
    cluster: TESTW
    notifications.argoproj.io/my-namespace.on-rollout-aborted.bot: ""
    notifications.argoproj.io/my-namespace.on-rollout-completed.bot: ""
    notifications.argoproj.io/my-namespace.on-rollout-step-completed.bot: ""
    notifications.argoproj.io/my-namespace.on-rollout-updated.bot: ""
    platforms: videoland
    releaseNotes: none
    releasedBy: xx@xx.com
  labels:
    app: my-service
  name: my-service
  namespace: my-namespace
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: my-service
  strategy:
    canary:
      analysis:
        args:
        - name: service
          value: my-service
        - name: namespace
          value: my-namespace
        - name: build
          value: 2022.09.15.6
        startingStep: 1
        templates:
        - templateName: build-low-error-low-latency
        - templateName: service-slo-99-5
      steps:
      - setWeight: 100
      - pause:
          duration: 5m
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: my-service
        build: 2022.09.15.6
    spec:
      containers:
      - env:
        envFrom:
        - configMapRef:
            name: my-service-6t6g87d9g8
        image: prodacrfreemiumwecai.azurecr.io/my-namespace/my-service:2022.09.15.6
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 5
        name: my-service
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        - containerPort: 5005
          name: grpc
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 0.3
            memory: 1000Mi
          requests:
            cpu: 0.05
            memory: 500Mi
      dnsConfig:
        options:
        - name: single-request-reopen
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: my-service
  name: ingress-my-service-validate
  namespace: my-namespace
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - backend:
          service:
            name: my-service
            port:
              number: 80
        path: /my-namespace/my-service
        pathType: ImplementationSpecific


```

**Expected behavior**

Not throw an error

**Screenshots**

**Version**

**Logs**

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x26b4051]

goroutine 1 [running]:
github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/lint.setIngressManagedAnnotation({0xc0002f7800?, 0x1, 0xc227d00?}, {{0x0, 0x0, 0x0}, {0xc00004e600, 0x9, 0x10}, {0xc00000c618, ...}, ...})
	/go/src/github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/lint/lint.go:264 +0xd1
github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/lint.(*LintOptions).lintResource(0x0?, {0x7ff7bfeffae5?, 0x0?})
	/go/src/github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/lint/lint.go:119 +0x7b0
github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/lint.NewCmdLint.func1(0xc000118a00?, {0xc00048d740?, 0x2?, 0x2?})
	/go/src/github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/lint/lint.go:56 +0x37
github.com/spf13/cobra.(*Command).execute(0xc000118a00, {0xc00048d720, 0x2, 0x2})
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004f9900)
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
	/go/src/github.com/argoproj/argo-rollouts/cmd/kubectl-argo-rollouts/main.go:21 +0x9a

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
