### ISSUE TITLE
Not configuring proper ServiceAccount on pods

### ISSUE THREAD

**Issue by sang-w0o** [argoproj/argo-rollouts#2254]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've inclued the version of argo rollouts.

**Describe the bug**

We can define ServiceAccount on `spec.template.spec.serviceAccountName` in Rollout yaml file.
But the pods created by this Rollout uses default ServiceAccount, not using the ServiceAccount that I have configured.
The Kubernetes Deployment works just fine using the same `spec.template.spec.serviceAccountName`.

**To Reproduce**

**Expected behavior**

Pods should be ran using the given ServiceAccount.

Below is my yaml file for Rollout.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: planit-deployment
  namespace: planit
  labels:
    app: planit
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: planit
  template:
    metadata:
      labels:
        app: planit
    spec:
      serviceAccount: datadog-agent-cluster-agent # this ServiceAccount should be applied to pods.
      automountServiceAccountToken: false
      containers:
        - name: MY_NAME
          image: MY_IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 1
              memory: 4096Mi
            requests:
              cpu: 1
              memory: 4096Mi
        - name: datadog-agent
          image: datadog/agent:latest
          ports:
            - containerPort: 8126
              name: traceport
              protocol: TCP
          env:
            # omitted
  strategy:
    blueGreen:
      activeService: planit-service
      previewService: planit-service-preview
      autoPromotionEnabled: true
```

And as below, serviceAccount of pod is default.

<img width="663" alt="image" src="https://user-images.githubusercontent.com/48438083/191273617-9cf4655e-b73f-4f74-b904-30cf18d3c980.png">

**Version**

```
kubectl-argo-rollouts: v1.2.2+22aff27
  BuildDate: 2022-07-26T17:26:38Z
  GitCommit: 22aff273bf95646e0cd02555fbe7d2da0f903316
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: darwin/amd64
```

1.3.0

**Logs**

- No errors were found on logs.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
