### ISSUE TITLE
grpc versions of traffic routers and metric providers

### ISSUE THREAD

**Issue by zachaller** [argoproj/argo-rollouts#2262]
# Summary

Add a traffic router and metric provider grpc implementations.

# Use Cases

This would allow implementations of both traffic routers and metric providers to live outside of the argo rollouts repo. 

The use cases being custom implementations to still leverage argo rollouts. We have uses cases currently where rollouts is managing an istio virtual service that another internal controller then leverages the configuration of the virtual service to configure an internal traffic router like service. If there was a grpc implementation of the traffic router interface we could cut out the watching of the istio virtual service.

 It would also be beneficial to support running both at the same time where argo rollouts would manage istio traffic router normally but also send request to the grpc service this could be used for various type of audits and other internal tracking.

It would also allow metric providers to live outside of the rollouts codebase.

Metric provider spec idea:
```yaml
kind: ClusterAnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: always-pass
spec:
  metrics:
    - name: pass
      interval: 5s
      failureLimit: 1
      provider:
        grpc:
          address: <grpc_address>
          metaData: # This would be converted to json and sent over grpc as a []byte or string
            customName1: customValue1
            customName2: {{args.service-name}}
            customName3:
              nestedCustomName1: customValue2
              nestedCustomName2: customValue3
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
