### ISSUE TITLE
Suport jsonBody for web metric provider

### ISSUE THREAD

**Issue by zachaller** [argoproj/argo-rollouts#2275]
# Summary

Add support to web metric provider to make posting json easier. We would do this by adding a new field called `jsonBody`.

Today in order to post json to a web metric provider to POST data you end up with a metric configuration like this
```
metrics:
  - name: webmetric
    successCondition: result == true
    provider:
      web:
        method: POST # valid values are GET|POST|PUT, defaults to GET
        url: "http://my-server.com/api/v1/measurement?service={{ args.service-name }}"
        timeoutSeconds: 20 # defaults to 10 seconds
        headers:
          - key: Authorization
            value: "Bearer {{ args.api-token }}"
          - key: Content-Type # if body is a json, it is recommended to set the Content-Type
            value: "application/json"
        body: "{\"key\": \"string value\"}"
        jsonPath: "{$.data.ok}"
```

The body field being just a string that gets posted as the body in the http request.

I propose to add something like `jsonBody` which would make constructing json payloads cleaner

```
metrics:
  - name: webmetric
    successCondition: result == true
    provider:
      web:
        method: POST # valid values are GET|POST|PUT, defaults to GET
        url: "http://my-server.com/api/v1/measurement?service={{ args.service-name }}"
        timeoutSeconds: 20 # defaults to 10 seconds
        headers:
          - key: Authorization
            value: "Bearer {{ args.api-token }}"
          - key: Content-Type # if body is a json, it is recommended to set the Content-Type
            value: "application/json"
        jsonBody:  # If using jsonBody we could also auto set Content-Type headers
          key1: value_1
          key2:
            nestedObj: nested value
            key3: {{ args.api-token }}
        jsonPath: "{$.data.ok}"
```

I am not sure if today we support parsing templated args into body or not but it would be very valuable to do that if we do not as well.

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
