### ISSUE TITLE
How can I debug if the value in setWeight is different from actualWeight

### ISSUE THREAD

**Issue by kaikiat** [argoproj/argo-rollouts#2281]
**Describe the bug**
The setWeight is different from actualWeight.

**To Reproduce**
This is my rollout yaml 
```
 strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      maxSurge: "25%" # The maximum number of replicas the rollout can create 
      maxUnavailable: 0 # The maximum number of pods that can be unavailable during the update.
      analysis:
        templates:
        - templateName: analyse-request
        args:
          - name: service-name
            value: prometheus-kube-prometheus-prometheus.default.svc.cluster.local
        startingStep: 1
      steps:
      - setWeight: 70
      - pause:
          duration: 180s
      - setWeight: 95
      - pause: 
          duration: 180s
```
**Expected behavior**
Expects setWeight to be the same as actualWeight. But actualWeight is always 50%

**Screenshots**

<img width="340" alt="Screenshot 2022-10-02 at 10 35 45 PM" src="https://user-images.githubusercontent.com/32543853/193459726-3d04332c-a27e-4fef-a7fc-ccc4462db8ea.png">

**Version**
Latest 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
