### ISSUE TITLE
Prometheus metrics should support self-signed certs. 

### ISSUE THREAD

**Issue by todaywasawesome** [argoproj/argo-rollouts#2298]
Many metrics providers that are locally hosted on the same Kubernetes cluster use internal, self-signed certs. This can throw errors when trying to use the available https endpoints. We should add support for self-signed certs. 

https://github.com/argoproj/argo-rollouts/blob/4d8fbd151e10bb7c08fe6a573f65857cb91ec330/metricproviders/prometheus/prometheus.go#L146-L173

**Comment by dratler** [comment]
Hi @todaywasawesome ,
Is this still open for the grab ?

**Comment by dratler** [comment]
Also I think using self sign certificate will be good for local only unless some 3rd party can use it for wrong

**Comment by christianh814** [comment]
I imagine the spec could look like this (Similar to the Web provider)

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testing
spec:
  args:
  - name: service-name
  - api-token
  - ca-cert
  metrics:
  - name: success-rate
    interval: 5m
    successCondition: len(result) == 0 || result[0] >= 0.95
    failureLimit: 3
    provider:
      prometheus:
        address: https://prometheus.example.com:9090
        caCert: "{{ args.ca-cert }}"
        headers: 
          - key: Authorization
            value: "Bearer {{ args.api-token }}"
        query: sum(irate(istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}",response_code!~"5.*"}[5m]))
```
