### ISSUE TITLE
Argo does not change the service tag to the old version after the Rollout canary is interrupted

### ISSUE THREAD

**Issue by hyt05** [argoproj/argo-rollouts#2316]
When I publish a grayscale version normally, argo will modify the selector value of the service, and when I click interrupt, argo does not modify the selector value of the old version, or is there any alternative?

There is a stable service called rollout-stable and a preview service called rollout-canary, argo added tags to both services after the first release
```
kubectl get svc -n hub rollout-stable -ojson|jq .spec.selector
{
  "app": "rollout-canary",
  "rollouts-pod-template-hash": "77895dd98c"
}
kubectl get svc -n hub rollout-canary -ojson|jq .spec.selector
{
  "app": "rollout-canary",
  "rollouts-pod-template-hash": "77895dd98c"
}
```
When I do a canary release it works fine now
```
kubectl get svc -n hub rollout-canary -ojson|jq .spec.selector
{
  "app": "rollout-canary",
  "rollouts-pod-template-hash": "7b7659586c"
}
```

After clicking abort
![image](https://user-images.githubusercontent.com/48778924/195310174-65fd1b27-a9cf-4502-9b99-e243c483d7b6.png)

Shouldn't rollouts-pod-template-hash value be modified to stable version 77895dd98c after abort?
```
kubectl get svc -n hub rollout-canary -ojson|jq .spec.selector
{
  "app": "rollout-canary",
  "rollouts-pod-template-hash": "7b7659586c"
}
```

Rollout configuration file
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-canary
spec:
  replicas: 4
  revisionHistoryLimit: 6
  selector:
    matchLabels:
      app: rollout-canary
  template:
    metadata:
      labels:
        app: rollout-canary
    spec:
      containers:
      - name: rollout-canary
        ## Available tags are red, green, blue, yellow
        image: 192.168.101.30/test/nginx:yellow
        #image: 192.168.101.30/test/nginx:yellow
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
  strategy:
    canary:
      canaryService: rollout-canary
      stableService: rollout-stable
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 100
---
kind: Service
apiVersion: v1
metadata:
  name: rollout-stable
spec:
  selector:
    app: rollout-canary
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: rollout-canary
spec:
  selector:
    app: rollout-canary
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
```
