### ISSUE TITLE
Wavefront as a Metric Provider

### ISSUE THREAD

**Issue by dthomson25** [argoproj/argo-rollouts#237]
In addition to Prometheus, there are requests to add [Wavefront](https://wavefront.com) as a metric provider. This might look something like:
```
metrics:
- name: my-webhook
   successCondition: result > 9
   provider:
     wavefront:
       url: http://wavefront.example.com
       query: "avg(ts(my.important.metric, pod=example-pod-abc123-ab12))
```

One open question for the wavefront integration is how the controller will get access to the API key required to communicate with Wavefront. Should the user provide a secret in the same namespace as the Rollout or should the controller have a secret with the key that is leveraged for all Wavefront calls? I'm leaning towards the 2nd approach at the moment.

As required for any metric provider integration, the implementation will need to implement all the methods of the [Provider Interface](https://github.com/argoproj/argo-rollouts/blob/master/metricproviders/metricproviders.go#L16-L26) and add the wavefront fields to the AnalysisRun structure in [analysis_type.go](https://github.com/argoproj/argo-rollouts/blob/master/pkg/apis/rollouts/v1alpha1/analysis_types.go#L87)
