### ISSUE TITLE
ExperimentStep specRef does not support preview use case

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#240]
I was trying to come up with an example where an experiment could be used as part of a rollout step, to support a preview/staging replicaset. The requirement is that a preview replicaset should be able to run in the production namespace, but without receiving any traffic (because it does not have the same selector labels).

```yaml
  strategy:
    canary:
      steps:
      - experiment:
          duration: 30
          templates:
          - name: preview
            specRef: canary
```

The problem with the above example, is that `specRef: canary` causes the selector labels from the canary pod template spec to be carried forward. This means that it also includes labels like `app: guestbook` from the pod template, which means that traffic will be directed to the preview -- the opposite of what I'm trying to achieve.

While specRef works well in addressing the baseline vs. canary for mann-whitney analysis, it does not work well for the preview pod use case. We need to come up with syntax which allows for a canary replicaset to be brought up, but with a different set of selectors.
