### ISSUE TITLE
Strange behavior with setMirrorRoute logic

### ISSUE THREAD

**Issue by igimot** [argoproj/argo-rollouts#2463]
### Discussed in https://github.com/argoproj/argo-rollouts/discussions/2462

<div type='discussions-op-text'>

<sup>Originally posted by **igimot** December  8, 2022</sup>
Argo-rollout does not change istio config when we use setMirrorRoute logic. Our infrastructure is built as gitops with argo-cd. 
What is visible in the istio service, the argo-rollout adds changes, but these changes are immediately returned. It can be seen in the video below.

Argo-cd: v2.3.5
Argo-rollout: v1.3.1

istio-application config
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-virtualservices
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "+1"
spec:
  ignoreDifferences:
  - group: networking.istio.io
    name: rollouts-demo-app-virtualservice
    namespace: billing
    kind: VirtualService
    jsonPointers:
    - /spec/http/*
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: devops
  source:
    directory:
      recurse: true
    path: main/infrastructure/istio-virtualservices/
    repoURL: git@gitlab.dev:devops/argocd-meta.git
    targetRevision: master
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    automated:
      prune: false
      selfHeal: true
```
rollouts-demo-app
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollouts-demo-app
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-health-degraded.slack: "test-rolllouts-notifications"
    notifications.argoproj.io/subscribe.on-sync-failed.slack: "test-rolllouts-notifications"
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: "test-rolllouts-notifications"
spec:
  project: evopay
  revisionHistoryLimit: 2
  ignoreDifferences:
  source:
    repoURL: git@gitlab.dev:helm/rollouts-demo-app.git
    targetRevision: master
    path: ./
    helm:
      valueFiles:
      - values/development-01.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
```
rollouts-demo-app-virtualservice
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rollouts-demo-app-virtualservice
  namespace: billing
spec:
  hosts:
  - "rollouts-demo-app.dev.com"
  gateways:
  - istio-system/ep-main-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: rollouts-demo-app.main.svc.cluster.local
      weight: 100
    - destination:
        host: rollouts-demo-app-canary.main.svc.cluster.local
      weight: 0
```
demo-app
```
canary:
      canaryService: rollouts-demo-app-canary
      stableService: rollouts-demo-app
      trafficRouting:
        managedRoutes:
          - name: "rollouts-demo-app-route-by-header"
        istio:
          virtualService: 
            name: "rollouts-demo-app-virtualservice"
      steps:
      - setCanaryScale:
          replicas: 1
      - setMirrorRoute:
          name: "rollouts-demo-app-route-by-header"
          percentage: 100
          match:
            - headers:
                whoareyou:
                  exact: "new-canary-pod"
      - pause: {}
```
![argo-rollout](https://user-images.githubusercontent.com/19408161/206398078-20cc1949-0184-43a0-91cd-ca2b78841925.gif)
</div>
