### ISSUE TITLE
Provide a way to allow analyses to complete the experiment 

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#248]
Currently Experiments either run forever, or complete after a specified duration. A new mode should be that a user can decide that an Experiment should run until one or more analyses complete.

We will probably need a way to mark individual analyses as required for completion. e.g.:

```yaml
spec:
  analyses:
  # success-rate is background analysis that we want running until experiment completes
  - name: success-rate
    templateName: success-rate

  # test1 and test2 are tests which we want to complete and terminate the experiment after
  - name: test1
    templateName: test1
    requiredForCompletion: true
  - name: test2
    templateName: test2
    requiredForCompletion: true
```
