### ISSUE TITLE
[Blue-Green] Delay in service selector update causes incorrect analisys

### ISSUE THREAD

**Issue by nestorsokil** [argoproj/argo-rollouts#2488]
**Describe the bug**

I'm using this basic blue-green strategy on EKS:
```yaml
strategy:
    blueGreen:
      activeService: {{ template "app.name" . }}-{{ .Values.stack }}-active
      previewService: {{ template "app.name" . }}-{{ .Values.stack }}-preview
      scaleDownDelaySeconds: 900
      scaleDownDelayRevisionLimit: 1
      maxUnavailable: 25%
      autoPromotionEnabled: true
      prePromotionAnalysis:
        templates:
          - templateName: {{ template "app.name" . }}-{{ .Values.stack }}-smoke-tests
```

Here `previewService` is a regular `ClusterIP` service.

The problem is that due to delays with service labels propagation and endpoint update the job running as part of prePromotionAnalysis is picking up the currently active and stable pods via the `previewService`. 

The very same problem was described here https://argoproj.github.io/argo-rollouts/features/bluegreen/#overview with regards to the next step when the new revision is promoted but the controller should keep the old revision around in case there are some stranded requests. 

So I was looking for a way to maybe add a similar couple of seconds delay before running the test. This seems like a rather noticeable issue so was kind of surprised that I wasn't able to find similar issues here.

**To Reproduce**

- Use the B-G strategy from above
- Use AnalysisTemplate with `provider: job` to make requests to the previewService
- SOMETIMES because of the random delay and scheduling on the kube nodes the request might end up being served by the stable revision instead of the preview.

**Expected behavior**

The expectation is as follows: 
- deploy a new revision
- run smoke tests against the `previewService` which points to newly created RS with `prePromotionAnalysis` (provider: job in my case)
- promote new revision

**Screenshots**

**Version**

v1.2.0

**Logs**

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
