### ISSUE TITLE
Canary rollouts fail to complete with Istio when using TLS matching in VirtualService

### ISSUE THREAD

**Issue by benwaffle** [argoproj/argo-rollouts#2501]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've included the version of argo rollouts.

**Describe the bug**

Doing a canary rollouts, while using Istio for traffic shifting, with a VirtualService that uses `spec.tls` instead of `spec.http`, fails to fully complete.

**To Reproduce**

1. Run argo rollouts 1.3.1 and istio (1.14.3)
1. Create a VirtualService using `spec.tls` for routing instead of `spec.http`
1. Do a canary deploy
1. See that canary rollout never completes

**Expected behavior**

Rollouts should not get stuck.

**Version**

We had just upgraded Argo Rollouts from 1.2.0 to 1.3.1

**Logs**

We saw the rollout proceed and the weight fully switch traffic to the canary, but not back to the main set of pods:
```yaml
      route:
      - destination:
          host: proxy
          subset: live
        weight: 0
      - destination:
          host: proxy
          subset: canary
        weight: 100
```

Argo logs:
```
argo-rollouts-75b4b796dc-cmdrp argo-rollouts time="2022-12-12T18:58:56Z" level=info msg="Found 1 TrafficRouting Reconcilers" namespace=proxy rollout=proxy-live
argo-rollouts-75b4b796dc-cmdrp argo-rollouts time="2022-12-12T18:58:56Z" level=info msg="Reconciling TrafficRouting with type 'Istio'" namespace=proxy rollout=proxy-live
argo-rollouts-75b4b796dc-cmdrp argo-rollouts time="2022-12-12T18:58:56Z" level=error msg="roCtx.reconcile err [RemoveManagedRoutes] spec.http not found: %!w(<nil>)" generation=39 namespace=proxy resourceVersion=59512495 rollout=proxy-live
argo-rollouts-75b4b796dc-cmdrp argo-rollouts time="2022-12-12T18:58:56Z" level=info msg="Reconciliation completed" generation=39 namespace=proxy resourceVersion=59512495 rollout=proxy-live time_ms=2.210657
argo-rollouts-75b4b796dc-cmdrp argo-rollouts time="2022-12-12T18:58:56Z" level=error msg="rollout syncHandler error: [RemoveManagedRoutes] spec.http not found: %!w(<nil>)" namespace=proxy rollout=proxy-live
```

Our VirtualService yaml is below:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app: proxy
  name: proxy-rollout-live
spec:
  gateways:
  - proxy
  hosts:
  - '*'
  tls:
  - match:
    - port: 443
      sniHosts:
      - '*'
    route:
    - destination:
        host: proxy
        subset: live
      weight: 100
    - destination:
        host: proxy
        subset: canary
      weight: 0
```

 Notice how we use `spec.tls` instead of `spec.http`. PR #2074 adds the new RemoveManagedRoutes code that only handles `spec.http`.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
