### ISSUE TITLE
Rollouts stuck - Nginx canary ingress is not created

### ISSUE THREAD

**Issue by dhruvang1** [argoproj/argo-rollouts#2524]
Checklist:

* [✓] I've included steps to reproduce the bug.
* [✓] I've inclued the version of argo rollouts.

**Describe the bug**

I want to enable Rollouts traffic management using Nginx as below. All of the required components i.e. Stable Ingress, Stable Service, Canary Ingress are declared. When the canary is updated from `{}` to use `trafficRouting`, Rollouts doesn't create the canary Ingress and ArgoCD is forever stuck in Progressing state. 

When updating the image for new deploy, a new replicaset is started with `replicas: 0` and the replicaset is not switched which blocks the deploys.

```
# Rollouts.yaml
strategy:
    canary:
      canaryMetadata:
        labels:
          rollouts_role: canary
      canaryService: iaweb-awscmhqa2-canary
      maxSurge: 50%
      maxUnavailable: 25%
      stableMetadata:
        labels:
          rollouts_role: stable
      stableService: iaweb-awscmhqa2
      steps:
        - setCanaryScale:
            matchTrafficWeight: false
        - setCanaryScale:
            weight: 100
        - setWeight: 100
      trafficRouting:
        nginx:
          stableIngress: iaweb-awscmhqa2
```

```
#stable-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-production-indeed-assessments-route53
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Request-Id: $req_id";
      proxy_set_header X-Request-Start "t=${msec}";
    nginx.ingress.kubernetes.io/custom-http-errors: '502,503'
    nginx.ingress.kubernetes.io/default-backend: iaweb-qa-awscmhqa2-custom-errors
  name: iaweb-awscmhqa2
spec:
  defaultBackend:
    service:
      name: iaweb-awscmhqa2
      port:
        number: 80
  ingressClassName: nginx-private
  rules:
    - host: abcd.com
    - host: '*.abcd.com'
      http:
        paths:
          - backend:
              service:
                name: iaweb-awscmhqa2
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - abcd.com
        - '*.abcd.com'
      secretName: ia-web-cert-assessments
status:
  loadBalancer:
    ingress:
      - hostname: >-
          2b9addabe6168b7872-3deffaffce82e1c3.elb.us-east-2.amazonaws.com
```
The rollouts controller is constantly in "panic" due to `runtime error: invalid memory address or nil pointer`. See more in logs below.

**Expected behavior**

Canary Ingress should be created & Rollouts should be shown 'Healthy' 

**Version**

v1.3.1

**Logs**

[rollouts-controller.log](https://github.com/argoproj/argo-rollouts/files/10452696/rollouts-controller.log) 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
