### ISSUE TITLE
Argo Rollouts gets stuck completing rollout with canary-header and connected virtualservices

### ISSUE THREAD

**Issue by m-wynn** [argoproj/argo-rollouts#2526]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've inclued the version of argo rollouts.

**Describe the bug**

When using a collection of VirtualServices:
* External-facing virtualservice taking traffic from a gateway, not argo-aware (not required to reproduce)
* "Mesh" virtualservice that either forwards to the "primary-virtualservice" below, or to an argo-managed route, depending on the incoming port
* "primary-virtualservice" delegate service that has an argo-managed route

and using a managed-header route, the rollout gets to the last step but then will not delete the managed route or scale-down the old version.  It prints the error:

```
APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"1079881123\", FieldPath:\"\"}): type: 'Warning' reason: 'TrafficRoutingError' admission webhook \"validation.istio.io\" denied the request: configuration is invalid: HTTP route, redirect or direct_response is required"
```

**To Reproduce**

Apply the snippet below:

<details>
<summary>YAML kubernetes snippet</summary>

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: example-rollout
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - containerPort: 80
  strategy:
    canary:
      trafficRouting:
        managedRoutes:
          - name: canary-header
        istio:
          virtualServices:
            - name: primary-virtualservice
              routes:
                - primary-route
            - name: internal-facing-virtualservice
              routes:
                - special-internal-route
          destinationRule:
            name: the-application
            canarySubsetName: canary
            stableSubsetName: stable
      steps:
        - setHeaderRoute: 
            name: "canary-header"
            match:
              - headerName: cookie
                headerValue:
                  regex: ^(.*;?)?(canary=true)(;.*)?

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: the-application
spec:
  host: the-application

---
apiVersion: v1
kind: Service
metadata:
  name: the-application
  labels:
    app: nginx
spec:
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: nginx

# ---
# # Virtualservice for all public traffic.  Not required to reproduce this bug
# apiVersion: networking.istio.io/v1beta1
# kind: VirtualService
# metadata:
#     name: external-facing-virtualservice
# spec:
#   gateways:
#     - istio-system/external
#   hosts:
#     - example.com
#   http:
#     - name: main-route
#       delegate:
#         name: primary-virtualservice

---
# Virtualservice for all internal traffic
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: internal-facing-virtualservice
spec:
  gateways:
    - mesh
  hosts:
    - the-application
  http:
    # Internal traffic on port 80 behaves like public traffic
    - name: runtime-main
      match:
        - port: 80
      delegate:
        name: primary-virtualservice
    # Internal traffic on port 81 has special access
    - name: special-internal-route
      match:
        - port: 81
      route:
        - destination:
            host: the-application
            subset: stable
          weight: 100
        - destination:
            host: the-application
            subset: canary
          weight: 0

---
# Delegate virtualservice for all public traffic and some of internal traffic
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: primary-virtualservice
spec:
  http:
    - name: primary-route
      route:
        - destination:
            host: the-application
            subset: stable
          weight: 100
        - destination:
            host: the-application
            subset: canary
          weight: 0
```
</details>

1. Apply that with `kubectl apply -f snippet.yaml`
2. Check that it deployed with `kubectl argo rollouts get rollouts example-rollout`
3. Run something to create a new version, e.g. `k patch rollout example-rollout --type merge -p '{"spec":{"template":{"metadata":{"labels":{"a":"test"}}}}}'`
4. Note that the the rollout metrics still say "Progressing" and the old version isn't being scaled down.

**Expected behavior**

The rollout should finish and scale-down the old version

**Version**

v1.3.1

**Logs**

```
event_reason=TrafficRoutingError namespace=test rollout=example-rollout
argo-rollouts-597c768bf7-t2hwc time="2023-01-19T23:16:32Z" level=error msg="roCtx.reconcile err admission webhook \"validation.istio.io\" denied the request: configuration is invalid: HTTP route, redirect or direct_response is required" generation=36 namespace=test resourceVersion=1079919570 rollout=example-rollout
argo-rollouts-597c768bf7-t2hwc time="2023-01-19T23:16:32Z" level=info msg="Reconciliation completed" generation=36 namespace=test resourceVersion=1079919570 rollout=example-rollout time_ms=17.972627000000003
argo-rollouts-597c768bf7-t2hwc time="2023-01-19T23:16:32Z" level=error msg="rollout syncHandler error: admission webhook \"validation.istio.io\" denied the request: configuration is invalid: HTTP route, redirect or direct_response is required" namespace=test rollout=example-rollout
argo-rollouts-597c768bf7-t2hwc time="2023-01-19T23:16:32Z" level=info msg="rollout syncHandler queue retries: 18 : key \"test/example-rollout\"" namespace=test rollout=example-rollout
argo-rollouts-597c768bf7-t2hwc time="2023-01-19T23:16:32Z" level=info msg="Event(v1.ObjectReference{Kind:\"Rollout\", Namespace:\"test\", Name:\"example-rollout\", UID:\"a21897fc-a875-488a-8d62-5d1bfec41ca8\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"1079919570\", FieldPath:\"\"}): type: 'Warning' reason: 'TrafficRoutingError' admission webhook \"validation.istio.io\" denied the request: configuration is invalid: HTTP route, redirect or direct_response is required"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
