### ISSUE TITLE
v1.4.0 Failed to create Service for template -- port.Name not being passed to CreateService

### ISSUE THREAD

**Issue by bt-macole** [argoproj/argo-rollouts#2599]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've inclued the version of argo rollouts.

**Describe the bug**

When creating the ports slice ([code here](https://github.com/argoproj/argo-rollouts/blob/4afac4ea733ebfbc3c18952fd3b60526d3723ab7/experiments/experiment.go#L289-L304)) to pass to `CreateService`, `port.Name` is omitted, when attempting to create a Service where `len(ports) > 1` this generates an invalid spec.

It seems this was not previously an issue because the created Service always only had the single hardcoded port. However, if more than 1 Service Port is defined, name is not optional (see k8s docs for more [here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#serviceport-v1-core))

**To Reproduce**

argo-rollouts: v1.4.x

Create an Experiment with more than 1 `rs.spec.template.spec.containers.ports`, such as:

example template.spec.containers.ports:
```yaml
...
    template:
      ...
      spec:
      ...
        containers:
           ...
              ports:
                - containerPort: 8080
                  name: a
                - containerPort: 8082
                  name: b
                - containerPort: 8083
                  name: c
...
```

will get error such as:
```
        Failed to create Service for template '<SERVICE NAME>': Service
        "<UNIQUE-SERVICE-NAME>" is invalid:
        [spec.ports[0].name: Required value, spec.ports[1].name: Required value,
        spec.ports[2].name: Required value]
``` 

With degraded rollout and experiment resources.

**Expected behavior**

Experiment creates resources.

**Version**

v1.4.0

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
