### ISSUE TITLE
Dashboard JSON.parse error with multiple values returned from cloudwatch

### ISSUE THREAD

**Issue by julianogv** [argoproj/argo-rollouts#2623]
Checklist:

* [X] I've included steps to reproduce the bug.
* [X] I've included the version of argo rollouts.

**Describe the bug**

I'm facing a bug whenever I click on the Analysis button to see the analysis values for a AnalysisTemplate using cloudwatch metrics, after clicking on it I'm redirected to a blank page.

My AnalysisTemplate using cloudwatch is returning more than one metric and it's raising a JSON.parse error as the stack below is showing.

The data it's trying to be parsed (JSON.parse) is `"[[0.3644409735780294 0.22732066274518992 0.37337090524832683 0.3314456297466965 0.334272042493761]]"`, which is actually not a valid JSON.

Is it really a bug or a limitation from argo rollout dashboard? As a workaround, I'm using TamperMonkey to solve this, removing the JSON.parse and showing the raw string.

```
react-dom.production.min.js:216 SyntaxError: Expected ',' or ']' after array element in JSON at position 21
    at JSON.parse (<anonymous>)
    at revision.tsx:209:86
    at Array.map (<anonymous>)
    at c (revision.tsx:201:55)
    at ni (react-dom.production.min.js:157:137)
    at Ii (react-dom.production.min.js:180:154)
    at Ws (react-dom.production.min.js:269:343)
    at Ll (react-dom.production.min.js:250:347)
    at Ml (react-dom.production.min.js:250:278)
    at vl (react-dom.production.min.js:250:138)
as @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
ua @ react-dom.production.min.js:131
fs @ react-dom.production.min.js:220
Yl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
zo @ react-dom.production.min.js:122
xl @ react-dom.production.min.js:252
fl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
zo @ react-dom.production.min.js:122
Bo @ react-dom.production.min.js:123
Uo @ react-dom.production.min.js:122
He @ react-dom.production.min.js:292
Kt @ react-dom.production.min.js:73
revision.tsx:209

Uncaught SyntaxError: Expected ',' or ']' after array element in JSON at position 21
    at JSON.parse (<anonymous>)
    at revision.tsx:209:86
    at Array.map (<anonymous>)
    at c (revision.tsx:201:55)
    at ni (react-dom.production.min.js:157:137)
    at Ii (react-dom.production.min.js:180:154)
    at Ws (react-dom.production.min.js:269:343)
    at Ll (react-dom.production.min.js:250:347)
    at Ml (react-dom.production.min.js:250:278)
    at vl (react-dom.production.min.js:250:138)
```
**To Reproduce**

- Create a AnalysisTemplate with a metric similar to the metric below

**Expected behavior**

I believe that It should show the returned values from cloudwatch even if it's not a valid json.

**Version**

kubectl-argo-rollouts: v1.4.0+e40c9fe
  BuildDate: 2023-01-09T20:20:38Z
  GitCommit: e40c9fe8a2f7fee9d8ee1c56b4c6c7b983fce135
  GitTreeState: clean
  GoVersion: go1.19.4
  Compiler: gc
  Platform: linux/amd64

**Analysis Template Metric definition**

```
  metrics:
  - name: error-rate
    interval: 1m
    successCondition: "len(result[0].Values) >= 1 and all(result[0].Values, {# <= 1.0})"
    failureLimit: 0
    provider:
      cloudWatch:
        interval: 5m
        metricDataQueries:
          - {
            "id": "errorrate",
            "expression": "((errors5xx+errors4xx)/requestcount)*100",
            "returnData": true
          }
          - {
            "id": "errors5xx",
            "metricStat": {
              "metric": {
                "namespace": "AWS/ApplicationELB",
                "metricName": "HTTPCode_ELB_5XX_Count",
                "dimensions": [
                  {
                    "name": "LoadBalancer",
                    "value": "<REDACTED>"
                  }
                ]
              },
              "period": 60,
              "stat": "Sum",
              "unit": "Count"
            },
            "returnData": false
          }
          - {
            "id": "errors4xx",
            "metricStat": {
              "metric": {
                "namespace": "AWS/ApplicationELB",
                "metricName": "HTTPCode_ELB_4XX_Count",
                "dimensions": [
                  {
                    "name": "LoadBalancer",
                    "value": "<REDACTED>"
                  }
                ]
              },
              "period": 60,
              "stat": "Sum",
              "unit": "Count"
            },
            "returnData": false
          }
          - {
            "id": "requestcount",
            "metricStat": {
              "metric": {
                "namespace": "AWS/ApplicationELB",
                "metricName": "RequestCount",
                "dimensions": [
                  {
                    "name": "LoadBalancer",
                    "value": "<REDACTED>"
                  }
                ]
              },
              "period": 60,
              "stat": "Sum",
              "unit": "Count"
            },
            "returnData": false
          }
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by sondrelg** [comment]
I think this might be solved by specifying `result[0]` in your analysis template @julianogv. This is how I do it:

```yaml
  - name: Database disk queue depth
    interval: 1m
    successCondition: all(result[0].Values, {# <= 2})
    inconclusiveLimit: 10
    consecutiveSuccessLimit: 5
    failureLimit: 3
    provider:
      cloudWatch:
        interval: 5m
        metricDataQueries:
          - id: diskQueueDepth
            returnData: true
            metricStat:
              metric:
                namespace: AWS/RDS
                metricName: DiskQueueDepth
                dimensions:
                  - name: DBInstanceIdentifier
                    value: "{{args.db-instance}}"
              period: 300
              stat: Average
```
