### ISSUE TITLE
unknown field "namespace" in io.argoproj.v1alpha1.Rollout.spec.template.metadata

### ISSUE THREAD

**Issue by sridhar-parvathala** [argoproj/argo-rollouts#2662]
Hello,

**Describe the bug**

I am trying to deploy a below `Rollout` resource and  the deployment is successfull. Then i have made some change in the original rollout.yaml by adding `namespace` field under pod spec template metadata which is working fine if the `Kind` is `Deployment` but the same is failing if the `Kind` is `Rollout` ( I have copied the modified rollout.yaml below)

https://raw.githubusercontent.com/argoproj/argo-rollouts/master/docs/getting-started/basic/rollout.yaml

> ubuntu@ip-10-150-113-101:~$ kubectl argo rollouts version
> kubectl-argo-rollouts: v1.3.1+b0b95ca
>   BuildDate: 2022-09-29T15:17:17Z
>   GitCommit: b0b95cade830d8a70624fcaaf8e92e1fe2ecd355
>   GitTreeState: clean
>   GoVersion: go1.18.6
>   Compiler: gc
>   Platform: linux/amd64

I am copying the modified Rollout yaml for your reference ,Please note the namespace field is added in two places which is supported and working fine if the Kind is `Deployment`.

$** **kubectl apply -f rollout.yaml 
error: error validating "rollout.yaml": error validating data: ValidationError(Rollout.spec.template.metadata): unknown field "namespace" in io.argoproj.v1alpha1.Rollout.spec.template.metadata; if you choose to ignore these errors, turn validation off with --validate=false**

```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
  namespace: rollout
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
        namespace: rollout
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m


```

Kindly let me know if any other information is needed.
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
