### ISSUE TITLE
DynamicStableScalePace: dynamically scale the stable ReplicaSet at a specified pace

### ISSUE THREAD

**Issue by zzr93** [argoproj/argo-rollouts#2687]
# Summary

**_dynamicStableScale_** usually used in **_resource-constrained_** environments, in order to limit total replicas' count by scaling down stable ReplicaSet step by step.
However, this step is triggered by a traffic switch which is usually defined in **setWeight**. So suppose I have a Rollout(replicaCount=**_10_**), 
and my environment can only support **_11_** replicas, my rollout.yaml probably looks like this:
```yaml
...
spec:
  strategy:
    canary:
      dynamicStableScale: true
      steps:
        - setWeight: 10
        # omit analysis
        - setWeight: 20
        - setWeight: 30
        - setWeight: 40
        - setWeight: 50
        - setWeight: 60
        - setWeight: 70
        - setWeight: 80
        - setWeight: 90
        - setWeight: 100
...
```
And it can be impractical if replicaCount floats.
So what I really need in this situation is dynamically scale the stable ReplicaSet at a specified pace. It would be perfect if I can express it like this:
```yaml
spec:
  strategy:
    canary:
    dynamicStableScalePace: 1
```

# Use Cases

When would you use this?
In resource-constrained environments, such as an AI inference cluster with limited GPUs.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
