### ISSUE TITLE
Ping-Pong with stickiness is not working as expected

### ISSUE THREAD

**Issue by dleinov** [argoproj/argo-rollouts#2726]
**Describe the bug**

When we use the Ping-Pong feature with stickiness the behavior is not consistent. One time we get 503 error after full promote the rollout and one time during the rollout all requests are going to canary image even the weight configuration. 
Seems that when the Ping-Pong and stickiness configured together it make mixing with the stable and canary. 

**To Reproduce**

1. Apply the resources:

Rollout:

```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  replicas: 1
  strategy:
    canary:
      pingPong:
        pongService: rollouts-demo-canary
        pingService: rollouts-demo-stable
      trafficRouting:
        alb:
          stickinessConfig:
            enabled: true
            durationSeconds: 3600
          ingress: rollouts-demo-ingress
          servicePort: 80
          rootService: rollouts-demo-root
      steps:
      - setWeight: 5
      - pause: {}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
```

Ingress:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
  name: rollouts-demo-ingress
spec:
  rules:
  - host: test.test.com
    http:
      paths:
      - backend:
          service:
            name: rollouts-demo-root
            port:
              name: use-annotation
        path: /
        pathType: Prefix
```

Services:

```
apiVersion: v1
kind: Service
metadata:
  name: rollouts-demo-root
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: rollouts-demo

---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-demo-canary
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: rollouts-demo

---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-demo-stable
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: rollouts-demo
```

2. Change the Image from blue to red
My requests are still going to blue as expected with the stickiness configuration. 
3. Make full promote 
After the rollout finished we got 503 Service Temporarily Unavailable error
4. Change again the Image from red to yellow
My requests are going to yellow 100%(the canary) with the stickiness configuration and not by the weight configuration (5% to canary) - not as expected.
5. Make full promote
After the rollout finished the requests went 100% to yellow image , the canary as expected. 

**Version:**

1.3.1
