### ISSUE TITLE
Automatically scale down Deployment after migrating to Rollout

### ISSUE THREAD

**Issue by carlossg** [argoproj/argo-rollouts#2748]
# Summary

When using `Rollout` with `workloadRef` it could be expected that the workload (`Deployment`) is scaled down as the `Rollout` is scaled up, or at the end after successful rollout

# Use Cases

During migration of 10s-1000s of Deployments to Rollouts

After talking to several maintainers during ArgoCon this could be a new field under `spec.workloadRef`, maybe something like

```yaml
spec:
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "acme"
    scaleDown: "never|onsuccess|progressively"
```

* never: do not downscale
* onsuccess: after successful rollout
* progressively: as rollout is scaled up deployment is scaled down. If rollout fails then deployment is scaled back up to original replicas (I think this may be interesting for very large replica numbers, but maybe too early to say)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
