### ISSUE TITLE
dynamicStableScale doesn't take setCanaryScale into account

### ISSUE THREAD

**Issue by shaoye** [argoproj/argo-rollouts#2749]
Checklist:

* [y] I've included steps to reproduce the bug.
* [y] I've included the version of argo rollouts.

**Describe the bug**

When use header based routing with `setHeaderRouting`, we avoid using `setWeight` to change the percentage again in the non-header-based route. So that we can make sure 100% of the traffic without the desired header can go to stable subset.

Here is our Rollout settings:
```yaml
      dynamicStableScale: true
      steps:
        - setCanaryScale:
            weight: 50
        - setHeaderRoute:
            match:
              - headerName: x-canary-version
                headerValue:
                  exact: canary
            name: canary-header-route
        - pause:
            duration: 10m
```
which generates the correct routes in a virtual service during an rollout
```yaml
  http:
    - match:
        - headers:
            x-canary-version:
              exact: canary
      name: canary-header-route
      route:
        - destination:
            host: xxx.default.svc.cluster.local
            subset: canary
          weight: 100
    - name: canary-route
      route:
        - destination:
            host: xxx.default.svc.cluster.local
            subset: stable
          weight: 100
        - destination:
            host: xxx.default.svc.cluster.local
            subset: canary
          weight: 0
``` 

But it seems like `dynamicStableScale` only takes `setWeight` into account, even if we've set `setCanaryScale.weight` to `50`, the stable replicaset stays at 100% during the rollout.

**Expected behavior**

the stable ReplicaSet can scale base on `setCanaryScale.weight` as well

**Version**

v1.4.1

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
