### ISSUE TITLE
setHeaderRoute will remove existing matches with withoutHeaders field

### ISSUE THREAD

**Issue by shaoye** [argoproj/argo-rollouts#2767]
**Describe the bug**

When using setHeaderRoute with istio, when a rollout finishes, argo will rewrite the existing match that has `withoutHeaders` field to `{}`

**To Reproduce**

create a rollout with the following strategy:

```yaml
  strategy:
    canary:
      steps:
        - setWeight: 50 
        - setHeaderRoute:
            name: canary-header-route
            match:
              - headerName: x-canary
                headerValue:
                  exact: "canary"
        - pause:
            duration: 20m   
```

create a virtualservice with the following spec:
```yaml
  http:
  - match:
    - withoutHeaders:
        x-canary:
          regex: "*"
    name: no-header-route
    route:
      - destination:
          host: service
          subset: stable
        weight: 100
```

Argo can inject a new route during step 2, the rendered virtualservice will be:
which is correct and perfect 
```yaml
  http:
    - match:
        - headers:
            x-canary:
              exact: canary
      name: canary-header-route
      route:
        - destination:
            host: service
            subset: canary
          weight: 100
  - match:
    - withoutHeaders:
        x-canary:
          regex: "*"
    name: no-header-route
    route:
      - destination:
          host: service
          subset: stable
        weight: 100
```

After step3, when the rollout finishes, argo will try to remove the `canary-header-route` match in the above virtualservice.

BUT, it also changes the `withoutHeaders` obj to empty, here is the virtualservice after step3:

```yaml
  http:
    - match:
        - {}
    name: no-header-route
    route:
      - destination:
          host: service
          subset: stable
        weight: 100
```

**Expected behavior**

Argo should leave the following route as it is
```yaml
  - match:
    - withoutHeaders:
        x-canary:
          regex: "*"
```

**Screenshots**

**Version**

latest (1.4.1)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
