### ISSUE TITLE
Datadog v2 analysis ends in Error due to 500 from Datadog

### ISSUE THREAD

**Issue by tukak** [argoproj/argo-rollouts#2771]
Checklist:

* [ x ] I've included steps to reproduce the bug.
* [ x ] I've included the version of argo rollouts.

**Describe the bug**

Switching to Datadog API v2 in analysis causes a 500 error in the AnalysisRun, returning webpage with JS.

**To Reproduce**

Take working analysis and add `apiVersion: v2` to the `spec.metrics.[].provider.datadog`, ie

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: rollout-test-success-rate
spec:
  metrics:
    - name: success-rate
      interval: 1m
      successCondition: default(result, 0) < 10
      provider:
        datadog:
          apiVersion: v2
          interval: 1m
          query: |
            avg:rollout.test.failures{*}.as_count()
```
**Expected behavior**

Finish the Analysis with Failed or Successful, as when the `apiVersion: v1` or not set.

**Version**

argo-rollouts:v1.5.0

**Logs**

```Metric "success-rate" assessed Error due to consecutiveErrors (5) > consecutiveErrorLimit (4): "Error Message: received non 2xx response code: 500```

Attached full logs as a file due to size.

[rollouts_log.txt](https://github.com/argoproj/argo-rollouts/files/11439949/rollouts_log.txt)
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
