### ISSUE TITLE
analysisRunMetadata gets removed by controller during rollout reconciliation process

### ISSUE THREAD

**Issue by shaoye** [argoproj/argo-rollouts#2778]
Checklist:

* [ 1] I've included steps to reproduce the bug.
* [ 1] I've included the version of argo rollouts.

**Describe the bug**

`strategy.canary.analysis.analysisRunMetadata` gets removed by controller during rollout reconciliation process.

**To Reproduce**

1. Create a Rollout with `analysisRunMetadata` and refer it to an existing Deployment
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
spec:
  replicas: 2 
  ...
  strategy:
    canary:
      analysis:
        analysisRunMetadata:
          labels:
            somelabel: xxxx
          annotations:
            someannotation: xxx
        templates:
          - templateName: general-template
            clusterScope: true
        dryRun:
          - metricName: .*
        ...
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-deployment
```
2. Modify any filed in my-deployment to trigger a rollout update
3. Rollout starts successfully but `analysisRunMetadata` field in Rollout is missing

We also noticed there is an error log from the controller says:

```
time="2023-05-14T03:31:57Z" level=error msg="roCtx.reconcile err Operation cannot be fulfilled on replicasets.apps \"my-deployment-5dc8d7d5b7\": the object has been modified; please apply your changes to the latest version and try again" generation=36 namespace=default resourceVersion=534994713 rollout=my-rollout

time="2023-05-14T03:31:57Z" level=info msg="Reconciliation completed" generation=36 namespace=default resourceVersion=534994713 rollout=my-rollout time_ms=456.309674
```

**Version**

1.5.0

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
