### ISSUE TITLE
invalid path status.alb.stableTargetGroup.name in rollout

### ISSUE THREAD

**Issue by moharam-dev** [argoproj/argo-rollouts#2812]
### Discussed in https://github.com/argoproj/argo-rollouts/discussions/2811

<div type='discussions-op-text'>

<sup>Originally posted by **moharam-dev** May 26, 2023</sup>
Hi All, 

I'm trying to pass target group name to analysis template in a rollout with traffic management ALB but keep getting the following error:
time="2023-05-26T09:40:47Z" level=info msg="rollout syncHandler queue retries: 44 : key \"app/app-rollouts\"" namespace=app rollout=app-rollouts
time="2023-05-26T09:40:47Z" level=error msg="invalid path status.alb.stableTargetGroup.name in rollout\n" error="<nil>"

I'm using the latest version of argo rollouts 1.5.1

Following part of my Rollout definition 

```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: app-rollouts
  namespace: app
spec:
  strategy:
    canary:
      analysis:
        templates:
        - templateName: app-success-rate-cw
        args:
        - name: canary-targetgroup-name
          valueFrom:
            fieldRef:
              fieldPath: status.alb.stableTargetGroup.name
      canaryService: app-rollouts-canary
      stableService: app-rollouts-stable
      trafficRouting:
        alb:
          ingress: app-ingress
          rootService: app-rollouts-root
          servicePort: 443
      steps:
      - setWeight: 20
      - pause: {duration: 1m}
      - setWeight: 40
      - pause: {duration: 1m}

```

It seems I'm missing something. Can you please help me with this?</div>
