### ISSUE TITLE
Experiment does not always create Service

### ISSUE THREAD

**Issue by mjallday** [argoproj/argo-rollouts#2816]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've included the version of argo rollouts.

**Describe the bug**

When I update a rollout that has an experiment attached to it, it is not creating a service definition which means i cannot access the pods via the service. When the experiment is first created I do see the service created successfully but it is torn down after the experiment completes and then no-longer be re-created subsequently

https://argo-rollouts.readthedocs.io/en/stable/features/experiment/

> Create and scale a ReplicaSet for each pod template specified under spec.templates. **If service is specified under a pod template, a Service will also be created for that pod.**

(Emphasis mine)

I believe [the bug lies here in this code](https://github.com/argoproj/argo-rollouts/blob/1d34b6330af109b984d385b410ab661dd7a53748/experiments/experiment.go#L130-L137) which only creates the service if the replicaset already exists.

**To Reproduce**

Take this configuration

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: experiment-with-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: experiment-with-service
  template:
    metadata:
      labels:
        name: experiment-with-service
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    canary:
      steps:
      - experiment:
          analyses:
          - name: acceptance-test
            templateName: preview-test
          duration: 5m
          templates:
          - metadata: {}
            name: preview
            specRef: canary
            # this does work but expects you to define it here rather than in the Experiment
            # service:
            #   name: experiment-with-service-preview
      - setWeight: 1
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: preview-test
spec:
  metrics:
  - name: acceptance-tests
    provider:
      job:
        spec:
          backoffLimit: 0
          # one hour
          ttlSecondsAfterFinished: 3600
          template:
            spec:
              restartPolicy: Never
              containers:
              - name: nc
                image: subfuzion/netcat
                command: ['nc', 'experiment-with-service-preview:8080']
---
apiVersion: argoproj.io/v1alpha1
kind: Experiment
metadata:
  name: experiment-with-service
spec:
  duration: 10s
  scaleDownDelaySeconds: 5
  # List of pod template specs to run in the experiment as ReplicaSets
  templates:
    - name: test
      replicas: 1
      # this does NOT work except for the first time
      service:
        name: experiment-with-service-preview
      selector:
        matchLabels:
          app: experiment-with-service
          purpose: experiment
      template:
        metadata:
          labels:
            app: experiment-with-service
            purpose: experiment
        spec:
          containers:
            - name: experiment-with-service
              image: nginx:1.19-alpine
              resources:
                requests:
                  memory: 16Mi
                  cpu: 1m
              ports:
                - protocol: TCP
                  containerPort: 8080
```

Apply it to the cluster using a command similar to `k -n test-foo apply -f rollout-experiment.yml`

The first time I run the preview I see the correctly created service

```sh
k -n test-foo get rollout,experiment,rs,pod,svc
```
which gives me
```
NAME                                          DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
rollout.argoproj.io/experiment-with-service   1                                            29s

NAME                                             STATUS    AGE
experiment.argoproj.io/experiment-with-service   Running   29s

NAME                                           DESIRED   CURRENT   READY   AGE
replicaset.apps/experiment-with-service-test   1         1         1       12s

NAME                                     READY   STATUS    RESTARTS   AGE
pod/experiment-with-service-test-sbvn4   1/1     Running   0          10s

NAME                                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/experiment-with-service-preview   ClusterIP   172.20.97.171   <none>        8080/TCP   11s
```

Now we perform another experiment - expecting this to also create a service to run the experiment against

`kubectl argo rollouts set image experiment-with-service rollouts-demo=nginx:1.18-alpine -n test-foo`

However, this does not create a service and the test will fail since nc is unable to connect to the service.

**Expected behavior**

The service should be created each time the preview runs. How it works if there are parallel experiments is not something I have an obvious answer for.
**Version**

1.5.1

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
