### ISSUE TITLE
will the setHeaderRoute support the nginx ingress soon?

### ISSUE THREAD

**Issue by andyliuliming** [argoproj/argo-rollouts#2830]
# Summary
will the setHeaderRoute support the nginx ingress soon?
What change needs making?

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by JMoserCricut** [comment]
@zachaller what do you think about adding support to allow nginx to utilize the setheaderroute? I'd like to be able to use that feature to send traffic first to some alpha users, then after that send traffic to just a portion of users, not sure if that is possible at the moment with nginx

**Comment by JMoserCricut** [comment]
I've found for our use case that the additionalIngressAnnotations will suffice for our use cases

https://argo-rollouts.readthedocs.io/en/stable/features/traffic-management/nginx/

```
        nginx:
          # Either stableIngress or stableIngresses must be configured, but not both.
          stableIngress: primary-ingress
          stableIngresses:
            - primary-ingress
            - secondary-ingress
            - tertiary-ingress
          annotationPrefix: customingress.nginx.ingress.kubernetes.io # optional
          additionalIngressAnnotations:   # optional
            canary-by-header: X-Canary
            canary-by-header-value: iwantsit
```
