### ISSUE TITLE
Canary deployment fails silently if the old pod spec has missing default values

### ISSUE THREAD

**Issue by Pratyush-123** [argoproj/argo-rollouts#2861]
Checklist:

* [ ] I've included steps to reproduce the bug.
* [X] I've included the version of argo rollouts.

**Describe the bug**
Deployment Type: Canary
For some weird reason still unknown to us pod created by argo rollout during a deployment didn't have the Add Capabilities in the security context. During the reconciliation the argo rollout controller was trying to constantly update the pod spec to add back these capabilities but was failing since it didn't have that permission with the error message shown in the logs. This error was only visible in argo rollouts pod logs and not on the argo cd ui.

When a new deployment was triggered for this rollout, during the canary deployment the new replica set got created successfully. However the pods were not coming up and no error was shown on the UI i.e. the deployment was failing silently and was stuck in progressing state without any error message.
This caused a CSO for Adobe Firefly and was resolved by deleting the pod which was causing the deployment to fail. 

I have done some initial debugging and found the following. 
I suspect this line of code https://github.com/argoproj/argo-rollouts/blob/release-1.4/rollout/canary.go#L39 casued the argo rollout to update the pod spec with the default values. This function adds the metadata using this line of code https://github.com/argoproj/argo-rollouts/blob/release-1.4/rollout/ephemeralmetadata.go#L75 which I think is adding the default values to the pod spec as well. Since the argo-rollout controller was not allowed to update the security context, it caused the reconciliation to fail the code never reached this line ( https://github.com/argoproj/argo-rollouts/blob/release-1.4/rollout/canary.go#L89) to update the replicaset with the new replica count. 

Moreover this error is just being logged in the argo rollout pods and not added to rollout condition and hence is not surfacing on to the argocd UI.

**To Reproduce**
Argo rollout template used.
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    binding: neuralfiltersplatform--firefly-production-firefly-prod
    environment: production
    flex.ethos.corp.adobe.com/instance: neuralfiltersplatform--firefly-deploy--ethos851-prod-o-c9934c62
    gitrepo: neuralfiltersplatform--firefly
    region: or2
  name: neuralfiltersplatform--firefly-production-firefly-prod
  namespace: ns-team-firefly-prod
spec:
  revisionHistoryLimit: 1
  strategy:
    canary:
      canaryMetadata:
        annotations:
          app.name: FireflyCanary
          deployside: b
        labels:
          deployside: b
          environment: or2
      canaryService: o75854558c5c4-canary
      dynamicStableScale: true
      maxSurge: 100%
      maxUnavailable: 34%
      stableMetadata:
        annotations:
          app.name: Firefly
          deployside: a
        labels:
          deployside: a
          environment: or2
      stableService: o75854558c5c4
      steps:
        - setWeight: 1
        - pause: {}
        - setWeight: 10
        - pause: {}
        - setWeight: 20
        - pause: {}
        - setWeight: 50
        - pause: {}
        - setWeight: 80
        - pause: {}
      trafficRouting:
        kapcom:
          httpProxy: neuralfiltersplatform--firefly-production-base-route
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: neuralfiltersplatform--firefly-production-firefly-prod
```

I am not able to reproduce the case where the old pods had missing security context capabilities. But if we can have a pod spec with modified pod spec default values then the above rollout object will replicate the issue. 

**Expected behavior**
Upon updating the deployment spec, argo rollouts controller should trigger the canary deployment without updating the pod spec for old pods. Moreover deployment should not fail silently and this error should surface on the argo cd UI.

**Screenshots**

**Version**
v1.4
We are maintaining a forked version with additional support for our inhouse ingress controller.

**Logs**

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME

time="2023-06-06T01:13:48Z" level=error msg="roCtx.reconcile err Pod \"neuralfiltersplatform--firefly-production-firefly-prod-76chhrb8\" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds`, `spec.tolerations` (only additions to existing tolerations) or `spec.terminationGracePeriodSeconds` (allow it to be set to 1 if it was previously negative)\n  core.PodSpec{\n  \tVolumes:        {{Name: \"sandbox-volume\", VolumeSource: {EmptyDir: &{}}}, {Name: \"dshm\", VolumeSource: {EmptyDir: &{Medium: \"Memory\", SizeLimit: &{i: {...}, Format: \"BinarySI\"}}}}, {Name: \"liveness-config\", VolumeSource: {ConfigMap: &{LocalObjectReference: {Name: \"liveness-config\"}, DefaultMode: &420}}}, {Name: \"startup-config\", VolumeSource: {ConfigMap: &{LocalObjectReference: {Name: \"startup-config\"}, DefaultMode: &420}}}, ...},\n  \tInitContainers: nil,\n  \tContainers: []core.Container{\n  \t\t{\n  \t\t\t... // 16 identical fields\n  \t\t\tTerminationMessagePolicy: \"File\",\n  \t\t\tImagePullPolicy:          \"IfNotPresent\",\n  \t\t\tSecurityContext: &core.SecurityContext{\n  \t\t\t\tCapabilities: &core.Capabilities{\n- \t\t\t\t\tAdd:  nil,\n+ \t\t\t\t\tAdd:  []core.Capability{\"AUDIT_WRITE\"},\n  \t\t\t\t\tDrop: {\"FSETID\", \"NET_RAW\", \"SETFCAP\", \"SETPCAP\", ...},\n  \t\t\t\t},\n  \t\t\t\tPrivileged:     nil,\n  \t\t\t\tSELinuxOptions: nil,\n  \t\t\t\t... // 2 identical fields\n  \t\t\t\tRunAsGroup:               nil,\n  \t\t\t\tRunAsNonRoot:             nil,\n- \t\t\t\tReadOnlyRootFilesystem:   nil,\n+ \t\t\t\tReadOnlyRootFilesystem:   &false,\n  \t\t\t\tAllowPrivilegeEscalation: &false,\n  \t\t\t\tProcMount:                nil,\n  \t\t\t\tSeccompProfile:           nil,\n  \t\t\t},\n  \t\t\tStdin:     false,\n  \t\t\tStdinOnce: false,\n  \t\t\tTTY:       false,\n  \t\t},\n  \t\t{\n  \t\t\t... // 16 identical fields\n  \t\t\tTerminationMessagePolicy: \"File\",\n  \t\t\tImagePullPolicy:          \"IfNotPresent\",\n  \t\t\tSecurityContext: &core.SecurityContext{\n  \t\t\t\tCapabilities: &core.Capabilities{\n- \t\t\t\t\tAdd:  nil,\n+ \t\t\t\t\tAdd:  []core.Capability{\"AUDIT_WRITE\"},\n  \t\t\t\t\tDrop: {\"FSETID\", \"NET_RAW\", \"SETFCAP\", \"SETPCAP\", ...},\n  \t\t\t\t},\n  \t\t\t\tPrivileged:     nil,\n  \t\t\t\tSELinuxOptions: nil,\n  \t\t\t\t... // 2 identical fields\n  \t\t\t\tRunAsGroup:               nil,\n  \t\t\t\tRunAsNonRoot:             nil,\n- \t\t\t\tReadOnlyRootFilesystem:   nil,\n+ \t\t\t\tReadOnlyRootFilesystem:   &false,\n  \t\t\t\tAllowPrivilegeEscalation: &false,\n  \t\t\t\tProcMount:                nil,\n  \t\t\t\tSeccompProfile:           nil,\n  \t\t\t},\n  \t\t\tStdin:     false,\n  \t\t\tStdinOnce: false,\n  \t\t\tTTY:       false,\n  \t\t},\n  \t},\n  \tEphemeralContainers: nil,\n  \tRestartPolicy:       \"Always\",\n  \t... // 26 identical fields\n  }\n" generation=27 namespace=ns-team-firefly-prod resourceVersion=147840512 rollout=neuralfiltersplatform--firefly-production-firefly-prod

time="2023-06-06T01:13:48Z" level=error msg="rollout syncHandler error: Pod \"neuralfiltersplatform--firefly-production-firefly-prod-76chhrb8\" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds`, `spec.tolerations` (only additions to existing tolerations) or `spec.terminationGracePeriodSeconds` (allow it to be set to 1 if it was previously negative)\n  core.PodSpec{\n  \tVolumes:        {{Name: \"sandbox-volume\", VolumeSource: {EmptyDir: &{}}}, {Name: \"dshm\", VolumeSource: {EmptyDir: &{Medium: \"Memory\", SizeLimit: &{i: {...}, Format: \"BinarySI\"}}}}, {Name: \"liveness-config\", VolumeSource: {ConfigMap: &{LocalObjectReference: {Name: \"liveness-config\"}, DefaultMode: &420}}}, {Name: \"startup-config\", VolumeSource: {ConfigMap: &{LocalObjectReference: {Name: \"startup-config\"}, DefaultMode: &420}}}, ...},\n  \tInitContainers: nil,\n  \tContainers: []core.Container{\n  \t\t{\n  \t\t\t... // 16 identical fields\n  \t\t\tTerminationMessagePolicy: \"File\",\n  \t\t\tImagePullPolicy:          \"IfNotPresent\",\n  \t\t\tSecurityContext: &core.SecurityContext{\n  \t\t\t\tCapabilities: &core.Capabilities{\n- \t\t\t\t\tAdd:  nil,\n+ \t\t\t\t\tAdd:  []core.Capability{\"AUDIT_WRITE\"},\n  \t\t\t\t\tDrop: {\"FSETID\", \"NET_RAW\", \"SETFCAP\", \"SETPCAP\", ...},\n  \t\t\t\t},\n  \t\t\t\tPrivileged:     nil,\n  \t\t\t\tSELinuxOptions: nil,\n  \t\t\t\t... // 2 identical fields\n  \t\t\t\tRunAsGroup:               nil,\n  \t\t\t\tRunAsNonRoot:             nil,\n- \t\t\t\tReadOnlyRootFilesystem:   nil,\n+ \t\t\t\tReadOnlyRootFilesystem:   &false,\n  \t\t\t\tAllowPrivilegeEscalation: &false,\n  \t\t\t\tProcMount:                nil,\n  \t\t\t\tSeccompProfile:           nil,\n  \t\t\t},\n  \t\t\tStdin:     false,\n  \t\t\tStdinOnce: false,\n  \t\t\tTTY:       false,\n  \t\t},\n  \t\t{\n  \t\t\t... // 16 identical fields\n  \t\t\tTerminationMessagePolicy: \"File\",\n  \t\t\tImagePullPolicy:          \"IfNotPresent\",\n  \t\t\tSecurityContext: &core.SecurityContext{\n  \t\t\t\tCapabilities: &core.Capabilities{\n- \t\t\t\t\tAdd:  nil,\n+ \t\t\t\t\tAdd:  []core.Capability{\"AUDIT_WRITE\"},\n  \t\t\t\t\tDrop: {\"FSETID\", \"NET_RAW\", \"SETFCAP\", \"SETPCAP\", ...},\n  \t\t\t\t},\n  \t\t\t\tPrivileged:     nil,\n  \t\t\t\tSELinuxOptions: nil,\n  \t\t\t\t... // 2 identical fields\n  \t\t\t\tRunAsGroup:               nil,\n  \t\t\t\tRunAsNonRoot:             nil,\n- \t\t\t\tReadOnlyRootFilesystem:   nil,\n+ \t\t\t\tReadOnlyRootFilesystem:   &false,\n  \t\t\t\tAllowPrivilegeEscalation: &false,\n  \t\t\t\tProcMount:                nil,\n  \t\t\t\tSeccompProfile:           nil,\n  \t\t\t},\n  \t\t\tStdin:     false,\n  \t\t\tStdinOnce: false,\n  \t\t\tTTY:       false,\n  \t\t},\n  \t},\n  \tEphemeralContainers: nil,\n  \tRestartPolicy:       \"Always\",\n  \t... // 26 identical fields\n  }\n" namespace=ns-team-firefly-prod rollout=neuralfiltersplatform--firefly-production-firefly-prod

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
> Forbidden: pod updates may not change fields other than

What is strange about this error is that Rollout does not create or update pods. It creates ReplicaSets which creates pods.

It does not even have privilege to do so:

```
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - update
  - watch
# pods eviction needed for restart
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
```
