### ISSUE TITLE
Add timeout attribute for prometheus metrics provider

### ISSUE THREAD

**Issue by AhmedGrati** [argoproj/argo-rollouts#2892]
# Summary

Add timeout attribute in the Prometheus metric provider of the `AnalysisTemplate`. It would look something like this:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 5m
    # NOTE: prometheus queries return results in the form of a vector.
    # So it is common to access the index 0 of the returned array to obtain the value
    successCondition: result[0] >= 0.95
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus.example.com:9090
        timeout: 40
```

# Use Cases

Can be useful when the query to the Prometheus server takes more than the default timeout which is `30 seconds`.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
