### ISSUE TITLE
Cors settings for setHeaderRoute:

### ISSUE THREAD

**Issue by turbotankist** [argoproj/argo-rollouts#2895]
# Summary
We have an istio virtual-service with cors
```
spec:
  http:
  - corsPolicy:
      allowCredentials: false
      allowHeaders:
      - '*'
      allowMethods:
      - POST
      - HEAD
      - GET
      allowOrigins:
      - exact: https://example.com
    name: canary-by-weight
    route:
    - destination:
        host: servicename
        port:
          number: 8080
      weight: 100
    - destination:
        host: servicename-canary
        port:
          number: 8080
      weight: 0
```
# Use Cases
if we deploy rollout with steps
```
      steps:
      - setCanaryScale:
          replicas: 2
      - setHeaderRoute:
          match:
          - headerName: x-canary
            headerValue:
              prefix: "true"
          name: canary-by-header
      - setWeight: 20
      - pause: {}
      trafficRouting:
        istio:
          virtualServices:
          - name: myservice
            routes:
            - canary-by-weight
        managedRoutes:
        - name: canary-by-header
```
then  the result virtualservice is
```
spec:
  http:
  - match:
    - headers:
        x-canary:
          prefix: "true"
    name: canary-by-header
    route:
    - destination:
        host: fillforms-canary
        port:
          number: 8080
      weight: 100
  - corsPolicy:
      allowCredentials: false
      allowHeaders:
      - '*'
      allowMethods:
      - POST
      - HEAD
      - GET
      allowOrigins:
      - exact: https://example.com
    name: canary-by-weight
    route:
    - destination:
        host: servicename
        port:
          number: 8080
      weight: 80
    - destination:
        host: servicename-canary
        port:
          number: 8080
      weight: 20
```
as a result the route `canary-by-header` doesn't work correctly without cors settings.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
