### ISSUE TITLE
setHeaderRoute adds header rules to aws load balancer in the wrong order

### ISSUE THREAD

**Issue by sametdoksanoglu** [argoproj/argo-rollouts#2902]
Describe the bug

The setHeaderRoute adds header rules to aws load balancer but in the wrong order. Header rule is added just after host rule. Since the host rule matches all the traffic. The header rule does not take any effect. Solution should be header rule should come before host rule.

To Reproduce
The setHeaderRoute on the steps:

**argoproj.io/v1alpha1 yaml related part** 
```
       trafficRouting:
        managedRoutes:
          - name: header-rule
        alb:
          ingress: test-server-external
          rootService: test-server
          servicePort: 8080
```
 
 **service yaml** 
```
apiVersion: v1
kind: Service
metadata:
  name: test-server
  namespace: test-namespace
  labels:
    app: test-server
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: test-server
  type: ClusterIP
  sessionAffinity: None
```
 
 **ingress yaml** 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: test-namespace
  name: test-server
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/load-balancer-name: test-server-external
    alb.ingress.kubernetes.io/conditions.test-server: >
      [{"field":"http-request-method","httpRequestMethodConfig":{"Values":["POST","GET"]}}]

spec:
  rules:
    - host: HOST
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-server
                port:
                  name: use-annotation
 ```
 
 **Version**
Argo rollout: 1.4.1
AWS ALB Controler : 2.5.2

**Comment by Mufaddal5253110** [comment]
I encountered the similar problem and have provided a workaround in issue #2829; you can attempt to apply this as well.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: test-namespace
  name: test-server
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/load-balancer-name: test-server-external
    alb.ingress.kubernetes.io/conditions.test-server: >
      [{"field":"http-request-method","httpRequestMethodConfig":{"Values":["POST","GET"]}}]

spec:
  rules:
    - host: HOST
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: test-server
                port:
                  name: use-annotation
```
