### ISSUE TITLE
CRD: allow specification of the desired step to be in

### ISSUE THREAD

**Issue by Snaipe** [argoproj/argo-rollouts#2906]
# Summary

One point of resistance in adopting Argo Rollouts for us is the departure from GitOps to represent the transitive state of a rollout. In other words, there are no good, streamlined way to represent in git which step the Rollout object is supposed to be at, and instead the documentation recommends using kubectl argo rollouts to manage rollouts, which is not version controlled.

Perhaps more importantly, if a rollout pauses for an extended period of time (say 12 hours), then whomever started the deployment will likely not be around or ready when the next step kicks in.

Today, this can be achieved sub-optimally by making use of the paused attribute. For instance, you could define a handful of steps to set the traffic weight, with pauses of 1h in between, start the rollout as paused, and flip-flop `.spec.paused` between true to resume the rollout whenever someone is back at their desk and false whenever said person walks out. This is of course not great.

It would be an improvement if we could specify which step the rollout is supposed to be at, and have Argo Rollouts reconcile the deployment to be at that step.

This could be implemented as a new `step` attribute in the rollout spec, which could be an index in the steps list:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  step: 1 # refers to .spec.strategy.canary.steps[1]
  strategy:
    canary:
      steps:
      - setWeight: 20
      - setWeight: 40
      - setWeight: 60
      - setWeight: 80
```

... or, we could make this more palatable by naming steps and using that:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  step: 40% # still refers to .spec.strategy.canary.steps[1]
  strategy:
    canary:
      steps:
      - setWeight: 20
      - name: 40%
        setWeight: 40
      - setWeight: 60
      - setWeight: 80
```

# Use Cases

This would allow for a pure-gitops flow for managing red-green/canary deployments.

### An Example Flow

Let's start from the demo rollout, with only `steps` modified for the sake of this example.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 20
      - setWeight: 40
      - setWeight: 60
      - setWeight: 80
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
```

Applying this deploys `argoproj/rollouts-demo:blue`, serving 100% of the traffic.

Now, let's say we want to update this to green, starting with a weight of 40 (i.e. step 1). We would make the following commit:

```diff
diff --git a/orig.yaml b/new.yaml
index 74a28c3..82eacb3 100644
--- a/orig.yaml
+++ b/new.yaml
@@ -4,6 +4,7 @@ metadata:
   name: rollouts-demo
 spec:
   replicas: 5
+  step: 1
   strategy:
     canary:
       steps:
@@ -22,7 +23,7 @@ spec:
     spec:
       containers:
       - name: rollouts-demo
-        image: argoproj/rollouts-demo:blue
+        image: argoproj/rollouts-demo:green
         ports:
         - name: http
           containerPort: 8080
```

Argo Rollouts would reconcile this, start the new deployment, execute steps 0 and 1, and stop.

If we wanted to proceed with the deployment, we'd either set `step` to 3 (i.e. the last step), or remove `step` altogether (at which points the steps would get executed to completion).

But let's say we discovered an issue with the green deployment and wanted to roll back. No problem, we can just `git revert` the commit that introduced this:

```diff
diff --git a/new.yaml b/orig.yaml
index 82eacb3..74a28c3 100644
--- a/new.yaml
+++ b/orig.yaml
@@ -4,7 +4,6 @@ metadata:
   name: rollouts-demo
 spec:
   replicas: 5
-  step: 1
   strategy:
     canary:
       steps:
@@ -23,7 +22,7 @@ spec:
     spec:
       containers:
       - name: rollouts-demo
-        image: argoproj/rollouts-demo:green
+        image: argoproj/rollouts-demo:blue
         ports:
         - name: http
           containerPort: 8080
```

By reverting the template spec back to its stable state, and because the upgrade was not completed, Argo Rollouts does as usual and treats this as a rollback that it expedites.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
I am still digesting a lot of this and need to think about it more but I am thinking that instead of `step:` being thought of as the step to be at. I think having it something like `stopStep: 2` which is the step to stop at is more clear to the behaviour would you agree?

**Comment by kostis-codefresh** [comment]
Two comments here

First of all this is a welcome addition. But we need to remember that Argo Rollouts is not dependent on Argo CD. Several companies use Argo Rollouts on its own and maybe they don't even care about GitOps at all. So we should make sure that the solution selected can work in both cases (GitOps and non-GitOps)

Secondly if we implement such spec, we need to do something similar for blue/green as well.

**Comment by kostis-codefresh** [comment]
Blue/Green should have a single switch like promoted=yes/no or something similar to decide if blue/green is in the initial phase (preview doesn't get any traffic at all) or promoted one (new color gets all the traffic)

At least this is what I imagine...

**Comment by zachaller** [comment]
Yea I agree for blue green I would probably just use `pauseAt:` the example below shows both cases although rollouts only allows canary or bluegreen of course. I also think that these would not have to be implemented together but it would be nice to maintain some similarity but I see it as two seperate PR's/Issues/Proposals etc etc. I also am not sure I really love the blue green side of it yet but as I think about it more that could change not opposed I just see less value as well.

```
spec:
  step: 1 # refers to .spec.strategy.canary.steps[1]
  strategy:
    canary:
      pauseAtStep:
    blueGreen:
      pauseAt:
```
