### ISSUE TITLE
Shared Prometheus provider config

### ISSUE THREAD

**Issue by akselleirv** [argoproj/argo-rollouts#2954]
# Summary

I want to have support for a shared Prometheus authentication method. 
# Use Cases

Given this `ClusterAnalysisTemplate` 

```
apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: generic-prometheus
spec:
  args:
    - name: prometheus-query
    - name: auth-token
      valueFrom:
        secretKeyRef:
          name: argo-rollouts-prom-token
          key: token
    - name: success-condition
  metrics:
    - name: query
      provider:
        prometheus:
          address: "http://example.com"
          headers:
            - key: Authorization
              value: "Bearer {{`{{  args.auth-token }}`}}"
          query: "up"
```

And if I would use this in a `Rollout` located in the default namespace, then the `argo-rollouts-prom-token` secret would be looked up in the default namespace.  However, I want to lookup a secret in the `argo-rollouts` namespace.

Another more preferred approach would be to reference a file inside the argo-rollouts controller. For example, I would use [service account token projection ](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#launch-a-pod-using-service-account-token-projection) and use that token to authenticate the argo-rollouts controller to a prometheus instance.

 
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
