### ISSUE TITLE
Analysis Step Stuck After Inconclusive Result in Argo Rollouts

### ISSUE THREAD

**Issue by pasha-codefresh** [argoproj/argo-rollouts#3015]
I encountered an issue when using Argo Rollouts in the [Argo Rollouts repository](https://github.com/argoproj/argo-rollouts). The problem occurs when I create rollouts that include an analysis step with an inconclusive result, followed by a pause step. Subsequently, when I attempt to promote the rollout using the `kubectl argo rollouts promote` command, the analysis step becomes stuck, and the rollout does not proceed as expected.

**Steps to Reproduce:**
1. Create a rollout YAML manifest that includes an analysis step with inconclusive results, followed by a pause step.
2. Apply the rollout manifest to your Kubernetes cluster.
3. Trigger the rollout using `kubectl argo rollouts promote`.

**Expected Behavior:**
The rollout should proceed as expected, with the analysis step functioning correctly and allowing further steps to execute after the analysis step.

**Actual Behavior:**
The analysis step becomes stuck, preventing the rollout from progressing further after the inconclusive analysis result.

**Example Rollout YAML Manifest:**

```yaml
strategy:
  canary:
    steps:
      - setWeight: 20
      - analysis:
          templates:
          - templateName: star-w-template-3-inconclusive
      - pause: {duration: 50s}
      - pause: {duration: 40s}
      - pause: {duration: 40s}
``` 

**Example AnalysisTemplate:**

```yaml
kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: star-w-template-3-inconclusive
spec:
  metrics:
  - name: starw-api-2
    count: 2
    interval: 5s
    initialDelay: 5s
    inconclusiveLimit: 1
    consecutiveErrorLimit: 3
    failureCondition: result == '170'
    successCondition: result == '175'
    failureLimit: 2
    provider:
      web:
        url: https://swapi.dev/api/people/1
        timeoutSeconds: 20 # defaults to 10 seconds
        jsonPath: "{$.height}"
```
