### ISSUE TITLE
HTTP Endpoint Migration

### ISSUE THREAD

**Issue by aweis89** [argoproj/argo-rollouts#3043]
# Summary

The objective is to enable controlled transitions of HTTP endpoints from one service (legacy) to another service (new), both implementing the same HTTP API. This will leverage Argo Rollouts' Analysis, Experiments, and Rollbacks features. The primary focus is to use Argo Rollouts for testing and traffic shifting during this endpoint migration, allowing migrations to be conducted incrementally—either in a canary-like fashion or all at once, in a blue/green manner.
 
# Use Cases

When transitioning from a monolithic to a microservices architecture, it becomes essential to incrementally move HTTP endpoints from the legacy service to the new service. Both services are expected to implement the same HTTP API. The ability to perform analyses and experiments ensures a controlled transition with rollback capabilities.

# Open questions

API and Controller Design: A new Custom Resource (CR) could be used to implement this functionality. The new CR would have its own spec and controller logic, focusing solely on traffic routing and associated analyses, without managing Pod lifecycles. Alternatively, this can be overloaded into the existing Rollout API by adding a field like `disablePodLifecycleManagement`.

Setting replicas: The implementation and API of this might need to change in order to take into account that both services are being managed by separate Deployments/Rollouts and possibly separate HPAs as well. For example, we might need a reference to the Deployment/Rollout and/or its HPA in-order to manipulate replicas in-addition to traffic routing.

Other than that, I think much of API could remain the same:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: HttpEndpointRollout
metadata:
  name: my-http-endpoint-rollout
spec:
  newEndpointScalingRef: # used for setting replica count
    kind: Rollout  # perhaps could also be Deployment or HPA
    name: new-service-rollout
  strategy:
    canary:
      steps:
      - setWeight: 10  # set 10% weight on new service
      - pause: {duration: 1h}
      - setWeight: 30
      - pause: {duration: 3h}
      - setWeight: 100  # set 100% weight on new service
       # keep background analysis running for 1w and rollback in the event of failure
      - pause: {duration: 1w}
  analysis:
    templates:
    - templateName: success-rate
  trafficRouting:
    virtualService:  # contains the routing rules that this would be limited to and where weights would be applied
      name: my-traffic-split
    trafficSplit:  # or for linkerd/SMI
      name: my-traffic-split

```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
