### ISSUE TITLE
analysis.args[].valueFrom.fieldRef passed inconsistently for background vs. inline

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#3053]
**Describe the bug**

Consider the following background analysis where we pass a parameter to analysis from the rollout labels:

```yaml
  strategy:
    canary:
      analysis:
        args:
          - name: tag
            valueFrom:
              fieldRef:
                fieldPath: 'metadata.labels[''tags.datadoghq.com/version'']'
```

But then, in the same we also do inline analysis and pass the same label:

```yaml
      steps:
        - setWeight: 1
        - pause:
            duration: 1m
        - analysis:
            args:
              - name: tag
                valueFrom:
                  fieldRef:
                    fieldPath: 'metadata.labels[''tags.datadoghq.com/version'']'
```

The resulting AnalysisRuns will use the *older label value* when starting the background analysis:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisRun
metadata:
  labels:
    rollout-type: Background
  name: guestbook-6c99c95749-325
spec:
  args:
    - name: tag
      value: 20230920-0114      # << this is the old
```

But will use the *new label value* when starting the inline analysis step:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisRun
metadata:
  labels:
    rollout-type: Step
    step-index: '2'
  name: guestbook-6c99c95749-325-2
spec:
  args:
    - name: tag
      value: 20230920-0221      # << this is the new
```

**To Reproduce**

Have a Rollout with a label that is passed to background and inline Analysis

**Expected behavior**

It should be consistent.

**Screenshots**

**Version**

v1.4

**Logs**

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
When trying to reproduce this, it seems to be working as expected:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: cat-fact
  labels:
    cat-fact-id: 5887e1d85c873e0011036889     # this must be modified at same time as container image
spec:
  strategy:
    canary:
      analysis:
        templates:
        - templateName: cat-fact
        args:
        - name: id
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['cat-fact-id']
      steps:
      - analysis:
          templates:
          - templateName: cat-fact
          args:
          - name: id
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['cat-fact-id']
      - pause: {}
  selector:
    matchLabels:
      app: cat-fact
  template:
    metadata:
      labels:
        app: cat-fact
    spec:
      containers:
      - name: rollouts-demo
        image: nginx:1.19-alpine    # modify this at same time as label
        resources:
          requests:
            memory: 16Mi
            cpu: 5m
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cat-fact
spec:
  args:
    - name: id
  metrics:
  - name: web
    interval: 5s
    count: 3
    successCondition: status.verified == true
    provider:
      web:
        url: "https://cat-fact.herokuapp.com/facts/{{args.id}}"
```

I modified image and changed label to `58e009390aac31001185ed10`, which produced the following two analysisruns:


```yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisRun
metadata:
  name: cat-fact-5c6c964669-2
spec:
  args:
  - name: id
    value: 58e009390aac31001185ed10
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisRun
metadata:
  name: cat-fact-5c6c964669-2-0
spec:
  args:
  - name: id
    value: 58e009390aac31001185ed10
```

I suspect the original problem may have been that the label may have been updated in a separate API call from the pod spec update. Because we start the background analysis as soon as the pod spec changes, the label and pod spec must be part of the same update. Otherwise, background analysis will start before the label update, and so will use the old label.

I will work with the original user to confirm.

**Comment by jessesuen** [comment]
If it turns out that the label update happens after the pod spec update, and it is difficult to change them at the same time, then the following workaround may be to use the `startingStep` feature of background analysis.

```yaml
spec:
  strategy:
    canary:
      analysis:
        startingStep: 1     will wait for steps[1] before creating background analysis 
        templates:
        - templateName: cat-fact
        args:
        - name: id
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['cat-fact-id']
      steps:
      - pause:
          duration: 10s    # this maximum time that you expect the label to be updated
      - analysis:
          templates:
          - templateName: cat-fact
          args:
          - name: id
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['cat-fact-id']
```

**Comment by jessesuen** [comment]
Spoke with the user and clarified that they are using the workloadRef feature. So there is a timing issue similar to what I described above. What happens is:

1. Deployment is updated with new image
2. Controller detects this and kicks off background analysisrun with older `metadata.labels` value in the Rollout
3. Rollout is updated with new labels
4. Controller reaches step with inline analysis, and kicks off inline analysis with newer `metadata.labels`

I am able to reproduce the behavior by first applying the Deployment change:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-fact
spec:
  replicas: 0
  selector:
    matchLabels:
      app: cat-fact
  template:
    metadata:
      labels:
        app: cat-fact
    spec:
      containers:
      - name: rollouts-demo
        image: nginx:1.10-alpine    # modify this
        resources:
          requests:
            memory: 16Mi
            cpu: 5m
```

Then waiting a few seconds, and applying the Rollout with new label:

```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: cat-fact
  labels: # pick one to change:
    #cat-fact-id: 5887e1d85c873e0011036889
    cat-fact-id: 58e00b5f0aac31001185ed24
    #cat-fact-id: 58e009390aac31001185ed10
    #cat-fact-id: 58e00af60aac31001185ed1d
    #cat-fact-id: 58e008780aac31001185ed05
spec:
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cat-fact
  strategy:
    canary:
      analysis:
        templates:
        - templateName: cat-fact
        args:
        - name: id
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['cat-fact-id']
      steps:
      - analysis:
          templates:
          - templateName: cat-fact
          args:
          - name: id
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['cat-fact-id']
      - pause: {}

---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cat-fact
spec:
  args:
    - name: id
  metrics:
  - name: web
    interval: 5s
    count: 3
    successCondition: result.status.verified == true
    provider:
      web:
        url: "https://cat-fact.herokuapp.com/facts/{{args.id}}"
```

So the workaround that I [described above](https://github.com/argoproj/argo-rollouts/issues/3053#issuecomment-1736306065) still valid. Basically, we need to delay background analysis until **_after_** the rollout is updated. And the way we can do this is by injecting a small delay as a canary step, and using the `startingStep` feature of background analysis.

NOTE: the workaround is not completely foolproof. If it takes more than 10s for the rollout to be updated after the deployment, it will still pick up the old value.
