### ISSUE TITLE
Downward API support

### ISSUE THREAD

**Issue by Desolar1um** [argoproj/argo-rollouts#3065]
# Summary

I'm not sure this is the case, but in my use it certainly has been. The Rollout resource seems to not support downward API.

# Use Cases

I use downward API to define a POD_NAME env variable used by my application as seen in the below example. Since switching to Rollout, the value of this var within the Pod is empty, hence app dies. I've worked around this a different way, but downward support would be really appreciated

```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: name
  namespace : namespace
  labels:
    app: name
spec:
  revisionHistoryLimit: 1
  strategy:
    canary:
      canaryService: name-canary
      stableService: name
      trafficRouting:
        nginx:
          stableIngress: name
      steps:
      - setWeight: 20
      - pause: {duration: 10}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  selector:
    matchLabels:
      app: name
  template:
    metadata:
      labels:
        app: name
    spec:
      imagePullSecrets:
      - name: secret
      containers:
      - name: name
        image: img
        livenessProbe:
          httpGet:
            port: http
            path: /livez
          initialDelaySeconds: 400
          periodSeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            port: http
            path: /readyz
          initialDelaySeconds: 10
          periodSeconds: 3
          timeoutSeconds: 5
        ports:
        - name: http
          containerPort: 8080
        - name: management
          containerPort: 9080
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      terminationGracePeriodSeconds: 120
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
