### ISSUE TITLE
Rollout failing with msg "the object has been modified; please apply your changes to the latest version"

### ISSUE THREAD

**Issue by pdeva** [argoproj/argo-rollouts#3080]
Checklist:

* [ x] I've included steps to reproduce the bug.
* [ x] I've included the version of argo rollouts.

**Describe the bug**
updates to services in argo rollouts are failing suddenly with this msg for no reason. the only change we made was change the image tag of the Rollout

**To Reproduce**
it fails and gets in this state when mutliple rollout image tags are updated at once. if we then do a `rollout retry` one service at a time, each service succeeds.

**Expected behavior**
Rollout should succeed. has no reason to fail since the only thing chaged is updated image tag

**Screenshots**
<img width="2957" alt="Screenshot 2023-10-05 at 8 01 19 PM" src="https://github.com/argoproj/argo-rollouts/assets/3190176/e43989eb-db86-4da8-b8ab-29cb414aef84">

<img width="1489" alt="Screenshot 2023-10-05 at 8 05 02 PM" src="https://github.com/argoproj/argo-rollouts/assets/3190176/a952c0fa-3ad7-4074-85e0-8bd332befd8a">

**Version**
1.6.0

**Logs**

```
roCtx.reconcile err Operation cannot be fulfilled on replicasets.apps "pg-query-65bc4849f5": the object has been modified; please apply your changes to the latest version and try again
```
```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by bpoland** [comment]
Hi @zachaller I am still seeing this `the object has been modified; please apply your changes to the latest version` error with replicasets using 1.6.2 which includes the fix from #3091 :(

**Comment by zachaller** [comment]
@bpoland It's a relatively normal log, Rollouts will retry the update, is there an issue you think this might be causing?

**Comment by bpoland** [comment]
> @bpoland It's a relatively normal log, Rollouts will retry the update, is there an issue you think this might be causing?

Yeah our rollout got stuck and I saw this message over and over.  The behaviour we saw was:
1. The rollout was in a healthy state (or so it said)
2. We updated the image on the Rollout (we are using workload referencing, in case that matters)
3. Rollouts created a new ReplicaSet with the updated image, but the new RS had 0 replicas (even though our first step is `setWeight: 1`) and nothing seemed to be happening
4. I manually promoted to the next step which is a pause and then to the next step `setWeight: 2` -- still the new RS was stuck at 0 replicas (Rollout was marked as "Progressing")
5. I tried manually scaling up the new RS to 1 replica. The new pod started but the steps did not progress
6. I checked rollout controller logs and saw it complaining about an RS for an old revision.  I manually deleted that RS and then the rollouts controller immediately picked up with the next step and the issue was resolved

**Comment by mclarke47** [comment]
I'm also seeing a LOT of these in the controller logs with a very similar setup to @bpoland which is causing rollouts to get stuck unless we manually retry the failures

**Comment by zachaller** [comment]
Do you guys have any type of policy agent that modifies the replicasets or possible the pod spec in the replicaset?

**Comment by zachaller** [comment]
@pdeva Are you able to reliably reproduce this. Also your image has a bunch of issues with the VirtualService but then you also show a log line on the ReplicaSet so it could be something else also modifying the VirtualService

**Comment by mclarke47** [comment]
@zachaller We have policy agents but it seemed to work fine on v1.3.0 which we just upgraded from.

I managed to find a rollout stuck in progress because it seemed like it wasn't updating the replica count in the new replica set.

<img width="922" alt="Screenshot 2023-11-13 at 8 31 32 AM" src="https://github.com/argoproj/argo-rollouts/assets/6514980/8f4f21a4-d5af-4dcf-b4d1-9595d9fb42b9">
<img width="1499" alt="Screenshot 2023-11-13 at 8 31 51 AM" src="https://github.com/argoproj/argo-rollouts/assets/6514980/cbce1c01-c8fc-4057-9bce-2a813f421fe1">
<img width="850" alt="Screenshot 2023-11-13 at 8 31 25 AM" src="https://github.com/argoproj/argo-rollouts/assets/6514980/9f0e88dd-707d-4527-9178-53b2704619cd">

[controller logs](https://gist.github.com/mclarke47/6bf96716ce34771058ef14ebf3d0484a)

**Comment by bpoland** [comment]
> Do you guys have any type of policy agent that modifies the replicasets or possible the pod spec in the replicaset? I have not experianced this and have never been able to reproduce it, most of the cases that I have seen people had some other controller fighting with rollouts controller on the replicaset that's not to say there isn't some issue within the rollouts controller just need to be able to reproduce it.

We have a linkerd injector which adds a container, maybe that is related?  Similar to @mclarke47 though, we have not experienced this previously (currently trying to upgrade from 1.4.1)

**Comment by zachaller** [comment]
I want to just comment I think we are also seeing some issues as well with one of our clusters in regards to this so spending some time looking into it.

**Comment by bpoland** [comment]
We don't use notifications currently.

**Comment by mclarke47** [comment]
No notification use here

**Comment by int128** [comment]
I have faced the similar problems in our cluster.

### 1. Rollout is stuck while canary update
When a Rollout is updated, both old and new ReplicaSet are running and then Rollout is stuck.
I could see the following message in the status of Rollout.

```
old replicas are pending termination
```

Here is a snippet of kubectl get replicaset. Hash `676f9f555d` are new, and `7b7cdd9847` is old.

```
worker-676f9f555d-25xd9                      1/1     Running     0          3h22m
worker-676f9f555d-dkmlt                      1/1     Running     0          3h22m
worker-7b7cdd9847-d4xl6                      1/1     Running     0          5h8m
```

I deleted the old ReplicaSet and then Rollout status became Healthy.

### 2. Rollout status becomes Degraded even if pods are running
When a Rollout is updated, it becomes the degraded status even if all new pods are running.
I could see the following message in the status of Rollout:

```
ProgressDeadlineExceeded: ReplicaSet "poller-64d95bc44b" has timed out progressing.
```

I could refresh the status of Rollout by restating the argo-rollouts-controller.

**Comment by zachaller** [comment]
Just released it, can you try it out?

**Comment by bpoland** [comment]
We've also upgraded and haven't seen the issue again since. Thanks!

**Comment by NaurisSadovskis** [comment]
hey folks, we're also seeing this on the latest Argo Rollouts version (the unreleased 1.7.x). 

In our case, we have a process which annotates (and labels) `Rollout` objects on each application deploy and we suspect the issue happens when:
1. Underlying `Deployment` is modified (triggering a new rollout) and a new `ReplicaSet` is created with the same labels/annotations as the original `Rollout` (`foo: bar`)
2. `Rollout` progresses
3. The original `Rollout` object is modified with a new label (`foo: foobar`) and `Deployment` is modified (again, triggering a new rollout)
4. This triggers the errors we've seen above.

_In some cases_, Argo Rollout Controller seems to lock up and stop reporting any data for that particular `Rollout` (usually one out of 15 we're running at a time) and the solution is to restart the controller to force it to reconcile the `Rollout` to the latest version it should be.

**Comment by zachaller** [comment]
@NaurisSadovskis Did you also see the issue on 1.5, the logs would be different and not log the error but could you also see if rollouts got stuck?

**Comment by int128** [comment]
I updated the controller to v1.6.4 and [this problem](https://github.com/argoproj/argo-rollouts/issues/3080#issuecomment-1835809731) occurs again.

For a workaround, we run a CronJob to restart the controller every day.

**Comment by zachaller** [comment]
@NaurisSadovskis would you be able to test a version with this patch: https://github.com/argoproj/argo-rollouts/pull/3272

**Comment by NaurisSadovskis** [comment]
@zachaller updated and the problem persists - more specifically controller is active, but it gets stuck on rolling out the new ReplicaSet. the  @int128's solution of restarting the controller solves this again.

**Comment by ajhodgson** [comment]
Just experienced this. 1.6.6. Definitely seems related to HPA.

**Comment by dodwmd** [comment]
We're also seeing this issue, using latest release.

**Comment by Danny5487401** [comment]
rollouts: v1.6.6 still have the same issue
![image](https://github.com/argoproj/argo-rollouts/assets/64348131/f40cb6be-28d8-4789-90a2-cf7c7054b6d7)

**Comment by marcusio888** [comment]
Good morning, the case must be reopened since with the new version of argo rollout v1.6.6 it continues to happen, in my case from time to time we have to restart argo rollout for it to be fixed. Annex logs.
`time="2024-03-18T12:34:23Z" level=info msg="Started syncing rollout" generation=651 namespace=homo resourceVersion=828745943 rollout=gqlpatear
time="2024-03-18T12:34:23Z" level=error msg="roCtx.reconcile err error updating replicaset in syncEphemeralMetadata: Operation cannot be fulfilled on replicasets.apps \"gqlpatear-5d58b9cb64\": the object has been modified; please apply your changes to the latest version and try again" generation=651 namespace=homo resourceVersion=828745943 rollout=gqlpatear
time="2024-03-18T12:34:23Z" level=info msg="Reconciliation completed" generation=651 namespace=homo resourceVersion=828745943 rollout=gqlpatear time_ms=37.496694
time="2024-03-18T12:34:23Z" level=error msg="rollout syncHandler error: error updating replicaset in syncEphemeralMetadata: Operation cannot be fulfilled on replicasets.apps \"gqlpatear-5d58b9cb64\": the object has been modified; please apply your changes to the latest version and try again" namespace=homo rollout=gqlpatear
time="2024-03-18T12:34:23Z" level=info msg="rollout syncHandler queue retries: 23471 : key \"homo/gqlpatear\"" namespace=homo rollout=gqlpatear
time="2024-03-18T12:34:23Z" level=error msg="error updating replicaset in syncEphemeralMetadata: Operation cannot be fulfilled on replicasets.apps \"gqlpatear-5d58b9cb64\": the object has been modified; please apply your changes to the latest version and try again\n" error="<nil>"`

**Comment by bpoland** [comment]
@zachaller can we reopen this issue? We are also continuing to hit it

**Comment by omer2500** [comment]
We are facing the same issue on v1.6.6

**Comment by DimKanoute** [comment]
Hey, coming here to say that we are facing the exact same issue. 

When HPA that scales a rollout, this will come into conflict with the argo-rollouts controller.

**Comment by bpoland** [comment]
I think this is the same issue so maybe we should keep posting over there: https://github.com/argoproj/argo-rollouts/issues/3316

**Comment by int128** [comment]
Unfortunately, we still need to restart the controllers of our clusters every hour.

Here is an example of CronJob.

```yaml
# Restart argo-rollouts every hour to avoid the following error:
# https://github.com/argoproj/argo-rollouts/issues/3080#issuecomment-1835809731
apiVersion: batch/v1
kind: CronJob
metadata:
  name: argo-rollouts-periodically-restart
spec:
  schedule: "0 * * * *" # every hour
  jobTemplate:
    spec:
      backoffLimit: 2
      ttlSecondsAfterFinished: 259200 # 3 days
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: argo-rollouts-periodically-restart
          containers:
            - name: kubectl-rollout-restart
              image: public.ecr.aws/bitnami/kubectl:1.29.1
              command:
                - kubectl
                - --v=3
                - --namespace=argo-rollouts
                - rollout
                - restart
                - deployment/argo-rollouts
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - "ALL"
              resources:
                limits:
                  memory: 64Mi
                requests:
                  cpu: 10m
                  memory: 64Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-rollouts-periodically-restart
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-rollouts-periodically-restart
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-rollouts-periodically-restart
subjects:
  - kind: ServiceAccount
    name: argo-rollouts-periodically-restart
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-rollouts-periodically-restart
rules:
  # https://stackoverflow.com/a/68980720
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["argo-rollouts"]
    verbs: ["get", "patch"]
```
