### ISSUE TITLE
Breaking changes when using kustomize v5 with rollout-transform.yaml

### ISSUE THREAD

**Issue by dlemfh** [argoproj/argo-rollouts#3105]
Checklist:

* [x] I've included steps to reproduce the bug.
* [ ] ~~I've included the version of argo rollouts.~~
  * → This issue is not tied to any specific argo rollouts version.

**Describe the bug**

Using kustomize v5.x.x with [rollout-transform.yaml](https://github.com/argoproj/argo-rollouts/blob/master/docs/features/kustomize/rollout-transform.yaml) causes breaking changes.

A kustomization.yaml that uses [rollout-transform.yaml](https://github.com/argoproj/argo-rollouts/blob/master/docs/features/kustomize/rollout-transform.yaml) along with the `labels` directive (with `includeSelectors: false` and `includeTemplates: true`) stops working correctly when upgrading kustomize to v5.

Example of kustomization.yaml that breaks:
```yaml
# Adapted snippet from `test/kustomize/rollout/kustomization.yaml`
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- ../../../docs/features/kustomize/rollout-transform.yaml

resources:
- rollout.yaml

labels:
- includeSelectors: false
  includeTemplates: true
  pairs:
    baz: qux

openapi:
  path: https://raw.githubusercontent.com/argoproj/argo-schema-generator/main/schema/argo_all_k8s_kustomize_schema.json
```

**To Reproduce**

I've forked and updated the kustomize test here: https://github.com/dlemfh/argo-rollouts/commit/ffe1f7fac7ff6e7e9f76060a59bceb5d8c032d8b#diff-e3c72800a3ccfbc82af00dd308fa4dd944d5e1702ed5e3ff5e807e91e39b2e23

Here you can check that running `make test-kustomize` with kustomize@v5 fails the test.
```bash
git clone git@github.com:dlemfh/argo-rollouts.git
cd argo-rollouts
git checkout edit-kustomize-test
brew install kustomize  # install latest kustomize (v5.x.x)

make test-kustomize
# check that test fails

# Note that if you run the test using kustomize v4, the test will pass.
```

**Expected behavior**

Using kustomize with [rollout-transform.yaml](https://github.com/argoproj/argo-rollouts/blob/master/docs/features/kustomize/rollout-transform.yaml) + `labels` with `includeSelectors: false` and `includeTemplates: true` should patch the specified label into both the rollout's `/metadata/labels` and `/spec/template/metadata/labels`.

However, using kustomize@v5 the same kustomization.yaml fails to patch the specified label into the `/spec/template/metadata/labels` field.

The reason is because starting kustomize@v5, using `labels` with `includeSelectors: false` and `includeTemplates: true` [takes its configuration from a new transformer configuration directive named `templateLabels`](https://github.com/kubernetes-sigs/kustomize/commit/e2196d9bd1a2fe97a9f54a125ece16e0e819a4e0),
which is not currently accounted for in [rollout-transform.yaml](https://github.com/argoproj/argo-rollouts/blob/master/docs/features/kustomize/rollout-transform.yaml).

**Screenshots**

**Version**

**Logs**

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
