### ISSUE TITLE
Rollout objects cannot use Bidirectional mountPropagation

### ISSUE THREAD

**Issue by martynd** [argoproj/argo-rollouts#3130]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've included the version of argo rollouts.

**Describe the bug**

Attempting to use `mountPropagation: Bidirectional` along with the requisite `privileged: true` in the `securityContext` results in the error `Forbidden: Bidirectional mount propagation is available only to privileged containers`
Creating an identical `Deployment` validates and is created as expected
Looking at the validation code, I suspect it comes from the fact it appears to drops privileged for certain operations.

**To Reproduce**

Create the following both in `Deployment` and `Rollout` form (their api version parts provided separately for convenience)

```
apiVersion: apps/v1
kind: Deployment
```
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
```
```
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /tmp
          mountPropagation: Bidirectional
          name: a-dir-to-mount
      volumes:
      - emptyDir: {}
        name: a-dir-to-mount
```

**Expected behavior**

The `Rollout` changes to be accepted and deployed in the same manner as the `Deployment` resource

**Version**
v1.6.0

**Logs**

```
{"level":"error","msg":"The Rollout \"test\" is invalid: spec.template.spec.containers[1].volumeMounts.mountPropagation: Forbidden: Bidirectional mount propagation is available only to privileged containers","namespace":"public","rollout":"test","time":"2023-10-26T23:04:10Z"}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
