### ISSUE TITLE
Canary rollout: analysis run from previous step remains running after promotion

### ISSUE THREAD

**Issue by oleksandr-codefresh** [argoproj/argo-rollouts#3220]
Checklist:

* [ ] I've included steps to reproduce the bug.
* [ ] I've included the version of argo rollouts.

**Describe the bug**

If canary rollout has 2 or more analysis steps one-by-one and you perform promotion on n-1 step with analysis. Analysis run of previous step will remain running while appropriate to new step won't be created.

**To Reproduce**

1. create canary rollout with 3 steps and 2 analysis steps one-by-one
```
- setWeight: 50
- analysis:
     templates:
     - templateName: test-template-a
- analysis:
     templates:
     - templateName: test-template-b     
```

2. try to call promote on `test-template-a` analysis step

**Expected behavior**

Old analysis run should be terminated and new one (for current step) should be created.

**Screenshots**
 \-

**Version**

tested on 1.5.0 and 1.6.3 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
