### ISSUE TITLE
Canary deployment duplicate metrics on Prometheus ServiceMonitor

### ISSUE THREAD

**Issue by leonardosmartins** [argoproj/argo-rollouts#3225]
**Describe the bug**

I'm using the canary deployment with Istio and Prometheus ServiceMonitor to collect pod metrics. During the canary deployment execution, the ServiceMonitor collects metrics from the stable service and also from the canary service and this is fine, because the stable service and the canary service point to different pods. But when the canary deployment ends, the stable service and the canary service point to the same pods and the ServiceMonitor keeps collecting metrics from both services, causing duplicate metrics on Prometheus

**To Reproduce**

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: demo-rollouts
  name: demo-rollouts
  namespace: demo-rollouts
spec:
  selector:
    matchLabels:
      app: demo-rollouts
  strategy:
    canary:
      canaryMetadata:
        annotations:
          version: canary
        labels:
          service.istio.io/canonical-revision: canary
          version: canary
      canaryService: demo-rollouts-canary
      stableMetadata:
        annotations:
          version: stable
        labels:
          service.istio.io/canonical-revision: stable
          version: stable
      stableService: demo-rollouts
      steps:
        - setWeight: 30
        - pause: {}
      trafficRouting:
        istio:
          virtualServices:
            - name: demo-rollouts
  template:
    metadata:
      labels:
        app: demo-rollouts
    containers:
      image: 'argoproj/rollouts-demo:yellow'
      imagePullPolicy: IfNotPresent
      name: demo-rollouts
      ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-rollouts
  name: demo-rollouts
  namespace: demo-rollouts
spec:
  ports:
    - name: http-web
      port: 80
      targetPort: 8080
    - name: https-web
      port: 443
      targetPort: 8080
  selector:
    app: demo-rollouts
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-rollouts
  name: demo-rollouts-canary
  namespace: demo-rollouts
spec:
  ports:
    - name: http-web
      port: 80
      targetPort: 8080
    - name: https-web
      port: 443
      targetPort: 8080
  selector:
    app: demo-rollouts
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: demo-rollouts
    release: kube-prometheus-stack
  name: demo-rollouts
  namespace: demo-rollouts
spec:
  endpoints:
    - path: /metrics
  namespaceSelector:
    matchNames:
      - demo-rollouts
  selector:
    matchLabels:
      app: demo-rollouts
```
 
**Expected behavior**

Disable canary service after canary deployment ends so that the ServiceMonitor does not collect metrics from canary service.

**Version**

1.5.1

---
**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
