### ISSUE TITLE
Support maxSurge for blueGreen

### ISSUE THREAD

**Issue by sdlevi27** [argoproj/argo-rollouts#3231]
# Summary

Add support to specify a maxSurge value when using a blueGreen deployment.  It appears to only be supported in canary deployments.

# Use Cases

When restarting a rollout, we are faced with 2 options - either restart one pod at a time (default maxUnavailable), or specify a maxUnavailable > 0.  Restarting a pod one at a time can take a long time.  If we specify a maxUnavailable value, we can restart more than one pod at a time, but we run the risk of dropping below our desired pod count during the recycle.

The preferred scenario would be to allow the ReplicaSet to scale beyond the current level, spin up new pods, then terminate the old pods once the new ones are Ready.  This would allow a very quick restart while maintaining desired pod capacity.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zimmertr** [comment]
You can define a `canary` strategy that might replicate the desired behavior provided you have a Virtual Service that routes traffic to different Services based on match criteria.

```yaml
spec:
  replicas: 10
  strategy:
    canary:
      canaryService: example-service-preview
      maxSurge: 1
      stableService: example-service
      steps:
      - setWeight: 1
```
