### ISSUE TITLE
BlueGreen doesn't scale down previously active replica after a rollback

### ISSUE THREAD

**Issue by samuelbaena** [argoproj/argo-rollouts#3242]
**Describe the bug**

After performing a rollback in Argo Rollouts, I would expect the previously active replica to downscale to 0 once the `autoPromotionSeconds`, `scaleDownDelaySeconds` as well as any analysis time happens, this is not true as both the rollbacked version and the until then active/stable one remains

**To Reproduce**

```
blueGreen:
      abortScaleDownDelaySeconds: 30
      activeMetadata:
        labels:
          role: active
      activeService: demo-test
      autoPromotionEnabled: true
      autoPromotionSeconds: 30
      previewMetadata:
        labels:
          role: preview
      previewReplicaCount: 1
      previewService: demo-preview
      scaleDownDelaySeconds: 30
```

1. Deploy normally
2. Rollback to previous version

**Expected behavior**

The previously Active replica is downscaled.

**Screenshots**

![image](https://github.com/argoproj/argo-rollouts/assets/59053118/5fa3018b-50fb-42db-9281-d3613f8f5e2c)

**Version**

v1.6.0

---
**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
