### ISSUE TITLE
AnalysisRun datadog with incomplete options

### ISSUE THREAD

**Issue by marcusio888** [argoproj/argo-rollouts#3261]
Checklist:

**bug**

I have the following analysis template:

```
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate
spec:
  args:
  - name: apmname
    value: microservicename
  - name: version
    value: master
  metrics:
  - name: error-rate
    interval: 1m
    successCondition: default(result, 0) <= 100
    failureLimit: 3
    provider:
      datadog:
        apiVersion: v2
        interval: 5m
        queries:
          a: sum:trace.handle.request.errors{service:{{args.apmname}},version:{{args.version}}}.as_count()
          b: sum:trace.handle.request.hits{service:{{args.apmname}},version:{{args.version}}}.as_count()
        formula: "100 * a/b"
```
        
When the rollout executes the analysis and generates the analysisrun it fails with the following error:

```
    message: 'received non 2xx response code: 400 {"errors":["Error parsing query:
     unable to parse : Rule ''query_expr'' didn''t match at '''' (line 1, column
     1)."]}'
```
     
Reviewing the resource created by the rollout, I observe that it does not take the formula and queries values.

```
apiVersion: argoproj.io/v1alpha1
kind: AnalysisRun
metadata:
  annotations:
    rollout.argoproj.io/revision: "3"
  creationTimestamp: "2023-12-13T15:58:48Z"
  generation: 6
  labels:
    app: microservicename
    rollout-type: Background
    rollouts-pod-template-hash: 6f6ccb8f55
  name: microservicename-6f6ccb8f55-3
  namespace: homo
  ownerReferences:
  - apiVersion: argoproj.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Rollout
    name: microservicename
    uid: af39838e-9f51-4444-b2f0-ed833b2182c1
  resourceVersion: "722659980"
  uid: 84b480c4-ca6b-40fa-b669-6da111b41ddf
spec:
  args:
  - name: apmname
    value: microservicename
  - name: version
    value: master
  metrics:
  - failureLimit: 3
    interval: 1m
    name: error-rate
    provider:
      datadog:
        apiVersion: v2
        interval: 5m
        query: ""
    successCondition: default(result, 0) <= 100
```

**To Reproduce**

1. Create an analysisTemplate with datadog with the queries and formulas fields
2. Create a rollout that generates an analysisrun based on the existing analysistemplate.
3. Observe the created analysisrun resource.

**Expected behavior**

The expected behavior is that it generates an analysisrun similar to the analysistemplate with the formula and queries fields, in addition to the rollout being able to process either the query field or queries.

**Screenshots**

![Screen Shot 2023-12-19 at 02 12 39](https://github.com/argoproj/argo-rollouts/assets/39507010/4211dbc2-b5b9-4a43-abd9-1257b2e77855)

**Version**

I am using the following version of argo rollout:
```
CHART APP VERSION
argo-rollouts-2.32.5 v1.6.2
and
argo-rollouts-2.32.8 v1.6.4
```

**Logs**

```
time="2023-12-19T04:47:03Z" level=info msg="Started syncing Analysis at (2023-12-19 04:47:03.000390407 +0000 UTC m=+480.531777363)" analysisrun=patear-analysis-6d86d6fd9d-13 namespace=homo
time="2023-12-19T04:47:03Z" level=info msg="Running overdue measurement" analysisrun=patear-analysis-6d86d6fd9d-13 metric=error-rate namespace=homo
time="2023-12-19T04:47:03Z" level=info msg="Taking 1 Measurement(s)..." analysisrun=patear-analysis-6d86d6fd9d-13 namespace=homo
time="2023-12-19T04:47:03Z" level=info msg="Measurement Completed. Result: Error" analysisrun=patear-analysis-6d86d6fd9d-13 metric=error-rate namespace=homo
time="2023-12-19T04:47:03Z" level=warning msg="Measurement had error: received non 2xx response code: 400 {\"errors\":[\"Error parsing query: unable to parse : Rule 'query_expr' didn't match at '' (line 1, column 1).\"]}" analysisrun=patear-analysis-6d86d6fd9d-13 metric=error-rate namespace=homo
time="2023-12-19T04:47:03Z" level=info msg="Metric 'error-rate' transitioned from Running -> Error" analysisrun=patear-analysis-6d86d6fd9d-13 metric=error-rate namespace=homo
time="2023-12-19T04:47:03Z" level=warning msg="Metric 'error-rate' Completed. Result: Error" analysisrun=patear-analysis-6d86d6fd9d-13 event_reason=MetricError namespace=homo
time="2023-12-19T04:47:03Z" level=warning msg="Analysis Completed. Result: Error" analysisrun=patear-analysis-6d86d6fd9d-13 event_reason=AnalysisRunError namespace=homo
```

** ATTENTION THIS IS THE FIX **
The fix is ​​found in one of the branches/commits present in the repo, you can see the following link that has the expressed DatadogMetrics fields but these queries and formula fields are not found in any version with helm chart.

`https://pkg.go.dev/github.com/argoproj/argo-rollouts@v1.6.0-rc1.0.20231212164541-3a257e374031/pkg/apis/rollouts/v1alpha1#DatadogMetric`

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
