### ISSUE TITLE
autoPromotionSeconds feature not working.

### ISSUE THREAD

**Issue by dipk-mish7** [argoproj/argo-rollouts#3271]
I am trying to achieve auto promotion of preview service to active if my analysis run succeeds, However it is not working. Below is my reference code which I am using followed by argo-rollouts dashboard which says that analysis run has been successful and yet nginx:latest is on preview. As per [bluegreen-pre-promotion-analysis](https://argo-rollouts.readthedocs.io/en/release-1.5/features/analysis/#bluegreen-pre-promotion-analysis) it should have promoted. See below 
![pre-promotion](https://github.com/argoproj/argo-rollouts/assets/52923075/fcb5a2f5-08b7-468b-adf5-1318b41ff376)

```
apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
 labels:
   app: nginx
spec:
 replicas: 1
 selector:
   matchLabels:
     app: nginx
 template:
   metadata:
     labels:
       app: nginx
   spec:
     containers:
     - name: nginx
       image: nginx:latest
       ports:
       - containerPort: 80
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
 name: nginx
spec:
 replicas: 1
 selector:
   matchLabels:
     app: nginx
 workloadRef:                        
   apiVersion: apps/v1
   kind: Deployment
   name: nginx-deployment
 revisionHistoryLimit: 0
 strategy:
   blueGreen:
     activeService: nginx-svc
     previewService: nginx-svc-preview
     autoPromotionEnabled: false
     autoPromotionSeconds: 10
     prePromotionAnalysis:
       templates:
       - templateName: smoke-tests
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
 name: smoke-tests
spec:
 metrics:
 - name: smoke-test-metrics
   count: 1
   interval: 0s
   failureLimit: 0
   provider:
     job:
       spec:
         backoffLimit: 0
         template:
           spec:
             containers:
             - name: failure
               image: alpine:3.8
               command: [sh, -c]                
               args: [echo "tests finished at $(date)" && exit 0]
             restartPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-preview
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

--- 
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
```

![analysis-template](https://github.com/argoproj/argo-rollouts/assets/52923075/8476bc78-204c-453b-a094-5b47b077a6fa)
