### ISSUE TITLE
rollout doesn't honor `canary.maxSurge` and `maxUnavailable` settings when `steps` filed is defined 

### ISSUE THREAD

**Issue by shaoye** [argoproj/argo-rollouts#3284]
Checklist:

* [ ] I've included steps to reproduce the bug.
* [ ] I've included the version of argo rollouts.

**Describe the bug**

According to the doc, argo-rollout only honors `maxSurge` and `maxUnavailable` fields if only `steps` field is omitted.

If this is intentional by design, we'd like to report a production outage we just had with the following settings.

```
spec:
  strategy:
    canary:
      steps:
        - setWeight: 50
        - setHeaderRoute:
        - pause:
            duration: 1h
      dynamicStableScale: true
      maxSurge: 10%
      maxUnavailable: 0%
```

We set the first step to have a weight of 50% so we can start evaluating the canary version in step 2.

We assumed argo will create new pods gradually to Weight 50 with 10% maxSurge. But it turns out argo created 50% more pods at once and we had a outage due to excessive connections to the DB.

After pausing for 1 hour, the replica set was bumped to 100% capacity again at once because not following the 10% maxSurge strategy, once again triggered an outage. 

We are eager to understand if there is any disadvantages by following both `maxSurge` and `steps` fields.

Otherwise we have to write the steps like this

```
      steps:
        - setWeight: 10
        - setWeight: 20
        - setWeight: 30
        - setWeight: 40
        - setWeight: 50
        - setHeaderRoute:
        - pause:
            duration: 1h
        - setWeight: 60
        - setWeight: 70
        - setWeight: 80
        - setWeight: 90
        - setWeight: 100
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

1.5.0

**Logs**

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
