### ISSUE TITLE
Experiment-related environment variables for Blue-Green-Canary model

### ISSUE THREAD

**Issue by illiasokolov** [argoproj/argo-rollouts#3298]
# Summary
**Motivation**:
I use the following configuration to achieve Blue-Green-Canary release model:
```yaml
    canary:
      canaryService: lims-api-canary
      minPodsPerReplicaSet: 3 # for HA
      steps:
        - experiment:
            templates:
              - name: green-preview
                replicas: 3
                specRef: canary
                service:
                  name: green-api
                selector:
                  matchLabels:
                    app: green-api
                metadata:
                  labels:
                    app: green-api
        - setWeight: 20
        - pause: {}
```
So it created an Experiment with new ReplicaSet with new image tag. It works like Green environment as there's no production traffic and it will be deleted after it's tested by our QA. Then Canary release is starting.
Our team would like to test Green environment with "Green" database, however there's no option to change Green ReplicaSet's envs.
What change needs making?
Ability to overwrite Experiment's environment variables.
For instance:
```yaml
      steps:
        - experiment:
            templates:
              - metadata:
                  labels:
                    app: green-preview
                name: green-preview
                replicas: 1
                selector:
                  matchLabels:
                    app: green-preview
                service:
                  name: green-preview
                specRef: canary
                env:
                  - name: DATABASE_URL
                    valueFrom:
                      secretKeyRef:
                        key: database_uri
                        name: green-demo-postgres
```
# Use Cases
In my opinion it's extremely useful for various testing!
When would you use this?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
