### ISSUE TITLE
Investigate and Implement HPA support

### ISSUE THREAD

**Issue by dthomson25** [argoproj/argo-rollouts#33]
In order to take advantage of the Horizontal Pod Autoscaler, Argo Rollout needs to support the Scale endpoint (https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#subresources), and output the correct replicas counts when using the BlueGreen and Canary Strategy.

**Comment by dthomson25** [comment]
Implemented by https://github.com/argoproj/argo-rollouts/pull/37

**Comment by sshishov** [comment]
Hello guys! We are using argo-rollouts + istio + hpa in our kubernetes cluster (EKS).
Our HPA is based on istio's latency metric. We start getting 503 errors as soon as HPA start upscaling the rollout.
Our configuration:
VirtualService:
```
spec:
  gateways:
  - mesh
  - istio-system/istio-ingressgateway-private
  hosts:
  - myservice.example.com
  http:
  - name: primary
    match: ...
    route:
    - destination:
        host: myservice-stable-svc
      weight: 100
    - destination:
        host: myservice-canary-svc
      weight: 0
```
Rollout:
```
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: myservice
  strategy:
    canary:
      canaryService: myservice-canary-svc
      stableService: myservice-stable-svc
      steps:
      - setWeight: 20
      - pause:
          duration: 5s
      - setWeight: 40
      - pause:
          duration: 4s
      - setWeight: 60
      - pause:
          duration: 3s
      - setWeight: 80
      - pause:
          duration: 2s
      trafficRouting:
        istio:
          virtualService:
            name: myservice-vs
            routes:
            - primary
```
Logs from argo-rollouts:
```
time="2020-07-15T10:06:24Z" level=info msg="Started syncing rollout at (2020-07-15 10:06:24.122439979 +0000 UTC m=+597937.784135576)" namespace=myns rollout=myservice
time="2020-07-15T10:06:24Z" level=info msg="Syncing replicas only (userPaused false, isScaling: true)" namespace=myns rollout=myservice
time="2020-07-15T10:06:24Z" level=info msg="Reconciling StableRS" namespace=myns rollout=myservice
time="2020-07-15T10:06:24Z" level=info msg="No StableRS exists to reconcile or matches newRS" namespace=myns rollout=myservice
time="2020-07-15T10:06:24Z" level=info msg="Reconciling new ReplicaSet 'myservice-64dcd5674b'" namespace=myns rollout=myservice
time="2020-07-15T10:06:24Z" level=info msg="Not finished reconciling new ReplicaSet 'myservice-64dcd5674b'" namespace=myns rollout=myservice
time="2020-07-15T10:06:24Z" level=info msg="No Steps remain in the canary steps" namespace=myns rollout=myservice
time="2020-07-15T10:06:24Z" level=info msg="Reconciling TrafficRouting with type 'Istio'" namespace=myns rollout=myservice
time="2020-07-15T10:06:24Z" level=info msg="Event(v1.ObjectReference{Kind:\"Rollout\", Namespace:\"myns\", Name:\"myservice\", UID:\"75ac370f-0091-4f4f-924d-46d0e028f3db\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"57484760\", FieldPath:\"\"}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled down replica set myservice-64dcd5674b to 2"
time="2020-07-15T10:06:24Z" level=info msg="Enqueuing parent of myns/myservice-64dcd5674b: Rollout myns/myservice"
time="2020-07-15T10:06:24Z" level=info msg="Updating VirtualService `myservice-vs` to desiredWeight '80'" namespace=myns rollout=myservice
time="2020-07-15T10:06:24Z" level=info msg="Event(v1.ObjectReference{Kind:\"Rollout\", Namespace:\"myns\", Name:\"myservice\", UID:\"75ac370f-0091-4f4f-924d-46d0e028f3db\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"57484760\", FieldPath:\"\"}): type: 'Normal' reason: 'UpdatingVirtualService' Updating VirtualService `myservice-vs` to desiredWeight '80'"
time="2020-07-15T10:06:24Z" level=info msg="Rollout has executed every step" namespace=myns rollout=myservice
time="2020-07-15T10:06:24Z" level=info msg="Enqueuing parent of myns/myservice-64dcd5674b: Rollout myns/myservice"
time="2020-07-15T10:06:24Z" level=info msg="Patch status successfully" namespace=myns rollout=myservice
time="2020-07-15T10:06:24Z" level=info msg="Reconciliation completed" namespace=myns rollout=myservice time_ms=72.971908
```

The question: why on HPA even upscale/downscale we are having an additional event in logs - start shifting traffic to canary? At this point, we have 0 pods for new canary (I assume canary is pointing to the same RS, as stable does). But why do we have 503 at this point? Are we missing something? Is HPA is not working as expected?
