### ISSUE TITLE
Consul Service Mesh - support for service subset canary deployments (Consul API V1)

### ISSUE THREAD

**Issue by david-yu** [argoproj/argo-rollouts#3311]
# Summary

Provide support within Argo Rollouts Controller to support subset level splitting for Canary deployments for Traffic Routing on Consul V1 API. The V2 API for Consul will also support host level splitting for Canary deployments, but for v1 we will only be able to provide subset level splitting. 

The following is an example for gradually rolling out 10% additional traffic at a time from the `stable` service subset to the `canary` service subset. 

```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-example
spec:
  ...
  strategy:
    canary:
      trafficRouting:
        consul:
          service:
            name: rollout-vsvc        # required
            routes:
            - primary                 # optional if there is a single route in VirtualService, required otherwise
          serviceResolver:
            name: rollout-svc-resolver    # required
            canarySubsetName: canary  # required
            stableSubsetName: stable  # required
      steps:
      - setWeight: 10
      - pause:
          duration: 10m
```

# Use Cases

When would you use this?

Service Mesh Canary Rollouts using Consul. The Consul team would be interested in contributing back to Argo Rollouts to get this to work with our V1 API. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
