### ISSUE TITLE
Getting "error updating replicaset in syncEphemeralMetadata" while triggering a new canary upgrade.

### ISSUE THREAD

**Issue by yechan-paytalab** [argoproj/argo-rollouts#3351]
Checklist:

* [✅] I've included steps to reproduce the bug.
* [✅ ] I've included the version of argo rollouts.

**Describe the bug**

Whenever I try to trigger another Canary deployment after the very first successful deployment, the Rollout creates a new replicaset for the new deployment but it doesn't create a new pod. It's just stuck in a "progressing" status for forever. I'm somehow only able to proceed when I manually remove the older replicaset. Please refer to the logs below.

**To Reproduce**

Trigger another Canary upgrade after the very first successful one.

**Expected behavior**

Everything goes well like a charm.

**Screenshots**

<img width="924" alt="Screenshot 2024-02-05 at 1 54 08 PM" src="https://github.com/argoproj/argo-rollouts/assets/138102762/0c71bd74-1f77-4302-a1c5-a97c6f209796">

<img width="564" alt="Screenshot 2024-02-05 at 1 54 13 PM" src="https://github.com/argoproj/argo-rollouts/assets/138102762/6d827832-6bb7-42db-a91c-ed52376a9869">

<img width="727" alt="Screenshot 2024-02-05 at 1 55 54 PM" src="https://github.com/argoproj/argo-rollouts/assets/138102762/13863480-f81a-4a0e-91ba-5ec3b1d0da16">

**Version**

v1.6.5

**Logs**

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

(...)
time="2024-02-05T04:43:07Z" level=error msg="error updating replicaset in syncEphemeralMetadata: ReplicaSet.apps \"<REDACTED>-staging-canary-59c85595cf\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{\"rollouts-pod-template-hash\":\"59c85595cf\"}: `selector` does not match template `labels`\n" error="<nil>"
time="2024-02-05T04:43:09Z" level=info msg="Started syncing rollout" generation=7 namespace=<REDACTED_NAMESPACE> resourceVersion=85270855 rollout=<REDACTED>-staging-canary-spot
time="2024-02-05T04:43:09Z" level=error msg="roCtx.reconcile err error updating replicaset in syncEphemeralMetadata: ReplicaSet.apps \"<REDACTED>-staging-canary-spot-5f558584d5\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{\"lifecycle\":\"spot\", \"rollouts-pod-template-hash\":\"5f558584d5\"}: `selector` does not match template `labels`" generation=7 namespace=<REDACTED_NAMESPACE> resourceVersion=85270855 rollout=<REDACTED>-staging-canary-spot
time="2024-02-05T04:43:09Z" level=info msg="Reconciliation completed" generation=7 namespace=<REDACTED_NAMESPACE> resourceVersion=85270855 rollout=<REDACTED>-staging-canary-spot time_ms=26.669502
time="2024-02-05T04:43:09Z" level=error msg="rollout syncHandler error: error updating replicaset in syncEphemeralMetadata: ReplicaSet.apps \"<REDACTED>-staging-canary-spot-5f558584d5\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{\"lifecycle\":\"spot\", \"rollouts-pod-template-hash\":\"5f558584d5\"}: `selector` does not match template `labels`" namespace=<REDACTED_NAMESPACE> rollout=<REDACTED>-staging-canary-spot
time="2024-02-05T04:43:09Z" level=info msg="rollout syncHandler queue retries: 110 : key \"<REDACTED_NAMESPACE>/<REDACTED>-staging-canary-spot\"" namespace=<REDACTED_NAMESPACE> rollout=<REDACTED>-staging-canary-spot
time="2024-02-05T04:43:09Z" level=error msg="error updating replicaset in syncEphemeralMetadata: ReplicaSet.apps \"<REDACTED>-staging-canary-spot-5f558584d5\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{\"lifecycle\":\"spot\", \"rollouts-pod-template-hash\":\"5f558584d5\"}: `selector` does not match template `labels`\n" error="<nil>"
time="2024-02-05T04:43:17Z" level=info msg="Started syncing rollout" generation=7 namespace=<REDACTED_NAMESPACE> resourceVersion=85270899 rollout=<REDACTED>-staging-canary
time="2024-02-05T04:43:17Z" level=error msg="roCtx.reconcile err error updating replicaset in syncEphemeralMetadata: ReplicaSet.apps \"<REDACTED>-staging-canary-59c85595cf\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{\"rollouts-pod-template-hash\":\"59c85595cf\"}: `selector` does not match template `labels`" generation=7 namespace=<REDACTED_NAMESPACE> resourceVersion=85270899 rollout=<REDACTED>-staging-canary
time="2024-02-05T04:43:17Z" level=info msg="Reconciliation completed" generation=7 namespace=<REDACTED_NAMESPACE> resourceVersion=85270899 rollout=<REDACTED>-staging-canary time_ms=40.631637
time="2024-02-05T04:43:17Z" level=error msg="rollout syncHandler error: error updating replicaset in syncEphemeralMetadata: ReplicaSet.apps \"<REDACTED>-staging-canary-59c85595cf\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{\"rollouts-pod-template-hash\":\"59c85595cf\"}: `selector` does not match template `labels`" namespace=<REDACTED_NAMESPACE> rollout=<REDACTED>-staging-canary
time="2024-02-05T04:43:17Z" level=info msg="rollout syncHandler queue retries: 109 : key \"<REDACTED_NAMESPACE>/<REDACTED>-staging-canary\"" namespace=<REDACTED_NAMESPACE> rollout=<REDACTED>-staging-canary
time="2024-02-05T04:43:17Z" level=error msg="error updating replicaset in syncEphemeralMetadata: ReplicaSet.apps \"<REDACTED>-staging-canary-59c85595cf\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{\"rollouts-pod-template-hash\":\"59c85595cf\"}: `selector` does not match template `labels`\n" error="<nil>"

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>

(...)
time="2024-02-05T04:40:39Z" level=error msg="roCtx.reconcile err error updating replicaset in syncEphemeralMetadata: ReplicaSet.apps \"<REDACTED>-staging-canary-spot-5f558584d5\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{\"lifecycle\":\"spot\", \"rollouts-pod-template-hash\":\"5f558584d5\"}: `selector` does not match template `labels`" generation=7 namespace=<REDACTED_NAMESPACE> resourceVersion=85270855 rollout=<REDACTED>-staging-canary-spot
time="2024-02-05T04:40:39Z" level=info msg="Reconciliation completed" generation=7 namespace=<REDACTED_NAMESPACE> resourceVersion=85270855 rollout=<REDACTED>-staging-canary-spot time_ms=30.950426999999998
time="2024-02-05T04:40:39Z" level=error msg="rollout syncHandler error: error updating replicaset in syncEphemeralMetadata: ReplicaSet.apps \"<REDACTED>-staging-canary-spot-5f558584d5\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{\"lifecycle\":\"spot\", \"rollouts-pod-template-hash\":\"5f558584d5\"}: `selector` does not match template `labels`" namespace=<REDACTED_NAMESPACE> rollout=<REDACTED>-staging-canary-spot
time="2024-02-05T04:40:39Z" level=info msg="rollout syncHandler queue retries: 95 : key \"<REDACTED_NAMESPACE>/<REDACTED>-staging-canary-spot\"" namespace=<REDACTED_NAMESPACE> rollout=<REDACTED>-staging-canary-spot
time="2024-02-05T04:40:49Z" level=info msg="Started syncing rollout" generation=7 namespace=<REDACTED_NAMESPACE> resourceVersion=85270855 rollout=<REDACTED>-staging-canary-spot
time="2024-02-05T04:40:49Z" level=error msg="roCtx.reconcile err error updating replicaset in syncEphemeralMetadata: ReplicaSet.apps \"<REDACTED>-staging-canary-spot-5f558584d5\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{\"lifecycle\":\"spot\", \"rollouts-pod-template-hash\":\"5f558584d5\"}: `selector` does not match template `labels`" generation=7 namespace=<REDACTED_NAMESPACE> resourceVersion=85270855 rollout=<REDACTED>-staging-canary-spot
time="2024-02-05T04:40:49Z" level=info msg="Reconciliation completed" generation=7 namespace=<REDACTED_NAMESPACE> resourceVersion=85270855 rollout=<REDACTED>-staging-canary-spot time_ms=34.936354
time="2024-02-05T04:40:49Z" level=error msg="rollout syncHandler error: error updating replicaset in syncEphemeralMetadata: ReplicaSet.apps \"<REDACTED>-staging-canary-spot-5f558584d5\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{\"lifecycle\":\"spot\", \"rollouts-pod-template-hash\":\"5f558584d5\"}: `selector` does not match template `labels`" namespace=<REDACTED_NAMESPACE> rollout=<REDACTED>-staging-canary-spot
time="2024-02-05T04:40:49Z" level=info msg="rollout syncHandler queue retries: 96 : key \"<REDACTED_NAMESPACE>/<REDACTED>-staging-canary-spot\"" namespace=<REDACTED_NAMESPACE> rollout=<REDACTED>-staging-canary-spot
```

**Rollout Resource**
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: <REDACTED>-staging
    argocd.argoproj.io/instance: staging-<REDACTED_NAMESPACE>-<REDACTED>
    lifecycle: spot
    service: <REDACTED>-staging
    tags.datadoghq.com/env: staging
    tags.datadoghq.com/service: <REDACTED>
    type: Stable
  name: <REDACTED>-staging-canary-spot
  namespace: <REDACTED_NAMESPACE>
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: <REDACTED>-staging
  strategy:
    canary:
      analysis:
        args:
          - name: service-name
            value: <REDACTED>
          - name: env
            value: staging
        startingStep: 2
        templates:
          - clusterScope: true
            templateName: auto-analysis
      canaryMetadata:
        annotations:
          type: Canary
        labels:
          admission.datadoghq.com/enabled: 'true'
          app: <REDACTED>-staging
          tags.datadoghq.com/env: staging
          tags.datadoghq.com/service: <REDACTED>
          type: Canary
      dynamicStableScale: true
      maxSurge: 1
      maxUnavailable: 0
      stableMetadata:
        annotations:
          type: Stable
        labels:
          admission.datadoghq.com/enabled: 'true'
          app: <REDACTED>-staging
          tags.datadoghq.com/env: staging
          tags.datadoghq.com/service: <REDACTED>
          type: Stable
      steps:
        - setCanaryScale:
            weight: 10
        - pause: {}
        - setWeight: 100
        - setCanaryScale:
            weight: 100
        - pause:
            duration: 1m
      trafficRouting:
        istio:
          destinationRule:
            canarySubsetName: canary
            name: <REDACTED>-dr
            stableSubsetName: stable
          virtualServices:
            - name: <REDACTED>-staging-virtualservice-canary
              routes:
                - weighted
            - name: <REDACTED>-staging-internal-communication
              routes:
                - weighted
  template:
    metadata:
      annotations:
        ad.datadoghq.com/<REDACTED>-staging.logs: |
          [
            {"source":"<REDACTED>-staging","service":"<REDACTED>","sourcecategory": "<REDACTED>"}
          ]
            
        admission.datadoghq.com/java-lib.version: v1.19.3
        cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
      labels:
        admission.datadoghq.com/enabled: 'true'
        app: <REDACTED>-staging
        lifecycle: spot
        tags.datadoghq.com/env: staging
        tags.datadoghq.com/service: <REDACTED>
        type: Stable
    spec:
      containers:
        - env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: DD_DATA_STREAMS_ENABLED
              value: 'true'
            - name: DD_PROFILING_ENABLED
              value: 'false'
            - name: DD_KAFKA_LEGACY_TRACING_ENABLED
              value: 'false'
            - name: DD_TRACE_KAFKA_ENABLED
              value: 'true'
            - name: DD_LOGS_INJECTION
              value: 'true'
            - name: APP_SETTINGS
              value: staging
            - name: APP_NAME
              value: <REDACTED>-staging
            - name: ENVIRONMENT
              value: staging
            - name: DEPLOYMENT
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.labels[''type'']'
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: DB_USERNAME_<REDACTED>
                  name: database-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD_<REDACTED>
                  name: database-secret
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: DB_NAME_<REDACTED>
                  name: database-secret
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  key: DB_PORT_<REDACTED>
                  name: database-secret
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: DB_HOST_<REDACTED>
                  name: database-secret
            - name: DB_READ_USERNAME
              valueFrom:
                secretKeyRef:
                  key: DB_READ_USERNAME_<REDACTED>
                  name: database-secret
            - name: DB_READ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_READ_PASSWORD_<REDACTED>
                  name: database-secret
            - name: DB_READ_NAME
              valueFrom:
                secretKeyRef:
                  key: DB_READ_NAME_<REDACTED>
                  name: database-secret
            - name: DB_READ_PORT
              valueFrom:
                secretKeyRef:
                  key: DB_READ_PORT_<REDACTED>
                  name: database-secret
            - name: DB_READ_HOST
              valueFrom:
                secretKeyRef:
                  key: DB_READ_HOST_<REDACTED>
                  name: database-secret
            - name: REDIS_ORDER_SERVICE_DATABASE_INDEX
              value: ''
            - name: REDIS_<REDACTED_NAMESPACE>_DATABASE_INDEX
              value: ''
            - name: DD_TRACE_HEADER_TAGS
              value: >-
                x-qa:http.headers.x-qa,x-platform:http.headers.x-platform,x-version:http.headers.x-version,x-deployment:http.headers.x-deployment,x-requestfrom:http.headers.x-requestfrom
          envFrom:
            - secretRef:
                name: database-secret
          image: >-
            642641366241.dkr.ecr.ap-northeast-2.amazonaws.com/<REDACTED>-staging:2024-01-29-21-22
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /health_check
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
          name: <REDACTED>-staging
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health_check
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 2Gi
          securityContext: {}
      nodeSelector:
        lifecycle: spot
      securityContext: {}
      serviceAccountName: default
      tolerations:
        - effect: NoSchedule
          key: lifecycle
          operator: Equal
          value: spot
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
