### ISSUE TITLE
Argo-rollouts controller crashing in AKS due to lease renew timeout.

### ISSUE THREAD

**Issue by codyadams32123** [argoproj/argo-rollouts#3355]
Checklist:

* [x ] I've included steps to reproduce the bug.
* [x ] I've included the version of argo rollouts.

**Describe the bug**

I have deployed the argo-rollouts chart to my Azure Kubernetes Service cluster in Central US and West Europe.
It randomly restarts throughout the day. The problem is we don't utilize argo-rollouts heavily yet and I don't expect normal operation on AKS to be difficult for the container.
It never reaches anywhere near the resources we have provisioned for it either so there is no resource constraint directly related to the pod.

Here is describe output for one of the containers relevant for the error:
```yaml
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 11 Jan 2024 05:36:10 -0800
      Finished:     Sun, 04 Feb 2024 06:58:10 -0800
    Ready:          True
    Restart Count:  7
```

**To Reproduce**

Deploy argo-rollouts controller v1.5.1 using chart v2.31.2 to an AKS cluster running K8s v1.26.6 

I am using the following values in the values.yaml
```
installCRDs: true
keepCRDs: false

clusterInstall: true

createClusterAggregateRoles: true

nameOverride:
fullnameOverride:

apiVersionOverrides:
  ingress: ""

kubeVersionOverride: ""

extraObjects: []

global:
  deploymentAnnotations: {}

controller:
  component: rollouts-controller
  deploymentAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8090"
  podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8090"
  nodeSelector: {}
  tolerations: []
  affinity: {}

  topologySpreadConstraints: []
  priorityClassName: "system-cluster-critical"
  replicas: 2
  image:
    registry: PLACEHOLDER
    repository: quay.io/argoproj/argo-rollouts
    tag: ""
    pullPolicy: IfNotPresent

  extraArgs: []

  extraEnv:
    - name: DD_AGENT_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP

  extraContainers: []

  initContainers: []
  createClusterRole: true
  containerPorts:
    metrics: 8090
    healthz: 8080
  metrics:
    enabled: true
    service:
      portName: metrics
      port: 8090
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8090"
    serviceMonitor:
      enabled: false
      additionalLabels: {}
      additionalAnnotations: {}
      relabelings: []
      metricRelabelings: []
  livenessProbe:
    httpGet:
      path: /healthz
      port: healthz
    initialDelaySeconds: 30
    periodSeconds: 20
    failureThreshold: 3
    successThreshold: 1
    timeoutSeconds: 10
  readinessProbe:
    httpGet:
      path: /metrics
      port: metrics
    initialDelaySeconds: 15
    periodSeconds: 5
    failureThreshold: 3
    successThreshold: 1
    timeoutSeconds: 4
  pdb:
    labels: {}
    annotations: {}
    enabled: true
    minAvailable: 50%
    maxUnavailable: # 0
  volumes: []
  volumeMounts: []
  metricProviderPlugins: {}
  trafficRouterPlugins: {}
serviceAccount:
  create: true
  annotations: {}
  name: ""
crdAnnotations: {}
podAnnotations: {}
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 101
  runAsGroup: 101
  fsGroup: 101
  supplementalGroups: [101]
containerSecurityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 101
  allowPrivilegeEscalation: false
serviceAnnotations: {}
podLabels: {}
imagePullSecrets: []

providerRBAC:
  enabled: true
  providers:
    istio: false
    smi: false
    ambassador: false
    awsLoadBalancerController: false
    awsAppMesh: false
    traefik: true
    apisix: false
dashboard:
  enabled: false
  readonly: true
  component: rollouts-dashboard
  deploymentAnnotations: {}
  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  topologySpreadConstraints: []
  priorityClassName: ""

  createClusterRole: true

  replicas: 1
  image:
    registry: PLACEHOLDER
    repository: quay.io/argoproj/kubectl-argo-rollouts
    tag: ""
    pullPolicy: IfNotPresent
  extraArgs: []
  extraEnv: []
  resources: {}
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 101
    runAsGroup: 101
    fsGroup: 101
    supplementalGroups: [101]
  containerSecurityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 101
    allowPrivilegeEscalation: false
  service:
    type: ClusterIP
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    externalIPs: []
    annotations: {}
    labels: {}
    portName: dashboard
    port: 3100
    targetPort: 3100
    nodePort:
  serviceAccount:
    create: true
    annotations: {}
    name: ""
  pdb:
    labels: {}
    annotations: {}
    enabled: false
    minAvailable: # 1
    maxUnavailable: # 0
  ingress:
    enabled: false
    annotations: {}
    labels: {}
    ingressClassName: ""
    hosts: []
    paths:
      - /
    pathType: Prefix
    extraPaths: []
    tls: []
  volumes: []
  volumeMounts: []
notifications:
  secret:
    create: false
    items: {}
  notifiers: {}
  templates: {}
  triggers: {}
````

**Expected behavior**

I would expect the behavior to retry obtaining a lease when it fails to renew due to Kube API. This should not cause the container to "Complete" and be restarted.

**Version**

Chart: argo-rollouts-2.31.2
Image: v1.5.1

`**Logs**`

```
time="2024-01-13T03:28:11Z" level=info msg="Argo Rollouts starting" version=v1.5.1+839f05d
time="2024-01-13T03:28:16Z" level=info msg="Creating event broadcaster"
time="2024-01-13T03:28:16Z" level=info msg="Setting up event handlers"
time="2024-01-13T03:28:16Z" level=info msg="Setting up experiments event handlers"
time="2024-01-13T03:28:16Z" level=info msg="Setting up analysis event handlers"
time="2024-01-13T03:28:16Z" level=info msg="Leaderelection get id argo-rollouts-574cd6b48f-qqjcx_1e3bf8a2-f030-4742-a3aa-348b86765b2a"
time="2024-01-13T03:28:16Z" level=info msg="Starting Healthz Server at 0.0.0.0:8080"
time="2024-01-13T03:28:16Z" level=info msg="attempting to acquire leader lease argo-rollouts/argo-rollouts-controller-lock...\n"
time="2024-01-13T03:28:16Z" level=info msg="Starting Metric Server at 0.0.0.0:8090"
time="2024-01-13T03:28:16Z" level=info msg="New leader elected: argo-rollouts-574cd6b48f-qqjcx_29474fde-f642-47cb-abf5-dd17003b5359"
time="2024-01-13T03:28:32Z" level=info msg="New leader elected: argo-rollouts-574cd6b48f-bbq8c_fa102931-1c24-4464-9207-d1d2d93b3430"
time="2024-01-13T10:33:50Z" level=error msg="error retrieving resource lock argo-rollouts/argo-rollouts-controller-lock: Get \"https://10.0.0.1:443/apis/coordination.k8s.io/v1/namespaces/argo-rollouts/leases/argo-rollouts-controller-lock\": http2: client connection lost\n" error="<nil>"
time="2024-01-23T19:16:33Z" level=error msg="error retrieving resource lock argo-rollouts/argo-rollouts-controller-lock: Get \"https://10.0.0.1:443/apis/coordination.k8s.io/v1/namespaces/argo-rollouts/leases/argo-rollouts-controller-lock\": http2: client connection lost\n" error="<nil>"
time="2024-02-04T14:58:27Z" level=info msg="successfully acquired lease argo-rollouts/argo-rollouts-controller-lock\n"
time="2024-02-04T14:58:27Z" level=info msg="New leader elected: argo-rollouts-574cd6b48f-qqjcx_1e3bf8a2-f030-4742-a3aa-348b86765b2a"
time="2024-02-04T14:58:27Z" level=info msg="I am the new leader: argo-rollouts-574cd6b48f-qqjcx_1e3bf8a2-f030-4742-a3aa-348b86765b2a"
time="2024-02-04T14:58:27Z" level=info msg="Starting Controllers"
time="2024-02-04T14:58:27Z" level=info msg="Waiting for controller's informer caches to sync"
time="2024-02-04T14:58:37Z" level=info msg="Trace[1956894304]: \"Reflector ListAndWatch\" name:pkg/mod/k8s.io/client-go@v0.25.8/tools/cache/reflector.go:169 (04-Feb-2024 14:58:27.075) (total time: 10714ms):\nTrace[1956894304]: ---\"Objects listed\" error:<nil> 10705ms (14:58:37.780)\nTrace[1956894304]: [10.714434231s] [10.714434231s] END\n"
time="2024-02-04T14:58:38Z" level=info msg="Started controller"
time="2024-02-04T14:58:38Z" level=info msg="Starting Experiment workers"
time="2024-02-04T14:58:38Z" level=info msg="Started Experiment workers"
time="2024-02-04T14:58:38Z" level=info msg="Starting Service workers"
time="2024-02-04T14:58:38Z" level=info msg="Starting Rollout workers"
time="2024-02-04T14:58:38Z" level=info msg="Started rollout workers"
time="2024-02-04T14:58:38Z" level=info msg="Starting analysis workers"
time="2024-02-04T14:58:38Z" level=warning msg="Controller is running."
time="2024-02-04T14:58:38Z" level=info msg="Starting Ingress workers"
time="2024-02-04T14:58:38Z" level=info msg="Started Service workers"
time="2024-02-04T14:58:38Z" level=info msg="Started Ingress workers"
time="2024-02-04T14:58:38Z" level=info msg="Started 30 analysis workers"
...
time="2024-02-06T15:32:00Z" level=error msg="Failed to update lock: Put \"https://10.0.0.1:443/apis/coordination.k8s.io/v1/namespaces/argo-rollouts/leases/argo-rollouts-controller-lock\": context deadline exceeded\n" error="<nil>"
time="2024-02-06T15:32:00Z" level=info msg="failed to renew lease argo-rollouts/argo-rollouts-controller-lock: timed out waiting for the condition\n"
time="2024-02-06T15:32:00Z" level=info msg="OnStoppedLeading called, shutting down: argo-rollouts-574cd6b48f-qqjcx_1e3bf8a2-f030-4742-a3aa-348b86765b2a, context err: %!s(<nil>)"
time="2024-02-06T15:32:00Z" level=info msg="Shutting down workers"
time="2024-02-06T15:32:00Z" level=warning msg="Controller has stopped."
time="2024-02-06T15:32:00Z" level=info msg="All experiment workers have stopped"
time="2024-02-06T15:32:00Z" level=info msg="All ingress workers have stopped"
time="2024-02-06T15:32:00Z" level=error msg="Metric Server Error: http: Server closed"
time="2024-02-06T15:32:00Z" level=info msg="All service workers have stopped"
time="2024-02-06T15:32:00Z" level=info msg="All analysis workers have stopped"
time="2024-02-06T15:32:00Z" level=error msg="Healthz Server Error: http: Server closed"
time="2024-02-06T15:32:00Z" level=info msg="All rollout workers have stopped"
time="2024-02-06T15:32:00Z" level=info msg="Exiting Main Run function"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
