### ISSUE TITLE
Support Linkerd as traffic provider

### ISSUE THREAD

**Issue by amcamina** [argoproj/argo-rollouts#3387]
# Summary

In our environment, the service mesh used is linkerd.
Linkerd is not officially supported by Argo Rollouts. However, Linkerd provided a way to use Argo Rollouts with it. I added a link below. 

## What change needs making?
The minimal change that I suggest is to add a key in values to add your rules in `ClusterRole` resource called `argo-controller-role` ([link](https://github.com/argoproj/argo-helm/blob/main/charts/argo-rollouts/templates/controller/clusterrole.yaml))

The lines that I would add to the ([file](https://github.com/argoproj/argo-helm/blob/main/charts/argo-rollouts/templates/controller/clusterrole.yaml)) would be:
```
{{- if .Values.providerRBAC.providers.linkerd }}
  # Access needed when using the Linkerd provider
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - httproutes
    verbs:
      - "*"
{{- end }}
```

## Reference
* https://linkerd.io/2.14/tasks/flagger/#argo-rollouts

# Use Cases
Use Argo Rollouts with Linkerd

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
