### ISSUE TITLE
Wrong "SkipSteps" during Rollback

### ISSUE THREAD

**Issue by Myafq** [argoproj/argo-rollouts#339]
When Rollout rolled back to previous version of image during indefinite pause or any pause as a last step, controller keeps both replica sets instead of removing new one.
Example: 
```
Name:            app
Namespace:       perf2
Status:          ◌ Progressing
Strategy:        Canary
  Step:          6/6
  SetWeight:     100
  ActualWeight:  100
Images:          registry/dev_phase2:20 (stable)
                 registry/dev_phase2:21
Replicas:
  Desired:       2
  Current:       2
  Updated:       1
  Ready:         2
  Available:     2

NAME                                     KIND        STATUS         AGE  INFO
⟳ app                           Rollout     ◌ Progressing  24h
├──# revision:27
│  └──⧉ app-676568d44           ReplicaSet  ✔ Healthy      24h  stable
│     └──□ app-676568d44-dk6hx  Pod         ✔ Running      59m  ready:1/1
├──# revision:26
│  └──⧉ app-966bb8d49           ReplicaSet  ✔ Healthy      74m
│     └──□ app-966bb8d49-9drcg  Pod         ✔ Running      20m  ready:1/1
└──# revision:6
   └──⧉ app-bbcbdf656           ReplicaSet  • ScaledDown   24h
```
And i see following event in Rollout:
```Normal  SkipSteps          31m (x2 over 23h)   rollouts-controller  Skipping all steps because the newRS is the stableRS.```

Strategy section:
```yaml
    canary:
      maxSurge: "50%"
      maxUnavailable: "10%"
      steps:
      - setWeight: 10
# here everything works as expected
      - pause: 
          duration: 60
      - setWeight: 50
# bug appears on this pause
      - pause: {}
      - setWeight: 80
# as well as on this one
      - pause: 
          duration: 120
```

After applying new Rollout back we also see strange behavior, it creates additional Pod:
```
Name:            app
Namespace:       perf2
Status:          ॥ Paused
Strategy:        Canary
  Step:          1/6
  SetWeight:     10
  ActualWeight:  33
Images:          registry/dev_phase2:20 (stable)
                 registry/dev_phase2:21 (canary)
Replicas:
  Desired:       2
  Current:       3
  Updated:       1
  Ready:         3
  Available:     3

NAME                                     KIND        STATUS        AGE  INFO
⟳ app                           Rollout     ॥ Paused      24h
├──# revision:28
│  └──⧉ app-966bb8d49           ReplicaSet  ✔ Healthy     79m  canary
│     └──□ app-966bb8d49-9drcg  Pod         ✔ Running     25m  ready:1/1
├──# revision:27
│  └──⧉ app-676568d44           ReplicaSet  ✔ Healthy     24h  stable
│     ├──□ app-676568d44-dk6hx  Pod         ✔ Running     64m  ready:1/1
│     └──□ app-676568d44-4wmbk  Pod         ✔ Running     11m  ready:1/1
└──# revision:6
   └──⧉ app-bbcbdf656           ReplicaSet  • ScaledDown  24h
```
