### ISSUE TITLE
503 responses from endpoint, when running weighted experiment

### ISSUE THREAD

**Issue by divyansh375** [argoproj/argo-rollouts#3420]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've included the version of argo rollouts.

**Describe the bug**

we noticed that when running argo rollouts experiment with weight, traffic is getting shifted to experiment pods, even before they are ready to accept traffic..due to this, few requests give 503 response for a short period of time.

Rollout Version I am using: v1.4

**To Reproduce**

1. run canary deployment with this config (you can use any traffic. router like istio):

```
   strategy:
      canary:
        steps:
          - experiment:
              duration: 5m
              analyses:
                - name: test-analysis
                  templateName: success-rate
                  requiredForCompletion: true
                  args:
                    - name: service-name
                      value: divtestflex-IT
              templates:
                - name: canaryexp
                  specRef: canary
                  weight: 50
                  metadata:
                    labels:
                      side: previewcanary
                - name: stablexp
                  specRef: stable
                  weight: 50
                  metadata:
                    labels:
                      side: previewstable

          - setWeight: 40
```
          

2. run a load test of around 10rps on your endpoint.
3. notice that once the experiment pods are up, there will be a short period of time, where you will see 503 response.

**Expected behavior**

the endpoint should return 200 response throughout the deployment

**Screenshots**

**Version**

**Logs**

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
