### ISSUE TITLE
when SyncOption's ServerSideApply=true,  Blue/Green deployments doesn't work well

### ISSUE THREAD

**Issue by kingbj940429** [argoproj/argo-rollouts#3437]
Checklist:

* [ ] I've included steps to reproduce the bug.
* [ ] I've included the version of argo rollouts.

**Describe the bug**

When SyncOption is set to ServerSideApply=true, features such as autoPromoteEnabled and AnalysisRun are not generated.

**To Reproduce**

I'm deploying a application using below yaml

Even though the AnalysisTemplate exists, AnalysisRun is not generated. Additionally, despite autoPromoteEnable being set to false, automatic promotion still occurs. Moreover, options such as previewReplicaCount in Blue/Green deployments are not functioning correctly.

![image](https://github.com/argoproj/argo-rollouts/assets/63000843/85b3ac4e-2c55-4265-81fe-3cda6cbf9c7b)

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-demo
  namespace: continuous-system
spec:
  generators:
    - list:
        elements:
          - deployTier: dev
            targetRevision: feature-0b154b
  template:
    metadata:
      name: "app-demo-{{deployTier}}"
      namespace: continuous-system
    spec:
      project: pf
      destination:
        namespace: insight
        server: "https://kubernetes.default.svc"
      source:
        chart: app-demo
        repoURL: "https://privates/repository/helm-hosted"
        targetRevision: "{{targetRevision}}"
        plugin:
          name: avp-helm
          env:
            - name: HELM_ARGS
              value: -f values-{{deployTier}}.yaml
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
        syncOptions:
          - ServerSideApply=false #-- to false
```

**Expected behavior**

`ServerSideApply=false`

**Screenshots**

![image](https://github.com/argoproj/argo-rollouts/assets/63000843/85b3ac4e-2c55-4265-81fe-3cda6cbf9c7b)
![스크린샷 2024-03-10 오후 11 55 25](https://github.com/argoproj/argo-rollouts/assets/63000843/3bc42adb-c137-4083-bc43-07357aec4f5a)
![image](https://github.com/argoproj/argo-rollouts/assets/63000843/c3743264-5430-47ab-aba7-bd3258956974)

**Version**

Argo Rollout Helm Chart v2.34.3

**Logs**

All log levels are info

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jebbers-lq** [comment]
My org is also experiencing this issue. We disabled ServerSideApply in our cluster as a successful workaround for the time-being. But we'd really prefer to have the option of using ServerSideApply in the future.

**Comment by andrewjamesbrown** [comment]
We're also experiencing this, when managing rollouts via ArgoCD.  If we use `kubectl apply -f rollout.yaml`, then change the image tag and finally `kubectl apply -f rollout.yaml --server-side`, rollouts work as intended.  It looks like this is specific to how ArgoCD is managing server-side apply.

**Comment by romancin** [comment]
+1, same problem here. In our case, it is impossible to disable ServerSideApply due to annotations surpassing maximum characters, so we can't use BlueGreen Strategy with Argo CD until this is solved :(

**Comment by motoki317** [comment]
The problem seems to lie in the difference of how client side kubectl merges maps and how SSA merges maps (specifically, `.spec.selector` in Service object).

For client side apply (`kubectl apply`), maps are always merged with the live object and fields controlled by kubectl are created/modified/deleted considering the kubectl client's last applied configuration.
https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/#how-different-types-of-fields-are-merged
This allows kubectl and therefore ArgoCD to sync the resource "correctly" along with Rollouts Controller which adds its own `rollouts-pod-template-hash` to the `.spec.selector` map object, without the kubectl deleting this map key.

For SSA, how maps are merged with the live object will differ with each object and field definition. For some object's some key it may perform a replace (`atomic`), and for some others it may perform a merge (`granular`).
https://kubernetes.io/docs/reference/using-api/server-side-apply/#merge-strategy
For Service object's `.spec.selector` key, the strategy is hard-coded to `atomic`, so when using SSA to apply the Service object, ArgoCD replaces the entire `.spec.selector` object, causing problem to Rollout Controller's behavior.
https://github.com/kubernetes/api/blob/f2b3dfac9f9ae72c30f767ec29ff086b0fd10211/core/v1/types.go#L5333

**Comment by ViktorLindgren95** [comment]
+1 . Problem still persist as of ```1.8.3``` . Auto promotion is skipped with blue green when using server side apply. The problem still consists even if you apply the sync annotation ```argocd.argoproj.io/sync-options: ServerSideApply=false``` to the rollout & template. The only solution seems to be as stated earlier to disable the server sync on the application level, which causes issues when running a large gitops layer

**Comment by motoki317** [comment]
@ViktorLindgren95 What version of ArgoCD are you using? There's a bug (non-implemented feature) in ArgoCD that prevents resource-level annotation `argocd.argoproj.io/sync-options: ServerSideApply=false` from working (https://github.com/argoproj/argo-cd/issues/20306), but this was only fixed in v2.14.0 or later (https://github.com/argoproj/argo-cd/commit/e2bc96bb8629f547b2667932dba72265c559120f).

This resource-level annotation is working for me in ArgoCD v3.0.10.
Note: you have to set this annotation to the active and preview `Service`s that the Argo Rollouts is controlling.

**Comment by ViktorLindgren95** [comment]
@motoki317 God i love an active community ^^, fast answer. Im using ```v3.0.12```.  

Alright so i have to set the ```argocd.argoproj.io/sync-options: ServerSideApply=false``` to services specifically or in addition to adding it to the rollout object, or is it the services that is causing the SSA issue?

**Comment by motoki317** [comment]
@ViktorLindgren95 
It is the `Service`s causing auto-promotion issues, as stated in [my comment](https://github.com/argoproj/argo-rollouts/issues/3437#issuecomment-2401902106).

So for example if you have a Rollout configuration like this:
```yaml
  strategy:
    blueGreen:
      activeService: your-active-svc
      previewService: your-preview-svc
```

You have to set this annotation to the Service objects:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: your-active-svc
  annotations:
    # See: https://github.com/argoproj/argo-rollouts/issues/3437
    argocd.argoproj.io/sync-options: ServerSideApply=false
```
(and set it for preview-svc as well)

You don't actually have to set this annotation to the `Rollout` object, only to the `Service` objects the blue-green Rollout is referencing to.

**Comment by ViktorLindgren95** [comment]
@motoki317 Works now. Services is the issue as you said. Thank you so much for a quick answer 😄

**Comment by seanturner026** [comment]
The `ServerSideApply=False` annotation on services didn't help sadly. 
Ended up doing a global `ignoreDifferences` which seemed to help.
Also currently have `SSA=False` on the Services which I think makes sense.

```yaml
configs:
  cm:
    resource.customizations.ignoreDifferences._Service: |
      jqPathExpressions:
        - .spec.selector."rollouts-pod-template-hash"
```

We've also got Server Side Diff enabled too.

```yaml
    controller.diff.server.side: "true"
```

The levers are fairly complex here TBH
