### ISSUE TITLE
Aggregate role names collide with workflow aggregate roles

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#35]
Looks like there was some copy and paste issues. This should not be named `argo-aggregate-to-view` since that's what we are using for argo workflow-controller.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-aggregate-to-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
```
