### ISSUE TITLE
BlueGreen AutoPromoteSeconds doesn't promote after timeout

### ISSUE THREAD

**Issue by Dymanik** [argoproj/argo-rollouts#351]
On version v0.6.2, the BlueGreenRollout stays paused after the time have passed. 
It seems like the pause condition is getting removed during the sync step, but it is getting added again during the rollout step.
The AutoPromoteSeconds seems to be based on the elapsed time of the last PauseCondition, so as it is getting removed during the sync step that information is lost and the rollout restarts the timer.

Manifest
```
# This example demonstrates a Rollout using the blue-green update strategy, which contains a manual
# gate before promoting the new stack.
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-bluegreen
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-bluegreen
  template:
    metadata:
      labels:
        app: rollout-bluegreen
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:green
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    blueGreen:
      # activeService specifies the service to update with the new template hash at time of promotion.
      # This field is mandatory for the blueGreen update strategy.
      activeService: rollout-bluegreen-active
      # previewService specifies the service to update with the new template hash before promotion.
      # This allows the preview stack to be reachable without serving production traffic.
      # This field is optional.
      previewService: rollout-bluegreen-preview
      # autoPromotionEnabled disables automated promotion of the new stack by pausing the rollout
      # immediately before the promotion. If omitted, the default behavior is to promote the new
      # stack as soon as the ReplicaSet are completely ready/available.
      # Rollouts can be resumed using: `kubectl argo rollouts resume ROLLOUT`
      autoPromotionEnabled: false
      autoPromotionSeconds: 20

---
kind: Service
apiVersion: v1
metadata:
  name: rollout-bluegreen-active
spec:
  selector:
    app: rollout-bluegreen
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: rollout-bluegreen-preview
spec:
  selector:
    app: rollout-bluegreen
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
```

Example output
```
Name:            rollout-bluegreen
Namespace:       argo-rollouts
Status:          ॥ Paused
Strategy:        BlueGreen
Images:          argoproj/rollouts-demo:blue (active)
                 argoproj/rollouts-demo:green (preview)
Replicas:
  Desired:       2
  Current:       4
  Updated:       2
  Ready:         4
  Available:     2

NAME                                           KIND        STATUS     AGE    INFO
⟳ rollout-bluegreen                            Rollout     ॥ Paused   8m42s
├──# revision:4
│  └──⧉ rollout-bluegreen-7d6b6cb796           ReplicaSet  ✔ Healthy  7m43s  preview
│     ├──□ rollout-bluegreen-7d6b6cb796-p8942  Pod         ✔ Running  3m51s  ready:1/1
│     └──□ rollout-bluegreen-7d6b6cb796-px94s  Pod         ✔ Running  3m51s  ready:1/1
└──# revision:3
   └──⧉ rollout-bluegreen-5f49884f5c           ReplicaSet  ✔ Healthy  8m42s  active
      ├──□ rollout-bluegreen-5f49884f5c-dn7sv  Pod         ✔ Running  8m42s  ready:1/1
      └──□ rollout-bluegreen-5f49884f5c-fvn9c  Pod         ✔ Running  8m42s  ready:1/1
```

Controller log during sync attempt
```
time="2020-01-10T14:35:34Z" level=info msg="Started syncing rollout at (2020-01-10 14:35:34.000572898 +0000 UTC m=+1270.136139285)" namespace=argo-rollouts rollout=rollout-bluegreen
time="2020-01-10T14:35:34Z" level=info msg="Syncing replicas only (controllerPaused: true, userPaused false, isScaling: false)" namespace=argo-rollouts rollout=rollout-bluegreen
time="2020-01-10T14:35:34Z" level=info msg="Patch status successfully" namespace=argo-rollouts rollout=rollout-bluegreen
time="2020-01-10T14:35:34Z" level=info msg="Reconciliation completed" namespace=argo-rollouts rollout=rollout-bluegreen time_ms=9.667608
time="2020-01-10T14:35:34Z" level=info msg="Successfully synced" namespace=argo-rollouts rollout=rollout-bluegreen
time="2020-01-10T14:35:34Z" level=info msg="Started syncing rollout at (2020-01-10 14:35:34.015914049 +0000 UTC m=+1270.151480385)" namespace=argo-rollouts rollout=rollout-bluegreen
time="2020-01-10T14:35:34Z" level=info msg="Condition Patch status successfully" namespace=argo-rollouts rollout=rollout-bluegreen
time="2020-01-10T14:35:34Z" level=info msg="Reconciling new ReplicaSet 'rollout-bluegreen-7d6b6cb796'" namespace=argo-rollouts rollout=rollout-bluegreen
time="2020-01-10T14:35:34Z" level=info msg="Reconciling new ReplicaSet 'rollout-bluegreen-7d6b6cb796'" namespace=argo-rollouts rollout=rollout-bluegreen
time="2020-01-10T14:35:34Z" level=info msg="Reconciling old replica sets" namespace=argo-rollouts rollout=rollout-bluegreen
time="2020-01-10T14:35:34Z" level=info msg="Cleaning up old replicasets" namespace=argo-rollouts rollout=rollout-bluegreen
time="2020-01-10T14:35:34Z" level=info msg="Reconciling preview service 'rollout-bluegreen-preview'" namespace=argo-rollouts rollout=rollout-bluegreen
time="2020-01-10T14:35:34Z" level=info msg="Reconciling pause" namespace=argo-rollouts rollout=rollout-bluegreen
time="2020-01-10T14:35:34Z" level=info msg="Not finished reconciling pause" namespace=argo-rollouts rollout=rollout-bluegreen
time="2020-01-10T14:35:34Z" level=info msg="Timed out (false) [last progress check: 2020-01-10 14:35:14 +0000 UTC - now: 2020-01-10 14:35:34.024587574 +0000 UTC m=+1270.160153915]" namespace=argo-rollouts rollout=rollout-bluegreen
time="2020-01-10T14:35:34Z" level=info msg="Adding pause reason BlueGreenPause with start time 2020-01-10T14:35:34Z" namespace=argo-rollouts rollout=rollout-bluegreen
time="2020-01-10T14:35:34Z" level=info msg="Patch status successfully" namespace=argo-rollouts rollout=rollout-bluegreen
time="2020-01-10T14:35:34Z" level=info msg="Reconciliation completed" namespace=argo-rollouts rollout=rollout-bluegreen time_ms=16.199512
time="2020-01-10T14:35:34Z" level=info msg="Successfully synced" namespace=argo-rollouts rollout=rollout-bluegreen
time="2020-01-10T14:35:34Z" level=info msg="Started syncing rollout at (2020-01-10 14:35:34.034635943 +0000 UTC m=+1270.170202364)" namespace=argo-rollouts rollout=rollout-bluegreen
time="2020-01-10T14:35:34Z" level=info msg="Condition Patch status successfully" namespace=argo-rollouts rollout=rollout-bluegreen
time="2020-01-10T14:35:34Z" level=info msg="Syncing replicas only (controllerPaused: true, userPaused false, isScaling: false)" namespace=argo-rollouts rollout=rollout-bluegreen
time="2020-01-10T14:35:34Z" level=info msg="Enqueueing Rollout in 19.95600978s seconds" namespace=argo-rollouts rollout=rollout-bluegreen
time="2020-01-10T14:35:34Z" level=info msg="No status changes. Skipping patch" namespace=argo-rollouts rollout=rollout-bluegreen
time="2020-01-10T14:35:34Z" level=info msg="Reconciliation completed" namespace=argo-rollouts rollout=rollout-bluegreen time_ms=9.886452
time="2020-01-10T14:35:34Z" level=info msg="Successfully synced" namespace=argo-rollouts rollout=rollout-bluegreen
time="2020-01-10T14:35:34Z" level=info msg="Started syncing rollout at (2020-01-10 14:35:34.049036638 +0000 UTC m=+1270.184603349)" namespace=argo-rollouts rollout=rollout-bluegreen
time="2020-01-10T14:35:34Z" level=info msg="Syncing replicas only (controllerPaused: true, userPaused false, isScaling: false)" namespace=argo-rollouts rollout=rollout-bluegreen
time="2020-01-10T14:35:34Z" level=info msg="Enqueueing Rollout in 19.950342563s seconds" namespace=argo-rollouts rollout=rollout-bluegreen
time="2020-01-10T14:35:34Z" level=info msg="No status changes. Skipping patch" namespace=argo-rollouts rollout=rollout-bluegreen
time="2020-01-10T14:35:34Z" level=info msg="Reconciliation completed" namespace=argo-rollouts rollout=rollout-bluegreen time_ms=1.134305
time="2020-01-10T14:35:34Z" level=info msg="Successfully synced" namespace=argo-rollouts rollout=rollout-bluegreen
```
