### ISSUE TITLE
[Possible Regression] A rollout object that uses workloadRef does not transparently pass through `template` (Deployment reference) to the notification webhook templates

### ISSUE THREAD

**Issue by Nexarian** [argoproj/argo-rollouts#3536]
Checklist:

* [X] I've included steps to reproduce the bug.
* [X] I've included the version of argo rollouts.

**Describe the bug**

The bug is identical to the closed report [here](https://github.com/argoproj/argo-rollouts/issues/1611). In summary: For Rollout objects that use `WorkloadRef` rather than directly inline the deployment manifest, referencing the `template` object in `argo-rollouts-notification-configmap`

The above issue was supposed to fix this, so one of the following is therefore true:
- This is a regression since then.
- The original issue was never truly fixed (note that the last comment on it is to this effect).
- I am doing something with my specific Rollout/Webhook/Notification configuration that uniquely breaks this scenario.

**To Reproduce**

Create rollout:

```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: test-deployment-service
  annotations:
    notifications.argoproj.io/subscribe.test-service.test-service: ""
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
        ...
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-deployment-service
```

Create webhook:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-notification-configmap
  labels:
    app.kubernetes.io/instance: test-deployment-service
data:
  template.test-service: |
    webhook:
      test-service:
        method: POST
        body: |
          {
            "data":  "{{ .rollout.spec.template }}"
          }
  trigger.test-service: |
    - description: "When to trigger the test service"
      when: rollout.status.blueGreen.activeSelector == rollout.status.blueGreen.previewSelector
      send:
      - test-service
  service.webhook.test-service: |
    url: [URL of service to call]
    headers:
    - name: accept
      value: application/json
    - name: Content-Type
      value: application/json
    - name: X-API-KEY
      value: $service-token
```

Deploy rollout with a simple deployment. This was largely tested with a "hello world" style service built using FastAPI.

When the webhook triggers, the data in the `template` object is `template:map[metadata:map[creationTimestamp:<nil>]` or simple "no value" in the Argo Rollouts logs.

**Expected behavior**

For this not to be an empty map with no value. The real thing I'm after is `"{{ .rollout.spec.template.spec.containers 0).image }}"` but that can't work if `.rollout.spec.template` doesn't resolve.

**Version**

`Argo Rollouts controller:` v1.6.6
`Helm Chart:` https://github.com/argoproj/argo-helm/blob/argo-rollouts-2.35.1/charts/argo-rollouts

**Incidental Information**
A few more details may help reproduce this that I'm not 100% sure are relevant:
- I have `--self-service-notification-enabled` turned on for my Argo Rollouts Deployment
- As you may note above, I am using a service token that is stored in `argo-rollouts-notification-secret`

---
**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
