### ISSUE TITLE
SMI (Service Mesh Interface) TrafficSplit Support

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#359]
For canary traffic routing, In addition to:
* istio supoprt (merged)
* nginx-ingress ([proposed](https://github.com/argoproj/argo-rollouts/blob/master/docs/features/traffic-management/nginx.md))

We also need a generic SMI traffic routing provider to support meshes like Linkerd, or even Istio using the [SMI adapter for Istio](https://github.com/deislabs/smi-adapter-istio).

This implementation should be much simpler than Istio provider since the `TrafficSplit` resource could be completely owned by the `Rollout` object itself, as opposed to referenced like the Istio provider.

**Comment by wmorgan** [comment]
Cool, please let us know how we can help from the Linkerd side

**Comment by ilevine** [comment]
Would you consider to add support for Gloo, envoy based API gateway? we would like to help
https://github.com/solo-io/gloo

**Comment by jessesuen** [comment]
Thanks for the offers of support! I think we might ask for some feedback on the proposal and API specification. We've already discussed what this might look like, internally but will formalize it into a proposal and send it out to the community. That said, the `TrafficSplit` interface is so simple that I can't imagine the spec to be any more complicated than:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
spec:
  ...
  strategy:
    canary:
      canaryService: canary-service # required
      stableService: stable-service  # required
      trafficRouting:
        smi: {}
      steps:
      - setWeight: 10
      - pause: {duration: 1h}
      - setWeight: 20
...
```

@ilevine yes, the goal for this is for rollouts to be extensible to support different service mesh / ingress controllers. The SMI provider support (this issue) will give us the common denominator for basic weight based traffic splits. For any advanced routing features which only available to specific mesh providers (e.g. istio header based traffic splitting), we would need have mesh specific fields in the specification.
