### ISSUE TITLE
Argo Rollout Canary Service with HTTPS not working

### ISSUE THREAD

**Issue by Cstack-Krish** [argoproj/argo-rollouts#3593]
**Describe the bug**

We are having a deployment with a service object that works only on HTTPS, we have configured argo rollouts with canary strategy with ambassador traffic routing. When a rollout is triggered a canary mapping file is generated/cloned as expected but the value of spec.service in the canary mapping file is not having the https://. Based on the code snippet that clones the mapping for canary service, seems like the value of spec.service in mapping gets replaced with the value of canaryservice in the rollout manifest.
https://github.com/argoproj/argo-rollouts/blob/2e7cf6932a0c5111967d6ba4b27716580985a34f/rollout/trafficrouting/ambassador/ambassador.go#L230-L256

We wanted the https:// to be retained for our functionality to work.

![image](https://github.com/argoproj/argo-rollouts/assets/80777629/ef0bb0c3-cb4c-481f-af6e-fb9c9a76e555)

**Expected behavior**

Cloned canary service mapping file should respect the protocol defined in the actual mapping which is https here.

**Rollout Spec**

```
strategy:
    canary:
      canaryService: identity-canary
      stableService: identity
      steps:
        - setWeight: 40
        - pause: {}
        - setWeight: 90
        - pause: {}
      trafficRouting:
        ambassador:
          mappings:
            - identity
```

**Ambassador Mapping**

```
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: identity
  namespace: identity-canary-qa1
spec:
  connect_timeout_ms: 3000
  hostname: hostname.com
  load_balancer:
    policy: round_robin
  prefix: /.*
  prefix_regex: true
  resolver: endpoint
  rewrite: ''
  service: 'https://identity/'
```

**Version**

Argo-Rollouts Version: v1.6.6
AgoCD Version: v2.11.0
Ambassador Version: v3.9.0

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
