### ISSUE TITLE
AnalysisTemplate with Datadog provider result in failure with "Error Message: received non 2xx response code: 404 {"errors":["Not found"]}" preventing rollouts from completing

### ISSUE THREAD

**Issue by andrii-korotkov-verkada** [argoproj/argo-rollouts#3605]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've included the version of argo rollouts.

**Describe the bug**

The rollouts with a canary and analysis steps and templates couldn't fetch Datadog metrics properly, resulting in failures like
```
Metric <X> assessed Error due to consecutiveErrors (N+1) > consecutiveErrorLimit (N): "Error Message: received non 2xx response code: 404 {"errors":["Not found"]}"
```
This error comes from Datadog API.
The issue was confirmed to happen only rarely on v1.6.6. Note that after downgrade and trying to sync the error would still pop up - you need a fresh build and deploy to see the issue gone. After upgrading back to v1.7.0-rc1 and doing a fresh deploy the issue is back.

**To Reproduce**

Create an analysis template with a Datadog query like below and try to do a rollout which uses it. Having a formula may or may not be important.
```
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate-inline
  labels:
    type: inline
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  args:
  - name: threshold
  - name: metric-prefix
  - name: env
  - name: service-name
  - name: version
  metrics:
  - name: error-rate
    interval: 60s
    count: 5
    successCondition: result <= {{args.threshold}}
    failureLimit: 2
    provider:
      datadog:
        interval: 5m
        query: |
          default_zero(sum:{{args.metric-prefix}}.errors{env:{{args.env}},service:{{args.service-name}},version:{{args.version}}}) /
          sum:{{args.metric-prefix}}.hits{env:{{args.env}},service:{{args.service-name}},version:{{args.version}}}.fill(last)
```

**Expected behavior**

The 404 shouldn't be returned by Datadog.

**Screenshots**

**Version**

v1.7.0-rc1

**Logs**

```
Measurement had error: received non 2xx response code: 404 {"errors":["Not found"]}
```
```
AnalysisRun Patch: {"status":{"metricResults":[{"consecutiveError":4,"error":4,"measurements":[{"finishedAt":"2024-05-29T18:31:59Z","message":"received non 2xx response code: 404 {\"errors\":[\"Not found\"]}","phase":"Error","startedAt":"2024-05-29T18:31:59Z"},{"finishedAt":"2024-05-29T18:32:09Z","message":"received non 2xx response code: 404 {\"errors\":[\"Not found\"]}","phase":"Error","startedAt":"2024-05-29T18:32:09Z"},{"finishedAt":"2024-05-29T18:32:19Z","message":"received non 2xx response code: 404 {\"errors\":[\"Not found\"]}","phase":"Error","startedAt":"2024-05-29T18:32:19Z"},{"finishedAt":"2024-05-29T18:32:29Z","message":"received non 2xx response code: 404 {\"errors\":[\"Not found\"]}","phase":"Error","startedAt":"2024-05-29T18:32:29Z"}],"name":"gateway-error-rate","phase":"Running"},{"consecutiveError":4,"error":4,"measurements":[{"finishedAt":"2024-05-29T18:31:59Z","message":"received non 2xx response code: 404 {\"errors\":[\"Not found\"]}","phase":"Error","startedAt":"2024-05-29T18:31:59Z"},{"finishedAt":"2024-05-29T18:32:09Z","message":"received non 2xx response code: 404 {\"errors\":[\"Not found\"]}","phase":"Error","startedAt":"2024-05-29T18:32:09Z"},{"finishedAt":"2024-05-29T18:32:19Z","message":"received non 2xx response code: 404 {\"errors\":[\"Not found\"]}","phase":"Error","startedAt":"2024-05-29T18:32:19Z"},{"finishedAt":"2024-05-29T18:32:29Z","message":"received non 2xx response code: 404 {\"errors\":[\"Not found\"]}","phase":"Error","startedAt":"2024-05-29T18:32:29Z"}],"name":"apdex-rate","phase":"Running"}]}}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
