### ISSUE TITLE
Broken Datadog apiVersion v1 analyses by default in v1.7.0

### ISSUE THREAD

**Issue by aguiraorodriguez** [argoproj/argo-rollouts#3641]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've included the version of argo rollouts.

**Describe the bug**

Datadog analyses that don't specify a version default to `v1` and the new field `aggregator` [defaults](https://github.com/argoproj/argo-rollouts/blob/master/manifests/crds/analysis-template-crd.yaml#L178) to `last` in the CRD. So, an existing v1 analysis will fail with this error:

```
time="2024-06-17T10:24:26Z" level=warning msg="Measurement had error: Aggregator is not supported in v1. Please review the Analysis Template." analysisrun=podinfo-856d6c544-278-4 metric=latency-slo namespace=example
```

This [test](https://github.com/argoproj/argo-rollouts/blob/ae3a53a2dee686d6e35ce464ed27acefa464ce9b/metricproviders/datadog/datadogV1_test.go#L324) is not catching this case because the metric object doesn't reproduce the default `last` value of `aggregator`.

**To Reproduce**

Given this spec of an analysis:

```yaml
spec:
  args:
    - name: service-name
    - name: environment
    - name: clusterName
  metrics:
    - count: 3
      failureLimit: 2
      interval: 60s
      name: latency-slo
      provider:
        datadog:
          apiVersion: v1
          interval: 60s
          query: |
            sum:http_request_duration_seconds.bucket{
              upper_bound:0.5,
              short_image:sre-podinfo,
              kube_namespace:example,
              env:{{args.environment}},
              kube_cluster_name:{{args.clusterName}},
              kube_service:{{args.service-name}}
            }.as_rate() /
            sum:http_request_duration_seconds.count{
              short_image:sre-podinfo,
              kube_namespace:example,
              env:{{args.environment}},
              kube_cluster_name:{{args.clusterName}},
              kube_service:{{args.service-name}}
            }.as_rate()
      successCondition: result >= 0.95
```

when migrating from Argo Rollouts 1.6.x to 1.7.0, the next run will fail with:

```
time="2024-06-17T10:24:26Z" level=warning msg="Measurement had error: Aggregator is not supported in v1. Please review the Analysis Template." analysisrun=podinfo-856d6c544-278-4 metric=latency-slo namespace=example
```

**Expected behavior**

The analysis should still use the implicit apiVersion `v1` and thus pass.

**Screenshots**

**Version**

v1.7.0

**Logs**

```
time="2024-06-17T10:24:26Z" level=warning msg="Measurement had error: Aggregator is not supported in v1. Please review the Analysis Template." analysisrun=podinfo-856d6c544-278-4 metric=latency-slo namespace=example
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
