### ISSUE TITLE
In Blue-Green, Pre-Promotion jobs are getting terminated prematurely whenever application pod crashes and the whole rollout is marked successfull

### ISSUE THREAD

**Issue by RishabKumar** [argoproj/argo-rollouts#3724]
Issue: In the v1.7.0+6937996 argo rollouts, the pre promotion job prematurely terminates whenever application pod crashes.
As a result the argo rollout is marked completed with success and the blue green switch is done. The pre-promotion job is not run again.

Expected Outcome: The argo rollout should retrigger the pre promotion job if they exited prematurely the last time.

Steps to reproduce:
- While the pre promotion job is running, kill the application pod.
- the pre promotion job will be marked successful and the blue-green switch will happen.

Sample Code:
**Rollout.yaml**
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app.kubernetes.io/name: argo-sample
    app.kubernetes.io/component: web
    application: argo_sample
  name: "argo-sample"
    
spec:
  analysis:
  progressDeadlineSeconds: 600
  progressDeadlineAbort: true
  replicas: 1
  strategy:
    blueGreen:
      activeService: "argo-sample-service"
      previewService: "argo-sample-service-preview"
      autoPromotionEnabled: true
      abortScaleDownDelaySeconds: 5
      scaleDownDelaySeconds: 5
      prePromotionAnalysis:
        templates:
        - templateName: "argo-sample-analysis"
  selector:
    matchLabels:
      app.kubernetes.io/name: argo-sample
      app.kubernetes.io/component: web
      application: argo_sample
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argo-sample
        app.kubernetes.io/component: web
        application: argo_sample
      annotations:
        linkerd.io/inject: disabled
    spec:	
      containers:
      - name: "argo-sample"      
        image: "alpine:latest"
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "-c"]
        args:
        - |
            sleep 100000
            echo "done"


```

**prepromotion.yaml**
```
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: "argo-sample-analysis"
  labels:
    app.kubernetes.io/component: "analysis-job"
spec:
  metrics:
  - name: "argo-sample-analysis-job"
    initialDelay: 5s
    failureLimit: 0
    interval: 8s
    count: 1
    provider:
      job:
        spec:
          template:
            metadata:
              labels:
                type: analysis-job
                app.kubernetes.io/component: "analysis-job"
              annotations:
                linkerd.io/inject: disabled
            spec:
              containers:
              - name: "test"
                image: "alpine:latest"
                command:
                - pwsh
                - -Command
                - |
                     sleep 3000
                     echo "job completed"
                     EXIT 0
              restartPolicy: Never
              nodeSelector: 
                kubernetes.io/os: linux
                kubernetes.io/arch: amd64
          backoffLimit: 4
```

**services.yaml**
```
apiVersion: v1
kind: Service
metadata:
  name: "argo-sample-service"
spec:
  selector:
    app.kubernetes.io/name: argo-sample
    app.kubernetes.io/component: "web"
  ports:
  - protocol: TCP
    port: 443
---

apiVersion: v1
kind: Service
metadata:
  name: "argo-sample-service-preview"
spec:
  selector:
    app.kubernetes.io/name: argo-sample
    app.kubernetes.io/component: "web"
  ports:
  - protocol: TCP
    port: 443

```
