### ISSUE TITLE
Global AnalysisTemplates (cross namespace references)

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#373]
Currently AnalysisTemplates are namespaced scoped objects, which limits their reusability within a cluster. 

We always envisioned the ability/use case where AnalysisTemplates could be defined someplace centrally in the cluster, and referenced by Rollouts & Experiments in different namespaces. This enables operators to install, and come up with a set of AnalysisTemplate definitions which are common to all users in their cluster, so that app developers would not need to understand how to write templates, or know the details of thing like prometheus hostnames, metric names, etc...

It would also help enable our original vision where AnalysisTemplates are shareable entities even across different companies and communities -- where a library of common patterns and templates could be contributed by different communities (e.g. AnalysisTemplates specific to the prometheus metrics produced by istio, linkerd, nginx-ingress, etc...).

To support centralized AnalysisTemplates, this proposal is to introduce an optional `namespace:` field to the analysis reference, like so:

```yaml
  strategy:
    canary:
      analysis:
        templateName: success-rate
        namespace: shared-rollouts-templates
```

For security purposes, the referenced AnalysisTemplates would need to "opt-in" on being able to be referenced globally in this manner. 

```yaml
kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: success-rate
spec:
  global: true  // indicates that this template can be referenced across namespaces
  metrics:
  - name: success-rate
```

One open issue is how to handle the case where an AnalysisTemplate references a secret as part of https://github.com/argoproj/argo-rollouts/issues/372.

**Comment by jdamour98** [comment]
+1

**Comment by mclarke47** [comment]
I'm going to pick this up!

**Comment by dthomson25** [comment]
This change is going to consist of three steps: Updating the spec, passing the AnalysisTemplate namespace from the Rollout to the Experimented created by the Rollout, and grabbing the global AnalysisTemplate when creating an AnalysisRun

### Updating the Spec:
1. Modifying the [AnalysisTemplateSpec](https://github.com/argoproj/argo-rollouts/blob/master/pkg/apis/rollouts/v1alpha1/analysis_types.go#L30) in AnalysisTemplate object to have a global field in the analysis.go.
1. Modifying the [RolloutAnalysisTemplates](https://github.com/argoproj/argo-rollouts/blob/master/pkg/apis/rollouts/v1alpha1/types.go#L352) and [RolloutExperimentStepAnalysisTemplateRef](https://github.com/argoproj/argo-rollouts/blob/master/pkg/apis/rollouts/v1alpha1/types.go#L268) in the Rollout object to have the namespace field
1. Modifying [ExperimentAnalysisTemplateRef](https://github.com/argoproj/argo-rollouts/blob/master/pkg/apis/rollouts/v1alpha1/experiment_types.go#L189) in the Experiment object to have the namespace field.
1. Using make codegen to rebuild the autogenerated code.

### Passing the AnalysisTemplate namespace from the Rollout to the Experimented created by the Rollout

1. Modify [this code block](https://github.com/argoproj/argo-rollouts/blob/master/rollout/experiment.go#L106) to pass the namespace to the experiment that is being created if it was specified in the Rollout.

### Grabbing the global AnalysisTemplate when creating an AnalysisRun
1. Modify these two code blocks [here](https://github.com/argoproj/argo-rollouts/blob/master/rollout/analysis.go#L345-L359) and [here](https://github.com/argoproj/argo-rollouts/blob/master/experiments/experiment.go#L493) to take the namespace into account (using the parent object's namespace if not specified) and then checking the returned analysis run has the global field set to true. If the global is false, we need to return an error.


That should be all the required changes! Let me know if you have any other questions!

**Comment by jessesuen** [comment]
Instead of cross namespace referencing, my thought on this has evolved into introducing ClusterAnalysisTemplate.

With workflows, we tried to see if we could reference WorkflowTemplates in a different namespace, or provide a way to mark them as global, in order to avoid ClusterWorkflowTemplates, but I think ultimately we decided a new cluster scoped CRD was a better/cleaner approach, despite having to introduce yet another CRD.

**Comment by jessesuen** [comment]
Some rationale. The original proposal requires namespace to be referenced as part of the template reference. i.e.:

```yaml
  strategy:
    canary:
      analysis:
        templateName: success-rate
        namespace: shared-rollouts-templates
```

But the choice to reference across namespace and use a namespace simply to hold analysis templates intended be used at a cluster scope, seems like an anti pattern, given there is already a native concept of cluster vs. namespaced scoped resources.

The new proposal (which is what was done in Argo Workflows), is to simply indicate when a template name is cluster-scoped (See https://github.com/argoproj/argo/blob/54f5be361f597d45c97469095a2e5cb5678436a8/examples/cluster-workflow-template/cluster-wftmpl-dag.yaml#L20-L22)

```yaml
  strategy:
    canary:
      analysis:
        templateName: success-rate
        clusterScope: true
```
