### ISSUE TITLE
Allow External Spec/Template References within the Rollouts Experiment Specification

### ISSUE THREAD

**Issue by tomsanbear** [argoproj/argo-rollouts#374]
**Summary:**
Currently, within a standalone argo-rollouts experiment, one has to write out the entire pod template for running experiments. It would be nice to reference existing/externally existing pod templates/deployments instead to allow for flexibility when using the experiments API. 

Sample Potential Spec (from: @jessesuen )
```
kind: Experiment
apiVersion: argoproj.io/v1alpha1
metadata:
  name: my-experiment
spec:
  templates:
  - name: foo
    specRef:
      kind: Deployment
      apiVersion: apps/v1
      name: my-deployment
```

**Motivation:**
I would like to use the experiments spec, and not the rollouts spec for testing deployments in my ArgoCD environments, but do not want to manage the pod specs in multiple places.

**Points of Interest:**
Some initial concerns/thoughts with this after chatting with @jessesuen 
- What will happen when the referenced spec is deleted or modified
- What restrictions need to be made
- What options are required when selecting/referencing a template to ensure uniqueness

([Original Conversation on slack](https://argoproj.slack.com/archives/CKTN88XFH/p1579580060022400))
