### ISSUE TITLE
Add timeout attribute for NewRelic metrics provider

### ISSUE THREAD

**Issue by orlando-valdez-ck** [argoproj/argo-rollouts#3741]
# Summary

Add an optional `timeout` attribute to the NewRelic provider spec in the `AnalysisTemplate` so we can send that to the NerdGraph Graphql API. This can look something like this,

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage
  namespace: default
spec:
  metrics:
    - name: cpu-usage
      interval: 2m
      failureCondition: "result['percentile[95]'] >= 70"
      failureLimit: 4
      provider:
        newRelic:
          timeout: 10 # this timeout will be sent to and applied by the NerdGraph API to the query
          profile: newrelic
          query: "FROM K8sContainerSample SELECT percentile(`cpuCoresUtilization`, 95)['95'] SINCE 1 WEEK AGO"
```
When not configured, the default of `5` seconds can be sent to the API.

# Use Cases

This can be used when using queries that take longer than the default of `5` seconds that the NerdGraph API uses when no timeout value is sent. This will avoid an AnalysisRun to error out with `NRDB query duration exceeded the set timeout` errors returned by the GraphQL API.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
