### ISSUE TITLE
New Relic canary verification

### ISSUE THREAD

**Issue by akorzy-pl** [argoproj/argo-rollouts#3771]
# Summary

Analysis templates for New Relic canary verification using response time and error rate.

# Motivation

Canary verification is most useful when it's automatic. Statistical analysis using averages and standard deviation can be used to detect anomalies in the response time and error rate. New Relic is an observability tool with its own query language NRQL. Generic reusable queries for canary analysis would be useful to the community.

# Proposal

The implementation described below has been used for around nine months in production at Priceline.com.

## Use Cases

Users of New Relic that want to increase software quality by using of automatic canary verification.

## Security Considerations

The New Relic token needs to be stored in a secret in each namespace where canaries are to be deployed.

## Risks and Mitigations

Some tuning of the parameters may be required for a given application to prevent false positives and negatives.

## Goals

Provide analysis templates for response time and error rate analysis.

## Non-Goals

Deploying the New Relic token is outside of scope of this proposal.

## Implementation

Note that we assume that data has a tag called `tags.DC`, which contains the name of the region. This allows for making more precise region-specific comparisons between the canary and stable data.

Response time analysis template:

```
kind: ClusterAnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: new-relic.canary.response-time.verification
spec:
  args:
  - name: appName
  - name: rolloutName
  - name: region
  - name: analysisInitialDelay
  - name: analysisInterval
  - name: analysisTimeWindow
    value: "70 seconds"  # follow the NRQL format for durations
  - name: analysisCount
    value: "5"
  - name: responseTimeDeviationThreshold
  - name: responseTimeResolution
  - name: numberOfEndpoints
    value: "5"
  - name: inconclusiveLimit
  - name: stablePodHash
  - name: latestPodHash
  - name: new-relic.user.api-key
    valueFrom:
      secretKeyRef:
        name: new-relic.secret
        key: user.api-key
  - name: new-relic.account-id
    valueFrom:
      secretKeyRef:
        name: new-relic.secret
        key: account-id
  metrics:
  - name: "NR Canary Response Time"
    successCondition: "len(result) > 0 && all(result, {.responseTimeDeviation < {{ args.responseTimeDeviationThreshold }}})"
    failureCondition: "false"
    initialDelay: "{{ args.analysisInitialDelay }}"
    interval: "{{ args.analysisInterval }}"
    count: "{{ args.analysisCount }}"
    inconclusiveLimit: "{{ args.inconclusiveLimit }}"
    provider:
      web:
        method: POST
        url: "https://api.newrelic.com/graphql"
        timeoutSeconds: 120
        headers:
          - key: Content-Type
            value: "application/json"
          - key: API-Key
            value: "{{ args.new-relic.user.api-key }}"
        jsonPath: "{$.data.actor.account.nrql.results}"
        jsonBody:
          query: |
              {
                actor {
                  account(id: {{ args.new-relic.account-id }}) {
                    nrql(
                      timeout: 120
                      query: """
                              select
                                  average(abs(`canary` - `stable`) / (`stdev` + {{ args.responseTimeResolution }})) as `responseTimeDeviation`,
                                  average(`canary`) as `canary`, average(`stable`) as `stable`, average(`stdev`) as `stdev`
                              from
                                  (
                                      select
                                          (filter(
                                              average(`apm.service.transaction.duration`),
                                              where
                                                host like '{{ args.rolloutName }}-{{ args.stablePodHash }}%'
                                          ) or -1.0) as `stable`,
                                          (filter(
                                              average(`apm.service.transaction.duration`),
                                              where
                                                host like '{{ args.rolloutName }}-{{ args.latestPodHash }}%'
                                          ) or -1.0) as `canary`,
                                          filter(
                                              stddev(`apm.service.transaction.duration`),
                                              where
                                                host like '{{ args.rolloutName }}-{{ args.stablePodHash }}%'
                                          ) as `stdev`
                                      from
                                          Metric
                                      where
                                          appName = '{{ args.appName }}'
                                          and tags.DC = '{{ args.region }}'
                                          and transactionName in (
                                              select
                                                  transactionName
                                              from
                                                  (
                                                      FROM
                                                          Metric
                                                      SELECT
                                                          count(`apm.service.transaction.duration`) FACET transactionName
                                                      WHERE
                                                          appName = '{{ args.appName }}'
                                                          and tags.DC = '{{ args.region }}'
                                                      LIMIT
                                                          {{ args.numberOfEndpoints }}
                                                  )
                                          ) FACET transactionName
                                  ) FACET transactionName since {{ args.analysisTimeWindow }} ago
                      """
                    ) {
                      results
                    }
                  }
                }
              }
          variables: ""
```

Error rate analysis template:

```
kind: ClusterAnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: new-relic.canary.error-rate.verification
spec:
  args:
  - name: appName
  - name: rolloutName
  - name: region
  - name: analysisInitialDelay
  - name: analysisInterval
  - name: analysisTimeWindow
    value: "70 seconds"  # follow the NRQL format for durations
  - name: analysisCount
    value: "5"
  - name: errorRateDeviationThreshold
  - name: errorRateResolution
    value: "0.05"
  - name: numberOfEndpoints
    value: "5"
  - name: inconclusiveLimit
  - name: stablePodHash
  - name: latestPodHash
  - name: new-relic.user.api-key
    valueFrom:
      secretKeyRef:
        name: new-relic.secret
        key: user.api-key
  - name: new-relic.account-id
    valueFrom:
      secretKeyRef:
        name: new-relic.secret
        key: account-id
  metrics:
  - name: "NR Canary Error Rate"
    successCondition: "all(result, {.errorRateDeviation < {{ args.errorRateDeviationThreshold }}})"
    failureCondition: "false"
    initialDelay: "{{ args.analysisInitialDelay }}"
    interval: "{{ args.analysisInterval }}"
    count: "{{ args.analysisCount }}"
    inconclusiveLimit: "{{ args.inconclusiveLimit }}"
    provider:
      web:
        method: POST
        url: "https://api.newrelic.com/graphql"
        timeoutSeconds: 120
        headers:
          - key: Content-Type
            value: "application/json"
          - key: API-Key
            value: "{{ args.new-relic.user.api-key }}"
        jsonPath: "{$.data.actor.account.nrql.results}"
        jsonBody:
          query: |
              {
                actor {
                  account(id: {{ args.new-relic.account-id }}) {
                    nrql(
                      timeout: 120
                      query: """
                              select
                                  average((`canary` - `stable`) / (`stable` + {{ args.errorRateResolution }})) as `errorRateDeviation`,
                                  average(`canary`) as `canary`, average(`stable`) as `stable`
                              from
                                  (
                                      select
                                          (filter(
                                              count(`apm.service.transaction.error.count`) / count(`apm.service.transaction.duration`),
                                              where
                                                host like '{{ args.rolloutName }}-{{ args.stablePodHash }}%'
                                          ) or 0) as `stable`,
                                          (filter(
                                              count(`apm.service.transaction.error.count`) / count(`apm.service.transaction.duration`),
                                              where
                                                host like '{{ args.rolloutName }}-{{ args.latestPodHash }}%'
                                          ) or 0) as `canary`
                                      from
                                          Metric
                                      where
                                          appName = '{{ args.appName }}'
                                          and tags.DC = '{{ args.region }}'
                                          and transactionName in (
                                              select
                                                  transactionName
                                              from
                                                  (
                                                      FROM
                                                          Metric
                                                      SELECT
                                                          count(`apm.service.transaction.duration`) FACET transactionName
                                                      WHERE
                                                          appName = '{{ args.appName }}'
                                                          and tags.DC = '{{ args.region }}'
                                                      LIMIT
                                                          {{ args.numberOfEndpoints }}
                                                  )
                                          ) FACET transactionName
                                  ) FACET transactionName since {{ args.analysisTimeWindow }} ago
                      """
                    ) {
                      results
                    }
                  }
                }
              }
          variables: ""
```

## Examples

Please find below an example of a Rollout definition:

```
metadata:
  labels:
    application: my-app
    cluster: cluster-name-1
    region: us-east1
spec:
  strategy:
    canary:
      steps:
        - setWeight: 1
        - analysis:
            analysisRunMetadata: {}
            args:
              - name: metricName
                value: 'Automatic canary verification'
              - name: appName
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['application']
              - name: rolloutName
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: region
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['region']
              - name: stablePodHash
                valueFrom:
                  podTemplateHashValue: Stable
              - name: latestPodHash
                valueFrom:
                  podTemplateHashValue: Latest
              - name: analysisCount
                value: "30"
              - name: analysisInitialDelay
                value: 4m
              - name: analysisInterval
                value: 1m
              - name: analysisTimeWindow
                value: 70 seconds
              - name: errorRateDeviationThreshold
                value: "2.0"
              - name: errorRateResolution
                value: "0.05"
              - name: inconclusiveLimit
                value: "3"
              - name: responseTimeDeviationThreshold
                value: "6.0"
              - name: responseTimeResolution
                value: "0.3"
            templates:
              - clusterScope: true
                templateName: new-relic.canary.response-time.verification
              - clusterScope: true
                templateName: new-relic.canary.error-rate.verification
        - setWeight: 100
```

## Upgrade/Downgrade Strategy

There is no impact for users who don't use this feature.

# Drawbacks

Currently unknown ;)

# Alternatives

A New Relic metric provider is available in Argo Rollouts, but it isn't used in this implementation, as the standard web provider will suffice.

---

**Message from the maintainers**:

Impacted by this missing feature? Give it a 👍. We prioritize the issues with the most 👍.
