### ISSUE TITLE
setHeaderRoute causes sync loop when rollout steps have finished

### ISSUE THREAD

**Issue by rolandkool** [argoproj/argo-rollouts#3773]
Checklist:

* [ ] I've included steps to reproduce the bug.
* [ ] I've included the version of argo rollouts.

**Describe the bug**

When a Rollout is using Istio and has a `setHeaderRoute` step configured in the steps section, a sync loop is triggered at the end of a Rollout process. The `VirtualService` is continuously updated between the following to states:

```
  http:
  - match:
    - headers:
        canary:
          exact: "true"
    name: canary-header
    route:
    - destination:
        host: recommendationservice.recosvc.svc.cluster.local
        subset: canary
      weight: 100
  - name: primary
    route:
    - destination:
        host: recommendationservice.recosvc.svc.cluster.local
        subset: stable
      weight: 100
    - destination:
        host: recommendationservice.recosvc.svc.cluster.local
        subset: canary
      weight: 0
```

and

```
  http:
  - name: primary
    route:
    - destination:
        host: recommendationservice.recosvc.svc.cluster.local
        subset: stable
      weight: 100
    - destination:
        host: recommendationservice.recosvc.svc.cluster.local
        subset: canary
      weight: 0
```

**To Reproduce**

The following Rollout resource triggers it:
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    rollout.argoproj.io/revision: "2"
    rollout.argoproj.io/workload-generation: "24"
  name: recosvc-canary-rollout
  namespace: recosvc
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    canary:
      analysis:
         ...
      steps:
      - setHeaderRoute:
          match:
          - headerName: canary
            headerValue:
              exact: "true"
          name: canary-header
      - setWeight: 25
      - pause:
          duration: 2m
      - setWeight: 50
      - pause:
          duration: 2m
      - setWeight: 75
      - pause:
          duration: 2m
      trafficRouting:
        istio:
          destinationRule:
            canarySubsetName: canary
            name: recommendationservice
            stableSubsetName: stable
          virtualService:
            name: recommendationservice
            routes:
            - primary
        managedRoutes:
        - name: canary-header
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: recommendationservice
```

**Expected behavior**

Rollout should not continue updating the `VirtualService` indefinitely.

**Version**

1.7.1

**Logs**

Due to size, a logfile has been attached.
[argo-rollout.log](https://github.com/user-attachments/files/16509362/argo-rollout.log)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
