### ISSUE TITLE
HPA targeting a Rollout scales down AnalysisRun Job generated pods

### ISSUE THREAD

**Issue by davcd** [argoproj/argo-rollouts#3828]
Checklist:

* [X] I've included steps to reproduce the bug.
* [X] I've included the version of argo rollouts.

**Describe the bug**

Having a Rollout that runs an analysis, and a HPA targeting to that Rollout. If an scale down event occurs during the execution of the analysis, the pod generated by the AnalysisRun Job is terminated. Also the Rollout proceeds as passed even the analysis did not finish.

**To Reproduce**

Having the following resources

- Rollout with an AnalysisRun
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
...
spec:
  ...
  strategy:
    blueGreen:
      activeService: my-service
      previewService: my-service-preview
      prePromotionAnalysis:
        templates:
          - templateName: some-analysis-maybe-e2e
```

- HPA referencing a Rollout:
```
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
...
spec:
  maxReplicas: Y
  minReplicas: X
  ...
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: rollout-name
```

And the following events occurrs:

- A new Rollout starts:
  - Preview pods are booted
  - Pre promotion analysis run job starts, creating analysis pod

- For some reason (ie burst traffic end) an scale down event is generated:
  - Both old and preview replicaset are scaled down
  - Analysis pod is terminated too

**Expected behavior**

AnalysisRun Job generated pods are not affected by HPA

**Version**
v1.7.2+59e5bd3

---
**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
