### ISSUE TITLE
Ability to reference an Exeriment template's podTemplateHash

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#383]
Rollouts is meant to support the use case where a baseline `ReplicaSet` could be started at the same time as a canary `ReplicaSet`, for the purposes of performing statistical canary analysis (e.g. mann-whitney).

However, this experience needs some more work. There's currently a limitation where we cannot reference the `pod-template-hash` of any of the templates that are involved in the experiment step.

Currently only the following is supported:

```yaml
            args:
            - name: baseline-hash
              valueFrom:
                podTemplateHash: Stable   # currently we only support magic values of "Stable" or "Latest"
```

However, the "Stable" hash is not useful because it would also include the pods which have already been running.

This proposal is to somehow be able to reference the podTemplateHash as a variable in the experiment. Here are some options:

**Option 1:**

We overload `valueFrom.podTemplateHash` to now be able to reference a name of a template (in addition to the `Stable` and `Latest` well-known references). For example:

```yaml
  strategy:
    canary:
      steps:
      - experiment:
          duration: 10m
          templates:
          - name: aaaaaaaa
            specRef: stable
          - name: bbbbbbb
            specRef: canary
          analysis:
            templateName: mann-whitney
            args:
            - name: baseline-hash
              valueFrom:
                podTemplateHash: aaaaaaaa  # name reference to the baseline's pod-template-hash
            - name: canary-hash
              valueFrom:
                podTemplateHash: bbbbbbb    # name reference to the canary's pod-template-hash
```

**Option 2:**

Introduce a `{{templates.TEMPLATENAME.podTemplateHash}}` variable:

```yaml
  strategy:
    canary:
      steps:
      - experiment:
          duration: 10m
          templates:
          - name: aaaaaaaa
            specRef: stable
          - name: bbbbbbb
            specRef: canary
          analysis:
            templateName: mann-whitney
            args:
            - name: baseline-hash
              value: "{{templates.aaaaaaaa.podTemplateHash}}"
            - name: canary-hash
              value: "{{templates.bbbbbbb.podTemplateHash}}"
```

**Comment by jessesuen** [comment]
Note that the solution needs to be independent of the Rollout integration with Experiment. In other words, we should be able to do something like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Experiment
metadata:
  name: experiment-with-analysis
spec:
  templates:
  - name: purple
    selector:
      matchLabels:
        app: rollouts-demo
    template:
      metadata:
        labels:
          app: rollouts-demo
      spec:
        containers:
        - name: rollouts-demo
          image: argoproj/rollouts-demo:purple
          imagePullPolicy: Always
  - name: orange
    selector:
      matchLabels:
        app: rollouts-demo
    template:
      metadata:
        labels:
          app: rollouts-demo
      spec:
        containers:
        - name: rollouts-demo
          image: argoproj/rollouts-demo:orange

  analyses:
  - name: success-rate-orange
    templateName: success-rate
    args:
      name: pod-hash
      value: "{{templates.orange.podTemplateHash}}"

  - name: success-rate-purple
    templateName: success-rate
    args:
      name: pod-hash
      value: "{{templates.purple.podTemplateHash}}"

```
