### ISSUE TITLE
Argo Rollouts unable to reconcile when service uses gRPC probes

### ISSUE THREAD

**Issue by erickbitso** [argoproj/argo-rollouts#3830]
I'm using ArgoCD (using Kustomize) + Argo Rollouts with an application that uses gRPC probes.
When I onboard an existing application (uses a Deployment) to use Rollouts (using ArgoCD I replace the Deployment with a Rollout using sync-waves to prevent downtime), the migration happens smoothly. However as I patch the Rollout resource with the new image, I see the ArgoCD Application marks the Rollout as Out of sync and it's unable to sync. The diff shows `service: null` in the gRPC probes.
This is an example of my Rollout resource

```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
    labels:
        app: myapp
    name: myapp
spec:
    selector:
        matchLabels:
            app: myapp
    strategy:
        canary:
            canaryService: myapp-canary
            stableService: myapp-stable
            steps:
                - setWeight: 10
                - pause:
                    duration: 90s
                - setWeight: 50
                - pause:
                    duration: 1m
                - setWeight: 80
                - pause:
                    duration: 1m
            trafficRouting:
                istio:
                    virtualServices:
                        - name: myapp
                          routes:
                            - primary
    template:
        spec:
            containers:
                - image: myapp:NOTAG
                  livenessProbe:
                    failureThreshold: 10
                    grpc:
                        port: 8201
                        service: ""
                  name: myapp
                  ports:
                    - containerPort: 8201
                      name: grpc
                      protocol: TCP
                  readinessProbe:
                    failureThreshold: 3
                    grpc:
                        port: 8201
                        service: ""
                  startupProbe:
                    failureThreshold: 300
                    grpc:
                        port: 8201
                        service: ""
```

ArgoCD Application manifest

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: myapp
    namespace: argocd
spec:
    destination:
        name:myapp
        namespace: dev
        server: null
    ignoreDifferences:
        - group: ""
          kind: Service
          managedFieldsManagers:
            - rollouts-controller
        - group: networking.istio.io
          kind: VirtualService
          managedFieldsManagers:
            - rollouts-controller
        - group: argoproj.io
          jqPathExpressions:
            - .spec.template.spec.containers[] | .livenessProbe.grpc.service
            - .spec.template.spec.containers[] | .readinessProbe.grpc.service
            - .spec.template.spec.containers[] | .startupProbe.grpc.service
          kind: Rollout
    project: default
    revisionHistoryLimit: 10
    source:
        path: entities/deployments/dev/morty-test
        plugin:
            name: entity-deployment-plugin-v1.0
        repoURL: https://github.com/xxx/xxx-environments
    syncPolicy:
        automated:
            allowEmpty: true
            prune: true
            selfHeal: true
        retry:
            backoff:
                duration: 5s
                factor: 2
                maxDuration: 3m
            limit: 5
        syncOptions:
            - Validate=false
            - RespectIgnoreDifferences=true
            - PruneLast=true
```
As seen above, I even tried to ignore the service field in the probes, to no avail

As seen below, the ArgoCD diff shows that in the live manifest Probes.grpc.service = null and it's unable to reconcile it, as the desired value is empty
<img width="1323" alt="Screenshot 2024-09-10 at 11 16 07 p m" src="https://github.com/user-attachments/assets/c6d08ca0-3aa2-4c32-a245-bc6ca1aeebe2">
This however, does not represent reality, as if I do a kubectl get against the rollout, I can clearly see that service = "" (which is the default value)
![Screenshot 2024-09-10 at 6 27 31 p m](https://github.com/user-attachments/assets/e33f487b-41e1-4d19-9e81-93fc011df271)
In order to work around this, I can change the probes to either use HTTP or exec and then the problem is not present.

ArgoCD version: v2.11.7+e4a0246
Argo Rollouts version: v 1.7.1

**Expected behavior**

ArgoCD is able to reconcile the Rollout resource, the service field is shown as "" (empty string) and not null.

**Logs**

```
time="2024-09-10T23:20:22Z" level=info msg="Adding resource result, status: 'Synced', phase: 'Running', message: 'rollout.argoproj.io/ohlc unchanged'" application=argocd/ohlc-dev kind=Rollout name=ohlc namespace=dev phase=Sync syncId=41807-hOUzF
time="2024-09-10T23:20:22Z" level=info msg="Updating operation state. phase: Running -> Succeeded, message: 'one or more tasks are running' -> 'successfully synced (all tasks run)'" application=argocd/ohlc-dev syncId=41807-hOUzF
time="2024-09-10T23:20:22Z" level=info msg="sync/terminate complete" application=argocd/ohlc-dev duration=93.849526ms syncId=41807-hOUzF
time="2024-09-10T23:20:22Z" level=info msg="updated 'argocd/ohlc-dev' operation (phase: Succeeded)" appNamespace=argocd application=ohlc-dev project=default
time="2024-09-10T23:20:22Z" level=info msg="Partial sync operation to cb84e63c2e01f472682d8a38d425c39fe9c4e42f succeeded" application=ohlc-dev dest-namespace=dev dest-server="https://xxx.gr7.us-east-2.eks.amazonaws.com" reason=OperationCompleted type=Normal
time="2024-09-10T23:20:22Z" level=info msg="Refreshing app status (controller refresh requested), level (2)" application=argocd/ohlc-dev
time="2024-09-10T23:20:22Z" level=info msg="Comparing app state (cluster: https://xxx.gr7.us-east-2.eks.amazonaws.com, namespace: dev)" application=argocd/ohlc-dev
time="2024-09-10T23:20:22Z" level=info msg="GetRepoObjs stats" application=argocd/ohlc-dev build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=75 unmarshal_ms=47 version_ms=27
time="2024-09-10T23:20:22Z" level=info msg="Normalized app spec: {\"status\":{\"sync\":{\"comparedTo\":{\"destination\":{\"name\":\"xxx-dev\",\"namespace\":\"dev\"},\"ignoreDifferences\":[{\"kind\":\"Service\",\"managedFieldsManagers\":[\"rollouts-controller\"]},{\"group\":\"networking.istio.io\",\"kind\":\"VirtualService\",\"managedFieldsManagers\":[\"rollouts-controller\"]},{\"group\":\"argoproj.io\",\"jqPathExpressions\":[\".spec.template.spec.containers[] | .livenessProbe.grpc.service\",\".spec.template.spec.containers[] | .readinessProbe.grpc.service\",\".spec.template.spec.containers[] | .startupProbe.grpc.service\"],\"kind\":\"Rollout\"}],\"source\":{\"path\":\"entities/deployments/dev/ohlc\",\"plugin\":{\"name\":\"entity-deployment-plugin-v1.0\"},\"repoURL\":\"https://github.com/xxx/xxx-environments\",\"targetRevision\":\"HEAD\"}}}}}" application=argocd/ohlc-dev
time="2024-09-10T23:20:22Z" level=info msg="Skipping auto-sync: already attempted sync to cb84e63c2e01f472682d8a38d425c39fe9c4e42f with timeout 5s (retrying in 4.391952896s)" application=argocd/ohlc-dev
time="2024-09-10T23:20:22Z" level=info msg="Update successful" application=argocd/ohlc-dev
time="2024-09-10T23:20:22Z" level=info msg="Reconciliation completed" application=argocd/ohlc-dev dedup_ms=0 dest-name=xxx-dev dest-namespace=dev dest-server="https://xxx.gr7.us-east-2.eks.amazonaws.com" diff_ms=33 fields.level=2 git_ms=75 health_ms=1 live_ms=12 patch_ms=17 setop_ms=0 settings_ms=0 sync_ms=0 time_ms=198
time="2024-09-10T23:20:27Z" level=info msg="Refreshing app status (controller refresh requested), level (827562262216)" application=argocd/ohlc-dev
time="2024-09-10T23:20:27Z" level=info msg="Comparing app state (cluster: https://xxx.gr7.us-east-2.eks.amazonaws.com, namespace: dev)" application=argocd/ohlc-dev
time="2024-09-10T23:20:27Z" level=info msg="GetRepoObjs stats" application=argocd/ohlc-dev build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=29 unmarshal_ms=12 version_ms=16
time="2024-09-10T23:20:27Z" level=info msg="Normalized app spec: {\"status\":{\"sync\":{\"comparedTo\":{\"destination\":{\"name\":\"xxx-dev\",\"namespace\":\"dev\"},\"ignoreDifferences\":[{\"kind\":\"Service\",\"managedFieldsManagers\":[\"rollouts-controller\"]},{\"group\":\"networking.istio.io\",\"kind\":\"VirtualService\",\"managedFieldsManagers\":[\"rollouts-controller\"]},{\"group\":\"argoproj.io\",\"jqPathExpressions\":[\".spec.template.spec.containers[] | .livenessProbe.grpc.service\",\".spec.template.spec.containers[] | .readinessProbe.grpc.service\",\".spec.template.spec.containers[] | .startupProbe.grpc.service\"],\"kind\":\"Rollout\"}],\"source\":{\"path\":\"entities/deployments/dev/ohlc\",\"plugin\":{\"name\":\"entity-deployment-plugin-v1.0\"},\"repoURL\":\"https://github.com/xxx/xxx-environments\",\"targetRevision\":\"HEAD\"}}}}}" application=argocd/ohlc-dev

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
