### ISSUE TITLE
Patch in the VirtualService is not working when there is only one named route

### ISSUE THREAD

**Issue by jeanmorais** [argoproj/argo-rollouts#3884]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've included the version of argo rollouts.

**Describe the bug**

When the VirtualService has only 1 HTTPRoute, with the defined `name`, and this name is not defined in `Rollout` (`trafficRouting.istio.virtualService.routes`), the patch is not performed.

**To Reproduce**

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
  name: canary-sample-app
  namespace: sample-canary
spec:
  replicas: 3
  selector:
    matchLabels:
      app: canary-sample-app
  strategy:
    canary:
      canaryMetadata:
        labels:
          canary: "true"
      maxSurge: 25%
      maxUnavailable: 0
      stableMetadata:
        labels:
          canary: "false"
      steps:
      - pause: {}
      - setWeight: 30
      - pause: {}
      - setWeight: 70
      - pause: {}
      trafficRouting:
        istio:
          destinationRule:
            canarySubsetName: canary
            name: canary-sample-app
            stableSubsetName: stable
          virtualService:
            name: canary-sample-app
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: canary-sample-app
  namespace: sample-canary
spec:
  gateways:
  - canary-sample-app
  hosts:
  - canary-sample-app.domain.com
  http:
  - match:
    - uri:
        prefix: /
    name: default
    route:
    - destination:
        host: canary-sample-app
        port:
          number: 80
        subset: stable
      weight: 100
    - destination:
        host: canary-sample-app
        port:
          number: 80
        subset: canary
      weight: 0
```

The doc mentions that (optional if there is a single route in VirtualService, required otherwise):
```yaml
      trafficRouting:
        istio:
          virtualService:
            name: rollout-vsvc   # required
            routes:
            - primary            # optional if there is a single route in VirtualService, required otherwise
```
Ref: https://argo-rollouts.readthedocs.io/en/stable/features/traffic-management/istio/#host-level-traffic-splitting

But it doesn't happen here:
https://github.com/argoproj/argo-rollouts/blob/50300e5525848e09c68d7e89c02cdc8fa022b414/rollout/trafficrouting/istio/istio.go#L903-L913

Maybe, the code should first check if the VirtualService has only one route, and then return it (I've tested it and it worked):
```go
// something like this
	if len(routeNames) == 0 {
		if len(httpRoutes) == 1 {
			return []int{0}, nil
		}
		
		for i, route := range httpRoutes {
			if route.Name == "" {
				return []int{i}, nil
			}
		}
	}
```

Could you confirm if this is enough? I can open a PR with this fix.

**Expected behavior**

The  `weight` field changed according to the promotion of the steps.

**Version**

v1.7.2

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
