### ISSUE TITLE
UI - route path basing with nginx-ingress gives blank page - Uncaught SyntaxError: Unexpected number

### ISSUE THREAD

**Issue by tbernacchi** [argoproj/argo-rollouts#3927]
**Describe the bug**
argo-rollouts UI gives blank page using path based routing with nginx-ingress

**To Reproduce**
```
helm install argo-rollouts argo/argo-rollouts -n argo-rollouts --set dashboard.enabled=true
```
[reference](https://artifacthub.io/packages/helm/argo/argo-rollouts)

Create a ingress route:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: self-signed
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  generation: 3
  name: argo-rollouts
  namespace: argo-rollouts
spec:
  ingressClassName: nginx
  rules:
  - host: mykubernetes.com
    http:
      paths:
      - backend:
          service:
            name: argo-rollouts-dashboard
            port:
              number: 3100
        path: /argo-rollouts(/|$)(.*)
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - mykubernetes.com
    secretName: my-kubernetes-cert
```

Try to access the UI on `mykubernetes.com/argo-rollouts/rollouts`

**Expected behavior**

Access the argo-rollouts UI.

**Screenshots UI-error**

![image](https://github.com/user-attachments/assets/938b84c3-bc3c-42c4-aca9-6866c36a913f)

**Version**

```version=v1.7.2+59e5bd3```

**Logs**

```
# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts
Found 2 pods, using pod/argo-rollouts-7fbb98c9f8-k6h7t
time="2024-10-24T14:19:56Z" level=info msg="Argo Rollouts starting" version=v1.7.2+59e5bd3
time="2024-10-24T14:19:56Z" level=info msg="Creating event broadcaster"
time="2024-10-24T14:19:56Z" level=info msg="Setting up event handlers"
time="2024-10-24T14:19:56Z" level=info msg="Setting up experiments event handlers"
time="2024-10-24T14:19:56Z" level=info msg="Setting up analysis event handlers"
time="2024-10-24T14:19:56Z" level=info msg="Leaderelection get id argo-rollouts-7fbb98c9f8-k6h7t_02c8b926-7041-4aec-955e-ac1990eb7a2f"
time="2024-10-24T14:19:56Z" level=info msg="attempting to acquire leader lease argo-rollouts/argo-rollouts-controller-lock..."
time="2024-10-24T14:19:56Z" level=info msg="Starting Healthz Server at 0.0.0.0:8080"
time="2024-10-24T14:19:56Z" level=info msg="Starting Metric Server at 0.0.0.0:8090"
time="2024-10-24T14:19:56Z" level=info msg="New leader elected: argo-rollouts-7fbb98c9f8-hzwcp_815190f4-34e9-435d-a2fa-0d5ce5b0b569"
time="2024-10-24T14:20:13Z" level=info msg="New leader elected: argo-rollouts-7fbb98c9f8-v5c8d_733fb990-baeb-485a-9bb6-f03180079aab"
```

Looking at the ingress-controller logs I got 200 in the request...

```192.168.1.101 - - [21/Oct/2024:15:51:40 +0000] "GET /argo-rollouts/rollouts HTTP/2.0" 200 297 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" 208 0.005 [argo-rollouts-argo-rollouts-dashboard-3100] [] 10.42.0.91:3100 297 0.005 200 e82fbe4208a76b7f5f8d0318550cb83f```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
