### ISSUE TITLE
Correct the yaml of `Store Oauth access token in argo-rollouts-notification-secret secret` doc 

### ISSUE THREAD

**Issue by chansuke** [argoproj/argo-rollouts#3942]
Checklist:

* [ ] I've included steps to reproduce the bug.
* [ ] I've included the version of argo rollouts.

**Describe the bug**

While reading the [Slack integration documentation](https://argo-rollouts.readthedocs.io/en/stable/generated/notification-services/slack/), I noticed a potential issue with the example YAML.
The secret's name seems to be incorrectly specified in the documentation.

In the YAML snippet, the name field is shown as "secret-name". However, it should be `argo-rollouts-notification-secret`?

```yaml
  apiVersion: v1
  kind: Secret
  metadata:
      name: <secret-name> // It should be `argo-rollouts-notification-secret` ?
  stringData:
      slack-token: <Oauth-access-token>
```
 
Reference: [source code](https://github.com/argoproj/argo-rollouts/blob/53c4f12d66620e9224d3810489b94cfe8f35b054/utils/record/record.go#L51)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

**Logs**

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
