### ISSUE TITLE
Rollout stuck in infinite "Progressing" even after progressDeadlineSeconds exceeds

### ISSUE THREAD

**Issue by greykurotsuki** [argoproj/argo-rollouts#3988]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've included the version of argo rollouts.

**Describe the bug**

In the default scenario, Rollouts work as expected: after a ReplicaSet becomes healthy, it starts the analysis and promotes the new stable version. However, I encountered an issue when deploying a broken revision.

For example, I intentionally misconfigured the `startupProbe` to make it fail, so the ReplicaSet could never become ready. I expected the Rollout to mark this revision as **Degraded** and abort the preview release once `progressDeadlineSeconds` was exceeded. This behavior worked as expected for the first broken revision, but did not for revision 4, which has different image tag and is broken.

**To Reproduce**

My configurations:

`bluegreen-service.yaml`:
```
apiVersion: v1
kind: Service
metadata:
  name: bluegreen-demo-preview
  labels:
    app: bluegreen-demo
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: bluegreen-demo
---
apiVersion: v1
kind: Service
metadata:
  name: bluegreen-demo
  labels:
    app: bluegreen-demo
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: bluegreen-demo
```

`bluegreen-rollout.yaml`:
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: bluegreen-demo
  labels:
    app: bluegreen-demo
spec:
  replicas: 3
  revisionHistoryLimit: 1
  progressDeadlineSeconds: 60
  progressDeadlineAbort: true
  selector:
    matchLabels:
      app: bluegreen-demo
  template:
    metadata:
      labels:
        app: bluegreen-demo
    spec:
      containers:
      - name: bluegreen-demo
        image: argoproj/rollouts-demo:blue # initially "blue", but changed to "green" to create a new "broken" release
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
        startupProbe: # initially commented section, but uncommented once I need to break the new release.
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 30
  strategy:
    blueGreen:
      autoPromotionEnabled: false
      activeService: bluegreen-demo
      previewService: bluegreen-demo-preview
```
And a `kustomization.yaml` to deploy it:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- bluegreen-rollout.yaml
- bluegreen-service.yaml
```

1. Start with a fresh Rollout object with a healthy revision (Revision 1).
2. Deploy a broken revision (Revision 2) with the misconfigured health check.
Result: Rollout correctly marked it as Degraded after progressDeadlineSeconds and aborted the release.
3. Deploy a healthy revision (Revision 3).
Result: Revision 3 became the new stable version.
4. Deploy another broken revision (Revision 4).
Issue: The Rollout got stuck in an infinite Progressing state with the message: “active service cutover pending.”

**Expected behavior**

The Rollout should mark Revision 4 as **Degraded** and abort the release, similar to how it handled Revision 2.

**Screenshots**

<img width="711" alt="Initial release" src="https://github.com/user-attachments/assets/eac34b1a-7128-43ee-9a13-4d1134b394a2">

---

<img width="782" alt="Broken revision 2  expected behavior" src="https://github.com/user-attachments/assets/aaf6b29c-b275-47f0-9872-9a43a943e1e9">

---

<img width="744" alt="Successful revision 3" src="https://github.com/user-attachments/assets/ee884f47-4c3a-48f7-8647-291fb5bcdd82">

---

<img width="800" alt="Broken revision 4, stuck in infinite progressing state" src="https://github.com/user-attachments/assets/6622c707-00d8-4279-ad35-3d2c057284ed">

---

**Version**

**Argo Rollouts Version**: 2.37.7 (Chart version)
**Argo Rollouts Image**: quay.io/argoproj/argo-rollouts:v1.7.2

**Logs**

Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts
[controller-logs.txt](https://github.com/user-attachments/files/18038448/controller-logs.txt)

Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=bluegreen-demo
[bluegreen-rollout-grep-logs.txt](https://github.com/user-attachments/files/18038443/bluegreen-rollout-grep-logs.txt)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
