### ISSUE TITLE
Feature: ingress-nginx traffic management

### ISSUE THREAD

**Issue by moensch** [argoproj/argo-rollouts#401]
We intend on contributing ingress-nginx traffic management. Opening this issue to discuss the proposed design.

I propose we extend the [proposed spec](https://github.com/argoproj/argo-rollouts/blob/737d9cd537303ccf40c29056925da730a9763f07/docs/features/traffic-management/nginx.md#integration-with-argo-rollouts) with an additional `canaryIngress` field. this means the user has to create **two** `extensions/v1beta1.Ingress` resources, and pass both to the rollouts controller.
We should also rename `primaryIngress` to `stableIngress` to match `stableService`.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
spec:
  ...
  strategy:
    canary:
      canaryService: canary-service # required
      stableService: stable-service  # required
      trafficRouting:
        nginx:
           annotationPrefix: example.nginx.com/ # optional
           stableIngress: stable-ingress  # required
```

The controller will then perform the following actions:

1. Validate the `Ingress` referenced by `stableIngress` is pointed at the `stableService ` in all host rules (`/rules[*]/http/paths[*]/backend/serviceName`)
2. Create a copy of the `stableIngress` (append `name` with `-canary`). In this copy, add the  `nginx.ingress.kubernetes.io/canary: "true"` annotation.
4. During reconcile, update the `nginx.ingress.kubernetes.io/canary-weight` annotation on the canary ingress to match the desired weight. Set to `0` once we reach `100`, similar as is done with the current Istio traffic management reconciler.
