### ISSUE TITLE
Support SMI TrafficMetrics as a metric provider

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#406]
The SMI spec introduces TrafficMetrics as a new kubernetes kind to power things like HPA and canary updates:

https://github.com/deislabs/smi-spec/blob/master/traffic-metrics.md

An example TrafficMetrics looks like:

```yaml
apiVersion: metrics.smi-spec.io/v1alpha1
kind: TrafficMetrics
# See ObjectReference v1 core for full spec
resource:
  name: foo-775b9cbd88-ntxsl
  namespace: foobar
  kind: Pod
edge:
  direction: to
  resource:
    name: baz-577db7d977-lsk2q
    namespace: foobar
    kind: Pod
timestamp: 2019-04-08T22:25:55Z
window: 30s
metrics:
- name: p99_response_latency
  unit: seconds
  value: 10m
- name: p90_response_latency
  unit: seconds
  value: 10m
- name: p50_response_latency
  unit: seconds
  value: 10m
- name: success_count
  value: 100
- name: failure_count
  value: 100
```

How TrafficMetrics could be used to drive canary promotions is described here:
https://github.com/deislabs/smi-spec/blob/master/traffic-metrics.md#canary

Today we currently support prometheus, wavefront, web, job, kayenta as metric providers. As support for additional metric providers is requested/desired, this list will continue to grow.

By supporting `TrafficMetrics` API, this enables Rollouts to gain metric analysis for any mesh provider which implements the spec, for free. Rollouts should add native support for using `TrafficMetrics` to drive canary promotion, in order to encourage SMI standards, and limit our need to continue to add native support for many metric providers.
