### ISSUE TITLE
unable to load plugin in version 1.8

### ISSUE THREAD

**Issue by guy-frontegg** [argoproj/argo-rollouts#4096]
Checklist:

* [X] I've included steps to reproduce the bug.
* [X] I've included the version of argo rollouts.

**Describe the bug**

When upgrading to version 1.8 and have argo rollout load plugin 
````yaml
 trafficRouterPlugins: |-
        - name: "argoproj-labs/gatewayAPI"
          location: "https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/releases/download/v0.2.0/gateway-api-plugin-linux-amd64"
````
argo rollout pod throws this error
`time="2025-02-02T15:06:33Z" level=fatal msg="Failed to init config: failed to unmarshal traffic router plugins while initializing: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go value of type []types.PluginItem"
`
**To Reproduce**

Simply add the rollouts-plugin-trafficrouter-gatewayapi via config map

**Expected behavior**

Should load up the plugin

**Screenshots**

**Version**

New version 1.8

**Logs**

```
time="2025-02-02T15:06:33Z" level=fatal msg="Failed to init config: failed to unmarshal traffic router plugins while initializing: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go value of type []types.PluginItem"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
