### ISSUE TITLE
failed to find the credentials for datadog metrics provider in v1.8.0

### ISSUE THREAD

**Issue by TAKAyukiatkwsk** [argoproj/argo-rollouts#4103]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've included the version of argo rollouts.

**Describe the bug**

After v1.8.0, AnalysisRun fails with Datadog metrics. It fails to find credentials for Datadog.

**To Reproduce**

- Create AnalysisTemplate and use Datadog provider metrics
- Create Rollout and configure analysis from the AnalysisTemplate
- Configure Secret in argo-rollouts namespace (address is not specified).
- Start rollout

```
apiVersion: v1
kind: Secret
metadata:
  name: datadog
type: Opaque
stringData:
  api-key: <datadog-api-key>
  app-key: <datadog-app-key>
```

**Expected behavior**

- Succeed to find the credentials and get Datadog metrics.
- If `address` is not specified in datadog Secret, use the default endpoint (`https://api.datadoghq.com/`)
  - at https://github.com/argoproj/argo-rollouts/blob/v1.8.0/metricproviders/datadog/datadog.go#L94-L97

**Screenshots**

**Version**

v1.8.0

**Logs**

```
time="2025-02-03T07:57:07Z" level=warning msg="Measurement had error: failed to find the credentials for datadog metrics provider" analysisrun=api-server-rollout-86b7689974-221 metric=http-error namespace=***
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
