### ISSUE TITLE
Rollout Stuck Indefinitely When New Pods Fail to Come Up – Abort and Progress Deadline Not Triggering

### ISSUE THREAD

**Issue by revandarth** [argoproj/argo-rollouts#4128]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've included the version of argo rollouts.

**Describe the bug**

When deploying a Canary Rollout (using workloadRef) in Argo Rollouts v1.8.0, if the new version's pods fail to come up (e.g. due to ImagePullBackOff), the rollout remains stuck in a "Progressing" state indefinitely. Even with `progressDeadlineSeconds: 600` and `progressDeadlineAbort: true` configured, the rollout never marks itself as failed and manual abort commands (`kubectl argo rollouts abort <rollout-name>`) do not take effect unless the failing ReplicaSet is manually deleted. This blocks any subsequent updates, as the rollout remains stuck with the failing new ReplicaSet.

**To Reproduce**

1. Create a Canary Rollout using `workloadRef` to an existing Deployment.
2. Update the rollout to use a new image that is misconfigured or non-existent so that pods fail (e.g., trigger ImagePullBackOff).
3. Confirm that the rollout status remains "Progressing" with a message like:

```
Name:            xapproxy
Namespace:       red
Status:          ◌ Progressing
Message:         more replicas need to be updated
Strategy:        Canary
  Step:          0/4
  SetWeight:     10
  ActualWeight:  0
Images:         dockerhub.io/istio/proxyv2:1.17.1 (canary, stable)
                dockerhub.io/myproxy:25.2.1.3-745.76dfaae (canary)
                dockerhub.io/myproxy:25.2.1.3-746.76dfaae (stable)
```

4. Run the command:
```bash
kubectl argo rollouts abort <rollout-name> -n <namespace>
```

and observe that the rollout does not transition to a failed/aborted state. 

5. As a workaround, executing argo undo/abort:
`kubectl argo rollouts undo <rollout-name> -n <namespace>` or `kubectl argo rollouts abort <rollout-name> -n <namespace>`

followed by manually deleting the failing ReplicaSet (e.g., `kubectl delete rs <failing-replicaset> -n <namespace>`) is required before any new version updates are applied.

**Expected behavior**

- The rollout controller should detect that the new ReplicaSet’s pods are not becoming Ready within the defined progress deadline and automatically abort or mark the rollout as failed.
- The abort command should work regardless of the pod state, allowing the rollout to revert to the stable ReplicaSet and enabling new updates.
- No manual intervention (such as deleting the failing ReplicaSet) should be necessary.

**Version**

Argo Rollouts version: 1.8.0 (stable, released ~2 weeks ago)

**Comment by zachaller** [comment]
Can you confirm if this behavior exists on older versions? Does this also only effect workloadRef, if you don't use workloadRef does it behave as expected?

**Comment by revandarth** [comment]
@zachaller  sorry for the late response. 

This behavior does not happen with v1.7.2. If a pod becomes stuck, the earlier version allows for subsequent updates, and the abort command operates correctly. It shows the same behavior regardless of whether workloadRef or without. 

Please let me if you require additional information to reproduce this issue. Others are experiencing similar issue and have reported them on Slack, please see the following thread.

https://cloud-native.slack.com/archives/C01U781DW2E/p1739561010345209

**Comment by nebojsa-prodana** [comment]
UPDATE: I just tried the latest master and the issue is not present in there. Could we make a new release so that we do not have to rely on an unreleased version?

**Comment by darthkurak** [comment]
Have the same issue. Checked on 1.8.2 and helm chart: 2.39.3. It is a very annoying issue. If someone deploys a failing service - it will stuck unless manually remove the broken Replica Set.

**Comment by dtamrazovupgrade** [comment]
@zachaller I've reproduced it with the following setup. This issue did not occur on our prior version v1.7.1, it sounds like v1.7.3 is when it was introduced:

Argo Rollouts version: v1.8.1

Manifests:

```yaml
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: my-srvc
  namespace: my-namespace
spec:
  hosts:
  - my-srvc.my-namespace.svc.cluster.local
  http:
  - name: primary
    route:
    - destination:
        host: my-srvc
        port:
          number: 8080
        subset: stable
      weight: 100
    - destination:
        host: my-srvc
        port:
          number: 8080
        subset: canary
      weight: 0
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  annotations:
    argo-rollouts.argoproj.io/managed-by-rollouts: my-srvc
  name: my-srvc
  namespace: my-namespace
spec:
  host: my-srvc
  subsets:
  - labels:
      app: my-srvc
    name: canary
  - labels:
      app: my-srvc
    name: stable
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-srvc
  namespace: my-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-srvc
  strategy:
    canary:
      maxSurge: 25%
      maxUnavailable: 25%
      steps:
      - setWeight: 20
      - pause:
          duration: 1m
      - setWeight: 100
      trafficRouting:
        istio:
          destinationRule:
            canarySubsetName: canary
            name: my-srvc
            stableSubsetName: stable
          virtualService:
            name: my-srvc
            routes:
            - primary
  template:
    spec:
      containers:
      - image: nginx:alpine
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 10
        name: app
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 128Mi
```

Steps to reproduce: 


1. Apply the manifests included in the output
2. Observe the rollout gets to a healthy state
3. Change the image on the rollout to eg `nginx:does-not-exist`
4. Note that the canary replicaset cannot get healthy pods as they crash with an `ImagePullBackoff`
  - The same can be reproduced with any container you can get running & reliably crash during the rollout process; an invalid image reference is simply the easiest way to get an unhealthy canary replica set
6. Abort the rollout
7. Observe that `.status.aborted: true` is set on the Rollout, yet the canary replica set is not being cleaned up
8. The only remedy is to manually delete the canary replica set to get the Rollout unstuck

**Comment by pjiang-dev** [comment]
@dtamrazovupgrade @zachaller I tried reproducing this using the same setup above and did encounter the bug. However i noticed that the rollout did not include a canary/stable service. Once i added a canary and stable service, the abort rollout and timeout worked fine. See the example below

```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-srvc
  namespace: my-namespace
spec:
  replicas: 3
  progressDeadlineSeconds: 600
  progressDeadlineAbort: true
  selector:
    matchLabels:
      app: my-srvc
  strategy:
    canary:
      maxSurge: 25%
      maxUnavailable: 25%
      canaryService: my-srvc-canary
      stableService: my-srvc-stable
      steps:
      - setWeight: 20
      - pause:
          duration: 1m
      - setWeight: 100
      trafficRouting:
        istio:
          destinationRule:
            canarySubsetName: canary
            name: my-srvc
            stableSubsetName: stable
          virtualService:
            name: my-srvc
            routes:
            - primary
  template:
    metadata:
      labels:
        app: my-srvc
    spec:
      containers:
      - image: nginx:does-not-exist
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 10
        name: app
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: my-srvc-stable
  namespace: my-namespace
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-srvc
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: my-srvc-canary
  namespace: my-namespace
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-srvc
  type: ClusterIP
```

My guess on why the abort doesn't work in this setup and fails silently:
1. Abort requires reconciliation to complete
2. Reconciliation requires traffic routing to succeed
3. Istio is stopping traffic due to unhealthy pods/replicaset and reconcile exists before completion

My proposal is either:
1. Properly Log the abort failure instead of silently failing and document
2. Fix abort so it will work no matter the rollout traffic setup
What do you think @zachaller
