### ISSUE TITLE
Cloudwatch metric fails to retrieve AWS/RDS CPUUtilization

### ISSUE THREAD

**Issue by sondrelg** [argoproj/argo-rollouts#4147]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've included the version of argo rollouts.

**Describe the bug**

I've added a CloudWatch metric to an analysis template, but the query never returns data.

**To Reproduce**

Add this to your analysis template:

```yaml
    - name: Database CPU utilization
      interval: 1m
      successCondition: all(result[0].Values, {# <= 50})
      inconclusiveLimit: 10
      consecutiveSuccessLimit: 5
      failureLimit: 3
      provider:
        cloudWatch:
          interval: 1m
          metricDataQueries:
            - id: cpu
              returnData: true
              metricStat:
                metric:
                  namespace: AWS/RDS
                  metricName: CPUUtilization
                  dimensions:
                    - name: DBInstanceIdentifier
                      value: "{{args.db-instance}}"
                period: 60
                stat: Average
```

**Expected behavior**

These metrics work:

```yaml
    - name: Database disk queue depth
      interval: 1m
      successCondition: all(result[0].Values, {# <= 2})
      inconclusiveLimit: 10
      consecutiveSuccessLimit: 5
      failureLimit: 3
      provider:
        cloudWatch:
          interval: 1m
          metricDataQueries:
            - id: diskQueueDepth
              returnData: true
              metricStat:
                metric:
                  namespace: AWS/RDS
                  metricName: DiskQueueDepth
                  dimensions:
                    - name: DBInstanceIdentifier
                      value: "{{args.db-instance}}"
                period: 60
                stat: Average

    - name: Database read iops
      interval: 1m
      successCondition: all(result[0].Values, {# <= 2500})
      inconclusiveLimit: 5
      consecutiveSuccessLimit: 5
      failureLimit: 3
      provider:
        cloudWatch:
          interval: 1m
          metricDataQueries:
            - id: readIops
              returnData: true
              metricStat:
                metric:
                  namespace: AWS/RDS
                  metricName: ReadIOPS
                  dimensions:
                    - name: DBInstanceIdentifier
                      value: "{{args.db-instance}}"
                period: 60
                stat: Maximum
```

So should CPUUtilization.

For context, running 

```console
❯ aws cloudwatch get-metric-data \
              --profile <my-profile> \
              --region eu-north-1 \
              --start-time 2025-02-07T10:40:00Z \
              --end-time 2025-02-07T10:41:00Z \
              --metric-data-queries '
              [{
                "Id": "cpu",
                "MetricStat": {
                  "Metric": {
                    "Namespace": "AWS/RDS",
                    "MetricName": "CPUUtilization",
                    "Dimensions": [
                      {
                        "Name": "DBInstanceIdentifier",
                        "Value": "<my instance>"
                      }
                    ]
                  },
                  "Period": 60,
                  "Stat": "Maximum"
                }
              }]'
```

works fine, and I've double checked that the instance ID and metric is correct. I've also experimented with different `Period` values.

Here's the `AnalysisTemplate` measurements:

```
    - consecutiveSuccess: 5
      count: 5
      measurements:
        - finishedAt: '2025-02-21T08:37:49Z'
          phase: Successful
          startedAt: '2025-02-21T08:37:48Z'
          value: '[[]]'
        - finishedAt: '2025-02-21T08:38:49Z'
          phase: Successful
          startedAt: '2025-02-21T08:38:49Z'
          value: '[[]]'
        - finishedAt: '2025-02-21T08:39:49Z'
          phase: Successful
          startedAt: '2025-02-21T08:39:49Z'
          value: '[[]]'
        - finishedAt: '2025-02-21T08:40:49Z'
          phase: Successful
          startedAt: '2025-02-21T08:40:49Z'
          value: '[[]]'
        - finishedAt: '2025-02-21T08:41:49Z'
          phase: Successful
          startedAt: '2025-02-21T08:41:49Z'
          value: '[[]]'
      name: Database CPU utilization
      phase: Successful
      successful: 5
    - consecutiveSuccess: 5
      count: 5
      measurements:
        - finishedAt: '2025-02-21T08:37:49Z'
          phase: Successful
          startedAt: '2025-02-21T08:37:48Z'
          value: '[[0]]'
        - finishedAt: '2025-02-21T08:38:49Z'
          phase: Successful
          startedAt: '2025-02-21T08:38:49Z'
          value: '[[0]]'
        - finishedAt: '2025-02-21T08:39:49Z'
          phase: Successful
          startedAt: '2025-02-21T08:39:49Z'
          value: '[[0]]'
        - finishedAt: '2025-02-21T08:40:49Z'
          phase: Successful
          startedAt: '2025-02-21T08:40:49Z'
          value: '[[0]]'
        - finishedAt: '2025-02-21T08:41:49Z'
          phase: Successful
          startedAt: '2025-02-21T08:41:49Z'
          value: '[[]]'
      name: Database disk queue depth
      phase: Successful
      successful: 5
    - consecutiveSuccess: 5
      count: 5
      measurements:
        - finishedAt: '2025-02-21T08:37:49Z'
          phase: Successful
          startedAt: '2025-02-21T08:37:48Z'
          value: '[[15.571078472233799]]'
        - finishedAt: '2025-02-21T08:38:49Z'
          phase: Successful
          startedAt: '2025-02-21T08:38:49Z'
          value: '[[0.033332222259258026]]'
        - finishedAt: '2025-02-21T08:39:49Z'
          phase: Successful
          startedAt: '2025-02-21T08:39:49Z'
          value: '[[0]]'
        - finishedAt: '2025-02-21T08:40:49Z'
          phase: Successful
          startedAt: '2025-02-21T08:40:49Z'
          value: '[[0.08331250520703158]]'
        - finishedAt: '2025-02-21T08:41:49Z'
          phase: Successful
          startedAt: '2025-02-21T08:41:49Z'
          value: '[[]]'
      name: Database read iops
      phase: Successful
      successful: 5
```

**Version**

v1.8.0

**Logs**

```console
time="2025-02-21T08:38:49Z" level=info msg="Started syncing Analysis at (2025-02-21 08:38:49.00111711 +0000 UTC m=+632880.494957554)" analysisrun=service-name-6d6dd986bc-61 namespace=platform
time="2025-02-21T08:38:49Z" level=info msg="Running overdue measurement" analysisrun=service-name-6d6dd986bc-61 metric="Database CPU utilization" namespace=platform
time="2025-02-21T08:38:49Z" level=info msg="Running overdue measurement" analysisrun=service-name-6d6dd986bc-61 metric="Database disk queue depth" namespace=platform
time="2025-02-21T08:38:49Z" level=info msg="Running overdue measurement" analysisrun=service-name-6d6dd986bc-61 metric="Database read iops" namespace=platform
time="2025-02-21T08:38:49Z" level=info msg="Taking 3 Measurement(s)..." analysisrun=service-name-6d6dd986bc-61 namespace=platform
time="2025-02-21T08:38:49Z" level=info msg="Measurement Completed. Result: Successful" analysisrun=service-name-6d6dd986bc-61 metric="Database read iops" namespace=platform
time="2025-02-21T08:38:49Z" level=info msg="Measurement Completed. Result: Successful" analysisrun=service-name-6d6dd986bc-61 metric="Database CPU utilization" namespace=platform
time="2025-02-21T08:38:49Z" level=info msg="Measurement Completed. Result: Successful" analysisrun=service-name-6d6dd986bc-61 metric="Database disk queue depth" namespace=platform
...
time="2025-02-21T08:41:49Z" level=info msg="Taking 3 Measurement(s)..." analysisrun=service-name-6d6dd986bc-61 namespace=platform
time="2025-02-21T08:41:49Z" level=info msg="Measurement Completed. Result: Successful" analysisrun=service-name-6d6dd986bc-61 metric="Database read iops" namespace=platform
time="2025-02-21T08:41:49Z" level=info msg="Measurement Completed. Result: Successful" analysisrun=service-name-6d6dd986bc-61 metric="Database CPU utilization" namespace=platform
time="2025-02-21T08:41:49Z" level=info msg="Measurement Completed. Result: Successful" analysisrun=service-name-6d6dd986bc-61 metric="Database disk queue depth" namespace=platform
time="2025-02-21T08:41:49Z" level=info msg="Metric Assessment Result - Successful: ConsecutiveSuccessLimit (5) Reached" metric="Database CPU utilization"
time="2025-02-21T08:41:49Z" level=info msg="Metric 'Database CPU utilization' transitioned from Running -> Successful" analysisrun=service-name-6d6dd986bc-61 metric="Database CPU utilization" namespace=platform
time="2025-02-21T08:41:49Z" level=info msg="Metric 'Database CPU utilization' Completed. Result: Successful" analysisrun=service-name-6d6dd986bc-61 event_reason=MetricSuccessful namespace=platform
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by sondrelg** [comment]
Changing the cloudwatch interval and period to 5m fixed the issue:

```yaml
    - name: Database CPU utilization
      interval: 1m
      successCondition: all(result[0].Values, {# <= 50})
      inconclusiveLimit: 10
      consecutiveSuccessLimit: 5
      failureLimit: 3
      provider:
        cloudWatch:
          interval: 5m
          metricDataQueries:
            - id: cpu
              returnData: true
              metricStat:
                metric:
                  namespace: AWS/RDS
                  metricName: CPUUtilization
                  dimensions:
                    - name: DBInstanceIdentifier
                      value: "{{args.db-instance}}"
                period: 300
                stat: Average
```
