### ISSUE TITLE
Rollout status.alb.canaryTargetGroup not updating properly when pingpong feature enabled

### ISSUE THREAD

**Issue by raisalp** [argoproj/argo-rollouts#4184]
Checklist:
* argo-rollouts:v1.7.2

I am using canary deployment using traffic routing ALB ingress along with pingpong features. I know if I use the pingpong feature each time after a new version deployment, the target groups are going to interchange (canary and stable) but it is not updating the status (status.alb.canaryTargetGroup, status.alb.stableTargetGroup) on rollout. I am taking status.alb.canaryTargetGroup as an args in my analysis template to do the analysis on canaryTargetGroup but every alternative deployment I am getting wrong Targetgroup details

My Rollout:
```

`strategy:
    canary:
      analysis:
        startingStep: 6
        templates:
          - templateName: prod-srv-a-error-rate
      canaryMetadata:
        annotations:
          role: canary
        labels:
          role: canary
      pingPong:
        pingService: prod-srv-a
        pongService: prod-srv-a-preview
      stableMetadata:
        annotations:
          role: stable
        labels:
          role: stable
      steps:
        - setCanaryScale:
            replicas: 1
	more steps here to promote till 100% weight`

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
