### ISSUE TITLE
503 NC (NoClusterFound) errors on canary release with Istio

### ISSUE THREAD

**Issue by quentinplessis** [argoproj/argo-rollouts#4195]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've included the version of argo rollouts.

**Describe the bug**

When using canary release with Istio host-level traffic splitting, 503 NC (NoClusterFound) errors may occur at the very end of the rollout when the canary service becomes stable, as well as on rollout abortions. With high traffic throughput, errors almost always occur.

Let "old pods" be the pods before the rollout (stable pods) and "new pods" be the pods you want to rollout to (canary pods), then from my observations this happens because at the end of the rollout, old pods are not referenced by any kubernetes Service anymore, leading istio to remove the "inbound" cluster from old pods envoy config even though requests might still be going to them (as envoy config propagation is not immediate, client envoy may still send requests to old pods). Any request reaching old pods after that time ends up in 503 NoClusterFound error as no inbound cluster is defined on destination envoy.

Here are samples of old pods envoy clusters config to illustrate the issue:

Before rollout: both stable and canary services reference old pods --> both services appear in old pods envoy config
```json
{
    "name": "inbound|8080||",
    "type": "ORIGINAL_DST",
    "connectTimeout": "10s",
    "lbPolicy": "CLUSTER_PROVIDED",
    "upstreamBindConfig": {
        "sourceAddress": {
            "address": "127.0.0.6",
            "portValue": 0
        }
    },
    "metadata": {
        "filterMetadata": {
            "istio": {
                "services": [
                    {
                        "host": "my-app-canary-svc.my-ns.svc.cluster.local",
                        "name": "my-app-canary-svc",
                        "namespace": "my-ns"
                    },
                    {
                        "host": "my-app-stable-svc.my-ns.svc.cluster.local",
                        "name": "my-app-stable-svc",
                        "namespace": "my-ns"
                    }
                ]
            }
        }
    }
}
```

During rollout: stable service references old pods, canary service references new pods --> only stable service appear in old pods envoy config
```json
{
    "name": "inbound|8080||",
    "type": "ORIGINAL_DST",
    "connectTimeout": "10s",
    "lbPolicy": "CLUSTER_PROVIDED",
    "upstreamBindConfig": {
        "sourceAddress": {
            "address": "127.0.0.6",
            "portValue": 0
        }
    },
    "metadata": {
        "filterMetadata": {
            "istio": {
                "services": [
                    {
                        "host": "my-app-stable-svc.my-ns.svc.cluster.local",
                        "name": "my-app-stable-svc",
                        "namespace": "my-ns"
                    }
                ]
            }
        }
    }
}
```

At the end of the rollout : both stable and canary services reference new pods, no service reference old pods --> inbound cluster is deleted from old pods envoy config
```json
# no inbound cluster
```

A similar issue may happen when aborting the rollout. In that case new pods are not referenced by any Service, leading in a removal of "inbound" cluster in new pods envoy config and 503 NC errors in new pods.

**To Reproduce**

- Setup a Rollout with Istio host-level traffic splitting, with only one `setWeight: 100` step
- Disable virtual service retries to make issue more apparent (retrying may hide underlying issue)
- Send a few dozen RPS of requests and trigger the rollout
- When the new pods become ready for minReadySeconds, the canary revision becomes healthy and both stable and canary service are pointed to the new pods, leading in 503 errors for a short time for requests still going to the old pods.

Here is a sample of a setup (deployment is omitted as any workload should do)

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-rollout
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  strategy:
    canary:
      abortScaleDownDelaySeconds: 30
      canaryMetadata:
        annotations:
          role: canary
        labels:
          role: canary
      canaryService: my-app-canary-svc
      maxSurge: 100%
      maxUnavailable: 0
      minPodsPerReplicaSet: 2
      scaleDownDelaySeconds: 30
      stableMetadata:
        annotations:
          role: stable
        labels:
          role: stable
      stableService: my-app-stable-svc
      steps:
      - setWeight: 100
      trafficRouting:
        istio:
          virtualService:
            name: my-virtual-service
            routes:
            - primary
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-app-deploy
    scaleDown: never

---
apiVersion: networking.istio.io/v1
kind: VirtualService
  name: my-virtual-service
spec:
  http:
  - name: primary
    route:
    - destination:
        host: my-app-stable-svc
        port:
          number: 80
      weight: 100
    - destination:
        host: my-app-canary-svc
        port:
          number: 80
      weight: 0
    retries: 0

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-stable-svc
spec:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: my-app
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-canary-svc
spec:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: my-app
  type: ClusterIP
```

**Expected behavior**

503 NC errors should not happen. Waiting a few seconds (preferably customizable) after switching 100% of traffic to canary pods and before changing stable service selector should give istio enough time to propagate new traffic weight to all envoys, preventing new requests to be sent to old pods. Same goes when aborting. 

Adding a `pause: { duration: 15s }` step at the end is a limited workaround as "promote full" will ignore this step, and not applicable for abortions.

A working workaround is to create a dummy service on top of stable and canary services that points to all the pods of the rollout. This ensure that both old and new pods are always referenced by a service, and thus envoy config always contains the "inbound" cluster.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-app-dummy-svc
spec:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: my-app
  type: ClusterIP
```

Before rollout
```json
{
    "name": "inbound|8080||",
    "metadata": {
        "filterMetadata": {
            "istio": {
                "services": [
                    {
                        "host": "my-app-canary-svc.my-ns.svc.cluster.local",
                        "name": "my-app-canary-svc",
                        "namespace": "my-ns"
                    },
                    {
                        "host": "my-app-stable-svc.my-ns.svc.cluster.local",
                        "name": "my-app-stable-svc",
                        "namespace": "my-ns"
                    },
                    {
                        "host": "my-app-dummy-svc.my-ns.svc.cluster.local",
                        "name": "my-app-dummy-svc",
                        "namespace": "my-ns"
                    }
                ]
            }
        }
    }
}
```

During rollout
```json
{
    "name": "inbound|8080||",
    "metadata": {
        "filterMetadata": {
            "istio": {
                "services": [
                    {
                        "host": "my-app-stable-svc.my-ns.svc.cluster.local",
                        "name": "my-app-stable-svc",
                        "namespace": "my-ns"
                    },
                   {
                        "host": "my-app-dummy-svc.my-ns.svc.cluster.local",
                        "name": "my-app-dummy-svc",
                        "namespace": "my-ns"
                    }
                ]
            }
        }
    }
}
```

At the end of the rollout
```json
{
    "name": "inbound|8080||",
    "metadata": {
        "filterMetadata": {
            "istio": {
                "services": [
                   {
                        "host": "my-app-dummy-svc.my-ns.svc.cluster.local",
                        "name": "my-app-dummy-svc",
                        "namespace": "my-ns"
                    }
                ]
            }
        }
    }
}
```

**Version**

1.7.2

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
