### ISSUE TITLE
Unexpected replica reconcile errors in the controller logs

### ISSUE THREAD

**Issue by greeddj** [argoproj/argo-rollouts#4196]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've included the version of argo rollouts.

**Describe the bug**

While creating/updating a kind:Rollout object, I encountered errors in the controller logs.

This happens on both fresh and stale Kubernetes clusters, as well as on a newly installed Argo Rollouts setup. The issue occurs with or without external controllers that indirectly affect Rollout, such as KEDA.

This concerns me because, in the production environment, I have many Rollouts working with HPA, and with each change, I see a lot of errors.

As far as I understand, these are not critical errors since the applications continue to operate within their lifecycle. However, the controller's behavior cannot be considered normal.

**To Reproduce**

1) Run fresh k8s cluster or use existing
2) Use helm chart 2.39.X with argo-rollouts 1.8.0
3) Create simple Rollout and Service for it
4) Check the controller logs

**Expected behavior**

I expect the controller to handle the creation or update of a Rollout object correctly, without throwing any errors.

**Version**

```shell
➜ ~ kubectl version
Client Version: v1.32.3
Kustomize Version: v5.5.0
Server Version: v1.32.0

➜ ~ helm -n argo-rollouts list --output yaml
- app_version: v1.8.0
  chart: argo-rollouts-2.39.1
  name: argo-rollouts
  namespace: argo-rollouts
  revision: "1"
  status: deployed
  updated: 2025-03-19 21:13:14.973014 +0200 EET
```

**Logs**

```
➜ ~ kubectl -n argo-rollouts logs argo-rollouts-789b9cd8bb-2rpzw | grep -v 'level=info'
time="2025-03-19T19:13:29Z" level=warning msg="Controller is running."
time="2025-03-19T19:23:51Z" level=error msg="roCtx.reconcile err failed to scaleReplicaSetAndRecordEvent in reconcileNewReplicaSet: failed to scaleReplicaSet in scaleReplicaSetAndRecordEvent: failed to updateReplicaSet in scaleReplicaSet: error updating replicaset in updateReplicaSet test-7f8c7f57bf: Operation cannot be fulfilled on replicasets.apps \"test-7f8c7f57bf\": the object has been modified; please apply your changes to the latest version and try again" generation=1 namespace=test resourceVersion=1342 rollout=test
time="2025-03-19T19:23:51Z" level=error msg="rollout syncHandler error: failed to scaleReplicaSetAndRecordEvent in reconcileNewReplicaSet: failed to scaleReplicaSet in scaleReplicaSetAndRecordEvent: failed to updateReplicaSet in scaleReplicaSet: error updating replicaset in updateReplicaSet test-7f8c7f57bf: Operation cannot be fulfilled on replicasets.apps \"test-7f8c7f57bf\": the object has been modified; please apply your changes to the latest version and try again" namespace=test rollout=test
time="2025-03-19T19:23:51Z" level=error msg="failed to scaleReplicaSetAndRecordEvent in reconcileNewReplicaSet: failed to scaleReplicaSet in scaleReplicaSetAndRecordEvent: failed to updateReplicaSet in scaleReplicaSet: error updating replicaset in updateReplicaSet test-7f8c7f57bf: Operation cannot be fulfilled on replicasets.apps \"test-7f8c7f57bf\": the object has been modified; please apply your changes to the latest version and try again" error="<nil>"
```

**Workload example**

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: test
spec:
  ports:
  - name: app
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: test
  type: ClusterIP
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: test
  namespace: test
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: test
  strategy:
    blueGreen:
      activeService: test
      autoPromotionEnabled: true
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: nginx:1.26.3-bookworm
        imagePullPolicy: IfNotPresent
        name: test
        ports:
        - containerPort: 80
          name: app
          protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 60

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
