### ISSUE TITLE
blue-green preview replica set gets "stuck" if number of replicas has changed on the rollout object.

### ISSUE THREAD

**Issue by dandrivetime** [argoproj/argo-rollouts#4200]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've included the version of argo rollouts.

**Describe the bug**

rollout version (deployed via argocd and using helm):
repoURL: 'https://argoproj.github.io/argo-helm'
targetRevision: 2.37.6

- Using a blue-green deployment (have not tested in other deployment methods)
- The rollout has a "preview" and an "active" deployment replica set running fine.
- In the user's source code, they change the number of replicas on the rollout object (doesn't matter if it's +, or -)
- This manifest is stored in a gitops repo. ArgoCD reads the new manifest commit.
- The "preview" replica set does nothing, even if the container image has changed. It's stuck on the pre-deployment version.
- The "active" replica set instantly recognizes the change in replicas (from the rollout object change) and spins up/down the number of running pods.
- If you manually delete the "preview" replica set and allow the rollout to recreate it, all is well (until someone changes their replicas again).

**To Reproduce**

- Here is an entire set of objects we're working with on a typical deployment.
- Note, if the **replicas** property changes within the **rollout** object the behavior is observed.
- Even if you should get a new replica set because your container image (or other properties) has changed versions, nothing happens to the "preview" replica set. It remains "stuck" on the previous version until it's manually deleted.
- Full promotion, or redeploying the same object again does nothing.

```yaml
---
# Source: cx-standard/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: devops-wiki-manager
  namespace: devops
  labels:
    app: devops-wiki-manager
    chart: "cx-standard-0.1.24"
    githubrepo: cx-logic-devops-wiki-manager-api
    app.kubernetes.io/name: devops-wiki-manager
    app.kubernetes.io/instance: release-name
    featureBranch: "false"
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: devops-wiki-manager
---
# Source: cx-standard/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "devops-wiki-manager-stage"
  namespace: devops
  labels:
    app: devops-wiki-manager
    chart: "cx-standard-0.1.24"
    githubrepo: cx-logic-devops-wiki-manager-api
    app.kubernetes.io/name: devops-wiki-manager
    app.kubernetes.io/instance: release-name
    featureBranch: "false"
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: devops-wiki-manager
---
# Source: cx-standard/templates/ingress.yaml
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: devops-wiki-manager
  namespace: devops
  labels:
    app: devops-wiki-manager
    chart: "cx-standard-0.1.24"
    app.kubernetes.io/name: devops-wiki-manager
    githubrepo: cx-logic-devops-wiki-manager-api
    featureBranch: "false"
    traffic-type: internal
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
    traefik.ingress.kubernetes.io/router.tls: 'true'
spec:
  tls:
    - {}
  rules:
    - host: devops-wiki-manager-staging.int.yourdomain.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devops-wiki-manager
                port:
                  name: http
    - host: devops-wiki-manager.int.yourdomain.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devops-wiki-manager
                port:
                  name: http
---
# Source: cx-standard/templates/rollout.yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: devops-wiki-manager
  namespace: devops
  labels:
    app.kubernetes.io/name: devops-wiki-manager
    app.kubernetes.io/instance: devops-wiki-manager
    chart: "cx-standard-0.1.24"
    app: devops-wiki-manager
    version: "294650"
    featureBranch: "false"
    githubrepo: cx-logic-devops-wiki-manager-api
    
    business:  "cx"
    kind: "api"
    lob: "devops"
    location: "aks"
    product: "devops"
    team: "devops" 
    tier: "4"
    tags.datadoghq.com/env: "prod"
    tags.datadoghq.com/service: "devops-wiki-manager"
    tags.datadoghq.com/version: "294650"
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector: 
    matchLabels:
      app.kubernetes.io/name: devops-wiki-manager
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
        buildID: "294650"
        team: "devops"
      labels:
        app.kubernetes.io/name: devops-wiki-manager
        app.kubernetes.io/instance: devops-wiki-manager
        chart: "cx-standard-0.1.24"
        app: devops-wiki-manager
        version: "294650"
        featureBranch: "false"
        githubrepo: cx-logic-devops-wiki-manager-api
        business:  "cx"
        kind: "api"
        lob: "devops"
        location: "aks"
        product: "devops"
        team: "devops" 
        tier: "4"
        tags.datadoghq.com/env: "prod"
        tags.datadoghq.com/service: "devops-wiki-manager"
        tags.datadoghq.com/version: "294650"
    spec:
      securityContext:
        sysctls:
          - name: net.ipv4.ip_unprivileged_port_start
            value: '0'
      volumes:
          - name: write-access-vol
            emptyDir: {}
      containers:
        - name: devops-wiki-manager
          image: "someregistry.azurecr.io/yourdomain/cx.logic.devops.wiki-manager.api:294650"
          volumeMounts:
            - name: write-access-vol
              mountPath: /data/write
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            fsGroup: 1001
            allowPrivilegeEscalation: false
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /heartbeat
              port: 80
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /heartbeat
              port: 80
            initialDelaySeconds: 60
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /heartbeat
              port: 80
              scheme: HTTP
            periodSeconds: 30
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests: 
              cpu: "0"
              memory: "128Mi"
          env: 
            - name: CORECLR_ENABLE_PROFILING
              value: "1"
            - name: API_SERVER_APP_NAME
              value: devops-wiki-manager
            - name: API_SERVER_HOST
              value: 0.0.0.0
            - name: API_SERVER_PORT
              value: "80"
            - name: API_SERVER_RELOAD_ON_CHANGE
              value: "false"
            - name: API_SERVER_WORKERS_MAX
              value: "1"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: devops-wiki-manager
  strategy: 
    blueGreen:
      autoPromotionEnabled: false
      activeService: devops-wiki-manager
      previewService: devops-wiki-manager-stage
---
# Source: cx-standard/templates/virtualService.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: devops-wiki-manager
  namespace: devops  
  labels:
    app: devops-wiki-manager
    chart: "cx-standard-0.1.24"
    githubrepo: cx-logic-devops-wiki-manager-api
    app.kubernetes.io/name: devops-wiki-manager
    app.kubernetes.io/instance: release-name
    featureBranch: "false"
spec:
  hosts:
   - "devops-wiki-manager.int.yourdomain.cloud"
   - "devops-wiki-manager-staging.int.yourdomain.cloud"
   - "devops-wiki-manager-stage.devops.svc.cluster.local"
   - "devops-wiki-manager.devops.svc.cluster.local"
  http:
    - name: stage
      match:
        - headers:
            host:
              exact: devops-wiki-manager-staging.int.yourdomain.cloud
        - headers:
            host:
              exact: devops-wiki-manager-stage.devops.svc.cluster.local
      route:
        - destination:
            host: devops-wiki-manager-stage

    - name: primary
      route:
      - destination:
          port:
            number: 80
          host: devops-wiki-manager
        weight: 100
      - destination:
          port:
            number: 80
          host: devops-wiki-manager-stage
        weight: 0
```

**Expected behavior**

- We should still get a new replica set in "preview" because the container image (or other properties) has changed.
- Note, this is the expected behavior if you don't change the number of replicas on the rollout object.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
