### ISSUE TITLE
Merge Strategy Patch not working on Rollout .spec.template.spec.containers

### ISSUE THREAD

**Issue by brito-rafa** [argoproj/argo-rollouts#4210]
Checklist:

* [X] I've included steps to reproduce the bug.
* [X] I've included the version of argo rollouts.

**Describe the bug**

As of Rollout 1.82.X, we are using K8s libraries of 1.29.X.  There is a [fix](https://github.com/kubernetes/api/commit/0c53f558a11de4224cc78d7967fc82f274a0540b) on K8s API 1.30.X and beyond to determine  setting `PodSpec` with `//+listType` and `//+listMapKey=name` golang markers. This field is used for the Rollout `.spec.template.spec.containers`.
The impact of this is [Server-Side-Apply merge strategy](https://kubernetes.io/docs/reference/using-api/server-side-apply/#merge-strategy) for rollout is broken regarding this field.
Look the reproduction below.

The Rollout CRD needs to be re-generated with the latest K8s libraries.

**To Reproduce**

Please see the following Rollout object, note the entire field `.spec.template.spec.containers`

```
% k get rollout test-java-canary-api -o yaml | yq .spec.template.spec.containers
- args:
    - /bin/bash
    - -c
    - sleep 3600
  env:
    - name: APP_NAME
      value: test-java-canary
    - name: APP_STAGE
      value: qa
    - name: APP_RELEASE
      value: 6d1ff5b64ccc7ffd9f44d570853182396a9fa093
  image: busybox:latest
  imagePullPolicy: IfNotPresent
  name: test-java-canary-api
  resources:
    limits:
      cpu: 50m
      memory: 300Mi
    requests:
      cpu: 10m
      memory: 224Mi

```

Now, I want to patch only the `resources` field, following Server Side Apply (via Fully Specified Intent model using the strategic merge patch).

```
% cat strategic-merge-patch.yaml 
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: test-java-canary-api
spec:
  template:
    spec:
      containers:
      - name: test-java-canary-api
        resources:
          limits:
            cpu: 500m
            memory: 1120Mi
          requests:
            cpu: 50m
            memory: 224Mi

```

When apply this patch using the following command, please note all other fields are gone.

```
% k -n default apply --server-side=true --field-manager=stormforge -f strategic-merge-patch.yaml --force-conflicts --dry-run=server --show-managed-fields -o yaml | yq .spec.template.spec.containers
- name: test-java-canary-api
  resources:
    limits:
      cpu: 500m
      memory: 1120Mi
    requests:
      cpu: 50m
      memory: 224Mi

```

**Expected behavior**

The output of the command should be:

```
% k -n default apply --server-side=true --field-manager=stormforge -f strategic-merge-patch.yaml --force-conflicts --dry-run=server --show-managed-fields -o yaml | yq .spec.template.spec.containers
- args:
    - /bin/bash
    - -c
    - sleep 3600
  env:
    - name: APP_NAME
      value: test-java-canary
    - name: APP_STAGE
      value: qa
    - name: APP_RELEASE
      value: 6d1ff5b64ccc7ffd9f44d570853182396a9fa093
  image: busybox:latest
  imagePullPolicy: IfNotPresent
  name: test-java-canary-api
  resources:
    limits:
      cpu: 500m
      memory: 1120Mi
    requests:
      cpu: 50m
      memory: 224Mi

```

**Screenshots**

**Version**

1.8.2

**Logs**

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
