### ISSUE TITLE
Support configMapKeyRef in AnalysisTemplates

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#4215]
# Summary

It would be desirable to be able to reference values from a ConfigMap to use in the AnalysisTemplate. Something like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: args-example
spec:
  args:
  - name: foo
    valueFrom:
      configMapKeyRef:
        name: my-config-map
        key: foo
```

# Use Cases

Multiple AnalysisTemplates may want to reference the same value defined once in a single place. Currently, each of these AnalysisTemplate would need to repeat the args/values, which violates DRY.

We already support something similar for Secrets:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: args-example
spec:
  args:
  - name: api-token
    valueFrom:
      secretKeyRef:
        name: token-secret
        key: apiToken
```

This proposal is to support `configMapKeyRef` the same way we already do for `secretKeyRef`.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
