### ISSUE TITLE
Add feature to allow pods to be reused when changing setCanaryScale

### ISSUE THREAD

**Issue by diegobernardes** [argoproj/argo-rollouts#4233]
# Summary
Take a look at this canary rollout example:
```
- setCanaryScale:
    replicas: 1
- setHeaderRoute:
    name: test-e2e
    match:
      - headerName: test-e2e
        headerValue:
          exact: 'true'
- analysis:
    templates:
      - templateName: test-e2e
- setCanaryScale:
    matchTrafficWeight: true
- setWeight: 10
```

The issue is that once `setCanaryScale` is executed the pod is terminated and on the next step, the `setWeight`, it will be recreated. Ideally we should have an option to return to `setCanaryScale.matchTrafficWeight` without terminating the already running pod. My suggestion is to add a new attribute to the `setCanaryScale` to set the initial weight:
```
- setCanaryScale:
    initialWeight: 10
    matchTrafficWeight: true
```

The idea is that the `initialWeight` would be used to calculate the quantity of pods to be created and adjust accordantly. Maybe it will be just one instance and then nothing needs to be changed, or it could be ten because the service has a high throughput.

# Use Cases

* Speed up the rollout by reusing pods that are already running.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.``
