### ISSUE TITLE
Canary deployment while no traffic management - no canary and stable weights

### ISSUE THREAD

**Issue by dgmt** [argoproj/argo-rollouts#4241]
Checklist:

* [Y] I've included steps to reproduce the bug.
* [Y] I've included the version of argo rollouts.

**Describe the bug**

When using Argo Rollouts without traffic management, the rollout.Status.Canary.Weights field is nil. According to the documentation, the weights should still be approximated and usable even when traffic management is not configured. However, this does not seem to be the case.

**To Reproduce**

1. Create a rollout with a canary strategy but without traffic management. Example rollout spec:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: example-rollout
  namespace: default
spec:
  replicas: 3
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 50
        - pause: {}
        - setWeight: 100
```
2. Deploy the rollout using `kubectl apply -f rollout.yaml`
3. Retrieve the rollout object using the Argo Rollouts plugin:
`kubectl get rollout sample-service -o yaml`
4. Observe that the rollout.Status.Canary.Weights is nil.

**Expected behavior**

The rollout.Status.Canary.Weights field should be populated with approximated weights based on the canary strategy, even when traffic management is not configured.

**Version**

Tried v1.7.2, then updated to v1.8.2 and the problem persisted.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
