### ISSUE TITLE
When templating Workflow Reference with Kustomize a label may unintentionally create a Template section

### ISSUE THREAD

**Issue by avo-sepp** [argoproj/argo-rollouts#4246]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've included the version of argo rollouts.

**Describe the bug**

When creating application manifests with Kustomize, using the `labels` feature of Kustomize to apply labels, and attempting to apply a Workload Reference Rollout, Kustomize's Labels feature will create a template section in the Rollout. Which throws an error in Argo Rollouts

**To Reproduce**

First you have some `../base` for example:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# OpenAPI Schema for ArgoProj Objects
openapi:
  path: https://raw.githubusercontent.com/argoproj/argo-schema-generator/main/schema/argo_all_k8s_kustomize_schema.json
configurations:
- https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform-kustomize-v5.yaml
resources:
- resources/deployment.yaml
```

The `deployment.yaml` is a simple, regular, Kubernetes Deployment called `app`. Not a Rollout. 

Then you attempt to create a new version using this base. We'll call this version `prod`

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- resources/rollout.yaml
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: prod
    app.kubernetes.io/name: app
```

This kustomization for prod adds in the Workload Reference Rollout as shown below:

```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: app
  labels:
    app.kubernetes.io/name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  workloadRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: app
  strategy:
    blueGreen:
      activeService: app
      previewReplicaCount: 1
      previewService: app-preview
```

The resulting, produced Rollout, will now include a `template:` section, which throws an error. This section is created by the `labels` feature in Kustomize. 

```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app.kubernetes.io/instance: prod
    app.kubernetes.io/name: app
  name: app
status:
  conditions:
    - lastTransitionTime: '<z-time>'
      lastUpdateTime: '<z-time>'
      message: >-
        The Rollout "app" is invalid: spec.template: Internal error: template
        must be empty for workload reference rollout
      reason: InvalidSpec
      status: 'True'
      type: InvalidSpec
  message: >-
    InvalidSpec: The Rollout "app" is invalid: spec.template: Internal error:
    template must be empty for workload reference rollout
  observedGeneration: '3'
  phase: Degraded
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: prod
      app.kubernetes.io/name: app
  strategy:
    blueGreen:
      activeService: app
      previewReplicaCount: 1
      previewService: app-preview
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: prod
        app.kubernetes.io/name: app
  workloadRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: app
```

The error message `The Rollout "app" is invalid: spec.template: Internal error: template must be empty for workload reference rollout` is created because the Kustomize OpenAPI configuration tells Kustomize to add a `template.metadata.labels` section to the finished Rollout, even though that section is not allowed. 

**Expected behavior**

I would like the system to be resilient to seeing a template.metadata.labels section in the Rollout. That way it could proceed as expected. If Argo Rollouts completely ignored the `template` section if `workloadRef` is specified then this will not cause an issue. 

**Version**

`1.8.2`

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
