### ISSUE TITLE
`Progressive` option for `workloadRef` should take `MaxSurge` and `maxUnavailable` into account

### ISSUE THREAD

**Issue by mangatmodi** [argoproj/argo-rollouts#4260]
# Summary

We did a test in which we wanted to move one of our services from the `Deployment` object to the `Rollouts` object. We configured it as follows.

**Deployment**
```yaml
....
spec:
  replicas: 1000
  strategy:
    rollingUpdate:
      maxUnavailable: 5
      maxSurge: '10%'
...
```

**Rollouts**
```yaml
...
spec:
  replicas: 1000
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "service-name"
    scaleDown: progressively
    strategy:
      canary:
        maxUnavailable: 5
        maxSurge: '10%'
        steps:
          - setWeight: 10
          - pause:
              duration: 10m
          - setWeight: 20
          - pause:
               duration: 10m
         - setWeight: 100
          - pause:
              duration: 30m
...
```

We noticed that `Rollouts` created all 1000 pods and only started destroying the `Deployment` object. I understand this makes sense when it is a 1st creation of the `Rollouts` object. However, it is impossible to create 200% of the pods running.

Could we support `Progressive` so that the first `maxSurge` pods are added in the Rollouts, and then the same Pods are destroyed from the `Deployment`.

# Use Cases

When we migrate the services from Deployment to Rollouts.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
