### ISSUE TITLE
Default background propagation policy when deleting ReplicaSets causing degraded PodDisruptionBudget in Argo CD

### ISSUE THREAD

**Issue by ogierussell** [argoproj/argo-rollouts#4270]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've included the version of argo rollouts.

**Describe the bug**

Argo Rollouts appears to cause PodDisruptionBudgets (PDB) to be marked as degraded during deployments in Argo CD due to the background propagation policy used for ReplicaSet deletions. This occurs when the PodDisruptionBudget specifies a percentage for maxUnavailable.

**To Reproduce**
The following reproduction steps are to show how to reproduce without Argo Rollouts to show a minimal scenario that causes this.

Create a ReplicaSet:
```
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: repro-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repro-replicaset
  template:
    metadata:
      labels:
        app: repro-replicaset
    spec:
      containers:
      - name: example-conainer
        image: nginx
```

Apply it with `kubectl apply -f replicaset.yaml`

Create an associated PodDisruptionBudget with maxUnavailable populated as a percentage e.g
```
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: repro-pdb
spec:
  maxUnavailable: 85%
  selector:
    matchLabels:
      app: repro-replicaset
```

Apply it with `kubectl apply -f poddisruptionbudget.yaml`

Delete the Replicaset:
```
kubectl delete rs repro-replicaset
```

Describe the PDB
```
kubectl describe pdb repro-pdb
```

The following warning is shown:
```
Failed to calculate the number of expected pods: found no controllers for pod "xxxx"
```

A `SyncFailed` condition is applied to the PDB by Argo CD with the same message.

**Expected behavior**

No warning is triggered as is the case if the ReplicaSet is deleted with forground propagation policy e.g `kubectl delete rs repro-replicaset --cascade=foreground`

**Additional info**
This causes the PodDisruptionBudget to become degraded temporarily after a deployment in Argo CD when using Argo Rollouts.

Believe the code to delete ReplicaSets with default background propagation policy is [here](https://github.com/argoproj/argo-rollouts/blob/6f391aaf0323726520a62f64d6de9ee9b220e295/rollout/sync.go#L456). In comparison to jobs which look to be deleted with foreground propagation policy [here](https://github.com/argoproj/argo-rollouts/blob/16edf3a9b524d1047f461acae229788b90a77c46/metricproviders/job/job.go#L239-L240).

The relevant PodDisruptionBudget code looks to be [here](https://github.com/kubernetes/kubernetes/blob/23be9587a0f8677eb8091464098881df939c44a9/pkg/controller/disruption/disruption.go#L533-L547) and [here](https://github.com/kubernetes/kubernetes/blob/23be9587a0f8677eb8091464098881df939c44a9/pkg/controller/disruption/disruption.go#L599-L603).

We are using `argo-helm` with chart version `2.38.2`.

We currently workaround this issue by customizing the health check in Argo CD but would like to remove this workaround:
```
    resource.customizations.health.policy_PodDisruptionBudget: |
      hs = {}
      hs.status = "Progressing"
      hs.message = "Waiting for status"
      if obj.status ~= nil then
          if obj.status.conditions ~= nil then
              for i, condition in ipairs(obj.status.conditions) do
                  -- InsufficientPods can have valid use cases
                  -- Ignore "found no controllers for pod" as well
                  if condition.status == "False" and condition.reason ~= "InsufficientPods" and not string.find(condition.message or "", "found no controllers for pod") then
                      hs.status = "Degraded"
                      hs.message = "PodDisruptionBudget has " .. condition.reason
                      return hs
                  else
                      hs.status = "Healthy"
                      hs.message = "PodDisruptionBudget has " .. condition.reason
                  end
              end
          end
      end
      return hs
```

**Screenshots**

**Version**

1.7.2

**Logs**

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
