### ISSUE TITLE
Canary using trafficRouting does not respect maxSurge/maxUnavailable

### ISSUE THREAD

**Issue by amitpd** [argoproj/argo-rollouts#430]
**Pre-requisites:**
Deploy below Rollout
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: myapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: myapp:v1
        name: myapp
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          timeoutSeconds: 5
  strategy:
    canary:
      maxSurge: "25%"
      maxUnavailable: 0
      canaryService: myapp-canary
      stableService: myapp
      trafficRouting:
        nginx:
           primaryIngress: myapp-ingress
      steps:
      - experiment:
          duration: "2m"
          templates:
          - name: baseline
            specRef: stable
            replicas: 1
          - name: canary
            specRef: canary
          analyses:
          - name: success-rate
            templateName: success-rate
            args:
            - name: service-name
              value: myapp
```

**Steps to reproduce:**
- Change image tag to v2. Experiment is started.
- Wait for the analysis to complete and experiment duration to be over

**Actual Behavior:**
- A new replica set is created for image v2 and all 4 pods are crested
- Once all the 4 new pods are successfully running, the 4 pods of older replicaset is terminated at the same time.

**Expected/Desired Behavior:**
- Since maxSurge is set to 25%, only one pod of new replicaset should be created
- Since maxUnavailable is 0, one pod of older replicaset should be terminated only after the v2 pod is running.
