### ISSUE TITLE
Metrics for aborted rollouts

### ISSUE THREAD

**Issue by dimbleby** [argoproj/argo-rollouts#457]
Hi, 

I'm trying to use the metrics to monitor the state of my rollouts, and am confused about what I see when a rollout fails.

Say I have a canary strategy with an analysis step, like this:

```
    strategy:
      canary:
        steps:
        - setWeight: 50
        - analysis:
            templateName: whatever
        - setWeight: 100
```

and the analysis step fails.  Then the `rollout_phase{phase}` is reported as "progressing".  

This doesn't seem to me to be very helpful: it's the same thing that is reported when the rollout is actually making progress.

The rollout knows that it has failed, per the output of `kubectl describe rollout`:

```
    ...
    Message:               Rollout is aborted
    Reason:                RolloutAborted
    ...
```

Have I missed a metric that would show that the rollout is aborted, or does this not exist?  If it doesn't exist - any chance of adding something like this?

Thanks!
