### ISSUE TITLE
Allow Traffic shaping through header based routing

### ISSUE THREAD

**Issue by dthomson25** [argoproj/argo-rollouts#474]
Instead of routing traffic to different ReplicaSet by using percentage, some developers want to route traffic based on the headers of the request. For example, the developer may want their Firefox users to go to the canary version or the client adds a special canary header that users want to route to the canary ReplicaSet. Many traffic management tools (like Istio, linkerd via SMI, and Nginx ingress controller) offer support for header-based routing, but Argo Rollouts currently cannot automate the process.

Some questions that need to be addressed by the design:
- How does this integrate with setWeight steps?
- How do users decide how many replicas to run for ReplicaSet receiving the rerouted traffic
- Are there any difference between any of the traffic management providers?
- Does the controller keep the headers when the Rollout is in a steady-state?

**Comment by aweis89** [comment]
One thing to note, if the desired behavior is simply to always route matching header rules to the canary pods whenever they're available, and target the stable pods otherwise, this is currently achievable. Any traffic rule that only targets the canary SVC, will now meet those requirements (https://github.com/argoproj/argo-rollouts/pull/1022).

For example with Istio, you can now do:
```
spec:
  hosts:
  - somehost.com
  http:
  - match:
    - headers:
        some-header:
          exact: "whocares"
    name: by-header
    route:
    - destination:
        host: svc-canary
  - name: rollouts-route
    route:
    - destination:
        host: svc
      weight: 100
    - destination:
        host: svc-canary
      weight: 0
```

Of course, if more fine-grained control over the header traffic matching rule is desired, we'll still need to add additional support in Argo Rollouts so that we can specify which step we'd like to the header rule to begin taking effect. But just thought I'd mention that this is currently possible in-case the above would suffice for anyone viewing this.

**Comment by aweis89** [comment]
> Instead of routing traffic to different ReplicaSet by using percentage, some developers want to route traffic based on the headers of the request. For example, the developer may want their Firefox users to go to the canary version or the client adds a special canary header that users want to route to the canary ReplicaSet. Many traffic management tools (like Istio, linkerd via SMI, and Nginx ingress controller) offer support for header-based routing, but Argo Rollouts currently cannot automate the process.
> 
> Some questions that need to be addressed by the design:
> 
> * How does this integrate with setWeight steps?
> * How do users decide how many replicas to run for ReplicaSet receiving the rerouted traffic
> * Are there any difference between any of the traffic management providers?
> * Does the controller keep the headers when the Rollout is in a steady-state?

One solution I was wondering that may broaden the use-cases, as well as make this feature more maintainable, would be to add a generic `patch` step. The patch step would have a resource ref and a patch to apply to said resource. This could enable us to make any modification to any resource at any point of the rollout, leaving much of the above concerns to the end-user to decide. Perhaps we can even have a `PatchTemplate` resource that can be referenced in the `patch` step to avoid duplication similar to the `AnalysisTemplate`.

**Comment by sagarpreet-chadha** [comment]
Hey @aweis89 , thanks for answering this.
I have a quick question, what exactly happens if we use the above Istio virtual service crd and in rollout crd we define setWeight step as let’s say 5%.
1. Will all requests with custom header only be routed to canary OR all requests with custom header + 5% random traffic go to canary?
2. Is it mandatory to provide Weight in virtual Service or we can just define the header based routing logic only? Will argo rollout object be fine if we do not define Weight in Virtual service crd?

Thank you!

**Comment by nissy34** [comment]
Up*2. We need this feature.

**Comment by ssanders1449** [comment]
> One thing to note, if the desired behavior is simply to always route matching header rules to the canary pods whenever they're available, and target the stable pods otherwise, this is currently achievable. Any traffic rule that only targets the canary SVC, will now meet those requirements (#1022).
> 
> For example with Istio, you can now do:
> 
> ```
> spec:
>   hosts:
>   - somehost.com
>   http:
>   - match:
>     - headers:
>         some-header:
>           exact: "whocares"
>     name: by-header
>     route:
>     - destination:
>         host: svc-canary
>   - name: rollouts-route
>     route:
>     - destination:
>         host: svc
>       weight: 100
>     - destination:
>         host: svc-canary
>       weight: 0
> ```
> 
> Similarly, with Nginx, any ingress with header matching rules that points to the canary SVC will likewise behave the same, without needing any further support from Argo Rollouts.
> 
> Of course, if more fine-grained control over the header traffic matching rule is desired, we'll still need to add additional support in Argo Rollouts so that we can specify which step we'd like to the header rule to begin taking effect. But just thought I'd mention that this is currently possible in-case the above would suffice for anyone viewing this.

This would have been exactly what I need, and works fine when the the rollout completes normally.

However, in the case of an abort of the rollout, the canary service is not updated to with the hash of the stable service, so after the abort is complete, the canary service has no endpoints. So, any requests made with the header will now fail

Is it a bug that after an abort the canary service has no endpoints? I would have thought that when aborting we should patch the canary service with the hash of the stable replicaset before scaling down

**Comment by ttusin** [comment]
Up. Definitely need this feature.

**Comment by perenesenko** [comment]
For now as a draft: 

The rollout will have a new step for the header-based traffic `setHeaderBasedWeight`.
there will be a `header-name` property for the header name, and one of `value` or `regex` properties to specify the header value 

```
steps:
	setHeaderBasedWeight:
		header-name: "Agent" 
		regex: "Firefox*"
		value: "Firefox"
```

**Comment by mfkje06** [comment]
I just tested this case, but found the routing traffic base on headers and percentage existed at the same time.

If I only want the traffic existing through header based routing , how should i set them ?

**Comment by shaoye** [comment]
> I just tested this case, but found the routing traffic base on headers and percentage existed at the same time.
> 
> If I only want the traffic existing through header based routing , how should i set them ?

we made it work by setting `setCanaryScale` only. Don't  use `setWeight` since it will change the percentage in non-header route 

```yaml
      steps:
        - setCanaryScale:
            weight: 50
        - setHeaderRoute:
            match:
              - headerName: x-canary-version
                headerValue:
                  exact: canary
            name: canary-header-route
        - pause:
            duration: 10m
        - setHeaderRoute:
            name: canary-header-route
 ```
 
 the rendered virtual service during a rollout should look like this:
 
```yaml
  http:
    - match:
        - headers:
            x-canary-version:
              exact: canary
      name: canary-header-route
      route:
        - destination:
            host: svc
            subset: canary
          weight: 100
    - name: canary-route
      route:
        - destination:
            host: svc
            subset: stable
          weight: 100
        - destination:
            host: svc
            subset: canary
          weight: 0 # don't use setWeight since it will change the weight here
```


But this brings a new problem, `dynamicStableScale: true` is not working any more because the weight of stable subset is also 100%. We are looking for a way to scale it down to 50% while keep `weight: 100` in the second route
