### ISSUE TITLE
Introduce scaleDownDelay in canary (with traffic routing)

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#478]
Just like we have an implicit scaleDownDelay (default 30s) in the blue green strategy, I think we may also need an implicit scaleDownDelay with canary (with traffic routing). Here is the scenario:

```yaml
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause:
            duration: 30
        - setWeight: 50
        - pause:
            duration: 30
      trafficRouting:
        istio:
...
```

When the final step is reached we do several things **_simultaneously_**:
1. setWeight to 100
2. switch stable selector to new ReplicaSet
2. scale down the old replicaset to 0

However, as with blue-green, I do not believe it is possible for the effects of the `setWeight: 100` and changing service selectors to take effect immediately, especially across all mesh/ingress providers implementations.

Therefore, I propose that an implicit scaleDownDelay is introduced in the canary strategy, which delays the scale down of the old replicaset for 30 seconds (default), to give a chance for the 100% weight and service selectors to propagate properly.

NOTE that scaleDownDelay is only applicable for canary **_with_** trafficRouting since we cannot delay the scaleDown when using replica-count based canary when it need to reach 100%. (by definition 100% means the old replicaset is scaled down to zero).

A workaround in the meantime is to add two more steps to the canary steps

```yaml
        - setWeight: 100
        - pause:
            duration: 30
```
