### ISSUE TITLE
scaleDownDelaySeconds getting ignored on BlueGreen rollouts

### ISSUE THREAD

**Issue by markrity** [argoproj/argo-rollouts#501]
Hi,
We having an issue with our BlueGreen deployments, we have set `scaleDownDelaySeconds` to a high value, but old ReplicaSets pods getting terminated just a second after they are getting switched to a new ReplicaSet.

![](https://i.ibb.co/hcQJpry/Screen-Shot-2020-05-10-at-16-24-56.png)

Thats how our argo conf looks like :
```
  argo:
    previewReplicaCount: 1
    autoPromotionEnabled: false #We promote via CI/CD
    autoPromotionSeconds: 333333 # ignored if autoPromotionEnabled set to true
    scaleDownDelaySeconds: 600 # We want to keep it alive for a graceful shutdown
    scaleDownDelayRevisionLimit: 1
```

```
kubectl-argo-rollouts: v0.8.1+23fbc99
  BuildDate: 2020-04-20T23:58:37Z
  GitCommit: 23fbc99a91c6e3cf8aac90fdbc04ee608693ddfd
  GitTreeState: clean
  GoVersion: go1.13.1
  Compiler: gc
  Platform: darwin/amd64
```

Running on EKS 1.16, same was on 1.15. 

Any suggestions why this could happen ?
