### ISSUE TITLE
Value from secret in Analysis Template not resolved

### ISSUE THREAD

**Issue by nextrevision** [argoproj/argo-rollouts#522]
Attempting to reference a secret key as an arg in an AnalysisTemplate but receiving the following error when looking at the argo-rollouts container logs:

```
controller.go:169] args.api-key was not resolved
```

**AnalysisTemplate**

```
$ kubectl -n example get analysistemplate
NAME      AGE
smoketest   41h
```

```
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: smoketest
spec:
  args:
  - name: service-url
  - name: api-key
    valueFrom:
      secretKeyRef:
        name: smoketest
        key: apikey
  metrics:
  - name: smoketest
    failureLimit: 1
    provider:
      job:
        spec:
          backoffLimit: 0
          template:
            spec:
              containers:
              - name: smoketest
                image: smoketest:image
                args:
                  - "{{ args.service-url }}"
                  - "{{ args.api-key }}"
```

**Secret**

```
$ kubectl -n example get secret
NAME                    TYPE                                  DATA   AGE
default-token-xxxxx     kubernetes.io/service-account-token   3      7d1h
smoketest                 Opaque                                1      41h
```

```
$ kubectl -n example describe secret/smoketest
Name:         smoketest
Namespace:    example
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
apikey:  32 bytes
```

**Rollout**

```
$ kubectl -n example get rollouts
NAME    DESIRED   CURRENT   UP-TO-DATE   AVAILABLE
myapp   1         2         1
```

```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    rollout.argoproj.io/revision: "32"
  name: myapp
  namespace: example
spec:
  progressDeadlineSeconds: 300
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: myapp
  strategy:
    blueGreen:
      activeService: myapp
      autoPromotionEnabled: false
      prePromotionAnalysis:
        args:
        - name: service-url
          value: http://myapp-preview.example.svc.cluster.local:8080
        templates:
        - templateName: smoketest
      previewService: myapp-preview
