### ISSUE TITLE
boolean label causes silent failure and breaks kubectl plugin

### ISSUE THREAD

**Issue by mclarke47** [argoproj/argo-rollouts#533]
1. Follow the getting started guide

2. apply the following rollout 

```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        boolean-whoops: true
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - containerPort: 80
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
```
No complaints:
```
$ kubectl apply -f test.yaml
rollout.argoproj.io/test created
```
However the RS will not be created and not pods will appear

3. The `boolean-whoops: true` flag will cause an error to appear in the controller's logs
```
E0615 09:42:11.089480       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105: Failed to list *v1alpha1.Rollout: v1alpha1.RolloutList.Items: []v1alpha1.Rollout: v1alpha1.Rollout.Spec: v1alpha1.RolloutSpec.Template: v1.PodTemplateSpec.ObjectMeta: v1.ObjectMeta.Labels: ReadString: expects " or n, but found t, error found in #10 byte of ...|-whoops":true}},"spe|..., bigger context ...|adata":{"labels":{"app":"nginx","boolean-whoops":true}},"spec":{"containers":[{"image":"nginx:1.15.4|.
```
4. When running `kubectl argo rollouts list rollouts` the following error will be printed:
```
Error: v1alpha1.RolloutList.Items: []v1alpha1.Rollout: v1alpha1.Rollout.Spec: v1alpha1.RolloutSpec.Template: v1.PodTemplateSpec.ObjectMeta: v1.ObjectMeta.Labels: ReadString: expects " or n, but found t, error found in #10 byte of ...|-whoops":true}},"spe|..., bigger context ...|adata":{"labels":{"app":"nginx","boolean-whoops":true}},"spec":{"containers":[{"image":"nginx:1.15.4|...
```
