### ISSUE TITLE
ServiceNotFound error condition does not clear

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#551]
I applied a rollout with SMI strategy and referenced a service which did not exist. A expected, rollout had an error status:

```yaml
status:
  blueGreen: {}
  canary: {}
  conditions:
  - lastTransitionTime: "2020-06-25T11:41:56Z"
    lastUpdateTime: "2020-06-25T11:41:56Z"
    message: Service "rollouts-demo-canary" is not found
    reason: ServiceNotFound
    status: "False"
    type: Progressing
  observedGeneration: 64c8b974f7
```

However even after I applied the service, and modified the rollout, the error condition did not clear.
