### ISSUE TITLE
SMI RBAC privileges are missing

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#552]
The required RBAC for the controller to perform SMI tasks is missing. See:

```
argo-rollouts-597c9c45c7-8nbwm argo-rollouts E0625 12:00:08.131223       1 controller.go:169] trafficsplits.split.smi-spec.io "rollouts-demo" is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot get resource "trafficsplits" in API group "split.smi-spec.io" in the namespace "default"
argo-rollouts-597c9c45c7-8nbwm argo-rollouts time="2020-06-25T12:00:08Z" level=info msg="Event(v1.ObjectReference{Kind:\"Rollout\", Namespace:\"default\", Name:\"rollouts-demo\", UID:\"abe151a3-3216-4683-8ced-13ac825c14d2\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"5100\", FieldPath:\"\"}): type: 'Warning' reason: 'TrafficRoutingError' trafficsplits.split.smi-spec.io \"rollouts-demo\" is forbidden: User \"system:serviceaccount:argo-rollouts:argo-rollouts\" cannot get resource \"trafficsplits\" in API group \"split.smi-spec.io\" in the namespace \"default\""
```

I had to add this to the ClusterRole to get it to start working

```yaml
- apiGroups:
  - split.smi-spec.io
  resources:
  - trafficsplits
  verbs:
  - create
  - watch
  - get
  - update
  - patch
```
