### ISSUE TITLE
Scale canary stack even when weight is 0 (with traffic routing)

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#556]
Consider the following canary steps **AND the rollout is configured with traffic routing**:

```yaml
steps:
- setWeight: 0
- pause: {}
- setWeight: 10
- pause: { duration: 1h }
- setWeight: 20
- pause: { duration: 1h }
- setWeight: 30
- pause: { duration: 1h }
...
```

When the rollout is at the initial pause (the second step), the canary stack is scaled to zero. As soon as it reaches the `- setWeight: 10` step, the canary stack is scaled to 10%.  The fact that the rollout is scaled to zero at the initial pause,  makes some use cases of rollouts not possible. For example, some users want perform some tests on the canary stack, **_before_** the stack receives any production traffic, but still do a gradual release. Something like this:

```yaml
steps:
- setWeight: 0
- analysis:
    templates:
    - templateName: preview-test
- setWeight: 10
- pause: { duration: 1h }
- setWeight: 20
- pause: { duration: 1h }
- setWeight: 30
- pause: { duration: 1h }
...
```

I think we should allow users to control scaling the canary stack even when weight is zero to enable this use case. Of course, if a rollout is aborted, we should always scale the canary back to 0 replicas.

EDIT: corrected description to indicate that we match the scale of the canary stack to match the current weight (and not 100% as previously mistated)

**Comment by jessesuen** [comment]
Another example of why we may want to do this, is when we want to do traffic shadowing to the canary stack (https://github.com/argoproj/argo-rollouts/issues/563)

**Comment by shuheiktgw** [comment]
This totally makes sense. Let me work on this issue!

**Comment by aweis89** [comment]
I'd like to add another use-case where we're looking for this feature: We're using canary-by-header and we'd like 0% of none matching traffic to go to the canary pods. 

But I've noticed the issue @shuheiktgw mentioned regarding scaling. We encountered it because we tried to `setWeight` to only `1` but then noticed that only 1 pod would scale up, even though all of the canary traffic is going to the new pod.

IMO the best way to handle this type of situation would be to add an explicit new type of `step` that handles scaling the canaries without affecting traffic percentages. It could be called something along the lines of `scale: x%` and it would effectively cause a scale-up without affecting the weight.

**Comment by aweis89** [comment]
On second thought, perhaps it would be more versatile if we allowed for the option of having separate HPA's for the canary vs stable pods. We could add a `Spec.Strategy.Canary.StableHPA` and `Spec.Strategy.Canary.CanaryHPA`, which would just cause the controller to add the label selectors (`rollouts-pod-template-hash`) for stable and canary pods to the specified HPA. That would allow us to have separate scaling policies for the canary test run without having to create experiments

**Comment by jessesuen** [comment]
I spawned https://github.com/argoproj/argo-rollouts/issues/669 for a new feature to control canary scale. 

To resolve this issue, a change should be made that even at 0% canary weight, we scale up the canary stack to 100%, which is a much simpler feature.

**Comment by jessesuen** [comment]
So far, I think the proposal to have explicit scale steps seems like the best option. The syntax would look like:

```yaml
steps:
- setWeight: 10
- setCanaryScale:
     replicas: 1     # explicit count
- setCanaryScale:
     weight: 10     # percentage of spec.replicas
- setCanaryScale:
     matchTrafficWeight: true   # allow the steps to return to the default behavior of matching the canary traffic weight.
```

Currently, when iterating the steps, the canary scale will always match canary weight. With this feature, this behavior would be overridden with `setCanaryScale` step:

Here are some use cases:

1. Traffic shadowing

I want to perform traffic shadowing, so I need the canary scaled to 100% of the rollout.

```yaml
steps:
- setCanaryScale:
     weight: 100
- pause: {}
```

2. Preview testing

I want to scale the canary minimally, for the purposes of running tests against the canary, without having it receive live traffic:

```yaml
steps:
- setCanaryScale:
     replicas: 1
- pause: {}
```

3. Return to matching traffic weights:

After performing shadow or preview testing, it then would be desired to return to the default behavior, in which case we could introduce a step to restore the traffic weight matching for the remainder of the steps.

```yaml
steps:
- setCanaryScale:
     replicas: 1
- pause: {}
- setCanaryScale:
     matchTrafficWeight: true  # after this, canary scale will once again match traffic weight
- setWeight: 10
- pause: {duration: 1h}
- setWeight: 20
- pause: {duration: 1h}
- setWeight: 30
- pause: {duration: 1h}
- setWeight: 40
```
