### ISSUE TITLE
Allow rollout to Side by Side Deployments

### ISSUE THREAD

**Issue by Activehigh** [argoproj/argo-rollouts#562]
Hi Guys, 

Just wanted to add a feature request to allow side by side deployments with argo rollout. It already contains most of the things needed. 

**Expectation**

I have a repo and a rollout deployed in k8. Now 3 people are working in 3 branches and they want to deploy their feature branches side by side and shadow the traffic to them. Once the branch is merged back, the side by side deployment is removed by argo rollout.

Would love to contribute.  

Wanted to know what you guys think about this?

**Comment by jessesuen** [comment]
Traffic shadowing is a desired feature of rollouts. However, I think we had only considered shadowing traffic to just the canary or preview stack (during an update), and not other arbitrary services.

It's an interesting use case which is worth exploring. I think we would need to leave room in the syntax to support shadowing to arbitrary services. Something like:

```yaml
spec:
  strategy:
    canary:
      trafficShadowing:
        services:
        - name: guestbook-a
        - name: guestbook-b
      trafficRouting:
        nginx:
...
```
