### ISSUE TITLE
Rollback windows for fast-tracked rollbacks

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#574]
Spawned from https://github.com/argoproj/argo-rollouts/issues/557.

Currently we perform a "fast-tracked rollback" (which skips pauses, steps, analysis) in two circumstances:
1. we detect if we are moving back to a blue-green ReplicaSet which exists and is still scaled up (within its scaleDownDelay)
2. if we are moving back to the canary's "stable" ReplicaSet and the upgrade has **not yet completed**.

I think we should add more controls for intelligent, fast-tracked rollbacks for both the blue-green and canary strategies. For example, a use case is to have a fast-tracked rollback happen when moving to an older blue-green ReplicaSet even if it's scaled down (and not just if it's in the scaleDownDelay).

I think this can either be time based:

```yaml
spec:
  rollbackWindow:
    duration: 24h
  strategy:
    blueGreen:
...
```

Or it could possibly be revision based (e.g. fast-rollback if we are moving to an n-2 revision):

```yaml
spec:
  rollbackWindow:
    revisions: 2
  strategy:
    canary:
...
```

I propose to even place the `rollbackWindow` stanza outside strategy since both blue-green and canary would benefit from it.
