### ISSUE TITLE
Improve Rollout Error Handling and Status Display

### ISSUE THREAD

**Issue by seizadi** [argoproj/argo-rollouts#577]
When Rollout Spec is invalid provide better error handling.

For example, I get Status that the Spec is Invalid

```bash
Status:
  Conditions:
    Last Transition Time:  2020-07-08T22:05:27Z
    Last Update Time:      2020-07-08T22:05:27Z
    Message:               must be 1
    Reason:                InvalidSpec
    Status:                True
    Type:                  InvalidSpec
  Observed Generation:     5967656c48
```
 the Logs don't have appropriate detail

```bash
ERRO[2020-07-08T15:18:23-07:00] Spec submitted is invalid                     namespace=test rollout=rollouts-demo
```

Specifically print out the list off errors in the logs so that the Spec errors can be easily detected and fixed:
https://github.com/argoproj/argo-rollouts/blob/master/rollout/controller.go#L322

This is exasperated by the fact that in some cases I find Deployment Spec validation differs from Rollout Spec, one case for example was the liveliness probe for Deployment was accepted like this:
```yaml
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
```
But Rollout required:
```yaml
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
```

I have found other cases also, this is just an example, ideally Rollout should have the validation as Deployment controller.
