### ISSUE TITLE
Setup different docker labels/annotations for canary/stable pods

### ISSUE THREAD

**Issue by ozooxo** [argoproj/argo-rollouts#583]
It looks for me that Argo Rollouts can potentially simplify two `Deployment` Kubernetes objects

```
# deployment/canary.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-canary
  labels:
    track: canary
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: foo
        track: canary
    spec:
      containers:
      - image: foo:v4
---
# deployment/stable.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-stable
  labels:
    track: stable
spec:
  replicas: 9
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: foo
        track: stable
    spec:
      containers:
      - image: foo:v3
```

to one single `Rollout` Kubernetes object

```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: foo
spec:
  replicas: 10
  strategy:
    canary:
      maxSurge: 25%
      maxUnavailable: 25%
      steps:
      - setWeight: 10
      ...
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - image: foo:v4
```

However, imaging that I want to setup a canary test which compares the performance of the stable/canary servers, and fail the test if the canary servers perform significantly worse than the stable servers, I'd want a way to know if my pod is a canary pod or a stable pod.

(Not sure about Prometheus but should be similar) one way to do it in Datadog (I already know I can potentially use `webmetric` provider to communicate to Datadog API), is I'd need to define a special annotation and/or reuse my docker label in my pod template, and Datadog will [autodiscover it](https://docs.datadoghq.com/agent/kubernetes/tag/?tab=containerizedagent#tag-autodiscovery) and apply it as a tag I can use for filtering and comparison. In `Deployment`, it is something like

```
# deployment/canary.yaml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    metadata:
      labels:
        track: canary
      annotations:
        ad.datadoghq.com/tags: '{"track": "canary"}'
---
# deployment/stable.yaml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    metadata:
      labels:
        track: stable
      annotations:
        ad.datadoghq.com/tags: '{"track": "stable"}'
```

However, in the Argo `Rollout` Kubernetes object, since I can only define the pod template of the canary pod (and it seems to me Argo Rollouts doesn't know on the state of the stable pods, they are just the old pods created by the previous deployment and haven't been replaced yet; and since it is replacing a random set from the previous deployment, the remain ones can be either canary or stable for the previous deployment), I wonder if there's any workaround for me to setup those different labels/annotations?

Or is it possible for Argo Rollouts to update the labels/annotations (to something called `stable`) to the existing pods just the moment before it starts to rollout new pods?

Thanks!
