### ISSUE TITLE
Datadog metric provider

### ISSUE THREAD

**Issue by stephen-harris** [argoproj/argo-rollouts#702]
# Summary

In addition to WaveFront / Kayenta I'd like to suggest implementing a [Datadog ](https://www.datadoghq.com/) provider. 

# Use Cases

Due to limitations raised [here ](https://github.com/argoproj/argo-rollouts/issues/405) it's not possible to use the webmetric provider with Datadog. Additionally by providing an explicit provider makes configuring the analysis template simpler for the user.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by stephen-harris** [comment]
I'd be happy to provide a PR for this.

**Comment by jessesuen** [comment]
> I'd be happy to provide a PR for this.

That would be great! DataDog has been frequently requested, and we'd love to support it but lack the expertise, familiarity, and access to the tool.

**Comment by hari2192** [comment]
Datadog provider doesn't seems to be working for us.

I have updated argo-rollouts with latest version v0.9.2.

Also, followed instructions from here https://argoproj.github.io/argo-rollouts/features/analysis/#datadog-metrics

1. Created secret for datadog API key and APP key in argo-rollouts namespace:

```
apiVersion: v1
kind: Secret
metadata:
  name: datadog
type: Opaque
data:
  address: https://api.datadoghq.com
  api-key: <datadog-api-key>
  app-key: <datadog-app-key>
```

 2. Created analysis in application namespace:
```
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: loq-error-rate
spec:
  metrics:
  - name: error-rate
    interval: 5m
    successCondition: result <= 0.01
    failureLimit: 3
    provider:
      datadog:
        interval: 5m
        query: |
          sum:kubernetes.pods.running{env:dev,account:sandbox}
```

3. Ran the analysis but getting this error by describing analysis run:
```
Status:
  Message:  analysis spec invalid: metrics[0]: no provider specified
  Phase:    Error
```

Is there anything I am missing here ?
