### ISSUE TITLE
Allow to canary endpoint feature to support mupliple AWS ALB. #709

### ISSUE THREAD

**Issue by jukops** [argoproj/argo-rollouts#710]
# Summary
Our application has 2 ALBs. but looks support only an ALB. I'm using alb ingress controller for mapping between ingress and AWS ALB.

- currently yaml.
Only that `app-ext` ingress can receive canary traffic when deployment. Other ingress(ALB) which is connected to app pods should receive stable traffic as 100% when deployment.
```
  strategy:
    canary:
      canaryService: app-canary
      stableService: app-stable
      trafficRouting:
        alb:
          ingress: app-ext
          servicePort: 80
      steps:
      - setWeight: 5
      - pause: {}
```

# Use Cases
Our app has internal alb for VPC internal connection and has external alb for enduser(client). so required multiple ALBs.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
> Our app has internal alb for VPC internal connection and has external alb for enduser(client). so required multiple ALBs.

I think this use case makes sense to support multiple alb ingress references.

**Comment by jukops** [comment]
> > Our app has internal alb for VPC internal connection and has external alb for enduser(client). so required multiple ALBs.
> 
> I think this use case makes sense to support multiple alb ingress references.

Thanks for kindly reply.
Actually, This is the feature that I need. But I cannot attach multiple ALB :(
If it's implemented, It would be really good.

**Comment by allupaku** [comment]
Do you think a definition like this would suffice this use case ?

```
strategy:
    canary:
      canaryService: app-canary
      stableService: app-stable
      trafficRouting:
        alb:
          - ingress: app-ext
            servicePort: 443
         - ingress: app-interal
            servicePort: 80

```
