### ISSUE TITLE
Rollout stuck progressing when using short lived job post promotion analysis

### ISSUE THREAD

**Issue by peterstace** [argoproj/argo-rollouts#747]
## Summary 

First, thanks for Argoproj, it's been working great for us so far 👍 

We're using Argo Rollouts to deploy webservices using the BlueGreen strategy, using a post analysis that's based on a k8s Job. The Job verifiers that the webservices are working correctly using system level tests. The tests can take a variable amount of time to run, but can range anywhere from a few seconds to several minutes (depending on the particular webservice).

We've found that when the tests complete faster than 30 seconds, the Argo Rollout stays stuck in a progressing state forever. The old replicaset never scales down either (which is probably expected, given that the rollout is in a progressing state).

I believe that this is a bug, although it's possible that we're not configuring things correctly (in which case, any advice would be appreciated).

The logs seem to indicate that the argo-rollouts pod belives that the analysis is still running, even though it has completed (i.e. the `status` shows as being `Successful` when running `kubectl argo rollouts get rollout argobug -w`).

I've been able to work around the problem by adding an additional container to the AnalysisTemplate that just sleeps for 35s. This guarentees that the Job will take at least 30s to execute, and has been a robust workaround for us so far. The idea behind this workaround is that I noticed a countdown in the INFO field of the previous replicaset when running `kubectl argo rollouts get rollout argobug -w`. The countdown starts at `delay:30s` and counts down to 0, which then shows as `delay:passed`. I don't know for sure if it's related, but I suspect the problem may have to do with that.

A minimum working example that shows the problem is below:

```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argobug
  namespace: my-namespace
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: my-namespace
  project: default
  source:
    repoURL: https://github.com/my/repo.git
    path: argobug
    targetRevision: reproduce_argo_rollouts_bug
  syncPolicy:
    automated:
      prune: true
---
kind: Service
apiVersion: v1
metadata:
  name: argobug
  namespace: my-namespace
  labels:
    component: argobug
spec:
  ports: # ports not needed to show the bug
    - port: 80
      targetPort: 8080
      name: argobug
  selector:
    component: argobug
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: argobug
  namespace: my-namespace
spec:
  strategy:
    blueGreen:
      activeService: argobug
      postPromotionAnalysis:
        templates:
          - templateName: argobug
  selector:
    matchLabels:
      component: argobug
  template:
    metadata:
      labels:
        component: argobug
    spec:
      containers:
        - name: argobug
          image: alpine
          command: ["sh", "-c", "echo hello world && sleep infinity"]
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: argobug
  namespace: my-namespace
spec:
  args: []
  metrics:
    - name: verifier
      count: 1
      provider:
        job:
          spec:
            backoffLimit: 1
            template:
              metadata:
                annotations:
                  sidecar.istio.io/inject: "false"
              spec:
                restartPolicy: Never
                containers:
                  - name: sleep
                    image: alpine
                    command:
                      - sh
                      - -c
                      - |
                          sleep 10s # 10s will cause the Rollout to get stuck Progressing. Changing it to 35s allows the Rollout to become Healthy.
```

## Diagnostics

What version of Argo Rollouts are you running?

v0.8.3

---

Relevant parts of the argo-rollouts pod (I'm not too keen to share the whole log, since it's controlling many rollouts, and may contain sensitive info):

```
time="2020-09-29T04:21:29Z" level=info msg="Reconciling stable ReplicaSet 'argobug-7b8f984679'" namespace=my-namespace rollout=argobug
time="2020-09-29T04:21:29Z" level=info msg="Reconciling new ReplicaSet 'argobug-7b8f984679'" namespace=my-namespace rollout=argobug
time="2020-09-29T04:21:29Z" level=info msg="Reconciling old replica sets" namespace=my-namespace rollout=argobug
time="2020-09-29T04:21:29Z" level=info msg="Cannot scale down old ReplicaSets while Analysis is running and no ScaleDownDelaySeconds" namespace=my-namespace rollout=argobug
time="2020-09-29T04:21:29Z" level=info msg="Cleaning up old replicasets" namespace=my-namespace rollout=argobug
time="2020-09-29T04:21:29Z" level=info msg="Reconciling pause" namespace=my-namespace rollout=argobug
time="2020-09-29T04:21:29Z" level=info msg="Reconciling Post Promotion Analysis" namespace=my-namespace rollout=argobug
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
