### ISSUE TITLE
Analysis Arguments support for valueFrom 

### ISSUE THREAD

**Issue by inspiremirnal** [argoproj/argo-rollouts#778]
# Summary
Currently Analysis step under Canary can only read arguments value from value , and it would be more dynamic to use valueFrom, to refer to metadata labels.

When would you use this?

In case of keeping majority of things in kustomize base , so that overlays can just be overriding or populating only things that are not standard, it would be much better to have feature to refer metadata labels etc using valueFrom and then adding a FieldRef to it. In this way , the kustomize base can be dynamic and this information will be propagated to overlays as well during kustomize build , and hence , leads to cleaner and non-repetitive overlays templates.

An example would be like below, in kustomize-base.
```
          analyses:
          - name: some-analysis
            templateName: some-analysis
            args:
            - name: app
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: env
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['env']
            - name: region
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['region']

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
