### ISSUE TITLE
[WebMetrics] Support configure HTTP method and valid response code.

### ISSUE THREAD

**Issue by TommyLike** [argoproj/argo-rollouts#794]
# Summary

We have webmetric and it needs to be updated to support configure http method and valid response code.

# Use Cases
Check the endpoint's reachability (status code only, without specifying `JSONPATH` ) is another common usecase for rollout analysis.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
Is this a duplicate of https://github.com/argoproj/argo-rollouts/issues/371 ?

**Comment by TommyLike** [comment]
> Is this a duplicate of #371 ?

Yes, As long as if that issue will cover the case of no json response and only cares about the status code.

**Comment by perenesenko** [comment]
I'll take this one

**Comment by jessesuen** [comment]
Let's introduce a new response variable which will be made available in the `successCondition, failureCondition` which would have a code subfield.

Then the response could be interpreted as:

```yaml
successCondition: response.code == 200
```

NOTE: that the response variable will only be populated for the web metric.

**Comment by jessesuen** [comment]
Actually this is probably a better way. In parseResponse, we currently assume response is always JSON. But in the case that it is not (e.g. empty body or raw text), we can simply assign result to be the body of the response.

```golang
func (p *Provider) parseResponse(metric v1alpha1.Metric, response *http.Response) (string, v1alpha1.AnalysisPhase, error) {
	var data interface{}

	bodyBytes, err := ioutil.ReadAll(response.Body)
	if err != nil {
		return "", v1alpha1.AnalysisPhaseError, fmt.Errorf("Received no bytes in response: %v", err)
	}

	err = json.Unmarshal(bodyBytes, &data)
	if err != nil {
		return "", v1alpha1.AnalysisPhaseError, fmt.Errorf("Could not parse JSON body: %v", err)  // << instead of error, return result as string
	}
```

Then the web metric could be used like:

```yaml
  metrics:
  - name: webmetric
    successCondition: "true"   # note that we already mark measurements as Error if response is not 2xx
    provider:
      web:
        url: "http://my-server.com/api/v1/measurement?service={{ args.service-name }}"
```
