### ISSUE TITLE
Job's label value exceeds max value of 63 characters.

### ISSUE THREAD

**Issue by TommyLike** [argoproj/argo-rollouts#795]
## Summary 
Assume we have created an analysis template as below:
```
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: service-endpoint-reachable
spec:
  args:
  - name: service-fqdn
  - name: status-code
  metrics:
  - name: service-endpoint-reachable
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            spec:
              restartPolicy: Never
              containers:
                - name: curl-service-endpoint
                  image: curlimages/curl:7.73.0
                  command:
                    - /bin/sh
                    - -c
                    - |
                      curl -I {{args.service-fqdn}}
                      status_code=$(curl --write-out "%{http_code}\n" --silent --output /dev/null "{{args.service-fqdn}}");
                      [ $status_code -eq {{args.status-code}} ]
```
argo rollout will failed to create the wanted job due to the limit of max label value length(63) in kubernetes.
```
 message: 'Job.batch "990a01d4-ff15-402b-8516-0914c420e2b2.service-endpoint-reachable.5"
        is invalid: spec.template.labels: Invalid value: "990a01d4-ff15-402b-8516-0914c420e2b2.service-endpoint-reachable.5":
        must be no more than 63 characters'
```
I guess this is a known issue [1], but it's very likely to happen, due to the generation style.
[1]: https://github.com/argoproj/argo-rollouts/blob/a98a2742e522549a660e1de20b7b7c08dcc6884a/metricproviders/job/job.go#L57

## Diagnostics

What version of Argo Rollouts are you running?

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
