### ISSUE TITLE
scaleDownDelayRevisionLimit is not working as expected

### ISSUE THREAD

**Issue by nestorsokil** [argoproj/argo-rollouts#813]
## Summary 

What happened/what you expected to happen?
I’m using a large` scaleDownDelaySeconds` and `scaleDownDelayRevisionLimit: 1` , but what I’m observing is that after my `postPromotionAnalysis` is run I’m left with a single RS. What I would expect is to have the old one being kept running for `scaleDownDelaySeconds` or until another rollout happens and `scaleDownDelayRevisionLimit` is exceeded.

```
NAME                                                               KIND         STATUS        AGE    INFO
⟳ argoapp                                                         Rollout      ✔ Healthy     30m
├──# revision:3
│  ├──⧉ argoapp-6594b78d49                                        ReplicaSet   ✔ Healthy     7m38s  stable,active
│  │  └──□ argoapp-6594b78d49-6pkd8                               Pod          ✔ Running     7m38s  ready:1/1
│  ├──α argoapp-6594b78d49-3-pre                                  AnalysisRun  ✔ Successful  6m10s  ✔ 1
│  │  └──⊞ 545f1b24-814e-4943-9387-a63027ae2d38.acceptance-test.1  Job          ✔ Successful  6m10s
│  └──α argoapp-6594b78d49-3-post                                 AnalysisRun  ✔ Successful  5m38s  ✔ 20
├──# revision:2
│  ├──⧉ argoapp-7cb9fcbbf8                                        ReplicaSet   • ScaledDown  23m
│  ├──α argoapp-7cb9fcbbf8-2-pre                                  AnalysisRun  ✔ Successful  21m    ✔ 1
│  │  └──⊞ a46b4865-54ce-4a12-8d30-c419c0e52217.acceptance-test.1  Job          ✔ Successful  21m
│  └──α argoapp-7cb9fcbbf8-2-post                                 AnalysisRun  ✔ Successful  20m    ✔ 20
└──# revision:1
   └──⧉ argoapp-58c746787b                                        ReplicaSet   • ScaledDown  30m
```
^ revision:2 is ScaledDown as soon as `argoapp-6594b78d49-3-post` AnalysisRun is finished.

My manifest

```yaml
strategy:
    blueGreen:
      activeService: {{ template "app.name" . }}
      previewService: {{ template "app.name" . }}-canary
      scaleDownDelaySeconds: 31556926  # also tried 3600 and 600
      scaleDownDelayRevisionLimit: 1  # if this is 2, i will always have at least 2 running, but while post analysis is running there will be 3 RSs
      autoPromotionEnabled: true
      prePromotionAnalysis:
        templates:
          - templateName: {{ template "app.name" . }}-acceptance
      postPromotionAnalysis:
        templates:
          - templateName: {{ template "app.name" . }}-error-rate
          - templateName: {{ template "app.name" . }}-latency
```

MORE HERE: https://argoproj.slack.com/archives/CKTN88XFH/p1604228945105400

## Diagnostics

What version of Argo Rollouts are you running?

0.9.2

```
# Paste the logs from the rollout controller

TODO will attach later if needed, but this should be easy to reproduce
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
