### ISSUE TITLE
Make AnalysisTemplate more configurable

### ISSUE THREAD

**Issue by nestorsokil** [argoproj/argo-rollouts#825]
# Summary

There are a number of fields in AnalysisTemplate/ClusterAnalysisTemplate that are static (`consecutiveErrorLimit`, `interval`, `count`, etc). It would mean a lot of practical benefits to make them dynamically configurable.

# Use Cases
Having a single AnalysisTemplate you could define different threasholds for different applications (since they may have different tolerance to failures). The preferred experience IMO would be something like
```yaml
postPromotionAnalysis:
    templates:
    - templateName: error-rate
      failureLimit: 3
      interval: 5m
      count: 10
```

---
**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
Rather than add the values in the template reference, I think we should support these are arguments to the AnalysisTemplate. e.g.:

```
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate
spec:
  args:
  - name: interval
  - name: count
  metrics:
  - name: error-rate
    provider:
      prometheus:
        interval: "{{args.interval}}"
        count: "{{args.count}}"
```

and just use normal arg substitution to handle this.

**Comment by zimmertr** [comment]
> Rather than add the values in the template reference, I think we should support these are arguments to the AnalysisTemplate. e.g.:
> 
> ```
> apiVersion: argoproj.io/v1alpha1
> kind: AnalysisTemplate
> metadata:
>   name: error-rate
> spec:
>   args:
>   - name: interval
>   - name: count
>   metrics:
>   - name: error-rate
>     provider:
>       prometheus:
>         interval: "{{args.interval}}"
>         count: "{{args.count}}"
> ```
> 
> and just use normal arg substitution to handle this. We'll need to switch the type to use the `intstr.IntOrString` kubernetes type to support this. Currently I think they are all *int32

Does this actually work?

```
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cstmr-service
spec:
  args:
    - name: count
       value: 5
       ...
  metrics:
      ...
      count: "{{ args.count }}"
```

> one or more objects failed to apply, reason: error when patching "/dev/shm/2225555538": AnalysisTemplate.argoproj.io "..." is invalid: spec.args[0].value: Invalid value: "integer": spec.args[0].value in body must be of type string: "integer".
