### ISSUE TITLE
ARGO Rollouts with Azure Kubernetes Services (AKS)

### ISSUE THREAD

**Issue by ghostx3** [argoproj/argo-rollouts#864]
I'm looking for a way to use ARGO Rollouts with Azure AKS. In my case network plugin - Azure - and I'm also using Application Gateway to protect traffic.

Looking for use cases how-to implement ARGO Rollouts in a right way to get more flexibility managing traffic with Canary and BlueGreen scenarios.

I'd like to have native integration with Application Gateway in the first place, but I understand it doesn't support traffic weight. Azure Traffic Manager will be more appropriate service to use, but I concern about its global status and absence of ability to use private K8s services as backends.

Bu default AKS uses Azure Load Balancer as an ingress and it is not registered explicitly in AKS, so K8s Service just has a Kink of Service like Load Balancer and uses annotations to indicate it should be internal.

I'd appreciate any advice.

Thank you.

**Comment by carlosdoordash** [comment]
Argo Rollouts doesn't manipulate Kubernetes Ingress resources nor Cloud load balancers. Instead, it only updates the Kubernetes Service resource and specifically adds a selector `rollouts-pod-template-hash` to match the ReplicaSet hash of the active pods...

```
kubectl -n foo get service foo-service -o yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2020-11-16T10:34:42Z"
    name: foo-service
    namespace: foo
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: container-port
    selector:
      app: web
      rollouts-pod-template-hash: 78cf6689d8
```
