### ISSUE TITLE
Progressive rollout with istio subsets

### ISSUE THREAD

**Issue by msonnleitner** [argoproj/argo-rollouts#870]
# Summary

Is it possible or useful to do automated canary rollouts based on subsets? [Given the following rollout](https://argoproj.github.io/argo-rollouts/features/traffic-management/istio/), I was wondering, if there is any particular reason, that two services are required. Would it not be possible to use one service and two Istio subsets (like v1,v2)

```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-example
spec:
  ...
  strategy:
    canary:
      steps:
      - setWeight: 5
      - pause:
          duration: 10m
      canaryService: canary-svc # required
      stableService: stable-svc  # required
      trafficRouting:
        istio:
           virtualService: 
            name: rollout-vsvc  # required
            routes:
            - primary # At least one route is required?
```

Could it not potentially done like that?
```
  strategy:
    canary:
      steps:
      - setWeight: 5
      - pause:
          duration: 10m
      service: svc  # required
      canarySubset: v2 # required
      stableSubset: v1  # required
      trafficRouting:
        istio:
           virtualService: 
            name: rollout-vsvc  # required
            routes:
            - primary # At least one route is required?
```

# Motivation

Apart from the question, if two services or two subsets are a better approach:

In Anthos service mesh, there is a  (beta) dashboard for traffic splits which provides nice metrics for different versions of a service, providing visibility for different versions of services. For two different services, this would not work.

<img width="1056" alt="Screenshot 2020-12-01 at 09 40 17" src="https://user-images.githubusercontent.com/63719499/100716782-7338ca00-33b9-11eb-974c-83688ae712d4.png">
