### ISSUE TITLE
requiredForCompletion does not work

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#878]
## Summary 

Tried using `requiredForCompletion` feature for rollout/experiment/analysis but my experiment kept running forever.

```yaml
spec:
  strategy:
    canary:
      steps:
      - experiment:
          duration: 10s
          templates:
          - name: baseline
            specRef: stable
          - name: canary
            specRef: canary
          analyses:
          - name : echo-pod-hash
            templateName: echo-pod-hash
            requiredForCompletion: true
```

## Diagnostics

What version of Argo Rollouts are you running? v0.10.0

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
