### ISSUE TITLE
Does NewRelic provider support secretKeyRef?

### ISSUE THREAD

**Issue by makzzz1986** [argoproj/argo-rollouts#893]
# Summary

Old-fashion Web provider supports arguments from .spec, so I can use [ExternalSecrets](https://github.com/external-secrets/kubernetes-external-secrets), for example:
```
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
    - name: nr-app-name
    - name: nr-api-url
      value: https://insights-api.newrelic.com/v1/accounts/xxxx/query?nrql=
    - name: api-token
      valueFrom:
        secretKeyRef:
          name: external-env
          key: NEW_RELIC_ANALYSIS_TOKEN
  metrics:
    - name: success-rate
      successCondition: "asFloat(result) <= 0.02"
      provider:
        web:
          url: "{{ args.nr-api-url }}FROM%20Metric%20SELECT%20count%28apm.service.transaction.error.count%29/count%28apm.service.transaction.duration%29WHERE%20appName='{{ args.nr-app-name }}'%20SINCE%202%20minutes%20ago%20TIMESERIES"
          headers:
            - key: Accept
              value: application/json
            - key: X-Query-Key
              value: "{{ args.api-token }}"
          jsonPath: "{$.timeSeries[-1].results[0].result}" 
```

I couldn't find a way how I can use ExternalSecrets with NewRelic provider, I should hardcode Token in a Secret manifest. 
So the question is:
* How can I use `secretKeyRef` to provide a token for NewRelic analysis provider?

# Motivation

I really happy that now we have NewRelic integration and want to get rid off Web provider with URL-like queries, but I can't.

**Comment by makzzz1986** [comment]
ExternalSecrets creates Secret files with key names, so it is possible to create put variables with keys like /path/personal-api-key, /path/account-id, /path/region and obtain it by
```
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: newrelic
  namespace: argo-rollouts
secretDescriptor:
  backendType: systemManagerbyPath
  dataFromPath:
    - /path/
```
