### ISSUE TITLE
analysis run always recreate when rollout under canary pause status

### ISSUE THREAD

**Issue by zcc35357949** [argoproj/argo-rollouts#926]
## Summary 

What happened/what you expected to happen?
I create a rollout with background web analysis. I config analysis args to make the analysis run always become inconclusive status.However, the controller keep creating new analysis runs and these analysis runs will be deleted until rs deleted.

if rollout has been paused by inconclusive analysis run, analysis creation will skip.
https://github.com/argoproj/argo-rollouts/blob/master/rollout/analysis.go#L323

But If rollout has been paused by CanaryPauseStep, here always create new analysis run.
https://github.com/argoproj/argo-rollouts/blob/master/rollout/analysis.go#L163

Why the controller needs to create a new AnalysisRun if it has paused for the inconclusive analysisrun?

rollout.yml
```
...
  strategy:
    canary:
      analysis:
        startingStep: 1
        templates:
        - templateName: args-example
        args:
        # override default value
        - name: api-url
          value: http://xxx/api/done
      canaryService: canary-service
      stableService: stable-service
      maxSurge: "100%"
      steps:
      - setWeight: 20
      - pause: {}
```
analysis template:
```
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: args-example
spec:
  args:
  # optional
  - name: api-url
    value: http://example/measure
  metrics:
  - name: webmetric
    successCondition: result == 'nerver matched'
    failureCondition: result == 'nerver matched'
    provider:
      web:
        # placeholders are resolved when an AnalysisRun is created
        url: "{{ args.api-url }}"
        jsonPath: "{$.message}"
```

## Diagnostics

What version of Argo Rollouts are you running?

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
