### ISSUE TITLE
ProgressDeadlineExceeded condition not cleared in a paused blueGreen rollout

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#939]
## Summary 

When investigating a blueGreen rollout which was considered degraded because it had a ProgressDeadlineExceeded timeout condition, I noticed the pods were actually ready/available even though the condition was still set.

I think there may be a bug where the controller doesn't ever clear ProgressDeadlineExceeded once it reaches that condition.

## Diagnostics

What version of Argo Rollouts are you running? v0.10.2

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
I can reproduce this with the following rollout. The key part of reproducing this is: `autoPromotionEnabled: false`. 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-bluegreen
spec:
  replicas: 2
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 10 # note this is less than initialDelaySeconds
  selector:
    matchLabels:
      app: rollout-bluegreen
  template:
    metadata:
      labels:
        app: rollout-bluegreen
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:yellow
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 20
          httpGet:
            path: /color
            port: 8080
          periodSeconds: 30
  strategy:
    blueGreen: 
      autoPromotionEnabled: false
      activeService: rollout-bluegreen-active

```


Even though both stacks are ready, the rollout is still considered Degraded:

```
Name:            rollout-bluegreen
Namespace:       default
Status:          ✖ Degraded
Message:         ProgressDeadlineExceeded: ReplicaSet "rollout-bluegreen-fc4d695f9" has timed out progressing.
Strategy:        BlueGreen
Images:          argoproj/rollouts-demo:blue (stable, active)
                 argoproj/rollouts-demo:yellow (preview)
Replicas:
  Desired:       2
  Current:       4
  Updated:       2
  Ready:         2
  Available:     2

NAME                                           KIND        STATUS      AGE    INFO
⟳ rollout-bluegreen                            Rollout     ✖ Degraded  2m45s
├──# revision:2
│  └──⧉ rollout-bluegreen-fc4d695f9            ReplicaSet  ✔ Healthy   49s    preview
│     ├──□ rollout-bluegreen-fc4d695f9-95d7p   Pod         ✔ Running   49s    ready:1/1
│     └──□ rollout-bluegreen-fc4d695f9-n8rv6   Pod         ✔ Running   49s    ready:1/1
└──# revision:1
   └──⧉ rollout-bluegreen-7f9774c4ff           ReplicaSet  ✔ Healthy   2m45s  stable,active
      ├──□ rollout-bluegreen-7f9774c4ff-n5x4s  Pod         ✔ Running   2m45s  ready:1/1
      └──□ rollout-bluegreen-7f9774c4ff-t2r84  Pod         ✔ Running   2m45s  ready:1/1
```

**Comment by jessesuen** [comment]
This does **not** affect a canary rollout which hit a progressDeadlineSeconds timeout at a pause step. I tried with the following rollout:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-canary
spec:
  replicas: 3
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 10
  selector:
    matchLabels:
      app: rollout-canary
  template:
    metadata:
      labels:
        app: rollout-canary
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 20
          httpGet:
            path: /color
            port: 8080
          periodSeconds: 5
  strategy:
    canary: 
      steps:
      - setWeight: 20
      - pause: {}
```

The rollout did degrade as expected after 10 seconds, but the ProgressDeadlineExceeded condition cleared once the pod reached readiness:

```
Name:            rollout-canary
Namespace:       default
Status:          ॥ Paused
Message:         CanaryPauseStep
Strategy:        Canary
  Step:          1/8
  SetWeight:     20
  ActualWeight:  25
Images:          argoproj/rollouts-demo:blue (stable)
                 argoproj/rollouts-demo:yellow (canary)
Replicas:
  Desired:       3
  Current:       4
  Updated:       1
  Ready:         4
  Available:     4

NAME                                       KIND        STATUS     AGE    INFO
⟳ rollout-canary                           Rollout     ॥ Paused   2m55s
├──# revision:2
│  └──⧉ rollout-canary-8d469cd88           ReplicaSet  ✔ Healthy  74s    canary
│     └──□ rollout-canary-8d469cd88-tg4s7  Pod         ✔ Running  73s    ready:1/1
└──# revision:1
   └──⧉ rollout-canary-894965b64           ReplicaSet  ✔ Healthy  2m55s  stable
      ├──□ rollout-canary-894965b64-4sksd  Pod         ✔ Running  2m55s  ready:1/1
      ├──□ rollout-canary-894965b64-fzrqh  Pod         ✔ Running  2m55s  ready:1/1
      └──□ rollout-canary-894965b64-xxwpc  Pod         ✔ Running  2m55s  ready:1/1
```
