### ISSUE TITLE
Rollout stuck in "Progressing" indefinitely after failed experiment

### ISSUE THREAD

**Issue by artem-nefedov** [argoproj/argo-rollouts#942]
## Summary 

What happened/what you expected to happen?

Rollout would be forever stuck in "Progressing" after experiment with analysis failed.
Running `kubectl argo rollouts abort` does not help, but `kubectl argo rollouts restart` does.

It seems that it is only reproduced if the same experiment was already run successfully in the same rollout once prior to this.

Rollout strategy:

```
  strategy:
    canary:
      steps:
      - experiment:
          templates:
          - name: canary-prefiew
            specRef: canary
            selector:
              matchLabels:
                app: httpbin-test-ingress-private-preview
            metadata:
              labels:
                app: httpbin-test-ingress-private-preview
          analyses:
          - name: json-ok
            templateName: json-ok
            requiredForCompletion: true
            args:
            - name: service
              value: httpbin-test-ingress-private-preview.default.svc.cluster.local:8000
```

## Diagnostics

What version of Argo Rollouts are you running?

v0.10.2

# Paste the logs from the rollout controller

attached because of size

[logs.txt](https://github.com/argoproj/argo-rollouts/files/5809573/logs.txt)

# Screenshot of kubectl plugin output

![2](https://user-images.githubusercontent.com/7116010/104475290-fa3fab80-55cf-11eb-9786-e0083f467138.jpg)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
