### ISSUE TITLE
When scaleDownDelaySeconds is specified, the controller doesn't cancel AnalysisRuns.

### ISSUE THREAD

**Issue by takata-ast** [argoproj/argo-rollouts#955]
## Summary 

AS Docs(https://argoproj.github.io/argo-rollouts/features/bluegreen/),
A part of "postPromotionAnalysis" says  
"If scaleDownDelaySeconds is specified, the controller will cancel any AnalysisRuns at time of scaleDownDelay to scale down the ReplicaSet. "

But even scaleDownDelaySeconds is specifed, it will scale down the ReplicaSet only after the AnalysisRun completes.

## Diagnostics

version : v0.10.2

rollout.yaml
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: bluegreen-demo
  labels:
    app: bluegreen-demo
...
  strategy:
    blueGreen:
...
      postPromotionAnalysis:
        templates:
        - templateName: bluegreen-analysis-post
        args:
        - name: container-name
          value: argoproj/rollouts-demo
      previewReplicaCount: 3
      #autoPromotionSeconds: 300
      scaleDownDelaySeconds: 25
      scaleDownDelayRevisionLimit: 5
```

postPromotionAnalysis.yaml
```
metadata:
  name: bluegreen-analysis-post
spec:
  args:
  - name: container-name
  metrics:
  - name: bluegreen-analysis-post
    interval: 10s
    count: 4
...
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
