### ISSUE TITLE
Support triggering rollout when referenced ConfigMaps and/or Secrets change

### ISSUE THREAD

**Issue by vito-laurenza-zocdoc** [argoproj/argo-rollouts#958]
# Summary

Support for optionally triggering a rollout when one or more referenced ConfigMaps and/or Secrets change.

# Use Cases

Deployments can often be config changes only. It would be useful if a rollout could optionally happen when underlying ConfigMaps and/or Secrets used by the Deployment (as volume mounts, environment vars) are changed.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
A common technique to solving this is:
* helm - hash contents of configmap/secret and include it as an annotation in the pod.
* kustomize - use kustomize configmap/secret generators so that the name of the configmap/secret incorporates a hash of the contents of the config

**Comment by risinger** [comment]
I would be interested in seeing first-class support for config changes in Argo Rollouts similar to how [Flagger handles it](https://docs.flagger.app/usage/how-it-works). While I'm not fond of requiring the same config on basically every application, my main complaint with the status quo is the diff it generates. When using a hash to create a new configmap/secret for every change to it's contents, we're stuck with a useless Argo CD diff of the entire configmap/secret being added/removed.

**Comment by jessesuen** [comment]
I've been thinking about this some more. I think the way I would solve this, is with a simple controller that monitors ConfigMaps and Secrets. These objects would be annotated to have back-references to a rollout (or even deployment) which would needs to be redeployed upon change. For example:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  annotations:
    redeploy-on-update: rollout.argoproj.io/guestbook
data:
  foo: bar
```

The controller would continuously watch configmaps and secrets. When these objects are updated, it would inject a hash of the configmap into an annotation of the referenced rollout or deployment pod template. e.g.:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: guestbook
spec:
  template:
    metadata:
      annotations:
        configmap.my-config.hash: abcd1234
```

Because of the change in the `spec.template.metadata.annotations`, the rollout (or deployment) would then go through the normal update process.

The beauty of this approach is that this controller could operate standalone, and would even work with Deployments. In other words, non-rollout users of Argo CD and Deployments would benefit from this.
