### ISSUE TITLE
Support Ambassador AES as a traffic router for canary rollouts

### ISSUE THREAD

**Issue by leoluz** [argoproj/argo-rollouts#972]
# Summary

Add support for Ambassador AES to be used as a traffic router during canary rollouts.

What change needs making?

Provide a new `TrafficRoutingReconciler` implementation leveraging Ambassador AES canary deployment capabilities.

# Use Cases

When would you use this?

As a user of ArgoRollouts I want to be able to choose my existing Ambassador API gateway to control traffic during canary deployments.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by leoluz** [comment]
# Overview

The general idea of this implementation is leveraging [Ambassador canary releases feature](https://www.getambassador.io/docs/latest/topics/using/canary/) integrating it and making it compatible with Argo Rollouts canary deployments. Ambassador canary releases have a very similar weight based concept used to route traffic. Ambassador will be monitoring its `Mapping` resource in order to define how to route traffic to a specific service. It expects to have at least 2 Mappings available during the canary release:
- The base `Mapping` used to route all traffic to services
- The canary `Mapping` which is going to define the canary service as well as the desired weight

The example bellow shows how those `Mapping`s would look like:

```yaml
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  quote-backend
spec:
  prefix: /backend/
  service: quote
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  quote-backend2
spec:
  prefix: /backend/
  service: quote-canary
  weight: 10
```

# Proposal

In order to have Argo-Rollouts integrated the current idea is dynamically create the canary `Mapping` based on the provided base `Mapping`. In order to have that it is required to add the following change in Argo-Rollouts CRD allowing users to provide something like:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
spec:
  strategy:
    canary:
      stableService: quote
      canaryService: quote-canary
      trafficRouting:
        ambassador:
          mapping: quote-backend
```

With this configuration a canary `Mapping` can be dynamically generated and have the `weight` attribute updated regarding the steps configuration.

# Implementation

There is branch created implementing this proposal available in the following fork: 

https://github.com/datawire/argo-rollouts/commits/ambassador/canary

We are currently testing it and addressing some issues.
