### ISSUE TITLE
Analysis template support for interpolation in args

### ISSUE THREAD

**Issue by dudadornelles** [argoproj/argo-rollouts#987]
# Summary

It would be interesting to support interpolation on args, e.g:

```
args:
- name: environment
  value: tbd
- name: query
  value: avg:trace.servlet.request.hits{env:{{args.environment}},service:myapp}.as_count()
```

# Use Cases

We use kustomize for building manifests and without something like this, we have to override the whole query every time, whereas if this kind of interpolation was available, I'd have the cluster analysis template define the correct value and Id just override the `query` (and omit the `environment`) only in my base

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
