### ISSUE TITLE
indefinite pause: ability to specify duration

### ISSUE THREAD

**Issue by gaurav517** [argoproj/argo-rollouts#989]
# Summary
Currently to pause indefinitely, we need to specify pause as `{}` which is fine:
```
spec:
  strategy:
    canary:
      steps:
        - pause: {}                # pause indefinitely
```
However enhancement is that we should also be able to specify duration in such cases. For example: `- pause: { duration : -1 }` for indefinite pause or `- pause: { duration : 'infinity' }`. 

# Use Cases

There are use cases when we prune all empty objects in manifests and then `- pause: {}` gets pruned up.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
> There are use cases when we prune all empty objects in manifests and then - pause: {} gets pruned up.

I would argue you shouldn't be doing this. There are countless examples where an empty struct is significant in meaning. `emptyDir: {}` is one example. 

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: k8s.gcr.io/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
```
